### ISSUE TITLE
Cannot add separators to menus at runtime

### ISSUE THREAD

**Issue by peterfoot** [unoplatform/uno#10171]
### Current behavior

The MenuItem supports adding MenuFlyoutItems and MenuFlyoutSeparators via XAML as expected. However, when trying to build the menu dynamically in code an exception is raised when adding a MenuFlyoutSeparator on iOS and Android. (Not tested on macOS, WPF or Gtk). The code works correctly on Windows only. 

```
DynamicMenu.Items.Add(new MenuFlyoutItem() { Text = "One" });
DynamicMenu.Items.Add(new MenuFlyoutSeparator());
DynamicMenu.Items.Add(new MenuFlyoutItem() { Text = "Two" });
```

On the Android repro project this is the stacktrace:-
```
[DOTNET] [41m[30mfail[39m[22m[49m: Microsoft.UI.Xaml.UIElement[0]
[DOTNET]       Failed to raise 'PointerReleasedEvent': System.ArgumentOutOfRangeException: Index must be within the bounds of the List. (Parameter 'index')
[DOTNET]          at System.Collections.Generic.List`1[[Microsoft.UI.Xaml.Controls.MenuFlyoutItemBase, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]].Insert(Int32 index, MenuFlyoutItemBase item)
[DOTNET]          at Windows.Foundation.Collections.ObservableVector`1[[Microsoft.UI.Xaml.Controls.MenuFlyoutItemBase, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]].Insert(Int32 index, MenuFlyoutItemBase item) in C:\a\1\s\src\Uno.Foundation\Collections\ObservableVector.cs:line 64
[DOTNET]          at Microsoft.UI.Xaml.Controls.MenuBarItem.OnItemsVectorChanged(IObservableVector`1 sender, IVectorChangedEventArgs e) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\MenuBar\MenuBarItem.cs:line 204
[DOTNET]          at Windows.Foundation.Collections.ObservableVector`1[[Microsoft.UI.Xaml.Controls.MenuFlyoutItemBase, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]].RaiseVectorChanged(CollectionChange change, Int32 index) in C:\a\1\s\src\Uno.Foundation\Collections\ObservableVector.cs:line 98
[DOTNET]          at Windows.Foundation.Collections.ObservableVector`1[[Microsoft.UI.Xaml.Controls.MenuFlyoutItemBase, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]].Add(MenuFlyoutItemBase item) in C:\a\1\s\src\Uno.Foundation\Collections\ObservableVector.cs:line 42
[DOTNET]          at MenuSeparatorRepro.MainPage.Create_Click(Object sender, EventArgs e) in C:\Users\PeterFreemanFoot\source\repos\MenuSeparatorRepro\MenuSeparatorRepro.Shared\MainPage.xaml.cs:line 35
[DOTNET]          at MenuSeparatorRepro.MainPage.<>c__DisplayClass3_1.<InitializeComponent>b__11(Object Create_Click_sender, RoutedEventArgs Create_Click_e) in C:\Users\PeterFreemanFoot\source\repos\MenuSeparatorRepro\MenuSeparatorRepro.Mobile\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\MainPage_8ffa182592580ad23f051f548ff93cd0.cs:line 179
[DOTNET]          at Microsoft.UI.Xaml.Controls.Primitives.ButtonBase.OnClick() in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Primitives\ButtonBase\ButtonBase.mux.cs:line 734
[DOTNET]          at Microsoft.UI.Xaml.Controls.Button.OnClick() in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Button\Button.mux.cs:line 63
[DOTNET]          at Microsoft.UI.Xaml.Controls.Primitives.ButtonBase.PerformPointerUpAction() in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Primitives\ButtonBase\ButtonBase.mux.cs:line 655
[DOTNET]          at Microsoft.UI.Xaml.Controls.Primitives.ButtonBase.OnPointerReleased(PointerRoutedEventArgs args) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Primitives\ButtonBase\ButtonBase.mux.cs:line 630
[DOTNET]          at Microsoft.UI.Xaml.Controls.Control.<>c.<.cctor>b__381_10(Object sender, PointerRoutedEventArgs args) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Control\Control.cs:line 912
[DOTNET]          at Microsoft.UI.Xaml.UIElement.InvokeHandler(Object handler, RoutedEventArgs args) in C:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.RoutedEvents.cs:line 925
[DOTNET]          at Microsoft.UI.Xaml.UIElement.RaiseEvent(RoutedEvent routedEvent, RoutedEventArgs args, BubblingContext ctx) in C:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.RoutedEvents.cs:line 664
[DOTNET]          at Microsoft.UI.Xaml.UIElement.RaisePointerEvent(RoutedEvent evt, PointerRoutedEventArgs args, BubblingContext ctx) in C:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.Pointers.cs:line 1155
```
Looking at the MenuBarItem.cs source code we can see that the error is caused by casting the MenuFlyoutItemBase to MenuFlyoutItem which obviously fails with a MenuFlyoutSeparator:-
```
private void OnItemsVectorChanged(IObservableVector<MenuFlyoutItemBase> sender, IVectorChangedEventArgs e)
		{
			if (m_flyout != null)
			{
				var index = e.Index;
				switch (e.CollectionChange)
				{
					case CollectionChange.ItemInserted:
						m_flyout.Items.Insert((int)index, (MenuFlyoutItem)Items[(int)index]);
						break;
					case CollectionChange.ItemRemoved:
						m_flyout.Items.RemoveAt((int)index);
						break;
					default:
						break;
				}
			}
		}
```

### Expected behavior

I expect to be able to modify the menu items collection at runtime and add separators as required as is the current Windows/WASM behaviour.

### How to reproduce it (as minimally and precisely as possible)

[MenuSeparatorRepro.zip](https://github.com/unoplatform/uno/files/9810586/MenuSeparatorRepro.zip)

### Workaround

No workaround - either don't use separators or only use menus defined up-front in XAML.

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

4.5.12

### Affected platforms

Android, iOS

**Comment by trungnt2910** [comment]
> The code works correctly on Windows and WASM only.

It also fails on WASM, same error and code location.

```
fail: Windows.UI.Xaml.UIElement[0]
      Failed to raise 'PointerReleasedEvent': System.ArgumentOutOfRangeException: Index must be within the bounds of the List. (Parameter 'index')
         at System.Collections.Generic.List`1[[Windows.UI.Xaml.Controls.MenuFlyoutItemBase, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]].Insert(Int32 index, MenuFlyoutItemBase item) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\libraries\System.Private.CoreLib\src\System\Collections\Generic\List.cs:line 694
         at Windows.Foundation.Collections.ObservableVector`1[[Windows.UI.Xaml.Controls.MenuFlyoutItemBase, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]].Insert(Int32 index, MenuFlyoutItemBase item) in C:\a\1\s\src\Uno.Foundation\Collections\ObservableVector.cs:line 64
         at Windows.UI.Xaml.Controls.MenuBarItem.OnItemsVectorChanged(IObservableVector`1 sender, IVectorChangedEventArgs e) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\MenuBar\MenuBarItem.cs:line 204
         at Windows.Foundation.Collections.ObservableVector`1[[Windows.UI.Xaml.Controls.MenuFlyoutItemBase, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]].RaiseVectorChanged(CollectionChange change, Int32 index) in C:\a\1\s\src\Uno.Foundation\Collections\ObservableVector.cs:line 98
         at Windows.Foundation.Collections.ObservableVector`1[[Windows.UI.Xaml.Controls.MenuFlyoutItemBase, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]].Add(MenuFlyoutItemBase item) in C:\a\1\s\src\Uno.Foundation\Collections\ObservableVector.cs:line 42
         at TestManifest.MainPage.AddDynamicItemsButton_Click(Object sender, RoutedEventArgs args) in D:\CodingProjects\TestManifest\TestManifest\TestManifest.Shared\MainPage.xaml.cs:line 44
         at TestManifest.MainPage.<>c__DisplayClass5_4.<InitializeComponent>b__17(Object AddDynamicItemsButton_Click_sender, RoutedEventArgs AddDynamicItemsButton_Click_e) in D:\CodingProjects\TestManifest\TestManifest\TestManifest.Wasm\obj\Debug\net5.0\g\XamlCodeGenerator\MainPage_f7a73314868ec90c245c7d6c324e3469.g.cs:line 231
         at Windows.UI.Xaml.Controls.Primitives.ButtonBase.OnClick() in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Primitives\ButtonBase\ButtonBase.mux.cs:line 734
         at Windows.UI.Xaml.Controls.Button.OnClick() in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Button\Button.mux.cs:line 63
         at Windows.UI.Xaml.Controls.Primitives.ButtonBase.PerformPointerUpAction() in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Primitives\ButtonBase\ButtonBase.mux.cs:line 655
         at Windows.UI.Xaml.Controls.Primitives.ButtonBase.OnPointerReleased(PointerRoutedEventArgs args) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Primitives\ButtonBase\ButtonBase.mux.cs:line 630
         at Windows.UI.Xaml.Controls.Control.<>c.<.cctor>b__382_10(Object sender, PointerRoutedEventArgs args) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Control\Control.cs:line 912
         at Windows.UI.Xaml.UIElement.InvokeHandler(Object handler, RoutedEventArgs args) in C:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.RoutedEvents.cs:line 925
         at Windows.UI.Xaml.UIElement.RaiseEvent(RoutedEvent routedEvent, RoutedEventArgs args, BubblingContext ctx) in C:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.RoutedEvents.cs:line 664
         at Windows.UI.Xaml.UIElement.RaisePointerEvent(RoutedEvent evt, PointerRoutedEventArgs args, BubblingContext ctx) in C:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.Pointers.cs:line 1155
```
