### ISSUE TITLE
UNO App crashes.

### ISSUE THREAD

**Issue by CBrauer** [unoplatform/uno#10855]
### Current behavior

I have run into a problem when I tried to install and run the Uno App.

My Environment is:
  1. Microsoft Windows 11 Pro, Version	10.0.22621 Build 22621
  2. Microsoft Visual Studio Professional 2022 (64-bit) - Current Version 17.4.3

I followed the instructions at: https://platform.uno/docs/articles/get-started-vs-2022.html#finalize-your-environment
I selected:
  1. NET 6.0
  2. WinUI
  3. Gtk

all other items were unselected.

When Visual Studio 2022 started, I also selected "x64" and then I started the App.
I got the "Hello, world! screen.

I then selected "UnoPlatforApp.Skia.Gtk" as the Startup Project, and ran the program.

I got the following error:

```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Gtk.Application' threw an exception.
  Source=GtkSharp
  StackTrace:
   at Gtk.Application.Init()
   at Uno.UI.Runtime.Skia.GtkHost.Run()
   at UnoPlatformApp.Skia.Gtk.Program.Main(String[] args) in C:\Temp\UnoPlatformApp\UnoPlatformApp.Skia.Gtk\Program.cs:line 20

  This exception was originally thrown at this call stack:
    GLibrary.Load(Library)
    Gtk.Application.Application()

Inner Exception 1:
DllNotFoundException: Gtk: libgtk-3-0.dll, libgtk-3.so.0, libgtk-3.0.dylib, gtk-3.dll

```
Here is my uno-check script output:

```
Uno Platform Check v1.10.0.0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
This tool will check your Uno Platform development environment.
If problems are detected, it will offer the option to try and fix them for you, or suggest a way to fix them yourself.
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
» Synchronizing configuration... ok
» Scheduling appointments... ok

> OpenJDK 11.0 Checkup...
  - 11.0.16.1 (C:\Program Files\Microsoft\jdk-11.0.16.101-hotspot\bin\..)
  - 11.0.12 (C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin\..)
  - 18.0.2 (C:\Program Files\Common Files\Oracle\Java)

> Visual Studio 17.4.0 Checkup...
  - 17.5.0-pre.2.0 - C:\Program Files\Microsoft Visual Studio\2022\Preview
  - 17.4.3 - C:\Program Files\Microsoft Visual Studio\2022\Professional

> Visual Studio Workloads Checkup...
  - Universal Windows Platform development is installed (17.5.0-pre.2.0, 17.4.3)
  - Mobile development with .NET is installed (17.5.0-pre.2.0, 17.4.3)
  - ASP.NET and web development is installed (17.5.0-pre.2.0, 17.4.3)

> Android SDK Checkup...
  - emulator (31.3.14)
  - build-tools;32.0.0 (32.0.0)
  - platforms;android-32 (1)
  - system-images;android-31;google_apis;x86_64 (11)
  - platform-tools (33.0.3)
  - cmdline-tools;5.0 (5.0)

> Android Emulator Checkup...
  - Emulator: Android_Emulator_31 found.

> .NET SDK Checkup...
  - 6.0.402 - C:\Program Files\dotnet\sdk\6.0.402
  - 7.0.100-preview.7.22377.5 - C:\Program Files\dotnet\sdk\7.0.100-preview.7.22377.5
  - 7.0.100 - C:\Program Files\dotnet\sdk\7.0.100
  - 7.0.101 - C:\Program Files\dotnet\sdk\7.0.101

> .NET SDK - Workload Deduplication Checkup...

> Edge WebView2 Checkup...
  - Found Edge WebView2 version 108.0.1462.54

> .NET SDK - EnableWorkloadResolver.sentinel Checkup...
  - C:\Program Files\dotnet\sdk\7.0.100\EnableWorkloadResolver.sentinel exists.

> Windows Subsystem for Linux Checkup...
  ¡ WSL not available.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 Recommendation: Install WSL
To test Linux applications from this machine, follow these instructions to install and configure Windows Subsystem for
Linux: https://platform.uno/docs/articles/get-started-with-linux.html
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


> Windows Python Installation Checkup Checkup...
  - Python is installed in C:\WINDOWS\.

> Windows Long Path Checkup Checkup...
  - Long paths are enabled on Windows!

> Windows Hyper-V Checkup Checkup...
  - Hyper-V is configured

> .NET SDK - Workloads (7.0.100) Checkup...
  - android (Microsoft.NET.Sdk.Android.Manifest-7.0.100 : 33.0.4/7.0.100) installed.
  - ios (Microsoft.NET.Sdk.iOS.Manifest-7.0.100 : 16.0.1478/7.0.100) installed.
  - maccatalyst (Microsoft.NET.Sdk.MacCatalyst.Manifest-7.0.100 : 15.4.2372/7.0.100) installed.
  - macos (Microsoft.NET.Sdk.macOS.Manifest-7.0.100 : 12.3.2372/7.0.100) installed.
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

¡ Things look almost great, except some pesky warning(s) which may or may not be a problem, but at least if they are,
you'll know where to start searching!

Press Enter to finish...
```

Please help me.
Charles Brauer
CBrauer@CypressPoint.com

### Works on UWP/WinUI

None

**Comment by CBrauer** [comment]
Never mind.  I needed to install gtk3-runtime-3.24.31-2022-01-04-ts-win64.exe
It now runs.

**Comment by jeromelaban** [comment]
Thanks for the update. The error message for this is not clear enough, even [if listed here](https://platform.uno/docs/articles/get-started-wizard.html#systemdllnotfoundexception-gtk-libgtk-3-0dll), let's track in https://github.com/unoplatform/uno/issues/10927.
