### ISSUE TITLE
WebSockets connection from WASM calls the endpoint but connection fails nonetheless

### ISSUE THREAD

**Issue by rabejens** [unoplatform/uno#10908]
### Current behavior

I created a websocket endpoint in my Server part and am trying to call it from WASM. In the server logs I see that the call goes through, the websocket is accepted, but I get a connection failure nonetheless.

### Expected behavior

I should be able to communicate over the websocket.

### How to reproduce it (as minimally and precisely as possible)

1. Set up a Uno project with Server-side and WASM heads
2. Add the following into the `Program.cs` (prints the famous 99 bottles of beer):
    ```csharp
        app.Map("/api/ws/beer", async (HttpContext ctx) => {
            logger.LogInformation("Hit the WebSocket endpoint!");
            static string Bottles(int i, bool capitalize) {
                var msg = i switch {
                    0 => "no more bottles",
                    1 => "one bottle",
                    _ => i + " bottles"
                };
                return capitalize ? string.Concat(msg[..1].ToUpperInvariant(), msg[1..]) : msg;
            }
            if(ctx.WebSockets.IsWebSocketRequest) {
                logger.LogInformation("Client made WebSocket request, going to accept it");
                using var ws = await ctx.WebSockets.AcceptWebSocketAsync();
                var enc = new UTF8Encoding(false);
                for(var i = 99; i >= 0; i--) {
                    var msg = $"{Bottles(i, true)} of beer on the wall, {Bottles(i, false)} of beer! {((i == 0) ? "Go to the store, buy some more" : "Take one down, pass it around")}, {Bottles(i > 0 ? i - 1 : 99, false)} of beer on the wall.";
                    logger.LogInformation("Sending: {msg}", msg);
                    await ws.SendAsync(enc.GetBytes(msg), WebSocketMessageType.Text, true, default);
                    await Task.Delay(TimeSpan.FromSeconds(1));
                }
                logger.LogInformation("Sending end");
                await ws.SendAsync(enc.GetBytes("end"), WebSocketMessageType.Text, true, default);
                return;
            }
            logger.LogInformation("Client made HTTP request");
            ctx.Response.StatusCode = StatusCodes.Status400BadRequest;
            ctx.Response.Headers["X-Error-Message"] = "This is a WebSocket endpoint";
        });
    ```
3. Somewhere in your WASM app, do something like:
    ```csharp
    using var cws = new ClientWebSocket();
    await cws.ConnectAsync(new("wss://youthost.org/api/ws/beer"), default);
    ```

When in Step 3, you see on the server that the endpoint is invoked, but in the JavaScript console you see:

```
System.Net.WebSockets.WebSocketException (0x80004005): net_webstatus_ConnectFailure
dotnet.js:14  ---> WebSocket error
dotnet.js:14    at System.Net.WebSockets.BrowserWebSocket.<CancelationHelper>d__28.MoveNext()
dotnet.js:14    at System.Net.WebSockets.BrowserWebSocket.<ConnectAsyncCore>d__23.MoveNext()
dotnet.js:14    at System.Net.WebSockets.ClientWebSocket.<ConnectAsyncCore>d__21.MoveNext()
dotnet.js:14    at UnoApp.ViewModel.MainViewModel.<MakeWSApiCallAsync>d__24.MoveNext()
```

### Works on UWP/WinUI

None

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

WASM:

```xml
    <PackageReference Include="Microsoft.Extensions.Logging" Version="7.0.0" />
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="7.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.25.1" />
    <PackageReference Include="Uno.CommunityToolkit.WinUI.UI.Controls" Version="7.1.100" />
    <PackageReference Include="Uno.Extensions.Logging.WebAssembly.Console" Version="1.4.0" />
    <PackageReference Include="Uno.WinUI.WebAssembly" Version="4.6.39" />
    <PackageReference Include="Uno.WinUI.RemoteControl" Version="4.6.39" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.6.39" />
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="7.0.11" />
    <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="7.0.11" />
    <PackageReference Include="Uno.WinUI.Lottie" Version="4.6.39" />
```

Server:

```xml
		<PackageReference Include="Uno.Wasm.Bootstrap.Server" Version="7.0.11" />
		<PackageReference Include="Uno.Wasm.JupyterHub" Version="1.3.0" />
```

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
Thanks for the report. Could you create and attach here a sample app that reproduces your scenario, so we're certain of looking at the same issue?
