### ISSUE TITLE
[net7] Android build on .NET 7.0.102 fails with no Java peer type found.

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#11044]
### Current behavior

App built with AOT enabled fails with the following:

```
01-24 15:08:11.453 26988 26988 I MonoDroid: android.runtime.JavaProxyThrowable: System.NotSupportedException: Cannot create instance of type 'Windows.UI.Xaml.NativeApplication+ActivityCallbacks': no Java peer type found.
01-24 15:08:11.453 26988 26988 I MonoDroid:    at Java.Interop.JniPeerMembers.JniInstanceMethods..ctor(Type )
01-24 15:08:11.453 26988 26988 I MonoDroid:    at Java.Interop.JniPeerMembers.JniInstanceMethods.GetConstructorsForType(Type )
01-24 15:08:11.453 26988 26988 I MonoDroid:    at Java.Interop.JniPeerMembers.JniInstanceMethods.StartCreateInstance(String , Type , JniArgumentValue* )
01-24 15:08:11.453 26988 26988 I MonoDroid:    at Java.Lang.Object..ctor()
01-24 15:08:11.453 26988 26988 I MonoDroid:    at Windows.UI.Xaml.NativeApplication.ActivityCallbacks..ctor(NativeApplication )
01-24 15:08:11.453 26988 26988 I MonoDroid:    at Windows.UI.Xaml.NativeApplication.OnCreate()
01-24 15:08:11.453 26988 26988 I MonoDroid:    at Android.App.Application.n_OnCreate(IntPtr , IntPtr )
01-24 15:08:11.453 26988 26988 I MonoDroid:    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V , IntPtr , IntPtr )
01-24 15:08:11.453 26988 26988 I MonoDroid:     at crc64122dcf5ad656876d.NativeApplication.n_onCreate(Native Method)
01-24 15:08:11.453 26988 26988 I MonoDroid:     at crc64122dcf5ad656876d.NativeApplication.onCreate(NativeApplication.java:26)
01-24 15:08:11.453 26988 26988 I MonoDroid:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1223)
01-24 15:08:11.453 26988 26988 I MonoDroid:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6766)
01-24 15:08:11.453 26988 26988 I MonoDroid:     at android.app.ActivityThread.access$1500(ActivityThread.java:256)
01-24 15:08:11.453 26988 26988 I MonoDroid:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
01-24 15:08:11.453 26988 26988 I MonoDroid:     at android.os.Handler.dispatchMessage(Handler.java:106)
01-24 15:08:11.453 26988 26988 I MonoDroid:     at android.os.Looper.loopOnce(Looper.java:201)
01-24 15:08:11.453 26988 26988 I MonoDroid:     at android.os.Looper.loop(Looper.java:288)
01-24 15:08:11.453 26988 26988 I MonoDroid:     at android.app.ActivityThread.main(ActivityThread.java:7874)
01-24 15:08:11.453 26988 26988 I MonoDroid:     at java.lang.reflect.Method.invoke(Native Method)
01-24 15:08:11.453 26988 26988 I MonoDroid:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-24 15:08:11.453 26988 26988 I MonoDroid:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
01-24 15:08:11.453 26988 26988 I MonoDroid:
01-24 15:08:11.453 26988 26988 I MonoDroid:   --- End of managed Android.Runtime.JavaProxyThrowable stack trace ---
```

Opened for tracking in https://github.com/xamarin/xamarin-android/issues/7736

**Comment by jeromelaban** [comment]
Fixed in 4.7
