### ISSUE TITLE
Hot Reload crashes

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#11060]
Two stack traces for VS and VS Code follow:

### VS

```
[DEBUG] System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
[DEBUG]  ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
[DEBUG]    at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
[DEBUG]    at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
[DEBUG]    at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
[DEBUG]    at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
[DEBUG]    at Uno.UI.RemoteControl.Helpers.WebSocketHelper.ReadFrame(WebSocket socket, CancellationToken token) in C:\a\1\s\src\Uno.UI.RemoteControl\Helpers\WebSocketHelper.cs:line 27
[DEBUG]    at Uno.UI.RemoteControl.Host.RemoteControlServer.Run(WebSocket socket, CancellationToken ct) in C:\a\1\s\src\Uno.UI.RemoteControl.Host\RemoteControlServer.cs:line 58
[DEBUG]    at Uno.UI.RemoteControl.Host.RemoteControlExtensions.<>c__DisplayClass0_0.<<UseRemoteControlServer>b__1>d.MoveNext() in C:\a\1\s\src\Uno.UI.RemoteControl.Host\RemoteControlExtensions.cs:line 36
[DEBUG] --- End of stack trace from previous location where exception was thrown ---
[DEBUG]    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
[DEBUG]    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
[DEBUG] fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
[DEBUG]       An unhandled exception has occurred while executing the request.
[DEBUG] System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
[DEBUG]  ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
[DEBUG]    at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
[DEBUG]    at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
[DEBUG]    at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
[DEBUG]    at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
[DEBUG]    at Uno.UI.RemoteControl.Helpers.WebSocketHelper.ReadFrame(WebSocket socket, CancellationToken token) in C:\a\1\s\src\Uno.UI.RemoteControl\Helpers\WebSocketHelper.cs:line 27
[DEBUG]    at Uno.UI.RemoteControl.Host.RemoteControlServer.Run(WebSocket socket, CancellationToken ct) in C:\a\1\s\src\Uno.UI.RemoteControl.Host\RemoteControlServer.cs:line 58
[DEBUG]    at Uno.UI.RemoteControl.Host.RemoteControlExtensions.<>c__DisplayClass0_0.<<UseRemoteControlServer>b__1>d.MoveNext() in C:\a\1\s\src\Uno.UI.RemoteControl.Host\RemoteControlExtensions.cs:line 36
[DEBUG] --- End of stack trace from previous location where exception was thrown ---
[DEBUG]    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
[DEBUG]    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
[DEBUG] fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
[DEBUG]       An unhandled exception has occurred while executing the request.
[DEBUG] System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
[DEBUG]  ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
[DEBUG]    at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
[DEBUG]    at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
[DEBUG]    at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
[DEBUG]    at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
[DEBUG]    at Uno.UI.RemoteControl.Helpers.WebSocketHelper.ReadFrame(WebSocket socket, CancellationToken token) in C:\a\1\s\src\Uno.UI.RemoteControl\Helpers\WebSocketHelper.cs:line 27
[DEBUG]    at Uno.UI.RemoteControl.Host.RemoteControlServer.Run(WebSocket socket, CancellationToken ct) in C:\a\1\s\src\Uno.UI.RemoteControl.Host\RemoteControlServer.cs:line 58
[DEBUG]    at Uno.UI.RemoteControl.Host.RemoteControlExtensions.<>c__DisplayClass0_0.<<UseRemoteControlServer>b__1>d.MoveNext() in C:\a\1\s\src\Uno.UI.RemoteControl.Host\RemoteControlExtensions.cs:line 36
[DEBUG] --- End of stack trace from previous location where exception was thrown ---
[DEBUG]    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
[DEBUG]    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
[DEBUG] warn: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[2]
[DEBUG]       The response has already started, the error page middleware will not be executed.
[DEBUG] warn: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[2]
[DEBUG]       The response has already started, the error page middleware will not be executed.
[DEBUG] warn: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[2]
[DEBUG]       The response has already started, the error page middleware will not be executed.
[DEBUG] fail: Microsoft.AspNetCore.Server.Kestrel[13]
[DEBUG]       Connection id "0HMNVIGBCCS1V", Request id "0HMNVIGBCCS1V:00000001": An unhandled exception was thrown by the application.
[DEBUG] System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
[DEBUG]  ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
[DEBUG]    at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
[DEBUG]    at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
[DEBUG]    at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
[DEBUG]    at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
[DEBUG]    at Uno.UI.RemoteControl.Helpers.WebSocketHelper.ReadFrame(WebSocket socket, CancellationToken token) in C:\a\1\s\src\Uno.UI.RemoteControl\Helpers\WebSocketHelper.cs:line 27
[DEBUG]    at Uno.UI.RemoteControl.Host.RemoteControlServer.Run(WebSocket socket, CancellationToken ct) in C:\a\1\s\src\Uno.UI.RemoteControl.Host\RemoteControlServer.cs:line 58
[DEBUG]    at Uno.UI.RemoteControl.Host.RemoteControlExtensions.<>c__DisplayClass0_0.<<UseRemoteControlServer>b__1>d.MoveNext() in C:\a\1\s\src\Uno.UI.RemoteControl.Host\RemoteControlExtensions.cs:line 36
[DEBUG] --- End of stack trace from previous location where exception was thrown ---
[DEBUG]    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
[DEBUG]    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
[DEBUG]    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
[DEBUG]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[DEBUG] fail: Microsoft.AspNetCore.Server.Kestrel[13]
[DEBUG]       Connection id "0HMNVIGBCCS21", Request id "0HMNVIGBCCS21:00000001": An unhandled exception was thrown by the application.
[DEBUG] System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
[DEBUG]  ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
[DEBUG]    at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
[DEBUG]    at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
[DEBUG]    at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
[DEBUG]    at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
[DEBUG]    at Uno.UI.RemoteControl.Helpers.WebSocketHelper.ReadFrame(WebSocket socket, CancellationToken token) in C:\a\1\s\src\Uno.UI.RemoteControl\Helpers\WebSocketHelper.cs:line 27
[DEBUG]    at Uno.UI.RemoteControl.Host.RemoteControlServer.Run(WebSocket socket, CancellationToken ct) in C:\a\1\s\src\Uno.UI.RemoteControl.Host\RemoteControlServer.cs:line 58
[DEBUG]    at Uno.UI.RemoteControl.Host.RemoteControlExtensions.<>c__DisplayClass0_0.<<UseRemoteControlServer>b__1>d.MoveNext() in C:\a\1\s\src\Uno.UI.RemoteControl.Host\RemoteControlExtensions.cs:line 36
[DEBUG] --- End of stack trace from previous location where exception was thrown ---
[DEBUG]    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
[DEBUG]    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
[DEBUG]    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
[DEBUG]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[DEBUG] fail: Microsoft.AspNetCore.Server.Kestrel[13]
[DEBUG]       Connection id "0HMNVIGBCCS20", Request id "0HMNVIGBCCS20:00000001": An unhandled exception was thrown by the application.
[DEBUG] System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
[DEBUG]  ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
[DEBUG]    at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
[DEBUG]    at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
[DEBUG]    at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
[DEBUG]    at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
[DEBUG]    at Uno.UI.RemoteControl.Helpers.WebSocketHelper.ReadFrame(WebSocket socket, CancellationToken token) in C:\a\1\s\src\Uno.UI.RemoteControl\Helpers\WebSocketHelper.cs:line 27
[DEBUG]    at Uno.UI.RemoteControl.Host.RemoteControlServer.Run(WebSocket socket, CancellationToken ct) in C:\a\1\s\src\Uno.UI.RemoteControl.Host\RemoteControlServer.cs:line 58
[DEBUG]    at Uno.UI.RemoteControl.Host.RemoteControlExtensions.<>c__DisplayClass0_0.<<UseRemoteControlServer>b__1>d.MoveNext() in C:\a\1\s\src\Uno.UI.RemoteControl.Host\RemoteControlExtensions.cs:line 36
[DEBUG] --- End of stack trace from previous location where exception was thrown ---
[DEBUG]    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
[DEBUG]    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
[DEBUG]    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
[DEBUG]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[DEBUG] info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
[DEBUG]       Request finished in 352107.548ms 101 
[DEBUG] info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
[DEBUG]       Request finished in 352107.9606ms 101 
[DEBUG] info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
[DEBUG]       Request finished in 352107.5931ms 101 
[DEBUG] dbug: Microsoft.AspNetCore.Server.Kestrel[2]
[DEBUG]       Connection id "0HMNVIGBCCS1V" stopped.
[DEBUG] dbug: Microsoft.AspNetCore.Server.Kestrel[2]
[DEBUG]       Connection id "0HMNVIGBCCS21" stopped.
[DEBUG] dbug: Microsoft.AspNetCore.Server.Kestrel[2]
[DEBUG]       Connection id "0HMNVIGBCCS20" stopped.
```

### VS Code

Hot Reload in VS Code crashes with:

```
[ERROR]Unhandled exception. 
[ERROR]System.TypeInitializationException: The type initializer for 'Microsoft.Build.Collections.MSBuildNameIgnoreCaseComparer' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Microsoft.Build.Framework.NativeMethods' threw an exception.
 ---> System.TypeLoadException: Could not load type 'System.Runtime.InteropServices.OSPlatform' from assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Microsoft.Build.Framework.NativeMethods.get_IsLinux()
   at Microsoft.Build.Framework.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Build.Framework.NativeMethods.get_SystemInformation()
   at Microsoft.Build.Framework.NativeMethods.get_ProcessorArchitecture()
   at Microsoft.Build.Collections.MSBuildNameIgnoreCaseComparer..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents, Boolean loadProjectsReadOnly, Boolean useAsynchronousLogging, Boolean reuseProjectRootElementCache)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents, Boolean loadProjectsReadOnly)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, ToolsetDefinitionLocations toolsetDefinitionLocations)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties)
   at Microsoft.CodeAnalysis.MSBuild.Build.ProjectBuildManager.StartBatchBuild(IDictionary`2 globalProperties)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.LoadAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.LoadProjectInfoAsync(String projectFilePath, ProjectMap projectMap, IProgress`1 progress, ILogger msbuildLogger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.OpenProjectAsync(String projectFilePath, ILogger msbuildLogger, IProgress`1 progress, CancellationToken cancellationToken)
   at Uno.UI.RemoteControl.Host.HotReload.MetadataUpdates.CompilationWorkspaceProvider.CreateProject(TaskCompletionSource`1 taskCompletionSource, String projectPath, IReporter reporter, String[] metadataUpdateCapabilities, CancellationToken cancellationToken) in C:\a\1\s\src\Uno.UI.RemoteControl.Server.Processors\HotReload\MetadataUpdates\CompilationWorkspaceProvider.cs:line 65
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

**Comment by jeromelaban** [comment]
Both traces seem unrelated. VS's is only showing disconnections, whereas Code's is showing that there's a runtime mismatch (net7 vs net6). Which version of Uno were you using, and which version of the vscode addin are you using?
