### ISSUE TITLE
SkiaSharp Hardware Rendering

### ISSUE THREAD

**Issue by navio-n** [unoplatform/uno#11131]
## On which page?

https://github.com/unoplatform/Uno.Samples/blob/master/UI/SkiaSharpTest/SkiaSharpTest/SkiaSharpTest.Shared/MainPage.xaml

## What's wrong?

2 times SKXamlCanvas is used. SKSwapChainPanel should be used for Hardware Rendering? Or something is new?
On UWP sample it was not working also with Hardware Rendering...

**Comment by navio-n** [comment]
On the old sample only Wasm Hardware Rendering was wrong:

fail: Microsoft.UI.Xaml.FrameworkElement[0]
      OnElementLoaded failed in FrameworkElement
System.InvalidOperationException: Error #1 "ReferenceError: GL is not defined
    at SKSwapChainPanel.createWebGLContext (http://localhost:5000/package_4013587d970acb2839eb640458c1a6e2a0a1e221/SkiaSharp.Views.Uno.Wasm.js:154:31)
    at SKSwapChainPanel.createContext (http://localhost:5000/package_4013587d970acb2839eb640458c1a6e2a0a1e221/SkiaSharp.Views.Uno.Wasm.js:109:48)
    at eval (eval at closedEval (http://localhost:5000/package_4013587d970acb2839eb640458c1a6e2a0a1e221/dotnet.js:5:100345), <anonymous>:2:22)
    at eval (eval at closedEval (http://localhost:5000/package_4013587d970acb2839eb640458c1a6e2a0a1e221/dotnet.js:5:100345), <anonymous>:2:61)
    at closedEval (http://localhost:5000/package_4013587d970acb2839eb640458c1a6e2a0a1e221/dotnet.js:5:100345)
    at Object.mono_wasm_invoke_js (http://localhost:5000/package_4013587d970acb2839eb640458c1a6e2a0a1e221/dotnet.js:5:100361)
    at _mono_wasm_invoke_js (http://localhost:5000/package_4013587d970acb2839eb640458c1a6e2a0a1e221/dotnet.js:8477:64)
    at http://localhost:5000/package_4013587d970acb2839eb640458c1a6e2a0a1e221/dotnet.wasm:wasm-function[14582]:0x4de3e3
    at http://localhost:5000/package_4013587d970acb2839eb640458c1a6e2a0a1e221/dotnet.wasm:wasm-function[14529]:0x4dd327
    at http://localhost:5000/package_4013587d970acb2839eb640458c1a6e2a0a1e221/dotnet.wasm:wasm-function[14458]:0x4cdc0f" executing javascript: "(function() {const __parameter_0 = SkiaSharp.Views.Windows.SKSwapChainPanel.getInstance('1');
return __parameter_0.createContext('102882');return "ok"; })();"
   at WebAssembly.Runtime.InvokeJS(String str) in C:\a\1\s\src\Uno.Foundation.Runtime.WebAssembly\Interop\WebAssembly.Runtime.cs:line 44
   at Uno.Foundation.WebAssemblyRuntime.InnerInvokeJS(String str) in C:\a\1\s\src\Uno.Foundation.Runtime.WebAssembly\Interop\Runtime.wasm.cs:line 260
   at Uno.Foundation.WebAssemblyRuntime.InvokeJS(String str) in C:\a\1\s\src\Uno.Foundation.Runtime.WebAssembly\Interop\Runtime.wasm.cs:line 231
   at Uno.Foundation.WebAssemblyRuntime.InvokeJSWithInterop(FormattableString formattable) in C:\a\1\s\src\Uno.Foundation.Runtime.WebAssembly\Interop\Runtime.wasm.cs:line 328
   at SkiaSharp.Views.Windows.SKSwapChainPanel.SKSwapChainPanelJsInterop.CreateContext() in D:\a\1\s\source\SkiaSharp.Views.Uno\SkiaSharp.Views.Uno.Wasm\SKSwapChainPanel.Wasm.cs:line 183
   at SkiaSharp.Views.Windows.SKSwapChainPanel.DoLoaded() in D:\a\1\s\source\SkiaSharp.Views.Uno\SkiaSharp.Views.Uno.Wasm\SKSwapChainPanel.Wasm.cs:line 55
   at SkiaSharp.Views.Windows.SKSwapChainPanel.OnLoaded(Object sender, RoutedEventArgs e) in D:\a\1\s\source\SkiaSharp.Views.Uno\SkiaSharp.Views.Uno\SKSwapChainPanel.cs:line 128
   at Microsoft.UI.Xaml.FrameworkElement.<OnFwEltLoaded>g__InvokeLoaded|260_0() in /home/vsts/work/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.netstd.cs:line 83
   at Microsoft.UI.Xaml.FrameworkElement.<OnFwEltLoaded>g__InvokeLoadedWithTry|260_1() in /home/vsts/work/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.netstd.cs:line 96

**Comment by jeromelaban** [comment]
Thanks for the report. We're waiting on a SkiaSharp update (2.88.4) which contains fixes for the error you've posted above.

**Comment by jeromelaban** [comment]
The build is now published as 2.88.4-preview.84 on nuget.org.
