### ISSUE TITLE
The member/type is not implemented

### ISSUE THREAD

**Issue by long1bai** [unoplatform/uno#11187]
### Current behavior

Android使用`UserConsentVerifier.RequestVerificationAsync(String)` 方法会抛出异常。
{System.NotImplementedException: The member IAsyncOperation<UserConsentVerificationResult> UserConsentVerifier.RequestVerificationAsync(string message) is not implemented. For more information, visit https: //aka.platform.uno/notimplemented?m=IAsyncOperation%3CUserConsentVerificationResult%3E%20UserConsentVerifier.RequestVerificationAsync%28string%20message%29
   at Windows.Security.Credentials.UI.UserConsentVerifier.RequestVerificationAsync(String message) in C:\a\1\s\src\Uno.UWP\Generated\3.0.0.0\Windows.Security.Credentials.UI\UserConsentVerifier.cs:line 21
   at App1.MainPage.RequestConsent(String userMessage) in F:\l_project\project\Uno_project\App1\App1\MainPage.xaml.cs:line 103
}

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
## Note to contributors

This feature would need to be implemented in a similar fashion as `MessageDialog`:

https://github.com/unoplatform/uno/blob/0190ea92ffc138e1cc3259e59fdf2074cbc16465/src/Uno.UWP/UI/Popups/MessageDialog.cs#L19

**Comment by MartinZikmund** [comment]
Still relevant

**Comment by MartinZikmund** [comment]
# Repro generator

This issue was classified as not reproducible with a code sample or test.

**Reason:** This is a feature request for implementing the `UserConsentVerifier` API (currently throws `NotImplementedException`). It does not describe a bug in existing functionality that can be reproduced with a test.
