### ISSUE TITLE
[Playground] ComboBox- Getting error message and Combobox list is getting blank when choose any option from Combobox list.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#11334]
### Current behavior

https://user-images.githubusercontent.com/74563602/219252161-127ff1c0-2a21-4e5f-a0af-71a7df374277.mp4

![combobox issue](https://user-images.githubusercontent.com/74563602/219252396-5cf08423-391c-4654-b06a-2ad182ae14d4.png)

### Expected behavior

Combobox list should display properly.

### How to reproduce it (as minimally and precisely as possible)

1. Visit https://playgroundcanary.z19.web.core.windows.net/#passwordbox.
2. Go to the Snippets Listview.
3. Click on 'Combox' snippets option.
4. Click on the combobox list.
5. Observe that getting error message and Combobox list is getting blank when choose any option from Combobox list.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

**Comment by jeromelaban** [comment]
Exception for the issue:

```
System.NullReferenceException: Arg_NullReferenceException
   at Windows.UI.Xaml.Controls.VirtualizingPanelGenerator.RecycleViewForItem(FrameworkElement container, Int32 index, Boolean clearContainer)
   at Windows.UI.Xaml.Controls.VirtualizingPanelLayout.RecycleLine(Line line, Boolean clearContainer)
   at Windows.UI.Xaml.Controls.VirtualizingPanelLayout.ClearLines(Boolean clearContainer)
   at Windows.UI.Xaml.Controls.VirtualizingPanelLayout.Refresh()
   at Windows.UI.Xaml.Controls.Primitives.Selector.RefreshPartial()
   at Windows.UI.Xaml.Controls.Primitives.Selector.Refresh()
   at Windows.UI.Xaml.Controls.Primitives.Selector.OnItemsSourceChanged(DependencyPropertyChangedEventArgs e)
   at Windows.UI.Xaml.Controls.ItemsControl.<>c.<.cctor>b__207_4(DependencyObject s, DependencyPropertyChangedEventArgs e)
   at Windows.UI.Xaml.PropertyMetadata.RaisePropertyChanged(DependencyObject source, DependencyPropertyChangedEventArgs e)
   at Windows.UI.Xaml.DependencyObjectStore.InvokeCallbacks(DependencyObject actualInstanceAlias, DependencyProperty property, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence, Boolean bypassesPropagation)
   at Windows.UI.Xaml.DependencyObjectStore.RaiseCallbacks(DependencyObject actualInstanceAlias, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence)
   at Windows.UI.Xaml.DependencyObjectStore.InnerSetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isPersistentResourceBinding)
   at Windows.UI.Xaml.DependencyObjectStore.SetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isPersistentResourceBinding)
   at Windows.UI.Xaml.DependencyObjectExtensions.SetValue(Object instance, DependencyProperty property, Object value, Nullable`1 precedence)
   at Uno.UI.DataBinding.BindingPropertyHelper.<>c__DisplayClass42_9.<InternalGetValueSetter>b__13(Object instance, Object value)
   at Windows.UI.Xaml.Data.BindingExpression.SetTargetValue(Object value)
   at Windows.UI.Xaml.Data.BindingExpression.ApplyFallbackValue(Boolean useTypeDefaultValue)
   at Windows.UI.Xaml.Data.BindingExpression.<SetTargetValueSafe>g__SetTargetValueSafeWithTry|54_1(Object v, Boolean useTargetNullValue)
   at Windows.UI.Xaml.Data.BindingExpression.SetTargetValueSafe(Object v, Boolean useTargetNullValue)
   at Windows.UI.Xaml.Data.BindingExpression.SetTargetValueSafe(Object v)
   at Windows.UI.Xaml.Data.BindingExpression.Uno.UI.DataBinding.IValueChangedListener.OnValueChanged(Object o)
   at Uno.UI.DataBinding.BindingPath.Uno.UI.DataBinding.IValueChangedListener.OnValueChanged(Object o)
   at Uno.UI.DataBinding.BindingPath.BindingItem.RaiseValueChanged(Object newValue)
   at Uno.UI.DataBinding.BindingPath.BindingItem.OnDataContextChanged()
   at Uno.UI.DataBinding.BindingPath.BindingItem.SetWeakDataContext(ManagedWeakReference weakDataContext, Boolean transferReferenceOwnership)
   at Uno.UI.DataBinding.BindingPath.OnDataContextChanged()
   at Uno.UI.DataBinding.BindingPath.SetWeakDataContext(ManagedWeakReference weakDataContext)
   at Windows.UI.Xaml.Data.BindingExpression.ApplyBinding()
   at Windows.UI.Xaml.Data.BindingExpression.set_DataContext(Object value)
   at Windows.UI.Xaml.DependencyPropertyDetailsCollection.ApplyBinding(BindingExpression binding, Object dataContext)
   at Windows.UI.Xaml.DependencyPropertyDetailsCollection.ApplyDataContext(Object dataContext)
   at Windows.UI.Xaml.DependencyObjectStore.ApplyDataContext(Object actualDataContext)
   at Windows.UI.Xaml.DependencyObjectStore.OnDataContextChanged(Object providedDataContext, Object actualDataContext, DependencyPropertyValuePrecedences precedence)
   at Windows.UI.Xaml.DependencyObjectStore.InnerSetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isPersistentResourceBinding)
   at Windows.UI.Xaml.DependencyObjectStore.SetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isPersistentResourceBinding)
   at Windows.UI.Xaml.DependencyObjectStore.OnParentPropertyChangedCallback(ManagedWeakReference sourceInstance, DependencyProperty parentProperty, DependencyPropertyChangedEventArgs args)
   at Windows.UI.Xaml.DependencyObjectStore.CallChildCallback(DependencyObjectStore childStore, ManagedWeakReference instanceRef, DependencyProperty property, DependencyPropertyChangedEventArgs eventArgs)
   at Windows.UI.Xaml.DependencyObjectStore.InvokeCallbacks(DependencyObject actualInstanceAlias, DependencyProperty property, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence, Boolean bypassesPropagation)
   at Windows.UI.Xaml.DependencyObjectStore.RaiseCallbacks(DependencyObject actualInstanceAlias, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence)
   at Windows.UI.Xaml.DependencyObjectStore.InnerSetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isPersistentResourceBinding)
   at Windows.UI.Xaml.DependencyObjectStore.SetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isPersistentResourceBinding)
   at Windows.UI.Xaml.DependencyObjectStore.OnParentPropertyChangedCallback(ManagedWeakReference sourceInstance, DependencyProperty parentProperty, DependencyPropertyChangedEventArgs args)
   at Windows.UI.Xaml.DependencyObjectStore.CallChildCallback(DependencyObjectStore childStore, ManagedWeakReference instanceRef, DependencyProperty property, DependencyPropertyChangedEventArgs eventArgs)
   at Windows.UI.Xaml.DependencyObjectStore.InvokeCallbacks(DependencyObject actualInstanceAlias, DependencyProperty property, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence, Boolean bypassesPropagation)
   at Windows.UI.Xaml.DependencyObjectStore.RaiseCallbacks(DependencyObject actualInstanceAlias, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence)
   at Windows.UI.Xaml.DependencyObjectStore.InnerSetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isPersistentResourceBinding)
   at Windows.UI.Xaml.DependencyObjectStore.SetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isPersistentResourceBinding)
   at Windows.UI.Xaml.DependencyObjectStore.OnParentPropertyChangedCallback(ManagedWeakReference sourceInstance, DependencyProperty parentProperty, DependencyPropertyChangedEventArgs args)
   at Windows.UI.Xaml.DependencyObjectStore.CallChildCallback(DependencyObjectStore childStore, ManagedWeakReference instanceRef, DependencyProperty property, DependencyPropertyChangedEventArgs eventArgs)
   at Windows.UI.Xaml.DependencyObjectStore.InvokeCallbacks(DependencyObject actualInstanceAlias, DependencyProperty property, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence, Boolean bypassesPropagation)
   at Windows.UI.Xaml.DependencyObjectStore.RaiseCallbacks(DependencyObject actualInstanceAlias, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence)
   at Windows.UI.Xaml.DependencyObjectStore.InnerSetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isPersistentResourceBinding)
   at Windows.UI.Xaml.DependencyObjectStore.SetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isPersistentResourceBinding)
   at Windows.UI.Xaml.DependencyObjectStore.OnParentPropertyChangedCallback(ManagedWeakReference sourceInstance, DependencyProperty parentProperty, DependencyPropertyChangedEventArgs args)
   at Windows.UI.Xaml.DependencyObjectStore.CallChildCallback(DependencyObjectStore childStore, ManagedWeakReference instanceRef, DependencyProperty property, DependencyPropertyChangedEventArgs eventArgs)
   at Windows.UI.Xaml.DependencyObjectStore.InvokeCallbacks(DependencyObject actualInstanceAlias, DependencyProperty property, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence, Boolean bypassesPropagation)
   at Windows.UI.Xaml.DependencyObjectStore.RaiseCallbacks(DependencyObject actualInstanceAlias, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence)
   at Windows.UI.Xaml.DependencyObjectStore.InnerSetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isPersistentResourceBinding)
   at Windows.UI.Xaml.DependencyObjectStore.SetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isPersistentResourceBinding)
   at Windows.UI.Xaml.DependencyObjectStore.OnParentPropertyChangedCallback(ManagedWeakReference sourceInstance, DependencyProperty parentProperty, DependencyPropertyChangedEventArgs args)
   at Windows.UI.Xaml.DependencyObjectStore.CallChildCallback(DependencyObjectStore childStore, ManagedWeakReference instanceRef, DependencyProperty property, DependencyPropertyChangedEventArgs eventArgs)
   at Windows.UI.Xaml.DependencyObjectStore.InvokeCallbacks(DependencyObject actualInstanceAlias, DependencyProperty property, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence, Boolean bypassesPropagation)
   at Windows.UI.Xaml.DependencyObjectStore.RaiseCallbacks(DependencyObject actualInstanceAlias, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence)
   at Windows.UI.Xaml.DependencyObjectStore.InnerSetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isPersistentResourceBinding)
   at Windows.UI.Xaml.DependencyObjectStore.SetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isPersistentResourceBinding)
   at Windows.UI.Xaml.DependencyObjectStore.OnParentPropertyChangedCallback(ManagedWeakReference sourceInstance, DependencyProperty parentProperty, DependencyPropertyChangedEventArgs args)
   at Windows.UI.Xaml.DependencyObjectStore.CallChildCallback(DependencyObjectStore childStore, ManagedWeakReference instanceRef, DependencyProperty property, DependencyPropertyChangedEventArgs eventArgs)
   at Windows.UI.Xaml.DependencyObjectStore.InvokeCallbacks(DependencyObject actualInstanceAlias, DependencyProperty property, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence, Boolean bypassesPropagation)
   at Windows.UI.Xaml.DependencyObjectStore.RaiseCallbacks(DependencyObject actualInstanceAlias, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence)
   at Windows.UI.Xaml.DependencyObjectStore.InnerSetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isPersistentResourceBinding)
   at Windows.UI.Xaml.DependencyObjectStore.SetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isPersistentResourceBinding)
   at Windows.UI.Xaml.DependencyObjectStore.OnParentPropertyChangedCallback(ManagedWeakReference sourceInstance, DependencyProperty parentProperty, DependencyPropertyChangedEventArgs args)
   at Windows.UI.Xaml.DependencyObjectStore.CallChildCallback(DependencyObjectStore childStore, ManagedWeakReference instanceRef, DependencyProperty property, DependencyPropertyChangedEventArgs eventArgs)
   at Windows.UI.Xaml.DependencyObjectStore.InvokeCallbacks(DependencyObject actualInstanceAlias, DependencyProperty property, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence, Boolean bypassesPropagation)
   at Windows.UI.Xaml.DependencyObjectStore.RaiseCallbacks(DependencyObject actualInstanceAlias, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence)
   at Windows.UI.Xaml.DependencyObjectStore.InnerSetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isPersistentResourceBinding)
   at Windows.UI.Xaml.DependencyObjectStore.SetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isPersistentResourceBinding)
   at Windows.UI.Xaml.DependencyObjectStore.OnParentPropertyChangedCallback(ManagedWeakReference sourceInstance, DependencyProperty parentProperty, DependencyPropertyChangedEventArgs args)
   at Windows.UI.Xaml.DependencyObjectStore.CallChildCallback(DependencyObjectStore childStore, ManagedWeakReference instanceRef, DependencyProperty property, DependencyPropertyChangedEventArgs eventArgs)
   at Windows.UI.Xaml.DependencyObjectStore.InvokeCallbacks(DependencyObject actualInstanceAlias, DependencyProperty property, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence, Boolean bypassesPropagation)
   at Windows.UI.Xaml.DependencyObjectStore.RaiseCallbacks(DependencyObject actualInstanceAlias, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence)
   at Windows.UI.Xaml.DependencyObjectStore.InnerSetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isPersistentResourceBinding)
   at Windows.UI.Xaml.DependencyObjectStore.SetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isPersistentResourceBinding)
   at Windows.UI.Xaml.DependencyObjectStore.SetValue(DependencyProperty property, Object value)
   at Windows.UI.Xaml.UIElement.SetValue(DependencyProperty dp, Object value)
   at Windows.UI.Xaml.UIElement.set_DataContext(Object value)
   at Uno.UI.Demo.Samples.Playground.OnDataContextTextChanged(Object sender, TextChangedEventArgs e)
```
