### ISSUE TITLE
Android crash on net8

### ISSUE THREAD

**Issue by dansiegel** [unoplatform/uno#11839]
### Current behavior

When creating a project with net8 using the VS Uno App template the Android target crashes with the following stack:

```
{System.Reflection.TargetInvocationException}
"Exception has been thrown by the target of an invocation."
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at Java.Interop.TypeManager.CreateProxy(Type type, IntPtr handle, JniHandleOwnership transfer) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Interop/TypeManager.cs:line 334
   at Java.Interop.TypeManager.CreateInstance(IntPtr handle, JniHandleOwnership transfer, Type targetType) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Interop/TypeManager.cs:line 309
   at Java.Lang.Object.GetObject(IntPtr handle, JniHandleOwnership transfer, Type type) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Object.cs:line 304
   at Java.Lang.Object._GetObject[Application](IntPtr handle, JniHandleOwnership transfer) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Object.cs:line 290
   at Java.Lang.Object.GetObject[Application](IntPtr handle, JniHandleOwnership transfer) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Object.cs:line 281
   at Java.Lang.Object.GetObject[Application](IntPtr jnienv, IntPtr handle, JniHandleOwnership transfer) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Object.cs:line 275
   at Android.App.Application.n_OnCreate(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-33/mcw/Android.App.Application.cs:line 1081
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 27

{System.InvalidProgramException}
Unable to run method 'object Uno.UI.GlobalStaticResources/ResourceDictionarySingleton__SystemResources_5f92f4e5f4cf2cb9e7012d9dcb510f86:<get_SystemResources_5f92f4e5f4cf2cb9e7012d9dcb510f86_ResourceDictionary>b__1606_0 (object)': locals size too big.
   at Uno.UI.Xaml.WeakResourceInitializer.<>c__DisplayClass2_0.<.ctor>b__0() in C:\a\1\s\src\Uno.UI\UI\Xaml\WeakResourceInitializer.cs:line 28
   at Microsoft.UI.Xaml.ResourceDictionary.TryMaterializeLazy(ResourceKey& key, Object& value) in C:\a\1\s\src\Uno.UI\UI\Xaml\ResourceDictionary.cs:line 281
   at Microsoft.UI.Xaml.ResourceDictionary.TryMaterializeAll() in C:\a\1\s\src\Uno.UI\UI\Xaml\ResourceDictionary.cs:line 532
   at Microsoft.UI.Xaml.ResourceDictionary.GetEnumerator()+MoveNext() in C:\a\1\s\src\Uno.UI\UI\Xaml\ResourceDictionary.cs:line 491
   at Uno.UI.ResourceResolver.FindSymbolFontFamilyDictionary() in C:\a\1\s\src\Uno.UI\UI\Xaml\ResourceResolver.cs:line 158
   at Uno.UI.ResourceResolver.SetSymbolsFontFamily() in C:\a\1\s\src\Uno.UI\UI\Xaml\ResourceResolver.cs:line 127
   at Uno.UI.FeatureConfiguration.Font.set_SymbolsFont(String value) in C:\a\1\s\src\Uno.UI\FeatureConfiguration.cs:line 190
   at UnoApp1.AppHead.InitializeComponent_067AA826() in C:\Users\dansiegel\source\repos\UnoApp1\UnoApp1\UnoApp1.Mobile\obj\Debug\net8.0-android\g\XamlCodeGenerator\AppHead_c312f9d27d388a4db0d43d3cceee1f32.g.cs:line 92
   at UnoApp1.AppHead.InitializeComponent() in C:\Users\dansiegel\source\repos\UnoApp1\UnoApp1\UnoApp1.Mobile\obj\Debug\net8.0-android\g\XamlCodeGenerator\AppHead_c312f9d27d388a4db0d43d3cceee1f32.g.cs:line 58
   at UnoApp1.AppHead..ctor() in C:\Users\dansiegel\source\repos\UnoApp1\UnoApp1\UnoApp1.Base\AppHead.xaml.cs:line 11
   at UnoApp1.Droid.Application.<>c.<.ctor>b__0_0() in C:\Users\dansiegel\source\repos\UnoApp1\UnoApp1\UnoApp1.Mobile\Android\Main.Android.cs:line 26
   at Microsoft.UI.Xaml.NativeApplication..ctor(AppBuilder appBuilder, IntPtr javaReference, JniHandleOwnership transfer) in C:\a\1\s\src\Uno.UI\UI\Xaml\NativeApplication.cs:line 44
   at UnoApp1.Droid.Application..ctor(IntPtr javaReference, JniHandleOwnership transfer) in C:\Users\dansiegel\source\repos\UnoApp1\UnoApp1\UnoApp1.Mobile\Android\Main.Android.cs:line 26
   at System.Reflection.ConstructorInvoker.InterpretedInvoke(Object obj, IntPtr* args)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### Expected behavior

The app should start up without an error

### How to reproduce it (as minimally and precisely as possible)

[UnoApp1.zip](https://github.com/unoplatform/uno/files/11102989/UnoApp1.zip)

### Works on UWP/WinUI

None

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

4.8

### Affected platforms

Android, Solution Templates

### IDE

Visual Studio 2022

### IDE version

17.6.0 Preview 2.0

### Relevant plugins

Uno Platform Project Templates 4.8.8.8

### Anything else we need to know?

This was tested on a VM using the Visual Studio image on Azure.

**Comment by pictos** [comment]
Debugging on Android I could see this on Device Log, it says something about a virtual method on `AppHead.InitializeComponent`. I couldn't copy the text, since VS window doesn't allow that :/

![image](https://github.com/unoplatform/uno/assets/20712372/c23d74f3-0589-4c4a-9a55-09062f4c37c4)

**Comment by jeromelaban** [comment]
This issue is not happening anymore.
