### ISSUE TITLE
Random race condition happening in WPF runtime tests

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#12167]
### Current behavior

Very randomly, runtime WPF tests fail as follows:

```
      System.ArgumentException: SR.Argument_AddingDuplicate__
         at Uno.Collections.HashtableEx.Insert(Object key, Object nvalue, Boolean add) in D:\a\1\s\src\Uno.UWP\Collections\HashtableEx.cs:line 689
         at Windows.UI.Xaml.DependencyProperty.GetProperty(Type type, String name) in D:\a\1\s\src\Uno.UI\UI\Xaml\DependencyProperty.cs:line 333
         at Windows.UI.Xaml.DependencyObjectStore.OnParentPropertyChangedCallback(ManagedWeakReference sourceInstance, DependencyProperty parentProperty, Object newValue) in D:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 1084
         at Windows.UI.Xaml.DependencyObjectStore.<PropagateInheritedProperties>g__Propagate|151_0(DependencyObjectStore store, <>c__DisplayClass151_0&) in D:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 1558
         at Windows.UI.Xaml.DependencyObjectStore.PropagateInheritedProperties(DependencyObjectStore childStore)
         at Windows.UI.Xaml.DependencyObjectStore.RegisterInheritedPropertyChangedCallback(DependencyObjectStore childStore) in D:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 956
         at Windows.UI.Xaml.DependencyObjectStore.RegisterInheritedProperties(IDependencyObjectStoreProvider parentProvider) in D:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 1200
         at Windows.UI.Xaml.DependencyObjectStore.TryRegisterInheritedProperties(IDependencyObjectStoreProvider parentProvider, Boolean force) in D:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 1160
         at Windows.UI.Xaml.DependencyObjectStore.set_Parent(Object value) in D:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 161
         at Windows.UI.Xaml.Documents.InlineCollection..ctor(DependencyObject parent) in D:\a\1\s\src\Uno.UI\UI\Xaml\Documents\InlineCollection.cs:line 18
         at Windows.UI.Xaml.Controls.TextBlock.get_Inlines() in D:\a\1\s\src\Uno.UI\UI\Xaml\Controls\TextBlock\TextBlock.cs:line 90
         at Windows.UI.Xaml.Controls.TextBlock.ArrangeOverride(Size finalSize) in D:\a\1\s\src\Uno.UI\UI\Xaml\Controls\TextBlock\TextBlock.skia.cs:line 51
         at Windows.UI.Xaml.FrameworkElement.InnerArrangeCore(Rect finalRect) in D:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.Layout.netstd.cs:line 226
         at Windows.UI.Xaml.UIElement.Arrange(Rect finalRect) in D:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.Layout.netstd.cs:line 342
         at Windows.UI.Xaml.Controls.StackPanel.ArrangeOverride(Size arrangeSize) in D:\a\1\s\src\Uno.UI\UI\Xaml\Controls\StackPanel\StackPanel.Layout.cs:line 82
         at Windows.UI.Xaml.FrameworkElement.InnerArrangeCore(Rect finalRect) in D:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.Layout.netstd.cs:line 226
         at Windows.UI.Xaml.UIElement.Arrange(Rect finalRect) in D:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.Layout.netstd.cs:line 342
         at Windows.UI.Xaml.UIElement.Arrange(Rect finalRect) in D:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.Layout.netstd.cs:line 342
         at Windows.UI.Xaml.UIElement.Arrange(Rect finalRect) in D:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.Layout.netstd.cs:line 342
         at Windows.UI.Xaml.UIElement.Arrange(Rect finalRect) in D:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.Layout.netstd.cs:line 342
         at Windows.UI.Xaml.UIElement.Arrange(Rect finalRect) in D:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.Layout.netstd.cs:line 342
         at Windows.UI.Xaml.UIElement.Arrange(Rect finalRect) in D:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.Layout.netstd.cs:line 342
         at Windows.UI.Xaml.UIElement.Arrange(Rect finalRect) in D:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.Layout.netstd.cs:line 342
         at Windows.UI.Xaml.UIElement.Arrange(Rect finalRect) in D:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.Layout.netstd.cs:line 342
         at Windows.UI.Xaml.UIElement.Arrange(Rect finalRect) in D:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.Layout.netstd.cs:line 342
         at Windows.UI.Xaml.UIElement.Arrange(Rect finalRect) in D:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.Layout.netstd.cs:line 342
         at Windows.UI.Xaml.UIElement.Arrange(Rect finalRect) in D:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.Layout.netstd.cs:line 342
         at Windows.UI.Xaml.UIElement.Arrange(Rect finalRect) in D:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.Layout.netstd.cs:line 342
         at Windows.UI.Xaml.UIElement.Arrange(Rect finalRect) in D:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.Layout.netstd.cs:line 342
         at Windows.UI.Xaml.UIElement.Arrange(Rect finalRect) in D:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.Layout.netstd.cs:line 342
         at Windows.UI.Xaml.UIElement.Arrange(Rect finalRect) in D:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.Layout.netstd.cs:line 342
         at Windows.UI.Xaml.UIElement.Arrange(Rect finalRect) in D:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.Layout.netstd.cs:line 342
         at Windows.UI.Xaml.UIElement.Arrange(Rect finalRect) in D:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.Layout.netstd.cs:line 342
         at Windows.UI.Xaml.UIElement.Arrange(Rect finalRect) in D:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.Layout.netstd.cs:line 342
         at Uno.UI.XamlHost.Skia.Wpf.UnoXamlHostBase.ArrangeOverride(Size finalSize) in D:\a\1\s\src\Uno.UI.XamlHost.Skia.Wpf\UnoXamlHostBase.Layout.cs:line 47
         at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
         at System.Windows.UIElement.Arrange(Rect finalRect)
         at System.Windows.ContextLayoutManager.UpdateLayout()
         at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
         at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
         at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
         at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
         at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
         at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
         at System.Windows.Threading.DispatcherOperation.InvokeImpl()
         at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
```

### Works on UWP/WinUI

Yes

**Comment by Youssef1313** [comment]
```
         at Windows.UI.Xaml.Controls.TextBlock.get_Inlines() in D:\a\1\s\src\Uno.UI\UI\Xaml\Controls\TextBlock\TextBlock.cs:line 90
         at Windows.UI.Xaml.Controls.TextBlock.ArrangeOverride(Size finalSize) in D:\a\1\s\src\Uno.UI\UI\Xaml\Controls\TextBlock\TextBlock.skia.cs:line 51

```

@MartinZikmund Does it always involve TextBlock?

**Comment by MartinZikmund** [comment]
@Youssef1313 not completely sure. I have also seen #11538, which could be completely unrelated, but again seems like a race condition.

**Comment by MartinZikmund** [comment]
This was fixed in https://github.com/unoplatform/uno/pull/11983/ by ensuring `StyleHelper` runs on the UI thread
