### ISSUE TITLE
Uno.UI.Dispatching.CoreDispatcherSynchronizationContext unexpectedly null when using databinding in Microsoft.Xaml.UI.Controls.TabView

### ISSUE THREAD

**Issue by metacoresystems** [unoplatform/uno#12265]
### Current behavior

[UnoIssueRepro.zip](https://github.com/unoplatform/uno/files/11455870/UnoIssueRepro.zip)

I attach a simplified representative solution that consistently reproduces this unexpected behaviour. Note this is using Uno 4.7.37 running in a WebAssembly environment.

- I have a simple single main page that comprises a _Microsoft.Xaml.Controls.UI.TabView_ control bound to a list of tab view model items. Each tab's appearance is based upon the TabView's TabItemTemplate.
- Each _TabViewModelItem_ has a child list of _ItemViewModel_ items, which are displayed in the TabItemTemplate via use of an ItemsControl.
- Each of these ItemViewModel items has an _ObservableCollection_ of numbers which are returned by a _FakeNumbers_ ObservableCollection<int> property on the ItemViewModel.
- Each ItemViewModel is templated with a data template, that lists the _FakeNumbers_ list via the use of another ItemsControl which is bound to this property via its _ItemsSource_.
- When I first open the page, my _TabView_ control opens as expected on the first tab. The tab item template for the first tab is rendered, which contains the ItemsControl bound to the list of ItemViewModel items. The templates for each of these ItemViewModel items then causes the _FakeNumbers_ property to be fetched on ItemViewModel, by the data binding engine.
- For that first tab that is open, when I log the thread ID and presence of a dispatcher sync context using basic console logging in the _FakeNumbers_ ItemViewModel property:
`        public ObservableCollection<int> FakeNumbers
        {
            get
            {
                if (_fakeNumbers == null)
                {
                    _fakeNumbers = new ObservableCollection<int>();

                    Console.WriteLine($"#1 Thread ID {Thread.CurrentThread.ManagedThreadId} - {(SynchronizationContext.Current == null ? "<null>" : SynchronizationContext.Current.ToString())}");

                    _fakeAsyncService.FakeMethodAsync().ContinueWith(task =>
                    {
                        Console.WriteLine($"#3 Thread ID {Thread.CurrentThread.ManagedThreadId} - {(SynchronizationContext.Current == null ? "<null>" : SynchronizationContext.Current.ToString())}");

                        foreach (var number in task.Result)
                        {
                            _fakeNumbers.Add(number);
                        }
                    }, TaskScheduler.FromCurrentSynchronizationContext());
                }

                return _fakeNumbers;
            }
        }`
- I see as I would expect that the data binding engine when fetching the property has been called in a thread where the _SynchronizationContext_ is set to the Uno.UI.Dispatching.CoreDispatcherSynchronizationContext:

> #1 Thread ID 1 - Uno.UI.Dispatching.CoreDispatcherSynchronizationContext
> #2 Thread ID 1 - Uno.UI.Dispatching.CoreDispatcherSynchronizationContext
> #1 Thread ID 1 - Uno.UI.Dispatching.CoreDispatcherSynchronizationContext
> #2 Thread ID 1 - Uno.UI.Dispatching.CoreDispatcherSynchronizationContext
> #3 Thread ID 1 - Uno.UI.Dispatching.CoreDispatcherSynchronizationContext
> #3 Thread ID 1 - Uno.UI.Dispatching.CoreDispatcherSynchronizationContext

- This I would expect, as the data binding engine has gone to fetch the _FakeNumbers_ property on the WASM UI thead.
- However when I then switch to the second tab (which hasn't been rendered before), I am using the same view model structure and data. But, the same logging shows that when data binding goes to fetch the property the current _SynchronisationContext_ is not set. The same logging for the second tab:

> #1 Thread ID 1 - <null>
> #2 Thread ID 1 - <null>
> fail: Uno.UI.DataBinding.BindingPath+BindingItem[0]
>       Failed to get the source value for [FakeNumbers]
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
>  ---> System.InvalidOperationException: The current SynchronizationContext may not be used as a TaskScheduler.
>    at System.Threading.Tasks.SynchronizationContextTaskScheduler..ctor() in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\libraries\System.Private.CoreLib\src\System\Threading\Tasks\TaskScheduler.cs:line 577
>    at System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext() in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\libraries\System.Private.CoreLib\src\System\Threading\Tasks\TaskScheduler.cs:line 346
>    at UnoIssueRepro.ItemViewModel.get_FakeNumbers() in D:\Git\EntityForge\entity-forge\EntityForge.Framework.net7\UnoIssueRepro\UnoIssueRepro\ItemViewModel.cs:line 34
>    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\mono\System.Private.CoreLib\src\System\Reflection\MethodInvoker.Mono.cs:line 33
>    --- End of inner exception stack trace ---
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\libraries\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs:line 131
>    at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\libraries\System.Private.CoreLib\src\System\Reflection\MethodBase.cs:line 54
>    at Uno.UI.DataBinding.BindingPropertyHelper.<>c__DisplayClass12_0.<DefaultInvokerBuilder>b__0(Object instance, Object[] args) in /home/vsts/work/1/s/src/Uno.UI/DataBinding/BindingPropertyHelper.cs:line 81
>    at Uno.UI.DataBinding.BindingPropertyHelper.<>c__DisplayClass41_12.<InternalGetValueGetter>b__19(Object instance) in /home/vsts/work/1/s/src/Uno.UI/DataBinding/BindingPropertyHelper.cs:line 665
>    at Uno.UI.DataBinding.BindingPath.BindingItem.GetSourceValue(ValueGetterHandler getter) in /home/vsts/work/1/s/src/Uno.UI/DataBinding/BindingPath.cs:line 778
> fail: Uno.UI.DataBinding.BindingPropertyHelper[0]
>       The [Name] property getter does not exist on type [System.Int32]
> fail: Uno.UI.DataBinding.BindingPropertyHelper[0]
>       The [FakeNumbers] property getter does not exist on type [System.Int32]
> #1 Thread ID 1 - <null>
> #2 Thread ID 1 - <null>

- As you can see, on switching to the second tab, the Uno.UI.Dispatching.CoreDispatcherSynchronizationContext is no longer set to SynchronizationContext.Current as I would expect - it is null. Even though, curiously, the logging of the thread ID shows it is still the same thread that fetched the property successfully for the first open tab. This has caused the attempt to execute the continuation on the sync context to fail.

### Expected behavior

When I change to the second tab in UI, and the _FakeNumbers_ collection goes to be fetched by data binding, I expect the Uno.UI.Dispatching.CoreDispatcherSynchronizationContext to be set to SynchronizationContext.Current in the same way as it was when data binding fetched the _FakeNumbers_ collection in the first open tab.

This issue reproduces consistently using the attached solution.

### How to reproduce it (as minimally and precisely as possible)

Run the attached solution WASM project. Observe from the Output Window when the first tab opens that the Uno.UI.Dispatching.CoreDispatcherSynchronizationContext is set to SynchronizationContext.Current when data binding goes to fetch the _FakeNumbers_ ObservableCollection.

But now click on the second tab to display it. Observe that the same logging now shows that whilst the same thread is being used to fetch the _FakeNumbers_ collection, SynchronizationContext.Current is unexpectedly null.

### Workaround

None known at the moment.

### Works on UWP/WinUI

None

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno.Winui.WebAssembly 4.7.37

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

17.5.4

### Anything else we need to know?

I don't feel familiar enough with Uno and WebAssembly at the moment to amend the code.

**Comment by jeromelaban** [comment]
Thanks for the detailed analysis. This is a behavior that may be incorrect coming from the runtime, where some of the thread locals may incorrectly reset. It may also be a side-effect of some invocation not coming from the dispatcher itself (e.g. coming from a DOM event handler).

This looks similar to https://github.com/unoplatform/uno/issues/11257.

**Comment by MartinZikmund** [comment]
In progress

**Comment by MartinZikmund** [comment]
# Repro generator

Runtime test added in branch [`dev/mazi/repro/12265`](https://github.com/unoplatform/uno/compare/dev/mazi/repro/12265):
- `src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_TabView.SyncContext_12265.cs` → `Given_TabView_SyncContext_12265.When_Second_Tab_Selected_Binding_Has_SynchronizationContext_12265`

The test builds a `TabView` with two tabs, each bound to a VM whose `Numbers` getter captures `SynchronizationContext.Current`. After selecting the second tab, it asserts the captured context is non-null for both.

⚠️ The test **passes on Skia targets**. The issue was reported on **WebAssembly** (Uno 4.7.37), which is not covered by the Skia runtime test runner. PR #23024 adds the passing test as regression coverage; the WASM-specific sync-context propagation needs separate verification on WASM.
