### ISSUE TITLE
Changing a ScrollBar property in ScrollViewer's Template results in compilation errors

### ISSUE THREAD

**Issue by ramezgerges** [unoplatform/uno#12787]
### Current behavior

Changing the template of ScrollViewer to set the value of SmallChange of ScrollViewer's ScrollBar creates compilation errors (at least when I tried compiling for Skia).  The error has something to do with generating a merged xaml file.

```
  Uno.XamlMerge.Task.targets(15, 3): [MSB4018] The "BatchMergeXaml_f76645703193d279913d46c9181e0642bc79c095" task failed unexpectedly.
System.ArgumentOutOfRangeException: Insertion index was out of range. Must be non-negative and less than or equal to size.
Parameter name: index
   at System.Collections.ArrayList.Insert(Int32 index, Object value)
   at System.Xml.XmlNamedNodeMap.SmallXmlNodeList.Insert(Int32 index, Object value)
   at System.Xml.XmlNamedNodeMap.InsertNodeAt(Int32 i, XmlNode node)
   at System.Xml.XmlAttributeCollection.InsertNodeAt(Int32 i, XmlNode node)
   at System.Xml.XmlAttributeCollection.InsertAfter(XmlAttribute newNode, XmlAttribute refNode)
   at Uno.UI.Tasks.BatchMerge.BatchMergeXaml_f76645703193d279913d46c9181e0642bc79c095.BatchMerger.Merge(CustomTask owner, String mergedXamlFile, String projectFullPath, ITaskItem[] pageItems) in /_/src/Uno.XamlMerge.Task/BatchMergeXaml.cs:line 257
   at Uno.UI.Tasks.BatchMerge.BatchMergeXaml_f76645703193d279913d46c9181e0642bc79c095.Execute() in /_/src/Uno.XamlMerge.Task/BatchMergeXaml.cs:line 49
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

### How to reproduce it (as minimally and precisely as possible)

ramezgerges:uno:scrollviewer_scrolling_skia@3388733

### Workaround

Interestingly, everything works if I remove the line next to the added line in ramezgerges:uno:scrollviewer_scrolling_skia@3388733 or the line after that.

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
This is quite curious. This feels like a mixup with the ignorables, for some reason. Would you be able to add a test that tries to replicate the behavior in https://github.com/unoplatform/uno.xamlmerge.task/tree/main/src/Uno.XamlMerge.Tests ? Thanks!

**Comment by ramezgerges** [comment]
Here is a small repro:

```xaml
<ResourceDictionary
	xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
	xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
	xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
	xmlns:skia="http://uno.ui/skia"
	mc:Ignorable="skia">

	<Style TargetType="ScrollViewer">
		<Setter Property="Template">
			<Setter.Value>
				<ScrollBar
					Height="16"
					skia:Width="16" />
			</Setter.Value>
		</Setter>
	</Style>

</ResourceDictionary>
```

Note the fragility of the above repro. In the above snippet, if skia:Width and Height are swapped, the error goes away. If skia:Width becomes Width, the error goes away. If you remove mc:Ignorable, the error goes away.

**Comment by ramezgerges** [comment]
Here's a more complete environment for the problem: https://github.com/ramezgerges/uno.xamlmerge.task/tree/argoor_repro. Some changes were needed since the issue only reproduces on net461. You can find an added test here: https://github.com/ramezgerges/uno.xamlmerge.task/blob/argoor_repro/src/Uno.XamlMerge.Tests/Given_BatchMergeXaml.cs#L41C1.

**Comment by takla21** [comment]
I got the same issue on my side and indeed ordering properties set with ignorable does fix it as well. Also, one of you have a case like this

```xaml
<control ios:Property="test"/>
```
You still need to add a property after the ignorable one. In my case, I just added a `x:Name` so it does not affect the result
