### ISSUE TITLE
[Hot Restart] Exception raised when attempting to debug on device from VS Windows

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno#12948]
### Current behavior

Created a new app using the latest dev version of Uno.Templates.
Updated to latest uno packages
Attempted to run using Hot Restart on local device.
Raises the following exception:

EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.
   at Mono.Debugging.VisualStudio.ExceptionsAdapter.OnExceptionThrown(Object sender, TargetEventArgs args) in D:\a\_work\1\s\src\Debugging.VisualStudio.Vsix\Integration\ExceptionsAdapter.cs:line 56
   at Mono.Debugging.Client.DebuggerSession.OnTargetEvent(TargetEventArgs args) in D:\a\_work\1\s\External\debugger-libs\Mono.Debugging\Mono.Debugging.Client\DebuggerSession.cs:line 1254
   at Mono.Debugging.Soft.SoftDebuggerSession.HandleBreakEventSet(Event[] es, Boolean dequeuing) in D:\a\_work\1\s\External\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 2244
   at Mono.Debugging.Soft.SoftDebuggerSession.EventHandler() in D:\a\_work\1\s\External\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 1802

### Works on UWP/WinUI

None

### Anything else we need to know?

On older device (iphone 6S) the app is terminated by the OS before it raises the exception. Removing RemoteControl improves the startup performance enough for the app to launch to the point where the exception is thrown.

**Comment by jeromelaban** [comment]
Fixed in 5.0
