### ISSUE TITLE
[Playground][wasm]Button, ProgressBar, Card- Text is not visible in Dark Theme

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#13025]
### Current behavior

![Button failed1](https://github.com/unoplatform/uno/assets/74563602/f39b4252-43d4-4991-9060-99b4d95102b9)
![Progress failed](https://github.com/unoplatform/uno/assets/74563602/3c32834d-f95e-4758-9b92-64dd61a7d237)
![Card failed1](https://github.com/unoplatform/uno/assets/74563602/3ff639eb-edba-4610-a586-ef5e8748ac8d)

### Expected behavior

![Button correct 2](https://github.com/unoplatform/uno/assets/74563602/675abec6-46f1-4c53-89a2-e72546533437)
![progress correct](https://github.com/unoplatform/uno/assets/74563602/5cb0ab18-395b-4c55-9035-958c2f86187f)
![Card correct1](https://github.com/unoplatform/uno/assets/74563602/82bee6c0-a4a9-432d-9cf1-ae978910b386)

### How to reproduce it (as minimally and precisely as possible)

1. Visit https://playgroundcanary.z19.web.core.windows.net/#passwordbox.
2. Go to the Snippets Listview.
3. Click on 'Button' or 'Card' or 'ProgressBar' snippets option.
4. Click checkbox for dark theme.
5. Observe that  the displayed text for the selected sample is not visible in dark theme.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

**Comment by jeromelaban** [comment]
This issue is caused by samples not specifying theme resources for brushes.

**Comment by carlh98** [comment]
The xaml that is used has Foreground harcoded for the styles, removing the values, fixes the issues since it falls back to the style of the control.
![image](https://github.com/unoplatform/uno/assets/7770915/c733ab63-a252-4fe0-a15d-07004f391bf7)

@agneszitte I do not know where playground gets the xaml for the example, can you point me in the right direction?

**Comment by agneszitte** [comment]
@carlh98 prepare the snippets and share the saved links in the issue please, we will do the update when @jeromelaban and @carldebilly will be back next week

**Comment by carlh98** [comment]
Snippets
[PasswordBox](https://playgroundcanary.z19.web.core.windows.net/#425c8a98)
[ProgressBar](https://playgroundcanary.z19.web.core.windows.net/#b37eb58d)

I created a [PR draft](https://github.com/unoplatform/Uno.Playground/pull/440), but I was not able to test locally, after updating to the latest VS Preview (17.8.0 Preview 1.0) I'm getting the following error, I tried updating the bootstrap packages but I'm getting the same error

```
2>C:\Users\ch.mathieu\.nuget\packages\uno.wasm.bootstrap\8.0.0-dev.235\build\Uno.Wasm.Bootstrap.targets(204,3): error : System.Exception: Failed to execute the linker
2>C:\Users\ch.mathieu\.nuget\packages\uno.wasm.bootstrap\8.0.0-dev.235\build\Uno.Wasm.Bootstrap.targets(204,3): error :    at Uno.Wasm.Bootstrap.ShellTask_vc93fd98a085e94454c124782127efd35ac168bc9.RunPackager() in /_/src/Uno.Wasm.Bootstrap/ShellTask.cs:line 1023
2>C:\Users\ch.mathieu\.nuget\packages\uno.wasm.bootstrap\8.0.0-dev.235\build\Uno.Wasm.Bootstrap.targets(204,3): error :    at Uno.Wasm.Bootstrap.ShellTask_vc93fd98a085e94454c124782127efd35ac168bc9.Execute() in /_/src/Uno.Wasm.Bootstrap/ShellTask.cs:line 266
2>Done building project "Uno.Playground.WASM.csproj" -- FAILED.
```

**Comment by MartinZikmund** [comment]
@ebariche it seems this same problem is now happening in multiple places, any chance you could look into what could be causing it?

**Comment by silviuo** [comment]
Following up on @agneszitte's post in unoventive, here is an issue I discovered when comparing snippets under the three Uno Playground variants (Canary, Staging, Prod):

CalendarView - On Prod only, the down arrow icon shows as the up arrow:

current: 
![image](https://github.com/unoplatform/uno/assets/10283398/5d86122b-f869-48b0-bddf-df82092b9609)

expected: 
![image](https://github.com/unoplatform/uno/assets/10283398/120f6465-4d91-4517-aa9f-c00cbdb90953)

**Comment by jeromelaban** [comment]
@silviuo interesting! Could you open individual issues for what you've found?

**Comment by silviuo** [comment]
@jeromelaban I created separate issues for the problems I mentioned in the previous comment.

Related to this particular issue, however, besides the already mentioned snippets (Button, Cards, PasswordBox, ProgressBar), I also found the following that don't display some of the text in dark mode:

- CheckBox, Image, Path, RadioButton, Shape, ToggleButton - because of labels using hardcoded TextBlock Foreground values
e.g.
![image](https://github.com/unoplatform/uno/assets/10283398/4fad4954-3c5e-4491-8b76-90f156375302)

- Panels, TextBlock - because of TextBlocks styled with "SampleSectionTextBlockStyle" StaticResource
e.g.
![image](https://github.com/unoplatform/uno/assets/10283398/eb2d3dcb-2df9-4b3e-bcd9-25967ded0d32)

- TextBox - because of TextBoxes styled with "AndroidTextBoxStyle" StaticResource
e.g.
![image](https://github.com/unoplatform/uno/assets/10283398/544ffe9c-6b8d-44ba-bb09-fcc129497756)

**Comment by agneszitte** [comment]
@silviuo can you share the links of the other issues you opened please

**Comment by silviuo** [comment]
> @silviuo can you share the links of the other issues you opened please

@agneszitte 

https://github.com/unoplatform/uno/issues/13282

https://github.com/unoplatform/uno/issues/13283
