### ISSUE TITLE
XAML generation throws in design-time builds in Uno solution

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#13054]
### Current behavior

```
System.Exception: 'Processing failed for file C:\Users\PC\Desktop\uno\src\Uno.UI\UI\Xaml\Style\mergedstyles.xaml (Uno.UI.SourceGenerators.XamlGenerator.XamlParsingException: An error was found in VisualStateGroup ---> System.InvalidOperationException: Unable to resolve UnoViewGroup (Reason: None, Location:Unknown, Candidates: )
```

```
   at Uno.Roslyn.RoslynMetadataHelper.ThrowOnErrorSymbol(ISymbol symbol) in C:\Users\PC\Desktop\uno\src\SourceGenerators\Uno.UI.SourceGenerators\RoslynMetadataHelper.cs:line 51
   at Uno.Roslyn.RoslynMetadataHelper.SourceFindPropertyTypeByOwnerSymbol(INamedTypeSymbol type, String propertyName) in C:\Users\PC\Desktop\uno\src\SourceGenerators\Uno.UI.SourceGenerators\RoslynMetadataHelper.cs:line 168
   at Uno.Extensions.FuncMemoizeExtensions.<>c__DisplayClass8_0`3.<AsLockedMemoized>b__1(CachedTuple`2 k) in C:\Users\PC\Desktop\uno\src\Uno.Foundation\Uno.Core.Extensions\Uno.Core.Extensions\FuncMemoizeExtensions.cs:line 253
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Uno.Extensions.FuncMemoizeExtensions.<>c__DisplayClass8_0`3.<AsLockedMemoized>b__0(TArg1 arg1, TArg2 arg2) in C:\Users\PC\Desktop\uno\src\Uno.Foundation\Uno.Core.Extensions\Uno.Core.Extensions\FuncMemoizeExtensions.cs:line 249
   at Uno.Roslyn.RoslynMetadataHelper.FindPropertyTypeByOwnerSymbol(INamedTypeSymbol type, String propertyName) in C:\Users\PC\Desktop\uno\src\SourceGenerators\Uno.UI.SourceGenerators\RoslynMetadataHelper.cs:line 160
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildChild(IIndentedStringBuilder writer, XamlMemberDefinition owner, XamlObjectDefinition xamlObjectDefinition, String outerClosure) in C:\Users\PC\Desktop\uno\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 5825
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildLiteralPropertiesWithFilter(IIndentedStringBuilder writer, XamlObjectDefinition objectDefinition, String closureName, IEnumerable`1 extendedProperties, Func`2 propertyPredicate) in C:\Users\PC\Desktop\uno\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 5517
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildLiteralLazyVisualStateManagerProperties(IIndentedStringBuilder writer, XamlObjectDefinition objectDefinition, String closureName) in C:\Users\PC\Desktop\uno\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 5394
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildExtendedProperties(IIndentedStringBuilder outerwriter, XamlObjectDefinition objectDefinition, Boolean useGenericApply) in C:\Users\PC\Desktop\uno\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 3478
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildChild(IIndentedStringBuilder writer, XamlMemberDefinition owner, XamlObjectDefinition xamlObjectDefinition, String outerClosure) in C:\Users\PC\Desktop\uno\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 5907
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildProperties(IIndentedStringBuilder writer, XamlObjectDefinition topLevelControl, Boolean isInline, String closureName, Boolean useBase) in C:\Users\PC\Desktop\uno\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 2413
```

### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment]
I think there are two separate problems here:

1. We throw for error symbols
2. UnoViewGroup (written in Java) isn't properly seen in design-time builds

I think we shouldn't throw an exception for error symbols anyway.

**Comment by Youssef1313** [comment]
Yup, that is the point `2` in my previous comment.

Still, I don't think we should throw anyway. Consider a user project where he still has some code errors causing some error symbols. We shouldn't throw in this case, I think.

**Comment by Youssef1313** [comment]
https://github.com/unoplatform/uno/blob/e895f7893dd9619920c8a6ad55f81904cdc04f27/src/Uno.UI.BindingHelper.Android/Uno.UI.BindingHelper.Android.netcoremobile.csproj#L83

Why did this condition exist?

**Comment by jeromelaban** [comment]
> Why did this condition exist?

I don't recall specifically. Maybe there was a very old performance issue that got solved. We could try removing it.

**Comment by MartinZikmund** [comment]
This is only relevant to Android native, correct? @Youssef1313

**Comment by MartinZikmund** [comment]
# Repro generator

This issue was classified as not reproducible with a code sample or test.

**Reason:** The report describes an error thrown specifically during **design-time (IDE) builds** of `src/Uno.UI/UI/Xaml/Style/mergedstyles.xaml` inside the Uno solution itself. The "How to reproduce" and "Affected platforms" sections are empty, so the exact target/configuration/platform toggle that triggers `Unable to resolve UnoViewGroup` is unspecified. Design-time-only generator failures depend on the IDE state and currently-loaded solution filter rather than runtime behavior, and cannot be captured in a runtime or source-generator test without a deterministic repro path.

**Comment by Youssef1313** [comment]
> This is only relevant to Android native, correct? [@Youssef1313](https://github.com/Youssef1313)

@MartinZikmund Sorry missed your question earlier. Not really native-only. There are basically two concerns:

1. Generally throwing exceptions for error symbols. This is not a good idea to make and not specific to native Android. It's better if generators gracefully handle error symbols.
2. Specific to native Android: the `DesignTimeBuild` condition is buggy. But it seems like it was removed at some point.
