### ISSUE TITLE
XamlReader fails to parse ResourceDictionary.MergedDictionaries

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno#13100]
### Current behavior
Given the following XAML
```xml
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
					xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
	<ResourceDictionary.MergedDictionaries>
		<ResourceDictionary>
			<Color x:Key="MyColor">Red</Color>
		</ResourceDictionary>
	</ResourceDictionary.MergedDictionaries>
</ResourceDictionary>
```

XamlReader fails with

```
System.InvalidOperationException: The property System.Collections.Generic.IList`1[Windows.UI.Xaml.ResourceDictionary] MergedDictionaries type does not provide an Add method (Line 8:41
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.ProcessMemberElements(Object instance, XamlMemberDefinition member, PropertyInfo propertyInfo, Object rootInstance)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.ProcessNamedMember(XamlObjectDefinition control, Object instance, XamlMemberDefinition member, Object rootInstance)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.LoadObject(XamlObjectDefinition control, Object rootInstance, Object component, Boolean createInstanceFromXClass)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.ProcessMemberElements(Object instance, XamlMemberDefinition member, PropertyInfo propertyInfo, Object rootInstance)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.ProcessNamedMember(XamlObjectDefinition control, Object instance, XamlMemberDefinition member, Object rootInstance)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.LoadObject(XamlObjectDefinition control, Object rootInstance, Object component, Boolean createInstanceFromXClass)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.AddCollectionItems(Object collectionInstance, IEnumerable`1 nonBindingObjects, Object rootInstance)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.ProcessMemberElements(Object instance, XamlMemberDefinition member, PropertyInfo propertyInfo, Object rootInstance)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.ProcessNamedMember(XamlObjectDefinition control, Object instance, XamlMemberDefinition member, Object rootInstance)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.LoadObject(XamlObjectDefinition control, Object rootInstance, Object component, Boolean createInstanceFromXClass)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.Build(Object component, Boolean createInstanceFromXClass)
   at Windows.UI.Xaml.Markup.XamlReader.Load(String xaml)
   at Uno.UI.Demo.Samples.Playground.Update()
```

### Expected behavior
Should work

### Works on UWP/WinUI
Yes

**Comment by kazo0** [comment]
Whoever takes this on, please ping me as this branch should have a good start on this: https://github.com/unoplatform/uno/tree/dev/sb/xamlreader-bugs

**Comment by MartinZikmund** [comment]
Reopening for backport
