### ISSUE TITLE
Uno Platform .NET 7 unable to build with latest dev packages

### ISSUE THREAD

**Issue by jbtdevgit** [unoplatform/uno#13175]
### Current behavior
Unable to build an UNO project created with the .NET 7 template after updating `uno-dev` packages. 
Attached file is here [UnoApp1.zip](https://github.com/unoplatform/uno/files/12298160/UnoApp1.zip) but either way it should be easy to reproduce by the steps provided
Error shown below -- there should be multiple errors shown so it will be better to reproduce it in a project

Following this issue https://github.com/unoplatform/uno/discussions/13152#discussioncomment-6659581 did not help.
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	UXAML0001	
Processing failed for file D:\UnoApp1\UnoApp1\MainPage.xaml (Uno.UI.SourceGenerators.XamlGenerator.XamlParsingException: An error was found in Page ---> Uno.UI.SourceGenerators.XamlGenerator.XamlParsingException: An error was found in StackPanel ---> System.Exception: Expected end of x:Bind expression or start of argument list.
   at Uno.UI.SourceGenerators.XamlGenerator.Utils.XBindExpressionParser.CoreParser.ParseXBind()
   at Uno.UI.SourceGenerators.XamlGenerator.Utils.XBindExpressionParser.Rewrite(String contextName, String rawFunction, INamedTypeSymbol contextTypeSymbol, INamespaceSymbol globalNamespace, Boolean isRValue, Int32 xBindCounter, Func`2 findType)
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildXBindEvalFunction(XamlMemberDefinition member, XamlObjectDefinition bindNode)
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.<>c__DisplayClass175_0.<BuildComplexPropertyValue>g__WriteBinding|9(Boolean isTemplateBindingAttachedProperty, String prefix, <>c__DisplayClass175_1& , <>c__DisplayClass175_2& )
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildComplexPropertyValue(IIndentedStringBuilder writer, XamlMemberDefinition member, String prefix, String closureName, Boolean generateAssignation, ComponentDefinition componentDefinition)
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildExtendedProperties(IIndentedStringBuilder outerwriter, XamlObjectDefinition objectDefinition, Boolean useGenericApply)
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildChild(IIndentedStringBuilder writer, XamlMemberDefinition owner, XamlObjectDefinition xamlObjectDefinition, String outerClosure)
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildProperties(IIndentedStringBuilder writer, XamlObjectDefinition topLevelControl, Boolean isInline, String closureName, Boolean useBase)
   --- End of inner exception stack trace ---
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildProperties(IIndentedStringBuilder writer, XamlObjectDefinition topLevelControl, Boolean isInline, String closureName, Boolean useBase)
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildChild(IIndentedStringBuilder writer, XamlMemberDefinition owner, XamlObjectDefinition xamlObjectDefinition, String outerClosure)
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildProperties(IIndentedStringBuilder writer, XamlObjectDefinition topLevelControl, Boolean isInline, String closureName, Boolean useBase)
   --- End of inner exception stack trace ---
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildProperties(IIndentedStringBuilder writer, XamlObjectDefinition topLevelControl, Boolean isInline, String closureName, Boolean useBase)
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildGenericControlInitializerBody(IndentedStringBuilder writer, XamlObjectDefinition topLevelControl)
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildInitializeComponent(IndentedStringBuilder writer, XamlObjectDefinition topLevelControl, INamedTypeSymbol controlBaseType)
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.InnerGenerateFile()
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GenerateFile())	UnoApp1 (net7.0)	D:\UnoApp1\UnoApp1\UnoApp1.csproj	1	Active

```

### How to reproduce it (as minimally and precisely as possible)

- Create a new project using the template targeting .NET7
  - Platforms (`iOS`, `Mac Catalyst`, `Android`, `Windows`)
- Include `Dependency Injection`, `MVVM`, `Uno.Toolkit`
- Create a `ViewModel`
- Use `{x:Bind YourViewModel.YourProperty}` to bind the `View` and `ViewModel` via `DataContext` in code behind 
  - i.e
  - `this.DataContext = (Application.Current as App).Host?.Services.GetRequiredService<YourViewModel>();`
  - public YourViewModel ViewModel => (YourViewModel)DataContext;
 - Update packages to latest `5.0.*-dev-*` version
```
<PackageReference Include="Uno.Extensions" />
<PackageReference Include="Uno.WinUI" />
<PackageReference Include="Uno.Resizetizer" />
<PackageReference Include="Uno.Extensions.Toolkit.WinUI" />
<PackageReference Include="Uno.Toolkit.WinUI" />
<PackageReference Include="Uno.Extensions.Hosting.WinUI" />
```

### Works on UWP/WinUI

None

### NuGet package version(s)

```
<ItemGroup>
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.2.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="7.0.0" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.756" />
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="1.3.230502000" />
    <!-- Use previous version for unpackaged apps due to build issue https://github.com/microsoft/WindowsAppSDK/issues/3591 -->
    <!-- <PackageVersion Include="Microsoft.WindowsAppSDK" Version="1.2.230313.1" /> -->
    <PackageVersion Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.1" />
    <PackageVersion Include="Uno.Extensions.Hosting" Version="2.4.2" />
    <PackageVersion Include="Uno.Extensions.Hosting.WinUI" Version="3.0.0-dev.2138" />
    <PackageVersion Include="Uno.Extensions.Logging.OSLog" Version="1.4.0" />
    <PackageVersion Include="Uno.Toolkit.WinUI" Version="4.0.0-dev.67" />
    <PackageVersion Include="Uno.Extensions.Toolkit.WinUI" Version="3.0.0-dev.2138" />
    <PackageVersion Include="Uno.Resizetizer" Version="1.1.2" />
    <PackageVersion Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.9.45" />
    <PackageVersion Include="Uno.UniversalImageLoader" Version="1.9.36" />
    <PackageVersion Include="Uno.WinUI" Version="5.0.0-dev.1911" />
    <PackageVersion Include="Uno.WinUI.RemoteControl" Version="4.9.45" />
    <PackageVersion Include="Xamarin.Google.Android.Material" Version="1.8.0" />
  </ItemGroup>
```

### IDE

Visual Studio 2022

**Comment by limeniye** [comment]
You are updated only the ```"Uno.WinUI" Version="5.0.0-dev.1911"``` package.
Please, check the following example https://github.com/unoplatform/uno/discussions/13152#discussioncomment-6659581

**Comment by limeniye** [comment]
Updated. I did it with your attached archive. The package problem was resolved.

```XML
<Project ToolsVersion="15.0">
  <ItemGroup>
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.2.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="7.0.0" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.756" />
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="1.3.230502000" />
    <PackageVersion Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.1" />
    <PackageVersion Include="Uno.Extensions.Hosting" Version="2.4.2" />
    <PackageVersion Include="Uno.Extensions.Hosting.WinUI" Version="3.0.0-dev.2138" />
    <PackageVersion Include="Uno.Extensions.Logging.OSLog" Version="1.4.0" />
    <PackageVersion Include="Uno.Toolkit.WinUI" Version="4.0.0-dev.67" />
    <PackageVersion Include="Uno.Extensions.Toolkit.WinUI" Version="3.0.0-dev.2138" />
    <PackageVersion Include="Uno.Resizetizer" Version="1.1.2" />
    <PackageVersion Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="5.0.0-dev.1911" />
    <PackageVersion Include="Uno.WinUI.RemoteControl" Version="5.0.0-dev.1911" />	
    <PackageVersion Include="Uno.WinUI" Version="5.0.0-dev.1911" />	
    <PackageVersion Include="Uno.UniversalImageLoader" Version="1.9.36" />
    <PackageVersion Include="Xamarin.Google.Android.Material" Version="1.8.0" />
  </ItemGroup>
</Project>
```

**Comment by jbtdevgit** [comment]
> #### Updated
> I did it with your attached archive. The package problem was resolved.
> ```
> <Project ToolsVersion="15.0">
>   <ItemGroup>
>     <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.2.0" />
>     <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="7.0.0" />
>     <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.756" />
>     <PackageVersion Include="Microsoft.WindowsAppSDK" Version="1.3.230502000" />
>     <PackageVersion Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.1" />
>     <PackageVersion Include="Uno.Extensions.Hosting" Version="2.4.2" />
>     <PackageVersion Include="Uno.Extensions.Hosting.WinUI" Version="3.0.0-dev.2138" />
>     <PackageVersion Include="Uno.Extensions.Logging.OSLog" Version="1.4.0" />
>     <PackageVersion Include="Uno.Toolkit.WinUI" Version="4.0.0-dev.67" />
>     <PackageVersion Include="Uno.Extensions.Toolkit.WinUI" Version="3.0.0-dev.2138" />
>     <PackageVersion Include="Uno.Resizetizer" Version="1.1.2" />
>     <PackageVersion Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="5.0.0-dev.1911" />
>     <PackageVersion Include="Uno.WinUI.RemoteControl" Version="5.0.0-dev.1911" />	
>     <PackageVersion Include="Uno.WinUI" Version="5.0.0-dev.1911" />	
>     <PackageVersion Include="Uno.UniversalImageLoader" Version="1.9.36" />
>     <PackageVersion Include="Xamarin.Google.Android.Material" Version="1.8.0" />
>   </ItemGroup>
> </Project>
> ```

Hi @limeniye ,
Thanks for this, tried updating with the one you have said, I am having problems with `Uno.Extensions` `3.0.0-dev.1957` as well, throwing the same error, but the rest of the packages are working great!

**Comment by limeniye** [comment]
You have some "x:Bind" error exception.
I commented your MainPage.xaml file.
![image](https://github.com/unoplatform/uno/assets/69314237/f0bb99a4-d787-4a62-854e-be618835de81)

**Comment by jbtdevgit** [comment]
> You have some "x:Bind" error exception. I commented your MainPage.xaml file. ![image](https://user-images.githubusercontent.com/69314237/259335509-f0bb99a4-d787-4a62-854e-be618835de81.png)
> 
> Also you have some Host exception. But this two problems is another topic. I think you can close this Issue.
> 
> ![image](https://user-images.githubusercontent.com/69314237/259336164-3a4595ea-8844-4317-adf8-9cacc6d9f128.png)

Gotcha, thanks, will close the issue now.

**Comment by limeniye** [comment]
Also I want to say that you have a version difference again:

![image](https://github.com/unoplatform/uno/assets/69314237/98c70637-4969-4318-bc62-c48c9ce54916)
