### ISSUE TITLE
MediaPlayer tests are failing too often

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#13384]
### Current behavior

When_MediaPlayerElement_AutoPlay_Source
When_MediaPlayerElement_NotAutoPlay_Source
When_MediaPlayerElement_SetIsFullWindow_Check_Fullscreen
When_MediaPlayerElement_SetSource_Check_PlayStop

It is likely caused by the URL that may not always be available. Let's use uno assets site instead (maybe with a version of the file that is smaller than 5MB).

```
---
	Details:
Failed: When_MediaPlayerElement_AutoPlay_Source() [Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException] 
 Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Timed out waiting for condition to be met. Windows.UI.Xaml.Controls.MediaPlayerElement loaded
   at Private.Infrastructure.TestServices.WindowHelper.WaitFor(Func`1 condition, Int32 timeoutMS, String message, String callerMemberName, Int32 lineNumber)
   at Private.Infrastructure.TestServices.WindowHelper.<>c__DisplayClass33_0.<<WaitForLoaded>g__Do|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Private.Infrastructure.TestServices.WindowHelper.WaitForLoaded(FrameworkElement element, Int32 timeoutMS)
   at Uno.UI.RuntimeTests.Tests.Windows_UI_Xaml_Controls.Given_MediaPlayerElement.When_MediaPlayerElement_AutoPlay_Source()
   at Uno.UI.Samples.Tests.UnitTestsControl.<>c__DisplayClass63_1.<<ExecuteTestsForInstance>g__InvokeTestMethod|2>d.MoveNext()

Failed: When_MediaPlayerElement_NotAutoPlay_Source() [Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException] 
 Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Timed out waiting for condition to be met. Windows.UI.Xaml.Controls.MediaPlayerElement loaded
   at Private.Infrastructure.TestServices.WindowHelper.WaitFor(Func`1 condition, Int32 timeoutMS, String message, String callerMemberName, Int32 lineNumber)
   at Private.Infrastructure.TestServices.WindowHelper.<>c__DisplayClass33_0.<<WaitForLoaded>g__Do|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Private.Infrastructure.TestServices.WindowHelper.WaitForLoaded(FrameworkElement element, Int32 timeoutMS)
   at Uno.UI.RuntimeTests.Tests.Windows_UI_Xaml_Controls.Given_MediaPlayerElement.When_MediaPlayerElement_NotAutoPlay_Source()
   at Uno.UI.Samples.Tests.UnitTestsControl.<>c__DisplayClass63_1.<<ExecuteTestsForInstance>g__InvokeTestMethod|2>d.MoveNext()

Failed: When_MediaPlayerElement_SetIsFullWindow_Check_Fullscreen() [Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException] 
 Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Timed out waiting for condition to be met. Windows.UI.Xaml.Controls.MediaPlayerElement loaded
   at Private.Infrastructure.TestServices.WindowHelper.WaitFor(Func`1 condition, Int32 timeoutMS, String message, String callerMemberName, Int32 lineNumber)
   at Private.Infrastructure.TestServices.WindowHelper.<>c__DisplayClass33_0.<<WaitForLoaded>g__Do|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Private.Infrastructure.TestServices.WindowHelper.WaitForLoaded(FrameworkElement element, Int32 timeoutMS)
   at Uno.UI.RuntimeTests.Tests.Windows_UI_Xaml_Controls.Given_MediaPlayerElement.When_MediaPlayerElement_SetIsFullWindow_Check_Fullscreen()
   at Uno.UI.Samples.Tests.UnitTestsControl.<>c__DisplayClass63_1.<<ExecuteTestsForInstance>g__InvokeTestMethod|2>d.MoveNext()

Failed: When_MediaPlayerElement_SetSource_Check_PlayStop() [Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException] 
 Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Timed out waiting for condition to be met. Windows.UI.Xaml.Controls.MediaPlayerElement loaded
   at Private.Infrastructure.TestServices.WindowHelper.WaitFor(Func`1 condition, Int32 timeoutMS, String message, String callerMemberName, Int32 lineNumber)
   at Private.Infrastructure.TestServices.WindowHelper.<>c__DisplayClass33_0.<<WaitForLoaded>g__Do|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Private.Infrastructure.TestServices.WindowHelper.WaitForLoaded(FrameworkElement element, Int32 timeoutMS)
   at Uno.UI.RuntimeTests.Tests.Windows_UI_Xaml_Contr
```

### Expected behavior

No failure.

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
@rafael-rosa-knowcode I'm also adding `When_MediaPlayerElement_SetIsFullWindow_Check_Fullscreen` for android, which fails this way:

```
Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Timed out waiting for condition to be met. Windows.UI.Xaml.Controls.MediaPlayerElement loaded
   at Private.Infrastructure.TestServices.WindowHelper.WaitFor(Func`1 condition, Int32 timeoutMS, String message, String callerMemberName, Int32 lineNumber)
   at Private.Infrastructure.TestServices.WindowHelper.<>c__DisplayClass33_0.<<WaitForLoaded>g__Do|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Private.Infrastructure.TestServices.WindowHelper.WaitForLoaded(FrameworkElement element, Int32 timeoutMS)
   at Uno.UI.RuntimeTests.Tests.Windows_UI_Xaml_Controls.Given_MediaPlayerElement.When_MediaPlayerElement_SetIsFullWindow_Check_Fullscreen()
   at Uno.UI.Samples.Tests.UnitTestsControl.<>c__DisplayClass63_1.<<ExecuteTestsForInstance>g__InvokeTestMethod|2>d.MoveNext()
```

**Comment by MartinZikmund** [comment]
Still relevant

**Comment by MartinZikmund** [comment]
# Repro generator

This issue was classified as not reproducible with a separate code sample or test.

**Reason:** The four referenced tests (`When_MediaPlayerElement_AutoPlay_Source`, `_NotAutoPlay_Source`, `_SetIsFullWindow_Check_Fullscreen`, `_SetSource_Check_PlayStop`) already exist in `src/Uno.UI.RuntimeTests`. The bug is CI-only flakiness driven by the external test video URL availability and download time, not a defect in product code or a missing repro. Resolution is a flakiness fix on the existing tests (e.g. switch to a small Uno-hosted asset).
