### ISSUE TITLE
[WASM] 'No file descriptors available' exception on Windows.Storage code

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#13432]
### Current behavior

I'm exporting the content of my 'real world' DB to the local file system using UNO WASM + Chrome. This creates tons of files in folders and works no problem using WindowsAppSDK. 

However, on UNO WASM I get exception below. 
Please don't ask me for a repo since this is the real UNO WASM app (not released yet) on some real data - which I can't expose for obvious reasons. The issue is not reproducible with a trivial data set.

However, here are some details:
- WindowsAppSDK created ~700MB in 87 folders and ~11.500 files
- UNO WASM throws the towel after ~670MB in 80 folders and ~9000 files

Not sure if related, but most data is written by logic like below:
```
StorageFile file = await exportFolder.CreateFileAsync("Info.xml");
using (IRandomAccessStream stream = await file.OpenAsync(FileAccessMode.ReadWrite))
    using (Stream outputStream = stream.AsStreamForWrite())
        using (XmlWriter writer = XmlWriter.Create(outputStream, new XmlWriterSettings { Async = true, CheckCharacters = false, Indent = true }))
            document.WriteTo(writer);
```

This is pretty much latest UNO.
I'm not sure if this is a Microsoft WASM or an UNO WASM problem. Could you please shed some light?

```
dotnet.js:14 2023-08-28 15:16:52:371 System.IO.IOException: No file descriptors available : '/temp/WasmNativeCache/da825a21-d521-4b3a-9797-8119073c82a6'
dotnet.js:14    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\libraries\Common\src\Interop\Unix\Interop.IOErrors.cs:line 16
dotnet.js:14    at Interop.CheckIo(Error error, String path, Boolean isDirError) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\libraries\Common\src\Interop\Unix\Interop.IOErrors.cs:line 23
dotnet.js:14    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Func`4 createOpenException) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\libraries\System.Private.CoreLib\src\Microsoft\Win32\SafeHandles\SafeFileHandle.Unix.cs:line 113
dotnet.js:14    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\libraries\System.Private.CoreLib\src\Microsoft\Win32\SafeHandles\SafeFileHandle.Unix.cs:line 213
dotnet.js:14    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode, Func`4 createOpenException) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\libraries\System.Private.CoreLib\src\Microsoft\Win32\SafeHandles\SafeFileHandle.Unix.cs:line 180
dotnet.js:14    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\libraries\System.Private.CoreLib\src\System\IO\Strategies\OSFileStreamStrategy.cs:line 46
dotnet.js:14    at System.IO.Strategies.UnixFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\libraries\System.Private.CoreLib\src\System\IO\Strategies\UnixFileStreamStrategy.cs:line 15
dotnet.js:14    at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\libraries\System.Private.CoreLib\src\System\IO\Strategies\FileStreamHelpers.Unix.cs:line 17
dotnet.js:14    at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\libraries\System.Private.CoreLib\src\System\IO\Strategies\FileStreamHelpers.cs:line 24
dotnet.js:14    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\libraries\System.Private.CoreLib\src\System\IO\FileStream.cs:line 222
dotnet.js:14    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\libraries\System.Private.CoreLib\src\System\IO\FileStream.cs:line 146
dotnet.js:14    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\libraries\System.Private.CoreLib\src\System\IO\FileStream.cs:line 143
dotnet.js:14    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\libraries\System.Private.CoreLib\src\System\IO\FileStream.cs:line 136
dotnet.js:14    at System.IO.File.Create(String path, Int32 bufferSize) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\libraries\System.Private.CoreLib\src\System\IO\File.cs:line 71
dotnet.js:14    at System.IO.File.Create(String path) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\libraries\System.Private.CoreLib\src\System\IO\File.cs:line 64
dotnet.js:14    at Windows.Storage.StorageFolder.Local.CreateFileAsync(String desiredName, CreationCollisionOption options, CancellationToken cancellationToken) in /home/vsts/work/1/s/src/Uno.UWP/Storage/StorageFolder.Local.cs:line 110
dotnet.js:14    at Windows.Foundation.AsyncOperation`1.<BuildTaskAsync>d__23[[Windows.Storage.StorageFile, Uno, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]].MoveNext() in /home/vsts/work/1/s/src/Uno.Foundation/Internal/AsyncOperation.TResult.cs:line 83
dotnet.js:14    at System.WindowsRuntimeSystemExtensions.<AsTaskCore>d__11`1[[Windows.Storage.StorageFile, Uno, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]].MoveNext() in /home/vsts/work/1/s/src/Uno.UWP/System.Runtime/WindowsRuntimeSystemExtensions.cs:line 66
dotnet.js:14    at Uno.Storage.Streams.Internal.NativeWriteStream.CreateAsync(Guid fileId) in /home/vsts/work/1/s/src/Uno.UWP/Storage/Streams/Internal/NativeWriteStream.wasm.cs:line 54
dotnet.js:14    at Windows.Storage.Streams.FileRandomAccessStream.Native.CreateAsync(Guid fileId, FileAccessMode access) in /home/vsts/work/1/s/src/Uno.UWP/Storage/Streams/FileRandomAccessStream.native.wasm.cs:line 37
dotnet.js:14    at Windows.Storage.Streams.FileRandomAccessStream.CreateNativeAsync(Guid fileId, FileAccessMode access) in /home/vsts/work/1/s/src/Uno.UWP/Storage/Streams/FileRandomAccessStream.native.wasm.cs:line 13
dotnet.js:14    at Windows.Storage.StorageFile.NativeStorageFile.OpenAsync(CancellationToken ct, FileAccessMode accessMode, StorageOpenOptions options) in /home/vsts/work/1/s/src/Uno.UWP/Storage/StorageFile.native.wasm.cs:line 75
dotnet.js:14    at Windows.Storage.StorageFile.<>c__DisplayClass64_0.<<OpenAsync>b__0>d.MoveNext() in /home/vsts/work/1/s/src/Uno.UWP/Storage/StorageFile.cs:line 125
dotnet.js:14 --- End of stack trace from previous location ---
dotnet.js:14    at Windows.Foundation.AsyncOperation`1.<BuildTaskAsync>d__23[[Windows.Storage.Streams.IRandomAccessStream, Uno, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]].MoveNext() in /home/vsts/work/1/s/src/Uno.Foundation/Internal/AsyncOperation.TResult.cs:line 83
dotnet.js:14    at System.WindowsRuntimeSystemExtensions.<AsTaskCore>d__11`1[[Windows.Storage.Streams.IRandomAccessStream, Uno, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]].MoveNext() in /home/vsts/work/1/s/src/Uno.UWP/System.Runtime/WindowsRuntimeSystemExtensions.cs:line 66
dotnet.js:14    at Unusual.Gui.MainPage.<>c.<<ShowAccountMenuAt>b__70_17>d.MoveNext() in C:\Users\dierk\Documents\unusual-src\Unusual.Gui.Shared\Gui\MainPage.cs:line 1725
```

### Expected behavior

UNO WASM should work as WindowsAppSDK

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

WebAssembly

**Comment by Youssef1313** [comment]
This looks like a file descriptor leak where, somehow, we keep file handles without closing them?

**Comment by jeromelaban** [comment]
Interesting issue. @DierkDroth If you build the same logic without any `Windows.Storage` APIs and only `System.IO.File` APIs, do you get the same error?

**Comment by DierkDroth** [comment]
@jeromelaban nope. However, everything then is written to the IndexeDB (I'm sure you are aware) ... which is not what I wanted ...

**Comment by jeromelaban** [comment]
Writing to the file system through `System.IO.File` is not always written to the IndexedDB. It's only done for specific paths:
https://github.com/unoplatform/uno/blob/34a32058b812a0a08e658eba5e298ea9d258c231/src/Uno.UWP/Storage/ApplicationData.wasm.cs#L19-L24

If you're not getting the error, then this means that Uno is leaking streams somewhere along the line in `Windows.Storage`.

**Comment by DierkDroth** [comment]
Thanks for your feedback @jeromelaban. 

Meaning you would categorize that as a UNO WASM bug for now?

**Comment by DierkDroth** [comment]
@jeromelaban FYI
I also came across a couple of other gothas (which I was able to work around):
- System.IO.Path.GetInvalidFileNameChars does not yield the correct set of invalid chars, but only a few
- file names could not hold any char > 255
- file names could not have any leading/trailing blanks

**Comment by DierkDroth** [comment]
Magic and mystery ... I no longer can reproduce the scenario in my app (my code completely unchanged). So I'm going to close this issue for now.
