### ISSUE TITLE
[iOS] Receiving rather arbitrary `RetargetAssets_v[...]c" task failed unexpectedly` exception on release builds

### ISSUE THREAD

**Issue by marwalsch** [unoplatform/uno#13523]
### Current behavior

When trying to deploy release builds on iOS, the process might run into the following exception:
```
8>C:\Users\cc\.nuget\packages\uno.winui\4.9.45\buildTransitive\Uno.UI.Tasks.targets(137,3): error MSB4018: The "RetargetAssets_v3dafa2f9cc8b69fd31ae708bfa2e1ebf3617096c" task failed unexpectedly.
8>C:\Users\cc\.nuget\packages\uno.winui\4.9.45\buildTransitive\Uno.UI.Tasks.targets(137,3): error MSB4018: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Git\ProjectNative\Company.ProjectNative\Company.ProjectNative.iOS\obj\Release\net7.0-ios\ios-arm64\FontsPartialInfo.plist'.
8>C:\Users\cc\.nuget\packages\uno.winui\4.9.45\buildTransitive\Uno.UI.Tasks.targets(137,3): error MSB4018:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
8>C:\Users\cc\.nuget\packages\uno.winui\4.9.45\buildTransitive\Uno.UI.Tasks.targets(137,3): error MSB4018:    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
8>C:\Users\cc\.nuget\packages\uno.winui\4.9.45\buildTransitive\Uno.UI.Tasks.targets(137,3): error MSB4018:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
8>C:\Users\cc\.nuget\packages\uno.winui\4.9.45\buildTransitive\Uno.UI.Tasks.targets(137,3): error MSB4018:    at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
8>C:\Users\cc\.nuget\packages\uno.winui\4.9.45\buildTransitive\Uno.UI.Tasks.targets(137,3): error MSB4018:    at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
8>C:\Users\cc\.nuget\packages\uno.winui\4.9.45\buildTransitive\Uno.UI.Tasks.targets(137,3): error MSB4018:    at System.IO.StreamWriter..ctor(String path, Boolean append)
8>C:\Users\cc\.nuget\packages\uno.winui\4.9.45\buildTransitive\Uno.UI.Tasks.targets(137,3): error MSB4018:    at System.IO.File.CreateText(String path)
8>C:\Users\cc\.nuget\packages\uno.winui\4.9.45\buildTransitive\Uno.UI.Tasks.targets(137,3): error MSB4018:    at Uno.UI.Tasks.Assets.RetargetAssets_v3dafa2f9cc8b69fd31ae708bfa2e1ebf3617096c.GenerateFontPartialManifest(List`1 fontAssets, String iOSAppManifest) in C:\a\1\s\src\SourceGenerators\Uno.UI.Tasks\Assets\RetargetAssets.Fonts.cs:line 46
8>C:\Users\cc\.nuget\packages\uno.winui\4.9.45\buildTransitive\Uno.UI.Tasks.targets(137,3): error MSB4018:    at Uno.UI.Tasks.Assets.RetargetAssets_v3dafa2f9cc8b69fd31ae708bfa2e1ebf3617096c.ProcessContentItems(ITaskItem[] assets, Func`2 resourceToTargetPath, Func`2 pathEncoder) in C:\a\1\s\src\SourceGenerators\Uno.UI.Tasks\Assets\RetargetAssets.cs:line 85
8>C:\Users\cc\.nuget\packages\uno.winui\4.9.45\buildTransitive\Uno.UI.Tasks.targets(137,3): error MSB4018:    at Uno.UI.Tasks.Assets.RetargetAssets_v3dafa2f9cc8b69fd31ae708bfa2e1ebf3617096c.Execute() in C:\a\1\s\src\SourceGenerators\Uno.UI.Tasks\Assets\RetargetAssets.cs:line 77
8>C:\Users\cc\.nuget\packages\uno.winui\4.9.45\buildTransitive\Uno.UI.Tasks.targets(137,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
8>C:\Users\cc\.nuget\packages\uno.winui\4.9.45\buildTransitive\Uno.UI.Tasks.targets(137,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```
Usually this is resolved via cleaning, restarting VS, or re-establishing a connection to the Mac.
Any lead on what could be the issue is most welcome. Since this usually occurs towards the end of (potentially lengthy)
build processes and can be quite the nuisance.

### How to reproduce it (as minimally and precisely as possible)

Cannot give any instructions, as it pops up rather arbitrarily.

### Workaround

See above.

### Works on UWP/WinUI

Yes

### NuGet package version(s)

Uno.WinUI 4.9.45

### Affected platforms

iOS; not encountered on Android so far.

### IDE

Visual Studio 2022, v. 17.7.1

**Comment by jeromelaban** [comment]
Thanks for the report. We'll take a look but in the meantime, if you can [provide a binlog](https://platform.uno/docs/articles/uno-builds-troubleshooting.html), it will help. You can enable binlog generation in your VS continuously.

**Comment by marwalsch** [comment]
Thanks for that. I'll keep the bin-logger attached from now on and follow up if it pops up again.

**Comment by marwalsch** [comment]
I could reproduce this consistently after setting up a new machine.

It would only occur when initiating the build via the Rebuild command rather than running on a device or simulator (I generally stick to the former as deploying to a device is unnecessary for App Store builds).

The issue can be avoided by just running the app regularly; thus the eventual device deploy might fail due to inappropiate signing identities but the .ipa is build nonetheless.

I dare blame the initial arbitrariness of the error on a broken VS installation/caching issues.
