### ISSUE TITLE
WASM: Drag and Drop with multiple files

### ISSUE THREAD

**Issue by alove-kahua** [unoplatform/uno#13559]
### Current behavior

It's the exact same as this [issue](https://github.com/unoplatform/kahua-private/issues/40) except now throws an exception:

dotnet.native.js:39 Uncaught RuntimeError: unreachable
    at __trap (dotnet.native.wasm:0xf5eba8)
    at ___trap (dotnet.native.js:8924:45)
    at abort (dotnet.native.js:600:3)
    at _abort (dotnet.native.js:5158:2)
    at ves_icall_System_Environment_FailFast (dotnet.native.wasm:0xd0d5b7)
    at ves_icall_System_Environment_FailFast_raw (dotnet.native.wasm:0xd0f6ac)
    at do_icall (dotnet.native.wasm:0xc8e50f)
    at do_icall_wrapper (dotnet.native.wasm:0xc89068)
    at mono_interp_exec_method (dotnet.native.wasm:0xc7ae67)
    at interp_entry (dotnet.native.wasm:0xc8c74c)

### Expected behavior

No exception is thrown and all dragged files are returned.

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno.WinUI 5.0.0-dev.2456

### Affected platforms

WebAssembly

**Comment by alove-kahua** [comment]
[DragDrop.zip](https://github.com/unoplatform/uno/files/12553972/DragDrop.zip)

Project replicating the issue.  Drag and Drop at least 2 files onto the text in the center.  It shows a better error:

_bound_js_globalThis_console_error:7 fail: Windows.ApplicationModel.DataTransfer.DataPackage[0]
      Failed to asynchronously retrieve the data for id 'Shell IDList Array'
TypeError: Cannot read properties of undefined (reading 'getAsFileSystemHandle')
_bound_js_globalThis_console_error	@	_bound_js_globalThis_console_error:7
mono_wasm_invoke_bound_function	@	dotnet.js:5
_mono_wasm_invoke_bound_function	@	dotnet.js:14
$func316	@	dotnet.wasm:0x1df30
$func286	@	dotnet.wasm:0x1d2e0
$func224	@	dotnet.wasm:0xe644
$func223	@	dotnet.wasm:0xd4a2
$func8125	@	dotnet.wasm:0x1a9219
$func2057	@	dotnet.wasm:0x8aa95
$func2062	@	dotnet.wasm:0x8b164
$func2089	@	dotnet.wasm:0x8d337
$mono_wasm_invoke_method_bound	@	dotnet.wasm:0xa13d
Module._mono_wasm_invoke_method_bound	@	dotnet.js:14
invoke_method_and_handle_exception	@	dotnet.js:5
runtimeHelpers.javaScriptExports.complete_task	@	dotnet.js:5
(anonymous)	@	dotnet.js:5
Promise.catch (async)		
_marshal_task_to_cs	@	dotnet.js:5
_bound_js_globalThis_Windows_ApplicationModel_DataTransfer_DragDrop_Core_DragDropExtension_retrieveFiles	@	_bound_js_globalThis…ion_retrieveFiles:8
mono_wasm_invoke_bound_function	@	dotnet.js:5
_mono_wasm_invoke_bound_function	@	dotnet.js:14
$func316	@	dotnet.wasm:0x1df30
$func286	@	dotnet.wasm:0x1d2e0
$func224	@	dotnet.wasm:0xe644
$func223	@	dotnet.wasm:0xd4a2
$func8125	@	dotnet.wasm:0x1a9219
$func2057	@	dotnet.wasm:0x8aa95
$func2062	@	dotnet.wasm:0x8b164
$func2089	@	dotnet.wasm:0x8d337
$mono_wasm_invoke_method_bound	@	dotnet.wasm:0xa13d
Module._mono_wasm_invoke_method_bound	@	dotnet.js:14
invoke_method_and_handle_exception	@	dotnet.js:5
_bound_cs_Windows_ApplicationModel_DataTransfer_DragDrop_Core_DragDropExtension_OnNativeDropEvent	@	_bound_cs_Windows_Ap…OnNativeDropEvent:9
dispatchDropEvent
