### ISSUE TITLE
WASM: Cannot set TextDecorations on TextBlock inside of a Style

### ISSUE THREAD

**Issue by andrewkdci** [unoplatform/uno#13629]
### Current behavior

Setting the TextDecorations property on a TextBlock inside of a Style works for Windows heads. But when running a WASM (unhosted) head, it crashes the UI and results in an error in the debugger:

```
System.InvalidOperationException: Failed to load UnoTextDecorations.MainPage: System.ArgumentOutOfRangeException: No strategy registration for conversion 'TextDecorations' to 'UInt32' (Parameter 'extensionPoint')
   at Uno.Conversion.DefaultConversionExtensions.To(Object value, Type toType, CultureInfo culture) in /home/vsts/work/1/s/src/Uno.Foundation/Uno.Core.Extensions/Uno.Core.Extensions.Compatibility/Conversion/DefaultConversionExtensions.cs:line 85
   at Uno.UI.DataBinding.BindingPropertyHelper.Convert(Func`1 propertyType, Object value) in /home/vsts/work/1/s/src/Uno.UI/DataBinding/BindingPropertyHelper.cs:line 1081
   at Microsoft.UI.Xaml.Setter.ApplyTo(DependencyObject o) in /home/vsts/work/1/s/src/Uno.UI/UI/Xaml/Setter.cs:line 133
   at Microsoft.UI.Xaml.Style.ApplyTo(DependencyObject o, DependencyPropertyValuePrecedences precedence) in /home/vsts/work/1/s/src/Uno.UI/UI/Xaml/Style/Style.cs:line 90
   at Microsoft.UI.Xaml.FrameworkElement.OnStyleChanged(Style oldStyle, Style newStyle, DependencyPropertyValuePrecedences precedence) in /home/vsts/work/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.cs:line 660
   at Microsoft.UI.Xaml.FrameworkElement.ApplyStyle() in /home/vsts/work/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.cs:line 431
   at Microsoft.UI.Xaml.FrameworkElement.ApplyStyles() in /home/vsts/work/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.cs:line 364
   at Microsoft.UI.Xaml.FrameworkElement.CreationComplete() in /home/vsts/work/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.cs:line 383
   at UnoTextDecorations.MainPage.<InitializeComponent>b__1_4(TextBlock c0) in C:\Users\user1\source\repos\UnoTextDecorations\UnoTextDecorations\UnoTextDecorations.Wasm\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\MainPage_1321319e389ba5968a0b20f3de2318a3.cs:line 82
   at UnoTextDecorations.MainPage.InitializeComponent() in C:\Users\user1\source\repos\UnoTextDecorations\UnoTextDecorations\UnoTextDecorations.Wasm\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\MainPage_1321319e389ba5968a0b20f3de2318a3.cs:line 61
   at UnoTextDecorations.MainPage..ctor() in C:\Users\user1\source\repos\UnoTextDecorations\UnoTextDecorations\UnoTextDecorations.Shared\MainPage.xaml.cs:line 27
   at UnoTextDecorations.Wasm.MetadataBuilder_580.CreateInstance() in C:\Users\user1\source\repos\UnoTextDecorations\UnoTextDecorations\UnoTextDecorations.Wasm\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.BindableTypeProviders.BindableTypeProvidersSourceGenerator\BindableMetadata.g.cs:line 21166
   at Microsoft.UI.Xaml.Controls.Frame.CreatePageInstance(Type sourcePageType) in /home/vsts/work/1/s/src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs:line 454
   at Microsoft.UI.Xaml.PagePool.DequeuePage(Type pageType) in /home/vsts/work/1/s/src/Uno.UI/UI/Xaml/PagePool.cs:line 69
   at Microsoft.UI.Xaml.Controls.Frame.CreatePageInstanceCached(Type sourcePageType) in /home/vsts/work/1/s/src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs:line 444
   at Microsoft.UI.Xaml.Controls.Frame.EnsurePageInitialized(PageStackEntry entry) in /home/vsts/work/1/s/src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs:line 435
   at Microsoft.UI.Xaml.Controls.Frame.InnerNavigate(PageStackEntry entry, NavigationMode mode) in /home/vsts/work/1/s/src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs:line 283
   at UnoTextDecorations.App.OnNavigationFailed(Object sender, NavigationFailedEventArgs e) in C:\Users\user1\source\repos\UnoTextDecorations\UnoTextDecorations\UnoTextDecorations.Shared\App.xaml.cs:line 97
   at Microsoft.UI.Xaml.Controls.Frame.InnerNavigate(PageStackEntry entry, NavigationMode mode) in /home/vsts/work/1/s/src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs:line 300
   at Microsoft.UI.Xaml.Controls.Frame.Navigate(Type sourcePageType, Object parameter, NavigationTransitionInfo infoOverride) in /home/vsts/work/1/s/src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs:line 276
   at Microsoft.UI.Xaml.Controls.Frame.Navigate(Type sourcePageType, Object parameter) in /home/vsts/work/1/s/src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs:line 271
   at UnoTextDecorations.App.OnLaunched(LaunchActivatedEventArgs args) in C:\Users\user1\source\repos\UnoTextDecorations\UnoTextDecorations\UnoTextDecorations.Shared\App.xaml.cs:line 83
   at Microsoft.UI.Xaml.Application.Initialize() in /home/vsts/work/1/s/src/Uno.UI/UI/Xaml/Application.wasm.cs:line 130
   at Uno.UI.Dispatching.CoreDispatcher.InvokeOperationSafe(UIAsyncOperation operation) in /home/vsts/work/1/s/src/Uno.UI.Dispatching/Core/CoreDispatcher.cs:line 337
```

### Expected behavior

It should run and show underlined or strikethrough text when running as WASM.

### How to reproduce it (as minimally and precisely as possible)

Create an Uno project in Visual Studio 2022, target .NET 7 and create heads for Windows and WebAssembly (unhosted). Modify the MainPage.xaml to the following:

```
<Page
    x:Class="UnoTextDecorations.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:UnoTextDecorations"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"    
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Page.Resources>
        <Style x:Key="MyStyle" TargetType="TextBlock">
            <Setter Property="TextDecorations" Value="Underline"/>
        </Style>
    </Page.Resources>
    
    <Grid>
      <TextBlock Text="Hello, world!" Margin="20" FontSize="30" Style="{StaticResource MyStyle}"/>
    </Grid>
</Page>
```

Run the Windows head and observe an underlined "Hello, world!" text. Run the WASM head in debug mode and observe that the UI does not load and the aforementioned error in the Debug window.

### Workaround

Keep TextDecorations outside of Styles (although this may not be feasible/desirable for larger applications, such as my own).

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno.Extensions.Logging.WebAssembly.Console: 1.4.0
Uno.UI.Adapter.Microsoft.Extensions.Logging: 4.6.19
Uno.Wasm.Bootstrap: 7.0.3
Uno.Wasm.Bootstrap.DevServer: 7.0.3
Uno.WinUI.Lottie: 4.6.19
Uno.WinUI.RemoteControl: 4.6.19
Uno.WinUI.WebAssembly: 4.6.19

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

17.6.5

**Comment by jeromelaban** [comment]
Thanks for the report. 

This was fixed recently, either in version 4.10, or in 5.0-dev. Can you validate with either ones?
