### ISSUE TITLE
[Droid] `ListView` Called detach on an already detached child

### ISSUE THREAD

**Issue by FrozDark** [unoplatform/uno#13680]
### Current behavior

Simply scrolling ListView with items produces Unhandled exception below and unable to scroll up or down any further

Stack trace
```
Java.Lang.IllegalArgumentException: called detach on an already detached child UnoViewHolder{551d385 position=10 id=-1, oldPos=-1, pLpos:-1 tmpDetached} crc6499cc3f8d6dc23bc6.NativeListViewBase{ced9e11 VFED.V... ......ID 0,0-1080,1719}, adapter:crc6499cc3f8d6dc23bc6.NativeListViewBaseAdapter@96665e4, layout:Microsoft.UI.Xaml.Controls.ItemsStackPanelLayout, context:JupiterTrade.Droid.MainActivity
   at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference instance, JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 12324
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 75
   at AndroidX.RecyclerView.Widget.RecyclerView.LayoutManager.DetachView(View child) in C:\a\_work\1\s\generated\androidx.recyclerview.recyclerview\obj\Release
et6.0-android\generated\src\AndroidX.RecyclerView.Widget.RecyclerView.cs:line 5185
   at Microsoft.UI.Xaml.Controls.VirtualizingPanelLayout.TryDetachView(View view) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\ListViewBase\VirtualizingPanelLayout.Android.cs:line 2001
   at Microsoft.UI.Xaml.Controls.BufferViewCache.DetachAndCacheView(View view, Recycler recycler) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\ListViewBase\BufferViewCache.Android.cs:line 160
   at Microsoft.UI.Xaml.Controls.VirtualizingPanelLayout.RemoveTrailingView(GeneratorDirection fillDirection, Recycler recycler, Boolean detachOnly) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\ListViewBase\VirtualizingPanelLayout.Android.cs:line 2563
   at Microsoft.UI.Xaml.Controls.VirtualizingPanelLayout.RemoveTrailingLine(GeneratorDirection fillDirection, Recycler recycler, Boolean detachOnly) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\ListViewBase\VirtualizingPanelLayout.Android.cs:line 2577
   at Microsoft.UI.Xaml.Controls.VirtualizingPanelLayout.UnfillLayout(GeneratorDirection direction, Int32 offset, Int32 availableExtent, Recycler recycler, State state) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\ListViewBase\VirtualizingPanelLayout.Android.cs:line 1711
   at Microsoft.UI.Xaml.Controls.VirtualizingPanelLayout.ScrollByInner(Int32 offset, Recycler recycler, State state) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\ListViewBase\VirtualizingPanelLayout.Android.cs:line 1218
   at Microsoft.UI.Xaml.Controls.VirtualizingPanelLayout.ScrollBy(Int32 offset, Recycler recycler, State state) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\ListViewBase\VirtualizingPanelLayout.Android.cs:line 1148
   at Microsoft.UI.Xaml.Controls.VirtualizingPanelLayout.ScrollVerticallyBy(Int32 dy, Recycler recycler, State state) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\ListViewBase\VirtualizingPanelLayout.Android.cs:line 220
  --- End of managed Java.Lang.IllegalArgumentException stack trace ---
java.lang.IllegalArgumentException: called detach on an already detached child UnoViewHolder{551d385 position=10 id=-1, oldPos=-1, pLpos:-1 tmpDetached} crc6499cc3f8d6dc23bc6.NativeListViewBase{ced9e11 VFED.V... ......ID 0,0-1080,1719}, adapter:crc6499cc3f8d6dc23bc6.NativeListViewBaseAdapter@96665e4, layout:Microsoft.UI.Xaml.Controls.ItemsStackPanelLayout, context:JupiterTrade.Droid.MainActivity
	at androidx.recyclerview.widget.RecyclerView$5.detachViewFromParent(RecyclerView.java:1038)
	at androidx.recyclerview.widget.ChildHelper.detachViewFromParent(ChildHelper.java:284)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.detachViewInternal(RecyclerView.java:9619)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.detachView(RecyclerView.java:9592)
	at crc6499cc3f8d6dc23bc6.VirtualizingPanelLayout.n_scrollVerticallyBy(Native Method)
	at crc6499cc3f8d6dc23bc6.VirtualizingPanelLayout.scrollVerticallyBy(VirtualizingPanelLayout.java:67)
	at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:2050)
	at androidx.recyclerview.widget.RecyclerView.scrollByInternal(RecyclerView.java:2149)
	at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:3867)
	at android.view.View.dispatchTouchEvent(View.java:15026)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3115)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2788)
	at Uno.UI.UnoRecyclerView.access$001(UnoRecyclerView.java:10)
	at Uno.UI.UnoRecyclerView$TouchMotionTarget.dispatchToSuper(UnoRecyclerView.java:37)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoRecyclerView.dispatchTouchEvent(UnoRecyclerView.java:50)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:364)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:377)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:364)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:377)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:364)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:377)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:364)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:377)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:364)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:377)
	at crc6499cc3f8d6dc23bc6.ListViewBase.n_dispatchTouchEvent(Native Method)
	at crc6499cc3f8d6dc23bc6.ListViewBase.dispatchTouchEvent(ListViewBase.java:30)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:364)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:377)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at crc64bad6bab841c07a1a.NativeRefreshControl.n_dispatchTouchEvent(Native Method)
	at crc64bad6bab841c07a1a.NativeRefreshControl.dispatchTouchEvent(NativeRefreshControl.java:86)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:364)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:377)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:364)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:377)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:364)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:377)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:364)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:377)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:364)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:377)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:364)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:377)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:364)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:377)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:364)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:377)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:364)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:377)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:364)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:377)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:364)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:377)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:364)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:377)
	at Uno.UI.TouchMotionTarget.dispatchToChild(UnoMotionHelper.java:53)
	at Uno.UI.UnoMotionHelper.dispatchStaticTransformedMotionEventCore(UnoMotionHelper.java:419)
	at Uno.UI.UnoMotionHelper.dispatchStaticTransformedMotionEvent(UnoMotionHelper.java:389)
	at Uno.UI.UnoMotionHelper.dispatchStaticTransformedMotionEvent(UnoMotionHelper.java:331)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:187)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:377)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:364)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:377)
	at Uno.UI.TouchMotionTarget.dispatchToChild(UnoMotionHelper.java:53)
	at Uno.UI.UnoMotionHelper.dispatchStaticTransformedMotionEventCore(UnoMotionHelper.java:419)
	at Uno.UI.UnoMotionHelper.dispatchStaticTransformedMotionEvent(UnoMotionHelper.java:389)
	at Uno.UI.UnoMotionHelper.dispatchStaticTransformedMotionEvent(UnoMotionHelper.java:331)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:187)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:377)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:364)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:377)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:364)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:377)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:364)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:377)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:364)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:377)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:364)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:377)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:364)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:377)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:364)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:377)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:498)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1896)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4262)
	at crc6467d88aaa7548788d.BaseActivity.n_dispatchTouchEvent(Native Method)
	at crc6467d88aaa7548788d.BaseActivity.dispatchTouchEvent(BaseActivity.java:139)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:456)
	at android.view.View.dispatchPointerEvent(View.java:15285)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6542)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6342)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5798)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5855)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5821)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5986)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5829)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6043)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5802)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5855)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5821)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5829)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5802)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8842)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8793)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8762)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8965)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:247)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8922)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:9056)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1230)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1238)
	at android.view.Choreographer.doCallbacks(Choreographer.java:898)
	at android.view.Choreographer.doFrame(Choreographer.java:823)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1213)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7892)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

  --- End of managed Java.Lang.IllegalArgumentException stack trace ---
```

### Expected behavior

No exception with scrolling possibility

### How to reproduce it (as minimally and precisely as possible)

[DroidListViewIssue.zip](https://github.com/unoplatform/uno/files/12655945/DroidListViewIssue.zip)

### Works on UWP/WinUI

Yes

### NuGet package version(s)

Uno.WinUI 4.10.13

### Affected platforms

Android

### IDE

Visual Studio 2022

**Comment by Youssef1313** [comment]
@FrozDark Do you know if it's a recent regression?

**Comment by FrozDark** [comment]
> @FrozDark Do you know if it's a recent regression? We also need a repro.

Repro
[DroidListViewIssue.zip](https://github.com/unoplatform/uno/files/12655945/DroidListViewIssue.zip)

The last known version I used without that issue was 5.0.0-dev.2280

**Comment by Youssef1313** [comment]
Maybe regression from https://github.com/unoplatform/uno/pull/13507 ?

**Comment by ramezgerges** [comment]
> > @FrozDark Do you know if it's a recent regression? We also need a repro.
> 
> Repro [DroidListViewIssue.zip](https://github.com/unoplatform/uno/files/12655945/DroidListViewIssue.zip)
> 
> The last known version I've used without that issue was 5.0.0-dev.2280

Are you sure? 5.0.0-dev.2280 is actually reproducing for me, so it might not be a regression after all.

I'm having trouble reproducing this inside SamplesApp, so I'm not sure how far I can go with this.

**Comment by ramezgerges** [comment]
I couldn't get anywhere, but here's a much smaller repro

```xaml
    <Grid>
        <Grid>
            <ListView x:Name="lstView" SelectionMode="Single">
                <ListView.ItemTemplate>
                    <DataTemplate x:DataType="local:SampleModel">
                            <TextBlock Text="Hello" />
                    </DataTemplate>
                </ListView.ItemTemplate>
            </ListView>
        </Grid>
    </Grid>
```

```csharp
    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            this.InitializeComponent();
            lstView.ItemsSource = Enumerable.Range(1, 1000).ToList();
        }
    }
```

This reproduces as an external samples for everything: early 5x, latest 5x, 5.0.0-dev.2280, latest 4x. The only place where it doesn't reproduce is inside SamplesApp (master)

**Comment by FrozDark** [comment]
> > > @FrozDark Do you know if it's a recent regression? We also need a repro.
> > 
> > 
> > Repro [DroidListViewIssue.zip](https://github.com/unoplatform/uno/files/12655945/DroidListViewIssue.zip)
> > The last known version I've used without that issue was 5.0.0-dev.2280
> 
> Are you sure? 5.0.0-dev.2280 is actually reproducing for me, so it might not be a regression after all.
> 
> I'm having trouble reproducing this inside SamplesApp, so I'm not sure how far I can go with this.

Maybe I'm wrong as there was Enter keyboard key issue on that version and it has not been long in my app so I could not notice the issue

But I'm pretty sure it wasn't reproducable in 5.0.0-dev.1732 as it was the most long-living version in my app

**Comment by ramezgerges** [comment]
That's weird. 5.0.0-dev.1732 is still reproducing for me, so I'm not sure what mistake either of us did (if at all).

**Comment by FrozDark** [comment]
> That's weird. 5.0.0-dev.1732 is still reproducing for me, so I'm not sure what mistake either of us did (if at all).

Okay. Things getting more weird
The dev versions I mentioned were used in the old Uno template with Shared project
![ques](https://github.com/unoplatform/uno/assets/6670150/4fbfea47-a85b-4bfc-9e2d-b3f2ec7a91ae)

The issue is not reproducable if you use it with shared project template neither with the stable version nor with the latest dev

I've migrated my project with the newest stable release 4.10.13 when I posted this issue. And the issue is reproducable with the new uno template with PCL and it's weird
![err](https://github.com/unoplatform/uno/assets/6670150/a77e7e86-3893-4294-8cfb-69b42df62065)

**Comment by FrozDark** [comment]
@ramezgerges did you find any workaround?

**Comment by ramezgerges** [comment]
Sadly, I haven't.
