### ISSUE TITLE
`When_HotReloadScenario` fails in Uno.WinUI converted tree

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#13757]
### Current behavior

In WinUI converted source tree, the `When_HotReloadScenario` test fails with:

> System.InvalidOperationException: Failed to build app
at Uno.UI.RuntimeTests.Tests.HotReload.Given_HotReloadWorkspace.BuildTestApp() in D:\a\1\s\src\Uno.UI.RuntimeTests\Tests\HotReload\Given_HotReloadWorkspace.cs:line 176
at Uno.UI.RuntimeTests.Tests.HotReload.Given_HotReloadWorkspace.Initialize() in D:\a\1\s\src\Uno.UI.RuntimeTests\Tests\HotReload\Given_HotReloadWorkspace.cs:line 92
at Uno.UI.Samples.Tests.UnitTestsControl.<>c__DisplayClass63_1.<<ExecuteTestsForInstance>g__InvokeTestMethod|2>d.MoveNext() in D:\a\1\s\src\SamplesApp\SamplesApp.UnitTests.Shared\Controls\UnitTest\UnitTestsControl.cs:line 936

### Works on UWP/WinUI

None

**Comment by MartinZikmund** [comment]
CC @nickrandolph

**Comment by MartinZikmund** [comment]
Disabled the test temporarily for WinUI tree in https://github.com/unoplatform/uno/pull/13749
