### ISSUE TITLE
UI rendering issue with Focus rectangle, Skia

### ISSUE THREAD

**Issue by HakanL** [unoplatform/uno#13796]
### Current behavior

In some cases the focus rectangle gets rendered slightly off. I've been trying to figure out what's causing it, if it's something with timing of events where layout is updated or page transitions, but this is what it looks like:
![image](https://github.com/unoplatform/uno/assets/407941/e4ccf5a5-c14f-4af1-b78d-4c6d5d587acd)

### Expected behavior

It should look like this:
![image](https://github.com/unoplatform/uno/assets/407941/a5f9fdd6-54e2-4174-b0d3-a0572d8c2420)

Which it will if I tab forward/backward, I only get the issue when I'm navigating to this view and it's the initial focus item (It's a listview).

### How to reproduce it (as minimally and precisely as possible)

I realize I probably don't have enough details here to reproduce it, because this is part of my larger system using keyboard navigation controlled by an external rotary encoder. But I'm hoping there's some tracing that we can enable to show what if there's an issue with event firing order or something like that.

### Workaround

The system works, but it looks wrong.

### Works on UWP/WinUI

None

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.10.22

### Affected platforms

Skia (GTK on Linux/macOS/Windows), Skia (Linux Framebuffer)

### IDE

Visual Studio 2022

### Anything else we need to know?

Same issue on Linux FB and Skia GTK.

**Comment by Youssef1313** [comment]
Could you check if this is still an issue with latest 5.0 dev NuGet package? This indeed lacks information to reproduce the issue and root it down. It will be appreciated if you can get a minimal repro

**Comment by HakanL** [comment]
I'm trying to run 5.0.0-dev.3200 but I'm getting this error when trying to run:
```
System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'Microsoft.Toolkit.Uwp.UI.Lottie.LottieVisualSource' from assembly 'Uno.UI.Lottie, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'.
  Source=Uno.Material
  StackTrace:
   at Uno.Material.GlobalStaticResources.ResourceDictionarySingleton__mergedpages_v2_44627d8de4433209f2b1934267892e44.get_mergedpages_v2_44627d8de4433209f2b1934267892e44_ResourceDictionary()
   at Uno.Material.GlobalStaticResources.get_mergedpages_v2_44627d8de4433209f2b1934267892e44_ResourceDictionary()
   at Uno.Material.GlobalStaticResources.<>c.<RegisterResourceDictionariesBySource>b__44_4()
   at Uno.UI.ResourceResolver.RetrieveDictionaryForSource(String source, String currentAbsolutePath)
   at Uno.UI.ResourceResolver.RetrieveDictionaryForSource(Uri source)
   at Microsoft.UI.Xaml.ResourceDictionary.set_Source(Uri value)
   at Uno.Material.MaterialTheme.UpdateSource()
   at Uno.Material.MaterialTheme..ctor(ResourceDictionary colorOverride, ResourceDictionary fontOverride)
   at Uno.Toolkit.UI.Material.MaterialToolkitTheme.UpdateSource()
   at Uno.Toolkit.UI.Material.MaterialToolkitTheme..ctor(ResourceDictionary colorOverride, ResourceDictionary fontOverride)
   at Uno.Toolkit.UI.Material.MaterialToolkitTheme..ctor()
   at Shared.GlobalStaticResources.ResourceDictionarySingleton__AppResources_f7a78a4fe90b1c42d58a248a4dedb7e4.get_AppResources_f7a78a4fe90b1c42d58a248a4dedb7e4_ResourceDictionary() in C:\Projects\DMXCore\100\Software\Shared\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\AppResources_f7a78a4fe90b1c42d58a248a4dedb7e4.cs:line 89
   at Shared.GlobalStaticResources.get_AppResources_f7a78a4fe90b1c42d58a248a4dedb7e4_ResourceDictionary() in C:\Projects\DMXCore\100\Software\Shared\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\AppResources_f7a78a4fe90b1c42d58a248a4dedb7e4.cs:line 120
   at Shared.GlobalStaticResources.<>c.<RegisterResourceDictionariesBySource>b__29_0() in C:\Projects\DMXCore\100\Software\Shared\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\GlobalStaticResources.cs:line 161
   at Uno.UI.ResourceResolver.RetrieveDictionaryForSource(String source, String currentAbsolutePath)
   at DMXCore.DMXCore100.AppHead.InitializeComponent() in C:\Projects\DMXCore\100\Software\DMXCore100.Skia.Gtk\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\AppHead_0584c43aa423e3fe76f702d55cc14b2f.cs:line 100
   at DMXCore.DMXCore100.AppHead..ctor() in C:\Projects\DMXCore\100\Software\Base\AppHead.xaml.cs:line 11
   at DMXCore.DMXCore100.Skia.Gtk.Program.<>c.<Main>b__0_1() in C:\Projects\DMXCore\100\Software\DMXCore100.Skia.Gtk\Program.cs:line 24
   at Uno.UI.Runtime.Skia.Gtk.GtkHost.<StartApp>g__CreateApp|26_0(ApplicationInitializationCallbackParams _)
   at Microsoft.UI.Xaml.Application.StartPartial(ApplicationInitializationCallback callback)
   at Microsoft.UI.Xaml.Application.Start(ApplicationInitializationCallback callback)
   at Microsoft.UI.Xaml.Application.StartWithArguments(ApplicationInitializationCallback callback)
   at Uno.UI.Runtime.Skia.Gtk.GtkHost.StartApp()
   at Uno.UI.Runtime.Skia.Gtk.GtkHost.Run()
   at DMXCore.DMXCore100.Skia.Gtk.Program.Main() in C:\Projects\DMXCore\100\Software\DMXCore100.Skia.Gtk\Program.cs:line 34
```
When trying to run the Skia Gtk head on Windows and Linux (FB). Trying to upgrade so I can test this as well: https://github.com/unoplatform/uno/discussions/13512#discussioncomment-7067898

**Comment by Youssef1313** [comment]
I think you need update all Uno-related packages to latest, not just Uno.WinUI.

**Comment by HakanL** [comment]
> I think you need update all Uno-related packages to latest, not just Uno.WinUI.

I did. I upgraded all the Uno packages that had version 4 in it (I also tried the toolkit versions 2.5->3.0 but then ended up with a compiler error so I rolled that back.

**Comment by HakanL** [comment]
Isn't it strange that it's looking for `Uno.UI.Lottie` and not `Uno.WinUI.Lottie`? There are no references to Uno.UI.* in my solution, except `Uno.UI.Adapter.Microsoft.Extensions.Logging`.

**Comment by Youssef1313** [comment]
> Isn't it strange that it's looking for `Uno.UI.Lottie` and not `Uno.WinUI.Lottie`? There are no references to Uno.UI.* in my solution, except `Uno.UI.Adapter.Microsoft.Extensions.Logging`.

That is expected. The assembly name is always `Uno.UI.*.dll` (which is different from the package name `Uno.WinUI.*`

**Comment by HakanL** [comment]
Ah, `<PackageReference Include="Uno.CommunityToolkit.WinUI.UI.Controls" Version="7.1.200-dev.13.gef3f523648" />` was the culprit. Now it runs, let's test. One initial issue though, so in 4.10 I used to set the Gtk window size to not resizable, and a fixed size (to mimic my hardware). Now GtkHost.Window is gone, or not static anymore. I tried the ApplicationView, but it doesn't do anything. What's the preferred way to set the Gtk Window size in Uno5?

**Comment by HakanL** [comment]
Confirmed to still be an issue in 5.0.0.dev-3200. I realize it's very hard to find the cause without a minimal repo. I'll see what I can do, it's a larger project with plenty of dependencies.

**Comment by HakanL** [comment]
@Youssef1313 I'm getting this exception on Linux (Framebuffer). It works with Skia/Gtk on Windows:
```
Startup exception: System.InvalidOperationException: Failed to initialize the PointerManager: cannot resolve the IUnoCorePointerInputSource.
   at Uno.UI.Xaml.Core.InputManager.KeyboardManager.Init(Object host) in /__w/1/s/src/Uno.UI/UI/Xaml/Internal/InputManager.Keyboard.skia.cs:line 34
   at Uno.UI.Xaml.Core.InputManager.InitializeKeyboard(Object host) in /__w/1/s/src/Uno.UI/UI/Xaml/Internal/InputManager.Keyboard.skia.cs:line 18
   at Uno.UI.Xaml.Core.InputManager.Initialize(Object host) in /__w/1/s/src/Uno.UI/UI/Xaml/Internal/InputManager.cs:line 38
   at Uno.UI.Xaml.Core.ContentRoot.SetHost(Object host) in /__w/1/s/src/Uno.UI/UI/Xaml/Internal/ContentRoot.uno.cs:line 20
   at Uno.UI.Runtime.Skia.Linux.FrameBuffer.FrameBufferHost.OnCoreWindowContentRootSet(Object sender, Object e)
   at Uno.UI.Xaml.Core.ContentRootCoordinator.set_CoreWindowContentRoot(ContentRoot value) in /__w/1/s/src/Uno.UI/UI/Xaml/Internal/ContentRootCoordinator.cs:line 37
   at Uno.UI.Xaml.Core.ContentRoot..ctor(ContentRootType type, Color backgroundColor, UIElement rootElement, CoreServices coreServices) in /__w/1/s/src/Uno.UI/UI/Xaml/Internal/ContentRoot.cs:line 72
   at Uno.UI.Xaml.Core.ContentRootCoordinator.CreateContentRoot(ContentRootType type, Color backgroundColor, UIElement rootElement) in /__w/1/s/src/Uno.UI/UI/Xaml/Internal/ContentRootCoordinator.cs:line 46
   at Uno.UI.Xaml.Core.CoreServices.InitCoreWindowContentRoot() in /__w/1/s/src/Uno.UI/UI/Xaml/Internal/CoreServices.cs:line 75
   at Uno.UI.Xaml.Core.CoreServices.PutVisualRoot(DependencyObject dependencyObject) in /__w/1/s/src/Uno.UI/UI/Xaml/Internal/CoreServices.cs:line 61
   at Microsoft.UI.Xaml.Window.InternalSetContent(UIElement content) in /__w/1/s/src/Uno.UI/UI/Xaml/Window.skia.cs:line 64
   at Microsoft.UI.Xaml.Window.set_Content(UIElement value) in /__w/1/s/src/Uno.UI/UI/Xaml/Window.cs:line 124
   at Uno.Extensions.ApplicationBuilderExtensions.NavigateAsync[TShell](IApplicationBuilder appBuilder, Func`3 initialNavigate)
   at DMXCore.DMXCore100.App.OnLaunched(LaunchActivatedEventArgs args) in C:\Projects\DMXCore\100\Software\Shared\App.cs:line 277
```
Am I missing something in the upgrade to 5.0.0?

**Comment by Youssef1313** [comment]
That is probably a regression from https://github.com/unoplatform/uno/pull/13382 where only Gtk and Wpf were considered.

cc @MartinZikmund

**Comment by MartinZikmund** [comment]
The second issue is now fixed, not the original one though
