### ISSUE TITLE
[Wasm/Mac] Error retriving TimezoneData

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno#13882]
### Current behavior

Created app using unoapp template (default options)
Open in VS Code on Mac
Attempt to debug WASM target
Error:

```
uno-bootstrap.js:374 Error: Expected string argument, got undefined
    at Object.js_string_to_mono_string_root (dotnet.js:5:31748)
    at Object.converter_s [as compiled_function] (converter_s:12:5)
    at _Uno_Wasm_TimezoneData__Uno_Wasm_TimezoneData_TimezoneHelper_Setup (_Uno_Wasm_TimezoneData__Uno_Wasm_TimezoneData_TimezoneHelper_Setup:18:30)
    at Bootstrapper.timezoneSetup (uno-bootstrap.js:381:25)
    at Bootstrapper.mainInit (uno-bootstrap.js:366:30)
    at checkDone (uno-bootstrap.js:582:38)
    at processDependency (uno-bootstrap.js:600:37)
    at Object.execCb (require.js:5:16727)
    at e.check (require.js:5:10499)
    at e.<anonymous> (require.js:5:12915)
```

![Screenshot 2023-10-02 at 3 25 40 pm](https://github.com/unoplatform/uno/assets/1614057/dec51b5e-b550-483e-adf2-b7a6d77cab0b)

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

### IDE

Visual Studio Code

### IDE version

Mac

**Comment by jeromelaban** [comment]
@nickrandolph this is fixed using the .NET 8 bootstrapper, though I wonder which culture causes this issue.
