### ISSUE TITLE
App Crash canceling a photo capture on iOS

### ISSUE THREAD

**Issue by arnold256** [unoplatform/uno#14034]
### Current behavior

When calling `var photo = await captureUI.CaptureFileAsync(CameraCaptureUIMode.Photo);` to capture a photo on iOS if cancel is pressed instead of capturing a photo the entire app crashes.

```
[0:] An error occurred: 'Exception of type 'Foundation.You_Should_Not_Call_base_In_This_Method' was thrown.'. Callstack: '   at UIKit.UIImagePickerControllerDelegate.Canceled(UIImagePickerController picker)
   at Windows.Media.Capture.CameraDelegate.Canceled(UIImagePickerController picker)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at CameraCaptureUISample.EntryPoint.Main(String[] args) in C:\Repos\Uno.Samples\UI\CameraCaptureUI\CameraCaptureUISample\CameraCaptureUISample.Mobile\iOS\Main.iOS.cs:line 12
   at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)'
The app has been terminated.

```

### Expected behavior

null is returned.

### How to reproduce it (as minimally and precisely as possible)

Open the [CameraCaptureUISample](https://github.com/unoplatform/Uno.Samples/tree/master/UI/CameraCaptureUI ) solution.

Upgrade uno packages to `4.10.26`.
Press the `Capture Image ` button.
Press Cancel.

### Workaround

None that I can find.

### Works on UWP/WinUI

None

### Environment

Other

### NuGet package version(s)

Uno.Extensions.Logging.OSLog 1.6.0
Uno.WinUI 4.10.26
Uno.WinUI.RemoteControl 4.10.26
Uno.UI.Adapter.Microsoft.Extensions.Logging 4.10.26
Microsoft.Extensions.Logging.Console  7.0.0
Uno.WinUI.Lottie  4.10.26

### Affected platforms

iOS

### IDE

Visual Studio 2022

### IDE version

17.7.4

**Comment by arnold256** [comment]
Not sure if this is expected behaviour however now when I press cancel the app doesn't crash anymore however the button seems to do nothing.  I have to take a photo to make the camera go away and then the image fails.

If I don't press cancel the image does work.

**Comment by jeromelaban** [comment]
Thanks for the report. Indeed, I can repro the behavior.
