### ISSUE TITLE
Can't Start Tutorial App on Orange Pi

### ISSUE THREAD

**Issue by aliajboy** [unoplatform/uno#14050]
### Current behavior

Hi, 
I'm new to Pi and Uno Platform. I follow the tutorial for Raspberry Pi on UnoPlatform Docs and after I start "dotnet run" on GTK, I get following error:
`GLIB UNHANDLED EXCEPTIONSystem.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Uno.UI.Runtime.Skia.GLRenderSurfaceBase.UnoGLDrawingArea_Render(Object o, RenderArgs args)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)`

I test the exact same code on Windows and Ubuntu PC and worked OK! I have this issue just on my Orange Pi PC.
I tested everything and worth mentioning that I am using Latest Dotnet 7 SDK on both development PC and Orange Pi.

after the Dotnet Run Command, the app window will open with black screen but won't show even hello world label and close rapidly.

### How to reproduce it (as minimally and precisely as possible)

just do the tutorial. your docs are for .net 5 and is too Old!
Please check it and help me. I'm Stuck in it for 2 Days Now.

### Works on UWP/WinUI

None

### Environment

Armbian

### NuGet package version(s)

Latest Version Of Everything

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio Code

### IDE version

Latest as of now

### Anything else we need to know?

https://www.uplooder.net/img/image/41/60c481969ae57b5b7d492cb0eae8a2d1/asdasd.png

**Comment by aliajboy** [comment]
The Problem Was my OS. I was using Armbian and thought that it's OK! but it's not. I installed Ubuntu and Everything is now OK. Thank you

**Comment by jeromelaban** [comment]
Thanks for the report! I'll be keeping this particular issue opened, as we should not be failing with an NRE here. 

## Note for contributors
The issue is that we're assuming that `Content` is always available, where it obviously can't always be given the error you got:

https://github.com/unoplatform/uno/blob/2af7b1a6953cc501dd6b16c07c4510fd8a937828/src/Uno.UI.Runtime.Skia.Gtk/Rendering/GLRenderSurfaceBase.cs#L83

We should be returning an explicit error when this happens, so developers knows what to do.

**Comment by MartinZikmund** [comment]
As GTK is no longer supported and was replaced by X11 backend, closing this issue
