### ISSUE TITLE
Issue running with Wayland

### ISSUE THREAD

**Issue by HakanL** [unoplatform/uno#14064]
### Current behavior

When running under Wayland (GDK_BACKEND not set) I'm getting a strange issue. The display looks like this:
![image](https://github.com/unoplatform/uno/assets/407941/a033cb93-729e-4396-98f3-804d46e0d432)

To optimize my application I would prefer to run natively under Wayland and remove Xwayland as it doesn't really serve a purpose. But when I run without having GDK_BACKEND set (my system, RPi 4, only detects OpenGL, not OpenGL ES) I'm getting this in my startup log:
```
05:16:03.671 INF [DMXCore.DMXCore100.ViewModels.HomeViewModel] HomeViewModel created
05:16:03.734 WRN [Microsoft.UI.Xaml.Documents.Inline] The font MaterialLightFontFamily could not be found, using system default
05:16:03.738 ERR [Uno.UI.Dispatching.CoreDispatcher] Dispatcher unhandled exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.UI.Xaml.Documents.TextFormatting.FontDetailsCache.GetFontInternal(String name, Single fontSize, FontWeight weight, FontStyle style) in /__w/1/s/src/Uno.UI/UI/Xaml/Documents/TextFormatting/FontDetailsCache.skia.cs:line 93
   at Microsoft.UI.Xaml.Documents.TextFormatting.FontDetailsCache.<>c.<.cctor>b__4_0(String nm, Single sz, FontWeight wt, FontStyle sl) in /__w/1/s/src/Uno.UI/UI/Xaml/Documents/TextFormatting/FontDetailsCache.skia.cs:line 21
   at Uno.Extensions.FuncMemoizeExtensions.<>c__DisplayClass4_0`5.<AsMemoized>b__0(TParam1 arg1, TParam2 arg2, TParam3 arg3, TParam4 arg4) in /__w/1/s/src/Uno.Foundation/Uno.Core.Extensions/Uno.Core.Extensions/FuncMemoizeExtensions.cs:line 156
   at Microsoft.UI.Xaml.Documents.TextFormatting.FontDetailsCache.GetFont(String name, Single fontSize, FontWeight weight, FontStyle style) in /__w/1/s/src/Uno.UI/UI/Xaml/Documents/TextFormatting/FontDetailsCache.skia.cs:line 107
   at Microsoft.UI.Xaml.Documents.Inline.get_FontInfo() in /__w/1/s/src/Uno.UI/UI/Xaml/Documents/Inline.skia.cs:line 30
   at Microsoft.UI.Xaml.Documents.Run.GetSegments() in /__w/1/s/src/Uno.UI/UI/Xaml/Documents/Run.skia.cs:line 25
   at Microsoft.UI.Xaml.Documents.Run.get_Segments() in /__w/1/s/src/Uno.UI/UI/Xaml/Documents/Run.skia.cs:line 16
   at Microsoft.UI.Xaml.Documents.InlineCollection.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/Documents/InlineCollection.skia.cs:line 73
   at Microsoft.UI.Xaml.Controls.TextBlock.MeasureOverride(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.skia.cs:line 38
   at Microsoft.UI.Xaml.FrameworkElement.InnerMeasureCore(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.Layout.netstd.cs:line 99
   at Microsoft.UI.Xaml.FrameworkElement.MeasureCore(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.Layout.netstd.cs:line 78
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.netstd.cs:line 162
   at Microsoft.UI.Xaml.FrameworkElement.MeasureElement(UIElement view, Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.cs:line 330
   at Microsoft.UI.Xaml.Controls.StackPanel.MeasureOverride(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/StackPanel/StackPanel.Layout.cs:line 52
   at Microsoft.UI.Xaml.FrameworkElement.InnerMeasureCore(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.Layout.netstd.cs:line 99
   at Microsoft.UI.Xaml.FrameworkElement.MeasureCore(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.Layout.netstd.cs:line 78
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.netstd.cs:line 162
   at Microsoft.UI.Xaml.FrameworkElement.MeasureElement(UIElement view, Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.cs:line 330
   at Microsoft.UI.Xaml.Controls.Grid.MeasureCell(UIElement child, CellUnitTypes rowHeightTypes, CellUnitTypes columnWidthTypes, Boolean forceRowToInfinity, Double rowSpacing, Double columnSpacing) in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/Grid/Grid.cs:line 498
   at Microsoft.UI.Xaml.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Int32 cellCount, Double rowSpacing, Double columnSpacing, Boolean ignoreColumnDesiredSize, Boolean forceRowToInfinity, CellCacheStackVector& cellCacheVector) in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/Grid/Grid.cs:line 373
   at Microsoft.UI.Xaml.Controls.Grid.MeasureOverride(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/Grid/Grid.cs:line 1045
   at Microsoft.UI.Xaml.FrameworkElement.InnerMeasureCore(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.Layout.netstd.cs:line 99
   at Microsoft.UI.Xaml.FrameworkElement.MeasureCore(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.Layout.netstd.cs:line 78
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.netstd.cs:line 162
   at Microsoft.UI.Xaml.FrameworkElement.MeasureElement(UIElement view, Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.cs:line 330
   at Microsoft.UI.Xaml.FrameworkElement.MeasureOverride(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.cs:line 246
   at Microsoft.UI.Xaml.FrameworkElement.InnerMeasureCore(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.Layout.netstd.cs:line 99
   at Microsoft.UI.Xaml.FrameworkElement.MeasureCore(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.Layout.netstd.cs:line 78
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.netstd.cs:line 162
   at Microsoft.UI.Xaml.FrameworkElement.MeasureElement(UIElement view, Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.cs:line 330
   at Microsoft.UI.Xaml.FrameworkElement.MeasureOverride(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.cs:line 246
   at Microsoft.UI.Xaml.Controls.ContentPresenter.MeasureOverride(Size size) in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs:line 1130
   at Microsoft.UI.Xaml.FrameworkElement.InnerMeasureCore(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.Layout.netstd.cs:line 99
   at Microsoft.UI.Xaml.FrameworkElement.MeasureCore(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.Layout.netstd.cs:line 78
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.netstd.cs:line 162
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.netstd.cs:line 162
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.netstd.cs:line 162
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.netstd.cs:line 162
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.netstd.cs:line 162
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.netstd.cs:line 162
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.netstd.cs:line 162
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.netstd.cs:line 162
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.netstd.cs:line 162
   at Microsoft.UI.Xaml.XamlRoot.RunMeasureAndArrange() in /__w/1/s/src/Uno.UI/UI/Xaml/XamlRoot.netstd.cs:line 116
   at Microsoft.UI.Xaml.XamlRoot.<ScheduleInvalidateMeasureOrArrange>b__35_0() in /__w/1/s/src/Uno.UI/UI/Xaml/XamlRoot.netstd.cs:line 93
   at Uno.UI.Dispatching.CoreDispatcher.InvokeOperationSafe(UIAsyncOperation operation) in /__w/1/s/src/Uno.UI.Dispatching/Core/CoreDispatcher.cs:line 354
```

### Expected behavior

It's supposed to be like this (which is from running with GDK_BACKEND=x11):
![image](https://github.com/unoplatform/uno/assets/407941/7d63a8af-47e8-45f6-a4e8-e738f9203463)

### How to reproduce it (as minimally and precisely as possible)

Unfortunately I haven't tried this with a simple application yet. Am I correct in assuming that an "unset" GDK_BACKEND should then use native Wayland for GTK3?

### Workaround

Run using GDK_BACKEND=x11 and using Xwayland

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

4.10.26

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

**Comment by HakanL** [comment]
I may have jumped the gun, turns out it does *not* work on X11 either. I think I have another issue (with missing dependencies). I will close this issue, sorry about that.

**Comment by jeromelaban** [comment]
Thanks for the report. This feels like something we fixed in Uno 5 prerelease. Could you still try with it?

**Comment by HakanL** [comment]
It's probably an issue with running it in the lightweight docker base image `Alpine`. I have an issue with serial ports as well running under that, so I'm going to table this at the moment until .NET 8 is released (apparently there may be a fix in there for serial ports under Alpine).

**Comment by HakanL** [comment]
@jeromelaban Or do you mean that there are fixes to run natively under Wayland in Uno5? Because I don't seem to be able to run it without Xwayland even when I don't have the graphical/font issues above.

**Comment by jeromelaban** [comment]
@HakanL I mean fixes specific to the exception you've seen, not to Wayland specifically.

**Comment by HakanL** [comment]
@jeromelaban I see. I think it may be partly related to the `Alpine` distribution being so lightweight (it doesn't have glibc), so .NET is a little tricky to get to run there (but it's small, so it's great for Docker). I don't think it's worthwhile to test with Uno5 until the basics work under that (which for me is serial ports and fonts). But I'm very much interested in getting native Wayland to work, I'll look for an issue related to that, or open a new one.

**Comment by HakanL** [comment]
I opened a new ticket for Wayland support, https://github.com/unoplatform/uno/issues/14075
