### ISSUE TITLE
Native Wayland using OpenGL or OpenGLES on Raspberry Pi 4 isn't working

### ISSUE THREAD

**Issue by HakanL** [unoplatform/uno#14075]
### Current behavior

First what works: I can run `RenderSurfaceType = OpenGL` when I set `GDK_BACKEND=x11`, and obviously Software render surface works as well. But because I don't need anything else on x11, it's a waste of space and resources to go via that when native Wayland should be available. I can run gtk3-demo in both GL and GLES fine (but the "OpenGL Area" only works under GLES).

`GDK_BACKEND=wayland` and `RenderSurfaceType=OpenGL`
Start-up errors:
```
Marshaling render signal
GLIB UNHANDLED EXCEPTIONSystem.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotSupportedException: OpenGL is not supported in this system
   at Uno.UI.Runtime.Skia.OpenGLRenderSurface.CreateGRGLContext()
   at Uno.UI.Runtime.Skia.OpenGLRenderSurface.TryBuildGRContext()
   at Uno.UI.Runtime.Skia.GLRenderSurfaceBase.UnoGLDrawingArea_Render(Object o, RenderArgs args)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.Invoke(ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
Unsupported modifier requested
Unsupported modifier requested
Marshaling render signal
GLIB UNHANDLED EXCEPTIONSystem.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotSupportedException: OpenGL is not supported in this system
   at Uno.UI.Runtime.Skia.OpenGLRenderSurface.CreateGRGLContext()
   at Uno.UI.Runtime.Skia.OpenGLRenderSurface.TryBuildGRContext()
   at Uno.UI.Runtime.Skia.GLRenderSurfaceBase.UnoGLDrawingArea_Render(Object o, RenderArgs args)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.Invoke(ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
```
My application starts, but nothing is displayed.

`GDK_BACKEND=wayland` and `RenderSurfaceType=OpenGLES`
```
Unhandled exception. System.IO.FileNotFoundException: Could not find or load the native library: libGLESv2.so Attempted: "libGLESv2.so", "/root/VSLinuxDbg/DMXCore100/libGLESv2.so"
File name: 'libGLESv2.so'
   at Silk.NET.Core.Loader.LibraryLoader.ThrowLibNotFound(String name, PathResolver resolver)
   at Silk.NET.Core.Loader.LibraryLoader.LoadNativeLibrary(String name, PathResolver pathResolver)
   at Silk.NET.Core.Loader.UnmanagedLibrary..ctor(String name, LibraryLoader loader, PathResolver pathResolver)
   at Silk.NET.Core.Loader.UnmanagedLibrary..ctor(String name)
   at Silk.NET.Core.Contexts.DefaultNativeContext..ctor(String name)
   at Uno.UI.Runtime.Skia.OpenGLESRenderSurface.get_NativeContext()
   at Uno.UI.Runtime.Skia.OpenGLESRenderSurface..ctor()
   at Uno.UI.Runtime.Skia.GtkHost.BuildRenderSurfaceType()
   at Uno.UI.Runtime.Skia.GtkHost.FinalizeStartup()
   at Uno.UI.Runtime.Skia.GtkHost.SetupRenderSurface()
   at Uno.UI.Runtime.Skia.GtkHost.Run()
   at DMXCore.DMXCore100.Skia.Gtk.Program.Main() in C:\Projects\DMXCore\100\Software\DMXCore100.Skia.Gtk\Program.cs:line 70
Aborted
```

What is odd with this is that I have `libGLESv2.so.2` in my /usr/lib/aarch64-linux-gnu folder. This is a bookworm Docker container (based on `mcr.microsoft.com/dotnet/sdk:7.0-bookworm-slim-arm64v8`). As an attempt I linked ths `libGLESv2.so` file to `libGLESv2.so.2` and I can start my application, but I get these console errors: `Unsupported modifier requested` and the display is shifted about 100px to the right, parts missing of the UI and I can't really use it, my navigation buttons are missing.

This issue is somewhat related to this discussion: https://github.com/unoplatform/uno/discussions/13641.

### Expected behavior

My Uno Skia Gtk application using GL or GLES should work directly under Wayland on Raspberry Pi 4 hardware.

### How to reproduce it (as minimally and precisely as possible)

This is tricky, this is part of my large application, using docker, etc. My guess is that a simple application would exhibit the same issue, since I get these errors right at start-up, but I have not tested it.

### Workaround

Using `GDK_BACKEND=x11` and use Xwayland works.

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

4.10.26

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

### Anything else we need to know?

`glxinfo -B` output:
```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Broadcom (0x14e4)
    Device: V3D 4.2 (0xffffffff)
    Version: 23.2.1
    Accelerated: yes
    Video memory: 7863MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 3.1
    Max compat profile version: 3.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: Broadcom
OpenGL renderer string: V3D 4.2
OpenGL core profile version string: 3.1 Mesa 23.2.1-0+rpt2
OpenGL core profile shading language version string: 1.40
OpenGL core profile context flags: (none)

OpenGL version string: 3.1 Mesa 23.2.1-0+rpt2
OpenGL shading language version string: 1.40
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.1 Mesa 23.2.1-0+rpt2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
```

**Comment by MartinZikmund** [comment]
# Repro generator

This issue was classified as not reproducible with a code sample or test.

**Reason:** The issue is environment-specific and requires Raspberry Pi 4 hardware running a bookworm Docker container with Wayland (`GDK_BACKEND=wayland`) and a specific GPU driver stack (Broadcom V3D 4.2 / Mesa 23.2.1). Reproducing this requires dedicated ARM64 hardware with a native Wayland compositor — it cannot be automated in a standard CI or desktop environment.
