### ISSUE TITLE
System.InvalidCastException: Unable to cast object of type ' XXXX' to type 'YYYY'

### ISSUE THREAD

**Issue by sushuying521** [unoplatform/uno#14453]
### Current behavior

Hello, our project uses the c# language to develop the Uno framework + Gtk + Skia running on the Linux platform project, 
and it is always triggered **occasionally** when InitializeComponent() is executed 

```
System.InvalidCastException: Unable to cast object of type 'XXXXX' to type 'YYYYY'.””The following is an error message for one of them." ---> System.InvalidCastException: Unable to cast object of type 'System.Double' to type 'Windows.UI.Xaml.Input.XYFocusKeyboardNavigationMode'.
   at Windows.UI.Xaml.UIElement.OnXYFocusKeyboardNavigationBackingFieldUpdate(Object instance, Object newValue)
   at Windows.UI.Xaml.DependencyObjectStore.InvokeCallbacks(DependencyObject actualInstanceAlias, DependencyProperty property, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence, Boolean bypassesPropagation)
   at Windows.UI.Xaml.DependencyObjectStore.RaiseCallbacks(DependencyObject actualInstanceAlias, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence)
   at Windows.UI.Xaml.DependencyObjectStore.InnerSetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isPersistentResourceBinding)
   at Windows.UI.Xaml.DependencyObjectStore.OnParentPropertyChangedCallback(ManagedWeakReference sourceInstance, DependencyProperty parentProperty, Object newValue)
   at Windows.UI.Xaml.DependencyObjectStore.OnParentPropertyChangedCallback(ManagedWeakReference sourceInstance, DependencyProperty parentProperty, Object newValue)
   at Windows.UI.Xaml.DependencyObjectStore.<PropagateInheritedProperties>g__Propagate|151_0(DependencyObjectStore store, <>c__DisplayClass151_0&)
   at Windows.UI.Xaml.DependencyObjectStore.PropagateInheritedProperties(DependencyObjectStore childStore)
   at Windows.UI.Xaml.DependencyObjectStore.RegisterInheritedPropertyChangedCallback(DependencyObjectStore childStore)
   at Windows.UI.Xaml.DependencyObjectStore.RegisterInheritedProperties(IDependencyObjectStoreProvider parentProvider)
   at Windows.UI.Xaml.DependencyObjectStore.TryRegisterInheritedProperties(IDependencyObjectStoreProvider parentProvider, Boolean force)
   at Windows.UI.Xaml.DependencyObjectStore.set_Parent(Object value)
   at Windows.UI.Xaml.DependencyObjectExtensions.SetParent(IDependencyObjectStoreProvider storeProvider, Object parent)
   at Windows.UI.Xaml.UIElement.AddChild(UIElement child, Nullable`1 index)
   at Windows.UI.Xaml.Controls.Control.RegisterSubView(UIElement child)
   at Windows.UI.Xaml.Controls.Control.set_TemplatedRoot(UIElement value)
   at Windows.UI.Xaml.Controls.Control.UpdateTemplate()
   at Windows.UI.Xaml.Controls.Control.SetUpdateControlTemplate(Boolean forceUpdate)
   at Windows.UI.Xaml.Controls.Control.OnTemplateChanged(DependencyPropertyChangedEventArgs e)
   at Windows.UI.Xaml.Controls.Control.<>c.<.cctor>b__379_0(DependencyObject s, DependencyPropertyChangedEventArgs e)
   at Windows.UI.Xaml.DependencyObjectStore.InvokeCallbacks(DependencyObject actualInstanceAlias, DependencyProperty property, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence, Boolean bypassesPropagation)
   at Windows.UI.Xaml.DependencyObjectStore.RaiseCallbacks(DependencyObject actualInstanceAlias, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence)
   at Windows.UI.Xaml.DependencyObjectStore.InnerSetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isPersistentResourceBinding)
   at Windows.UI.Xaml.Setter.ApplyTo(DependencyObject o)
   at Windows.UI.Xaml.Style.ApplyTo(DependencyObject o, DependencyPropertyValuePrecedences precedence)
   at Windows.UI.Xaml.FrameworkElement.OnStyleChanged(Style oldStyle, Style newStyle, DependencyPropertyValuePrecedences precedence)
   at Windows.UI.Xaml.FrameworkElement.ApplyStyle()
   at Windows.UI.Xaml.FrameworkElement.ApplyStyles()
   at Windows.UI.Xaml.FrameworkElement.CreationComplete()
   at Uno.IntegrationTestPlatform.MyWindow.<>c.<InitializeComponent_44A45F2C>b__99_28(Button c18) in H:\Workflow\Vinno.Uno\Uno.IntegrationTestPlatform\obj\Release\netstandard2.0\g\XamlCodeGenerator\MyWindow_4a111db79bb1ee9bef1f3d2bdd7edb6c.g.cs:line 471"
```

### Works on UWP/WinUI

None

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

<PackageReference Include="Uno.UI" Version="4.9.17" />",

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

**Comment by Youssef1313** [comment]
Can you provide a repro please?

**Comment by sushuying521** [comment]
Xaml：
<UserControl
    x:Class="Myclass.MyWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    d:DesignHeight="300"
    d:DesignWidth="400">

    <Grid >
        <Popup x:Name="m_Popup" Height="72" Width="800">
            <Grid Background="#FF323232"  Width="800" Margin="72,0" MinHeight="72" >
            <TextBlock Margin="24,0"
                       HorizontalAlignment="Stretch"
                       VerticalAlignment="Center"
                       Text="{Binding StatusText}"
                       Foreground="White"
                       FontSize="{StaticResource TouchPanel.FontSize.Medium}"
                       TextWrapping="WrapWholeWords"
                       TextAlignment="Left" />
             </Grid>
        </Popup>
    </Grid>
</UserControl>
 it is always triggered **occasionally** when InitializeComponent() is executed

**Comment by jeromelaban** [comment]
Thanks. Make sure to provide all the details that are requested when creating a template, particularly the uno version that you're using.

**Comment by MartinZikmund** [comment]
Are you using `XYFocusKeyboardNavigation` anywhere within the code?

**Comment by Youssef1313** [comment]
I have seen it today in CI:

![image](https://github.com/unoplatform/uno/assets/31348972/f718e060-6572-4f66-a351-d96bed0f1acd)

https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=102402&view=logs&j=6d871ad7-2a7e-50b7-2020-9e22d4075df1&t=63c7d45e-2e27-5d4f-a2d8-bb7b8105683e&s=71fd53b2-b039-5dc2-9015-d1e3f7eed8d5

Happened for PR: #14476

**Comment by ebariche** [comment]
@MartinZikmund I doubt so !

**Comment by jeromelaban** [comment]
@ebariche this looks very similar to https://github.com/unoplatform/uno/discussions/14489. If people have been using the latest dev bits, though none of them have confirmed that they are, this would point to a change in dependency object.

**Comment by Youssef1313** [comment]
@jeromelaban I think some of the recent changes (specifically related to performance) assumed that certain code paths are only run in the UI thread.

Could it be something running in a different thread causing a race? In the stacktrace in the original post here, there is `IntegrationTestPlatform` in the stack trace.

**Comment by jeromelaban** [comment]
It may, indeed. We do not have UI Thread checks in DependencyObject, but it may be interesting to enable them to validate if that's the issue.

**Comment by MartinZikmund** [comment]
@sushuying521 Are you by any chance doing some asynchronous, non-UI thread work in your app by any chance?

**Comment by Youssef1313** [comment]
https://github.com/unoplatform/uno/pull/13963 might be related. It's one of those performance optimizations that rely on code properly executing in the UI thread.

If `GetPropertyType` is accessed by two different threads, bad things can happen.

**Comment by sushuying521** [comment]
> 谢谢。请确保提供创建模板时要求的所有详细信息，尤其是您正在使用的 uno 版本。

	<PackageReference Include="Uno.UI" Version="4.9.17" />

**Comment by sushuying521** [comment]
> Thanks. Make sure to provide all the details that are requested when creating a template, particularly the uno version that you're using.

	<PackageReference Include="Uno.UI" Version="4.9.17" />

**Comment by sushuying521** [comment]
> Are you using anywhere within the code?`XYFocusKeyboardNavigation`
This is not used in our code

**Comment by Youssef1313** [comment]
@sushuying521 Do you have subscription to `Unloaded` event anywhere in your code?

**Comment by Youssef1313** [comment]
@sushuying521 Also, are you using any `RadioButtons`s in your code (not `RadioButton`s). I mean this:

https://github.com/unoplatform/uno/blob/f3cc757fdd3e3cad983c671495fb78b7a70d71ab/src/Uno.UI/Microsoft/UI/Xaml/Controls/RadioButtons/RadioButtons.cs#L21

**Comment by Youssef1313** [comment]
@ebariche @jeromelaban I think this should be fixed and can be closed?

**Comment by jeromelaban** [comment]
Yes it is!
