### ISSUE TITLE
`Microsoft.UI.Xaml.UIElement.set_Name` void not found

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/uno#14552]
### Current behavior

 When I use SettingsControl from the CommunityToolkit with the current version, I get this issue on Uno targets:
 
`Method not found: 'Void Microsoft.UI.Xaml.UIElement.set_Name(System.String)'.`

----
 
 `  at CommunityToolkit.WinUI.Controls.SettingsControlsRns.__Resources._SettingsCard_30c3b459a7f4dbe486c9e9b705365136_SettingsCardRDSC0.Build(Object __ResourceOwner_1) in CommunityToolkit.WinUI.Controls.SettingsControlsRns.__Resources\_SettingsCard_30c3b459a7f4dbe486c9e9b705365136_SettingsCardRDSC0.cs:line 1440
   at CommunityToolkit.WinUI.Controls.SettingsControlsRns.GlobalStaticResources.ResourceDictionarySingleton__SettingsCard_30c3b459a7f4dbe486c9e9b705365136.<>c.<Get_16>b__9_7(Object __owner) in CommunityToolkit.WinUI.Controls.SettingsControlsRns\GlobalStaticResources.cs:line 258
   at Microsoft.UI.Xaml.FrameworkTemplate.Microsoft.UI.Xaml.IFrameworkTemplateInternal.LoadContent()
   at Microsoft.UI.Xaml.FrameworkTemplatePool.DequeueTemplate(FrameworkTemplate template)
   at Microsoft.UI.Xaml.FrameworkTemplate.LoadContentCached()
   at Microsoft.UI.Xaml.Controls.Control.UpdateTemplate()
   at Microsoft.UI.Xaml.Controls.Control.SetUpdateControlTemplate(Boolean forceUpdate)
   at Microsoft.UI.Xaml.Controls.Control.OnTemplateChanged(DependencyPropertyChangedEventArgs e)
   at Microsoft.UI.Xaml.Controls.Control.<>c.<.cctor>b__363_0(DependencyObject s, DependencyPropertyChangedEventArgs e)
   at Microsoft.UI.Xaml.DependencyObjectStore.InvokeCallbacks(DependencyObject actualInstanceAlias, DependencyProperty property, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence, Boolean bypassesPropagation)
   at Microsoft.UI.Xaml.DependencyObjectStore.RaiseCallbacks(DependencyObject actualInstanceAlias, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence)
   at Microsoft.UI.Xaml.DependencyObjectStore.InnerSetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isPersistentResourceBinding)
   at Microsoft.UI.Xaml.UIElement.SetValue(DependencyProperty dp, Object value)
   at Microsoft.UI.Xaml.Setter.ApplyTo(DependencyObject o)
   at Microsoft.UI.Xaml.Style.ApplyTo(DependencyObject o, DependencyPropertyValuePrecedences precedence)
   at Microsoft.UI.Xaml.FrameworkElement.CreationComplete()
   at ProjectSBS.Presentation.NestedPages.SettingsPage.<>c.<InitializeComponent>b__10_8(SettingsCard c7, SettingsPage __that, NameScope __nameScope) in C:\Users\domin\Projects\project-sbs\ProjectSBS\ProjectSBS\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\SettingsPage_eef118a3dfab090cca2c09d7a6e26287.cs:line 280
   at Uno.UI.Helpers.Xaml.ApplyExtensions.GenericApply[TType,TArg1,TArg2](TType instance, TArg1 arg1, TArg2 arg2, Action`3 apply)
   at ProjectSBS.Presentation.NestedPages.SettingsPage.InitializeComponent() in C:\Users\domin\Projects\project-sbs\ProjectSBS\ProjectSBS\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\SettingsPage_eef118a3dfab090cca2c09d7a6e26287.cs:line 72
   at ProjectSBS.Presentation.NestedPages.SettingsPage..ctor() in C:\Users\domin\Projects\project-sbs\ProjectSBS\ProjectSBS\Presentation\NestedPages\SettingsPage.xaml.cs:line 9
   at ProjectSBS.Skia.Gtk.MetadataBuilder_099.CreateInstance() in C:\Users\domin\Projects\project-sbs\ProjectSBS\ProjectSBS.Skia.Gtk\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.BindableTypeProviders.BindableTypeProvidersSourceGenerator\BindableMetadata.g.cs:line 3918
   at Microsoft.UI.Xaml.Controls.Frame.CreatePageInstance(Type sourcePageType)
   at Microsoft.UI.Xaml.PagePool.DequeuePage(Type pageType)
   at Microsoft.UI.Xaml.Controls.Frame.CreatePageInstanceCached(Type sourcePageType)
   at Microsoft.UI.Xaml.Controls.Frame.EnsurePageInitialized(PageStackEntry entry)
   at Microsoft.UI.Xaml.Controls.Frame.InnerNavigateUnsafe(PageStackEntry entry, NavigationMode mode)
   at Microsoft.UI.Xaml.Controls.Frame.InnerNavigate(PageStackEntry entry, NavigationMode mode)`

### Works on UWP/WinUI

Yes

### Affected platforms

WebAssembly, Android, iOS, macOS (AppKit), Mac Catalyst, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Linux Framebuffer)

### IDE

Visual Studio 2022

**Comment by morning4coffe-dev** [comment]
On Update conf, CC @MartinZikmund

**Comment by jeromelaban** [comment]
This is expected, you need to upgrade to a later version of the toolkit. The one you're using is compatible with uno 4.x.

**Comment by jeromelaban** [comment]
Ah! Yes, that version of toolkit is not compatible with Uno 5 yet.

**Comment by MartinZikmund** [comment]
Opened https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/157

**Comment by MartinZikmund** [comment]
This will be fixed with the upcoming 8.x release of Community Toolkit.

**Comment by agneszitte** [comment]
@jeromelaban, @MartinZikmund I think this issue can be closed now right?
@morning4coffe-dev if you can help confirm, please

FYI Documentation and samples with the latest details are on their way for WCT:
- https://github.com/unoplatform/uno/issues/16872
- https://github.com/unoplatform/Uno.Samples/issues/722

**Comment by MartinZikmund** [comment]
Yes, the required Uno fixes are merged on WCT side, so we can close. The release should hopefully happen soon as well
