### ISSUE TITLE
[WPF] Can't load svg

### ISSUE THREAD

**Issue by lld1995** [unoplatform/uno#14600]
### Current behavior

I test ListView on Uno.WinUI(5.0.48) and Uno.WinUI.Svg(5.0.48) and Svg.Skia(1.0.0.6) on WPF

fail: Uno.UI.Svg.SvgProvider[0]
      Failed to load SVG image.
      System.MissingMethodException: Method not found: 'SkiaSharp.SKPicture Svg.Skia.SKSvg.Load(System.IO.Stream)'.
         at Uno.UI.Svg.SvgProvider.<>c__DisplayClass22_0.<LoadSvgAsync>b__0()
         at System.Threading.Tasks.Task`1.InnerInvoke()
         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
      --- End of stack trace from previous location ---
         at Uno.UI.Svg.SvgProvider.TryLoadSvgDataAsync(Byte[] svgBytes) in /__w/1/s/src/AddIns/Uno.UI.Svg/SvgProvider.cs:line 110

### Works on UWP/WinUI

None

### Affected platforms

Skia (WPF)

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
Thanks for the report. 

It looks like there's a breaking change in Svg.Skia, we may need to upgrade to a later package, or use a different method that will prevent the breaking change to happen.

**Comment by Youssef1313** [comment]
@jeromelaban Most SKSvg factory methods had a breaking change, so it's hard to find a different method. The binary break is now fixed with https://github.com/wieslawsoltes/Svg.Skia/pull/192

I think this issue can be closed once a new package of Svg.Skia is published. Then, users can use the newly published version with the binary break fixed.
