### ISSUE TITLE
[Gallery][Android]DatePicker-The app crashes when first click on calendar and then any other control is clicked.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#15256]
### Current behavior

https://github.com/unoplatform/uno/assets/74563602/5e140f37-c25a-4914-9c63-c869830bbf27

https://github.com/unoplatform/uno/assets/74563602/70f3cfd1-8850-4efa-a1f8-54527441c439

### Expected behavior

The app should not crash.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Click "DatePicker" from the "UI Components" list.
4. Click on textbox to open calendar.
5. now click 'Cancel' button on calendar.
6. Now click on any other control like 'Card' control from the 'UI Components' list.
7. Notice that the app gets crashes.

### Works on UWP/WinUI

None

### Affected platforms

Android

**Comment by jeromelaban** [comment]
Stack trace:

```
01-29 22:10:24.212   509   509 D AndroidRuntime: Shutting down VM
01-29 22:10:24.212   509   509 E AndroidRuntime: FATAL EXCEPTION: main
01-29 22:10:24.212   509   509 E AndroidRuntime: Process: com.nventive.uno.ui.demo.canary, PID: 509
01-29 22:10:24.212   509   509 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.Threading.Tasks.TaskCanceledException: TaskCanceledException_ctor_DefaultMessage
01-29 22:10:24.212   509   509 E AndroidRuntime:    at System.WindowsRuntimeSystemExtensions.<AsTaskCore>d__11`1[[System.Nullable`1[[System.DateTimeOffset, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
01-29 22:10:24.212   509   509 E AndroidRuntime:    at Microsoft.UI.Xaml.Controls.DatePicker.ShowPickerFlyout()
01-29 22:10:24.212   509   509 E AndroidRuntime:    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object )
01-29 22:10:24.212   509   509 E AndroidRuntime:    at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0()
01-29 22:10:24.212   509   509 E AndroidRuntime:    at Java.Lang.Thread.RunnableImplementor.Run()
01-29 22:10:24.212   509   509 E AndroidRuntime:    at Java.Lang.IRunnableInvoker.n_Run(IntPtr , IntPtr )
01-29 22:10:24.212   509   509 E AndroidRuntime:    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V , IntPtr , IntPtr )
01-29 22:10:24.212   509   509 E AndroidRuntime:        at mono.java.lang.RunnableImplementor.n_run(Native Method)
01-29 22:10:24.212   509   509 E AndroidRuntime:        at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:31)
01-29 22:10:24.212   509   509 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
01-29 22:10:24.212   509   509 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
01-29 22:10:24.212   509   509 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
01-29 22:10:24.212   509   509 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
01-29 22:10:24.212   509   509 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7874)
01-29 22:10:24.212   509   509 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-29 22:10:24.212   509   509 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-29 22:10:24.212   509   509 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
01-29 22:10:24.214   509   509 W monodroid-assembly: Shared library 'liblog' not loaded, p/invoke '__android_log_print' may fail
01-29 22:10:24.214   509   509 I MonoDroid: UNHANDLED EXCEPTION:
01-29 22:10:24.216   509   509 I MonoDroid: Android.Runtime.JavaProxyThrowable: Exception_WasThrown, Android.Runtime.JavaProxyThrowable
01-29 22:10:24.216   509   509 I MonoDroid:
01-29 22:10:24.216   509   509 I MonoDroid:   --- End of managed Android.Runtime.JavaProxyThrowable stack trace ---
01-29 22:10:24.216   509   509 I MonoDroid: android.runtime.JavaProxyThrowable: System.Threading.Tasks.TaskCanceledException: TaskCanceledException_ctor_DefaultMessage
01-29 22:10:24.216   509   509 I MonoDroid:    at System.WindowsRuntimeSystemExtensions.<AsTaskCore>d__11`1[[System.Nullable`1[[System.DateTimeOffset, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
01-29 22:10:24.216   509   509 I MonoDroid:    at Microsoft.UI.Xaml.Controls.DatePicker.ShowPickerFlyout()
01-29 22:10:24.216   509   509 I MonoDroid:    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object )
01-29 22:10:24.216   509   509 I MonoDroid:    at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0()
01-29 22:10:24.216   509   509 I MonoDroid:    at Java.Lang.Thread.RunnableImplementor.Run()
01-29 22:10:24.216   509   509 I MonoDroid:    at Java.Lang.IRunnableInvoker.n_Run(IntPtr , IntPtr )
01-29 22:10:24.216   509   509 I MonoDroid:    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V , IntPtr , IntPtr )
01-29 22:10:24.216   509   509 I MonoDroid:     at mono.java.lang.RunnableImplementor.n_run(Native Method)
01-29 22:10:24.216   509   509 I MonoDroid:     at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:31)
01-29 22:10:24.216   509   509 I MonoDroid:     at android.os.Handler.handleCallback(Handler.java:938)
01-29 22:10:24.216   509   509 I MonoDroid:     at android.os.Handler.dispatchMessage(Handler.java:99)
01-29 22:10:24.216   509   509 I MonoDroid:     at android.os.Looper.loopOnce(Looper.java:201)
01-29 22:10:24.216   509   509 I MonoDroid:     at android.os.Looper.loop(Looper.java:288)
01-29 22:10:24.216   509   509 I MonoDroid:     at android.app.ActivityThread.main(ActivityThread.java:7874)
01-29 22:10:24.216   509   509 I MonoDroid:     at java.lang.reflect.Method.invoke(Native Method)
01-29 22:10:24.216   509   509 I MonoDroid:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-29 22:10:24.216   509   509 I MonoDroid:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
01-29 22:10:24.216   509   509 I MonoDroid:
01-29 22:10:24.216   509   509 I MonoDroid:   --- End of managed Android.Runtime.JavaProxyThrowable stack trace ---
01-29 22:10:24.216   509   509 I MonoDroid: android.runtime.JavaProxyThrowable: System.Threading.Tasks.TaskCanceledException: TaskCanceledException_ctor_DefaultMessage
01-29 22:10:24.216   509   509 I MonoDroid:    at System.WindowsRuntimeSystemExtensions.<AsTaskCore>d__11`1[[System.Nullable`1[[System.DateTimeOffset, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
01-29 22:10:24.216   509   509 I MonoDroid:    at Microsoft.UI.Xaml.Controls.DatePicker.ShowPickerFlyout()
01-29 22:10:24.216   509   509 I MonoDroid:    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object )
01-29 22:10:24.216   509   509 I MonoDroid:    at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0()
01-29 22:10:24.216   509   509 I MonoDroid:    at Java.Lang.Thread.RunnableImplementor.Run()
01-29 22:10:24.216   509   509 I MonoDroid:    at Java.Lang.IRunnableInvoker.n_Run(IntPtr , IntPtr )
01-29 22:10:24.216   509   509 I MonoDroid:    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V , IntPtr , IntPtr )
01-29 22:10:24.216   509   509 I MonoDroid:     at mono.java.lang.RunnableImplementor.n_run(Native Method)
01-29 22:10:24.216   509   509 I MonoDroid:     at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:31)
01-29 22:10:24.216   509   509 I MonoDroid:     at android.os.Handler.handleCallback(Handler.java:938)
01-29 22:10:24.216   509   509 I MonoDroid:     at android.os.Handler.dispatchMessage(Handler.java:99)
01-29 22:10:24.216   509   509 I MonoDroid:     at android.os.Looper.loopOnce(Looper.java:201)
01-29 22:10:24.216   509   509 I MonoDroid:     at android.os.Looper.loop(Looper.java:288)
01-29 22:10:24.216   509   509 I MonoDroid:     at android.app.ActivityThread.main(ActivityThread.java:7874)
01-29 22:10:24.216   509   509 I MonoDroid:     at java.lang.reflect.Method.invoke(Native Method)
01-29 22:10:24.216   509   509 I MonoDroid:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-29 22:10:24.216   509   509 I MonoDroid:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by jeromelaban** [comment]
@MartinZikmund does this look familiar? Could it be related to your recent changes in TimePicker?
