### ISSUE TITLE
Failure when using SystemNavigationManager.GetForCurrentView()

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#15289]
### Current behavior

The following:
```
SystemNavigationManager.GetForCurrentView().BackRequested += App_BackRequested;
```

Fails in the playground canary:

```
System.Collections.Generic.KeyNotFoundException: Arg_KeyNotFoundWithKey, Microsoft.UI.WindowId
dotnet.native.js:8    at System.Collections.Generic.Dictionary`2[[Microsoft.UI.WindowId, Uno, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null],[Windows.UI.ViewManagement.ApplicationView, Uno, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]].get_Item(WindowId key)
dotnet.native.js:8    at Windows.UI.ViewManagement.ApplicationView.GetForWindowId(WindowId windowId)
dotnet.native.js:8    at Windows.UI.ViewManagement.ApplicationView.GetForCurrentView()
dotnet.native.js:8    at Uno.UI.Demo.App.OnLaunched(LaunchActivatedEventArgs e)
```

### Expected behavior

No failure

### Works on UWP/WinUI

None

### NuGet package version(s)

5.2.0-dev.412

**Comment by Youssef1313** [comment]
This generally means that `GetForCurrentView` is called very early, before the window is initialized.
