### ISSUE TITLE
`SelectingTimeSetsSelectedTime` is failing

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#15459]
@MartinZikmund `SelectingTimeSetsSelectedTime` is failing, so I went to test it out locally, and it doesn't seem to be working locally even on master. Any idea why? 

```
Failed: SelectingTimeSetsSelectedTime() [System.ArgumentException] 
 System.ArgumentException: value
   at Windows.Globalization.Calendar.set_Period(Int32 value) in D:\uno\src\Uno.UWP\Globalization\Calendar.cs:line 296
   at Uno.UI.RuntimeTests.Tests.Windows_UI_Xaml_Controls.TimePickerIntegrationTests.CreateTime(Int32 hours, Int32 minutes, Int32 period) in D:\uno\src\Uno.UI.RuntimeTests\MUX\Microsoft_UI_Xaml_Controls\TimePicker\TimePickerIntegrationTests.cs:line 28
   at Uno.UI.RuntimeTests.Tests.Windows_UI_Xaml_Controls.TimePickerIntegrationTests.SelectingTimeSetsSelectedTime() in D:\uno\src\Uno.UI.RuntimeTests\MUX\Microsoft_UI_Xaml_Controls\TimePicker\TimePickerIntegrationTests.cs:line 279
   at Uno.UI.Samples.Tests.UnitTestsControl.<>c__DisplayClass63_2.<<ExecuteTestsForInstance>g__InvokeTestMethod|3>d.MoveNext() in D:\uno\src\SamplesApp\SamplesApp.UnitTests.Shared\Controls\UnitTest\UnitTestsControl.cs:line 894
```

_Originally posted by @ramezgerges in https://github.com/unoplatform/uno/pull/15354#issuecomment-1942032249_

**Comment by Youssef1313** [comment]
@MartinZikmund The only case for the code to throw is if the period being set is `2` with `_clock` being `TwentyFourHour`. Is this a case we should throw an exception for?
