### ISSUE TITLE
`When_MediaPlayerElement_SetSource_Check_Play` fails on Skia

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#15471]
### Current behavior

```
Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Timed out waiting for condition to be met. Timeout waiting for the playback session state changing to Play.
   at Private.Infrastructure.TestServices.WindowHelper.WaitFor(Func`1 condition, Int32 timeoutMS, String message, String callerMemberName, Int32 lineNumber) in C:\a\1\s\src\Uno.UI.RuntimeTests\IntegrationTests\common\TestServices.WindowHelper.cs:line 300
   at Uno.UI.RuntimeTests.Tests.Windows_UI_Xaml_Controls.Given_MediaPlayerElement.When_MediaPlayerElement_SetSource_Check_Play() in C:\a\1\s\src\Uno.UI.RuntimeTests\Tests\Windows_UI_Xaml_Controls\Given_MediaPlayerElement.cs:line 184
   at Uno.UI.Samples.Tests.UnitTestsControl.<>c__DisplayClass63_1.<<ExecuteTestsForInstance>g__InvokeTestMethod|3>d.MoveNext() in C:\a\1\s\src\SamplesApp\SamplesApp.UnitTests.Shared\Controls\UnitTest\UnitTestsControl.cs:line 962
```

### Expected behavior

It should pass.

### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment]
Ignoring in #15471
