### ISSUE TITLE
`When_Enabled_Inside_Disabled_Control` test is flaky on WinUI

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#15536]
### Current behavior

Running the test multiple times on WinUI, it randomly passes or fails.

```
Failed: When_Enabled_Inside_Disabled_Control() [Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException] 
 Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Assert.AreEqual failed. Expected:<True>. Actual:<False>. 
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.HandleFail(String assertionName, String message, Object[] parameters)
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.AreEqual[T](T expected, T actual, String message, Object[] parameters)
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.AreEqual[T](T expected, T actual)
   at Uno.UI.RuntimeTests.Tests.Windows_UI_Xaml_Controls.Given_Button.When_Enabled_Inside_Disabled_Control()
   at Uno.UI.Samples.Tests.UnitTestsControl.<>c__DisplayClass62_2.<<ExecuteTestsForInstance>g__InvokeTestMethod|3>d.MoveNext()
```

### Expected behavior

We should modify the test so that it's stable on WinUI.

### Works on UWP/WinUI

None

**Comment by ramezgerges** [comment]
Tested now, doesn't seem to ever fail on my end.
