### ISSUE TITLE
Exception System.ArgumentException: SR.Argument_AddingDuplicate__ when replacing items in ObservableCollection

### ISSUE THREAD

**Issue by HakanL** [unoplatform/uno#15673]
### Current behavior

I'm running into a problem with my project. I have XAML code that has an `ObservableCollection` with "columns". And each column can have multiple "menu items". The main collection is bound to an `ItemsControl` and it populates a `DockPanel`. Each child in that `ItemsControl` is a user control that has an `ItemsRepeater` with `Cards` (basically buttons on the screen, dynamically created from JSON). It works great when displayed the first time. 
But if I update the JSON in the backend, which basically clears the `ObservableCollection` and re-generates it, it should update the window with all the new controls. This throws an exception deep from within the depths of Uno. I have tried unsuccessfully to reproduce it in a simpler solution. I've also tried to eliminate some of the complexity in my application to see if it helps. For example, if I change out the `Card` (that generates the buttons) to just a `TextBlock`, then I can call the update function once, but after that I get the same error. Since I can't reproduce it in a simpler solution it's obviously hard to figure out what's going on. And the rest of my application works great, and if I navigate away from this view and then back into it then it works fine too, it's just the dynamic update feature that is causing this problem.
Any help on how I can troubleshoot this is appreciated. I opened it as a bug since it doesn't seem correct that this exception is thrown on otherwise working code, but I'd be the first to accept that I may be doing something wrong in my code.

Here's the full stack trace of the exception:
```
14:58:10.876 ERR [Uno.UI.Dispatching.NativeDispatcher] NativeDispatcher unhandled exception
System.ArgumentException: SR.Argument_AddingDuplicate__
   at Uno.Collections.HashtableEx.Insert(Object key, Object nvalue, Boolean add) in /__w/1/s/src/Uno.UWP/Collections/HashtableEx.cs:line 760
   at Microsoft.UI.Xaml.DependencyProperty.GetProperty(Type type, String name) in /__w/1/s/src/Uno.UI/UI/Xaml/DependencyProperty.cs:line 358
   at Microsoft.UI.Xaml.DependencyObjectStore.OnParentPropertyChangedCallback(ManagedWeakReference sourceInstance, DependencyProperty parentProperty, Object newValue) in /__w/1/s/src/Uno.UI/UI/Xaml/DependencyObjectStore.cs:line 1084
   at Microsoft.UI.Xaml.DependencyObjectStore.PropagateInheritedNonLocalProperties(DependencyObjectStore childStore) in /__w/1/s/src/Uno.UI/UI/Xaml/DependencyObjectStore.cs:line 1624
   at Microsoft.UI.Xaml.DependencyObjectStore.PropagateInheritedProperties(DependencyObjectStore childStore) in /__w/1/s/src/Uno.UI/UI/Xaml/DependencyObjectStore.cs:line 1579
   at Microsoft.UI.Xaml.DependencyObjectStore.RegisterInheritedPropertyChangedCallback(DependencyObjectStore childStore) in /__w/1/s/src/Uno.UI/UI/Xaml/DependencyObjectStore.cs:line 949
   at Microsoft.UI.Xaml.DependencyObjectStore.RegisterInheritedProperties(IDependencyObjectStoreProvider parentProvider) in /__w/1/s/src/Uno.UI/UI/Xaml/DependencyObjectStore.cs:line 1187
   at Microsoft.UI.Xaml.DependencyObjectStore.TryRegisterInheritedProperties(IDependencyObjectStoreProvider parentProvider, Boolean force) in /__w/1/s/src/Uno.UI/UI/Xaml/DependencyObjectStore.cs:line 1146
   at Microsoft.UI.Xaml.DependencyObjectStore.set_Parent(Object value) in /__w/1/s/src/Uno.UI/UI/Xaml/DependencyObjectStore.cs:line 154
   at Microsoft.UI.Xaml.Controls.UIElementCollection.Add(UIElement item) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElementCollection.cs:line 60
   at Microsoft.UI.Xaml.Controls.ViewManager.GetElementFromElementFactory(Int32 index) in /__w/1/s/src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/ViewManager.cs:line 832
   at Microsoft.UI.Xaml.Controls.ViewManager.GetElement(Int32 index, Boolean forceCreate, Boolean suppressAutoRecycle) in /__w/1/s/src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/ViewManager.cs:line 107
   at Microsoft.UI.Xaml.Controls.ItemsRepeater.GetElementImpl(Int32 index, Boolean forceCreate, Boolean suppressAutoRecycle) in /__w/1/s/src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/ItemsRepeater.cs:line 375
   at Microsoft.UI.Xaml.Controls.RepeaterLayoutContext.GetOrCreateElementAtCore(Int32 index, ElementRealizationOptions options) in /__w/1/s/src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/RepeaterLayoutContext.cs:line 26
   at Microsoft.UI.Xaml.Controls.VirtualizingLayoutContext.GetOrCreateElementAt(Int32 index, ElementRealizationOptions options) in /__w/1/s/src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/VirtualizingLayoutContext.cs:line 34
   at Microsoft.UI.Xaml.Controls.StackLayout.GetAverageElementSize(Size availableSize, VirtualizingLayoutContext context, StackLayoutState stackLayoutState) in /__w/1/s/src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/StackLayout.cs:line 344
   at Microsoft.UI.Xaml.Controls.StackLayout.GetAnchorForRealizationRect(Size availableSize, VirtualizingLayoutContext context) in /__w/1/s/src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/StackLayout.cs:line 135
   at Microsoft.UI.Xaml.Controls.StackLayout.Microsoft.UI.Xaml.Controls.IFlowLayoutAlgorithmDelegates.Algorithm_GetAnchorForRealizationRect(Size availableSize, VirtualizingLayoutContext context) in /__w/1/s/src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/StackLayout.cs:line 246
   at Microsoft.UI.Xaml.Controls.FlowLayoutAlgorithm.GetAnchorIndex(Size availableSize, Boolean isWrapping, Double minItemSpacing, Boolean disableVirtualization, String layoutId) in /__w/1/s/src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/FlowLayoutAlgorithm.cs:line 257
   at Microsoft.UI.Xaml.Controls.FlowLayoutAlgorithm.Measure(Size availableSize, VirtualizingLayoutContext context, Boolean isWrapping, Double minItemSpacing, Double lineSpacing, UInt32 maxItemsPerLine, ScrollOrientation orientation, Boolean disableVirtualization, String layoutId) in /__w/1/s/src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/FlowLayoutAlgorithm.cs:line 103
   at Microsoft.UI.Xaml.Controls.StackLayout.MeasureOverride(VirtualizingLayoutContext context, Size availableSize) in /__w/1/s/src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/StackLayout.cs:line 78
   at Microsoft.UI.Xaml.Controls.Layout.Measure(LayoutContext context, Size availableSize) in /__w/1/s/src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/Layout.cs:line 80
   at Microsoft.UI.Xaml.Controls.ItemsRepeater.MeasureOverride(Size availableSize) in /__w/1/s/src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/ItemsRepeater.cs:line 249
   at Microsoft.UI.Xaml.FrameworkElement.InnerMeasureCore(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.Layout.crossruntime.cs:line 137
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.crossruntime.cs:line 176
   at Microsoft.UI.Xaml.Controls.ScrollContentPresenter.MeasureOverride(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.cs:line 193
   at Microsoft.UI.Xaml.FrameworkElement.InnerMeasureCore(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.Layout.crossruntime.cs:line 137
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.crossruntime.cs:line 176
   at Microsoft.UI.Xaml.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Int32 cellCount, Double rowSpacing, Double columnSpacing, Boolean ignoreColumnDesiredSize, Boolean forceRowToInfinity, CellCacheStackVector& cellCacheVector) in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/Grid/Grid.cs:line 373
   at Microsoft.UI.Xaml.Controls.Grid.MeasureOverride(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/Grid/Grid.cs:line 1043
   at Microsoft.UI.Xaml.FrameworkElement.InnerMeasureCore(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.Layout.crossruntime.cs:line 137
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.crossruntime.cs:line 176
   at Microsoft.UI.Xaml.FrameworkElement.MeasureElement(UIElement view, Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.cs:line 315
   at Microsoft.UI.Xaml.Controls.Border.MeasureOverride(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/Border/Border.Layout.cs:line 28
   at Microsoft.UI.Xaml.FrameworkElement.InnerMeasureCore(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.Layout.crossruntime.cs:line 137
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.crossruntime.cs:line 176
   at Microsoft.UI.Xaml.FrameworkElement.MeasureFirstChild(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.cs:line 761
   at Microsoft.UI.Xaml.Controls.ScrollViewer.MeasureOverride(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.cs:line 669
   at Microsoft.UI.Xaml.FrameworkElement.InnerMeasureCore(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.Layout.crossruntime.cs:line 137
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.crossruntime.cs:line 176
   at Microsoft.UI.Xaml.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Int32 cellCount, Double rowSpacing, Double columnSpacing, Boolean ignoreColumnDesiredSize, Boolean forceRowToInfinity, CellCacheStackVector& cellCacheVector) in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/Grid/Grid.cs:line 373
   at Microsoft.UI.Xaml.Controls.Grid.MeasureOverride(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/Grid/Grid.cs:line 1043
   at Microsoft.UI.Xaml.FrameworkElement.InnerMeasureCore(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.Layout.crossruntime.cs:line 137
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.crossruntime.cs:line 176
   at Microsoft.UI.Xaml.FrameworkElement.MeasureFirstChild(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.cs:line 761
   at Microsoft.UI.Xaml.FrameworkElement.InnerMeasureCore(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.Layout.crossruntime.cs:line 137
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.crossruntime.cs:line 176
   at Microsoft.UI.Xaml.FrameworkElement.MeasureFirstChild(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.cs:line 761
   at Microsoft.UI.Xaml.Controls.ContentPresenter.MeasureOverride(Size size) in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs:line 1137
   at Microsoft.UI.Xaml.FrameworkElement.InnerMeasureCore(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.Layout.crossruntime.cs:line 137
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.crossruntime.cs:line 176
   at CommunityToolkit.WinUI.UI.Controls.DockPanel.MeasureOverride(Size availableSize)
   at Microsoft.UI.Xaml.FrameworkElement.InnerMeasureCore(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.Layout.crossruntime.cs:line 137
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.crossruntime.cs:line 176
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.crossruntime.cs:line 176
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.crossruntime.cs:line 176
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.crossruntime.cs:line 176
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.crossruntime.cs:line 176
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.crossruntime.cs:line 176
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.crossruntime.cs:line 176
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.crossruntime.cs:line 176
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.crossruntime.cs:line 176
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.crossruntime.cs:line 176
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.crossruntime.cs:line 176
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.crossruntime.cs:line 176
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.Layout.crossruntime.cs:line 171
   at Microsoft.UI.Xaml.XamlRoot.RunMeasureAndArrange() in /__w/1/s/src/Uno.UI/UI/Xaml/XamlRoot.crossruntime.cs:line 122
   at Uno.UI.Dispatching.NativeDispatcher.DispatchItems() in /__w/1/s/src/Uno.UI.Dispatching/Native/NativeDispatcher.cs:line 131
```

### Expected behavior

User controls should be re-created and no exception thrown

### Works on UWP/WinUI

None

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

```
<PackageReference Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.1" />
<PackageReference Include="Uno.Diagnostics.Eventing.Providers" Version="2.1.0" />
<PackageReference Include="Uno.Dsp.Tasks" Version="1.2.9" />
<PackageReference Include="Uno.Extensions.Authentication.WinUI" Version="4.0.0" />
<PackageReference Include="Uno.Extensions.Configuration" Version="4.0.0" />
<PackageReference Include="Uno.Extensions.Logging.Serilog" Version="4.0.0" />
<PackageReference Include="Uno.Extensions.Logging.WinUI" Version="4.0.0" />
<PackageReference Include="Uno.Extensions.Navigation.Toolkit.WinUI" Version="4.0.0" />
<PackageReference Include="Uno.Extensions.Navigation.WinUI" Version="4.0.0" />
<PackageReference Include="Uno.Material.WinUI" Version="4.1.1" />
<PackageReference Include="Uno.Resizetizer" Version="1.3.0" />
<PackageReference Include="Uno.Toolkit.WinUI" Version="5.1.7" />
<PackageReference Include="Uno.Toolkit.WinUI.Material" Version="5.1.7" />
<PackageReference Include="Uno.WinUI" Version="5.1.69" />
<PackageReference Include="CommunityToolkit.WinUI.UI.Controls" Version="7.1.2" />
<PackageReference Include="Uno.CommunityToolkit.WinUI.UI.Controls" Version="7.1.200" />
```

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

### Anything else we need to know?

I've only tested this on Windows Skia so far.

**Comment by Youssef1313** [comment]
I'd suspect that something else is accessing the DP system concurrently.

**Comment by HakanL** [comment]
Of course it is!! Holy moly, when in doubt, always schedule it on the UI Dispatcher... That solved it. @Youssef1313 Thank you for pointing me in the right direction! I've spent a lot of timing banging my head against this issue, partly because I didn't understand the exception.
