### ISSUE TITLE
`WebView` tests are flaky on iOS

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#15828]
### Current behavior

These tests were previously ignored and are restored with https://github.com/unoplatform/uno/commit/c6bf106fd3067a399cc2a8f3d9ea35294ea8864c

But they are still flaky.

https://dev.azure.com/uno-platform/Uno%20Platform/_TestManagement/Runs?runId=2738291&_a=resultSummary&resultId=100636

```
Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Timed out waiting for condition to be met. When_Navigate():51
   at Private.Infrastructure.TestServices.WindowHelper.WaitFor(Func`1 condition, Int32 timeoutMS, String message, String callerMemberName, Int32 lineNumber)
   at Uno.UI.RuntimeTests.Tests.Microsoft_UI_Xaml_Controls.Given_WebView2.When_Navigate()
   at Uno.UI.Samples.Tests.UnitTestsControl.<>c__DisplayClass63_1.<<ExecuteTestsForInstance>g__InvokeTestMethod|3>d.MoveNext()

```

### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment]
@MartinZikmund If the issue isn't apparent, I think we should ignore the tests again for CI stability.

**Comment by jeromelaban** [comment]
I'll include that in https://github.com/unoplatform/uno/pull/15781 to get the builds going.

**Comment by MartinZikmund** [comment]
Still relevant to Skia
