### ISSUE TITLE
Unable to launch FrameBuffer app

### ISSUE THREAD

**Issue by weitzhandler** [unoplatform/uno#15952]
### Current behavior

When trying to start the FrameBuffer head the following exception is thrown:

> System.DllNotFoundException: 'Unable to load DLL 'libc' or one of its dependencies: The specified module could not be found. (0x8007007E)'

StackTrace:

>   at Uno.UI.Runtime.Skia.Native.Libc.open(String pathname, Int32 flags, Int32 mode)
   at Uno.UI.Runtime.Skia.FrameBufferDevice..ctor(String fileName) in Uno.UI.Runtime.Skia\FrameBufferDevice.cs:line 77
   at Uno.UI.Runtime.Skia.Renderer..ctor(IXamlRootHost host) in Uno.UI.Runtime.Skia\Renderer.cs:line 33
   at Uno.UI.Runtime.Skia.Linux.FrameBuffer.FrameBufferHost.Initialize() in Uno.UI.Runtime.Skia.Linux.FrameBuffer\FrameBufferHost.cs:line 93
   at Uno.WinUI.Runtime.Skia.LinuxFB.EventLoop.Run() in Uno.WinUI.Runtime.Skia.LinuxFB\EventLoop.cs:line 103

### Expected behavior

FrameBuffer should run properly

### How to reproduce it (as minimally and precisely as possible)

Tried with newly generated app using Wizard.

### Works on UWP/WinUI

None

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

5.1.87

### Affected platforms

Skia (Linux Framebuffer)

### IDE

Visual Studio 2022

### Anything else we need to know?

- Tried Any CPU/x86/x64
- Uno check all green

**Comment by mcNets** [comment]
Are you trying to run the Linux head on a Windows machine?

I'm abe to run the WIndows head and I receive this error if I try to run the Linux head on a Windows machine.

**Comment by weitzhandler** [comment]
Yes on Windows from VS.
