### ISSUE TITLE
[Gallery][Skia.GTK/Wasm]Chip- Chip control page is blank

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#16047]
### Current behavior

![Chip issue](https://github.com/unoplatform/uno/assets/74563602/e2718dfb-21f7-49e4-ab20-fcaee0dfeb8d)

### Expected behavior

![Chip correct](https://github.com/unoplatform/uno/assets/74563602/9c29eb18-c17a-4fa0-8547-b2b4c77e331e)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Tap "Chip" from the "Toolkit" list.
4. Notice that the chip page is blank.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly, Skia (GTK on Linux/macOS/Windows)

**Comment by jeromelaban** [comment]
@kazo0 looks familiar?

**Comment by kazo0** [comment]
@jeromelaban Looking now,

Here's what I'm seeing in the console logs:

> fail: Microsoft.UI.Xaml.Data.BindingExpression[0]
>       Failed to apply binding to property [DependencyPropertyDetails(Content)] on [Microsoft.UI.Xaml.Controls.ContentPresenter] (Object reference not set to an instance of an object.)
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Uno.UI.ResourceResolver.ResolveResourceStatic(Object key, Type type, Object context) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/ResourceResolver.cs:line 89
>    at Uno.UI.ResourceResolverSingleton.ResolveResourceStatic(Object key, Type type, Object context) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/ResourceResolverSingleton.cs:line 33
>    at Uno.Toolkit.UI.Material.__Resources._mergedpages_WinUI_v2_72a29a0ae47960b9a27d0c35f05f05bb_mergedpages_WinUI_v2RDSC17.<>c__DisplayClass3_3.<Build>b__19() in D:\a\1\s\src\library\Uno.Toolkit.Material\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\mergedpages_WinUI_v2_72a29a0ae47960b9a27d0c35f05f05bb.cs:line 16167
>    at Microsoft.UI.Xaml.VisualState.EnsureMaterialized() in /agent/_work/1/s/src/Uno.UI/UI/Xaml/VisualState.cs:line 171
>    at Microsoft.UI.Xaml.VisualState.get_Storyboard() in /agent/_work/1/s/src/Uno.UI/UI/Xaml/VisualState.cs:line 35
>    at Microsoft.UI.Xaml.VisualStateGroup.GoToState(IFrameworkElement element, VisualState state, Boolean useTransitions, Action onStateChanged) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/VisualStateGroup.cs:line 237
>    at Microsoft.UI.Xaml.VisualStateManager.GoToStateCorePrivateBaseImplementation(Control control, VisualStateGroup group, VisualState state, Boolean useTransitions) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/VisualStateManager.cs:line 216
>    at Microsoft.UI.Xaml.VisualStateManager.GoToStateCore(Control control, FrameworkElement templateRoot, String stateName, VisualStateGroup group, VisualState state, Boolean useTransitions) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/VisualStateManager.cs:line 183
>    at Microsoft.UI.Xaml.VisualStateManager.GoToState(Control control, String stateName, Boolean useTransitions) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/VisualStateManager.cs:line 179
>    at Microsoft.UI.Xaml.Controls.Control.GoToState(Boolean useTransitions, String stateName) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/Controls/Control/Control.cs:line 1271
>    at Microsoft.UI.Xaml.Controls.Primitives.ToggleButton.ChangeVisualState(Boolean useTransitions) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/Controls/Primitives/ToggleButton.mux.cs:line 101
>    at Microsoft.UI.Xaml.Controls.Control.UpdateVisualState(Boolean useTransitions) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/Controls/Control/Control.cs:line 85
>    at Microsoft.UI.Xaml.Controls.Primitives.ButtonBase.OnApplyTemplate() in /agent/_work/1/s/src/Uno.UI/UI/Xaml/Controls/Primitives/ButtonBase/ButtonBase.mux.cs:line 724
>    at Uno.Toolkit.UI.Chip.OnApplyTemplate() in D:\a\1\s\src\Uno.Toolkit.UI\Controls\Chips\Chip.cs:line 37
>    at Microsoft.UI.Xaml.Controls.Control.TryCallOnApplyTemplate() in /agent/_work/1/s/src/Uno.UI/UI/Xaml/Controls/Control/Control.cs:line 320
>    at Microsoft.UI.Xaml.Controls.Control.OnPostLoading() in /agent/_work/1/s/src/Uno.UI/UI/Xaml/Controls/Control/Control.cs:line 308
>    at Microsoft.UI.Xaml.FrameworkElement.OnFwEltLoading() in /agent/_work/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.crossruntime.cs:line 66
>    at Microsoft.UI.Xaml.UIElement.OnElementLoading(Int32 depth) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/UIElement.crossruntime.cs:line 91
>    at Microsoft.UI.Xaml.UIElement.OnElementLoading(Int32 depth) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/UIElement.crossruntime.cs:line 102
>    at Microsoft.UI.Xaml.UIElement.OnElementLoading(Int32 depth) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/UIElement.crossruntime.cs:line 102
>    at Microsoft.UI.Xaml.UIElement.OnElementLoading(Int32 depth) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/UIElement.crossruntime.cs:line 102
>    at Microsoft.UI.Xaml.UIElement.OnElementLoading(Int32 depth) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/UIElement.crossruntime.cs:line 102
>    at Microsoft.UI.Xaml.UIElement.OnElementLoading(Int32 depth) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/UIElement.crossruntime.cs:line 102
>    at Microsoft.UI.Xaml.UIElement.OnElementLoading(Int32 depth) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/UIElement.crossruntime.cs:line 102
>    at Microsoft.UI.Xaml.UIElement.OnElementLoading(Int32 depth) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/UIElement.crossruntime.cs:line 102
>    at Microsoft.UI.Xaml.UIElement.OnElementLoading(Int32 depth) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/UIElement.crossruntime.cs:line 102
>    at Microsoft.UI.Xaml.UIElement.OnElementLoading(Int32 depth) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/UIElement.crossruntime.cs:line 102
>    at Microsoft.UI.Xaml.UIElement.OnElementLoading(Int32 depth) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/UIElement.crossruntime.cs:line 102
>    at Microsoft.UI.Xaml.UIElement.OnElementLoading(Int32 depth) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/UIElement.crossruntime.cs:line 102
>    at Microsoft.UI.Xaml.UIElement.OnElementLoading(Int32 depth) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/UIElement.crossruntime.cs:line 102
>    at Microsoft.UI.Xaml.UIElement.OnElementLoading(Int32 depth) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/UIElement.crossruntime.cs:line 102
>    at Microsoft.UI.Xaml.UIElement.OnElementLoading(Int32 depth) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/UIElement.crossruntime.cs:line 102
>    at Microsoft.UI.Xaml.UIElement.OnElementLoading(Int32 depth) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/UIElement.crossruntime.cs:line 102
>    at Microsoft.UI.Xaml.UIElement.OnElementLoading(Int32 depth) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/UIElement.crossruntime.cs:line 102
>    at Microsoft.UI.Xaml.UIElement.OnElementLoading(Int32 depth) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/UIElement.crossruntime.cs:line 102
>    at Microsoft.UI.Xaml.UIElement.OnElementLoading(Int32 depth) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/UIElement.crossruntime.cs:line 102
>    at Microsoft.UI.Xaml.UIElement.OnElementLoading(Int32 depth) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/UIElement.crossruntime.cs:line 102
>    at Microsoft.UI.Xaml.UIElement.OnElementLoading(Int32 depth) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/UIElement.crossruntime.cs:line 102
>    at Microsoft.UI.Xaml.UIElement.OnElementLoading(Int32 depth) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/UIElement.crossruntime.cs:line 102
>    at Microsoft.UI.Xaml.UIElement.OnElementLoading(Int32 depth) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/UIElement.crossruntime.cs:line 102
>    at Microsoft.UI.Xaml.UIElement.OnElementLoading(Int32 depth) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/UIElement.crossruntime.cs:line 102
>    at Microsoft.UI.Xaml.UIElement.OnElementLoading(Int32 depth) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/UIElement.crossruntime.cs:line 102
>    at Microsoft.UI.Xaml.UIElement.OnAddingChild(UIElement child) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/UIElement.crossruntime.cs:line 186
>    at Microsoft.UI.Xaml.UIElement.AddChild(UIElement child, Nullable`1 index) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/UIElement.wasm.cs:line 449
>    at Microsoft.UI.Xaml.Controls.ContentPresenter.RegisterContentTemplateRoot() in /agent/_work/1/s/src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.crossruntime.cs:line 12
>    at Microsoft.UI.Xaml.Controls.ContentPresenter.set_ContentTemplateRoot(UIElement value) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs:line 720
>    at Microsoft.UI.Xaml.Controls.ContentPresenter.UpdateContentTemplateRoot() in /agent/_work/1/s/src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs:line 914
>    at Microsoft.UI.Xaml.Controls.ContentPresenter.SetUpdateTemplate() in /agent/_work/1/s/src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs:line 1181
>    at Microsoft.UI.Xaml.Controls.ContentPresenter.OnContentChanged(Object oldValue, Object newValue) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs:line 644
>    at Microsoft.UI.Xaml.Controls.ContentPresenter.<>c.<.cctor>b__274_0(DependencyObject s, DependencyPropertyChangedEventArgs e) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs:line 114
>    at Microsoft.UI.Xaml.PropertyMetadata.RaisePropertyChanged(DependencyObject source, DependencyPropertyChangedEventArgs e) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/PropertyMetadata.cs:line 192
>    at Microsoft.UI.Xaml.DependencyObjectStore.InvokeCallbacks(DependencyObject actualInstanceAlias, DependencyProperty property, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence, Boolean bypassesPropagation) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/DependencyObjectStore.cs:line 1918
>    at Microsoft.UI.Xaml.DependencyObjectStore.RaiseCallbacks(DependencyObject actualInstanceAlias, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/DependencyObjectStore.cs:line 1822
>    at Microsoft.UI.Xaml.DependencyObjectStore.InnerSetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isPersistentResourceBinding) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/DependencyObjectStore.cs:line 513
>    at Microsoft.UI.Xaml.DependencyObjectStore.SetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isPersistentResourceBinding) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/DependencyObjectStore.cs:line 439
>    at Microsoft.UI.Xaml.DependencyObjectExtensions.SetValue(Object instance, DependencyProperty property, Object value, Nullable`1 precedence) in /agent/_work/1/s/src/Uno.UI/UI/Xaml/DependencyObjectExtensions.cs:line 318
>    at Uno.UI.DataBinding.BindingPropertyHelper.<>c__DisplayClass45_9.<InternalGetValueSetter>b__13(Object instance, Object value) in /agent/_work/1/s/src/Uno.UI/DataBinding/BindingPropertyHelper.cs:line 1011
>    at Microsoft.UI.Xaml.Data.BindingExpression.SetTargetValue(Object value) in /agent/_work/1/s/src/Uno.UI/DataBinding/BindingExpression.cs:line 455
>    at Microsoft.UI.Xaml.Data.BindingExpression.SetTargetValueSafe(Object v, Boolean useTargetNullValue) in /agent/_work/1/s/src/Uno.UI/DataBinding/BindingExpression.cs:line 673

**Comment by kazo0** [comment]
Ah probably because of https://github.com/unoplatform/Uno.Themes/pull/1369, the Chip style in Toolkit is still using this that was just removed from Themes

Odd that it causes a blank page
