### ISSUE TITLE
`CalendarView` issue when shown for the second time

### ISSUE THREAD

**Issue by FrozDark** [unoplatform/uno#16123]
### Current behavior

When the calendar is shown the second time it gets bugged with no interaction possible

Tested on Skia.WPF and Android have the same issue

![qtagsag](https://github.com/unoplatform/uno/assets/6670150/0af08103-789b-4afe-87b2-4af3658973ff)

### Expected behavior

No bug

### How to reproduce it (as minimally and precisely as possible)

[CalendarViewIssue.zip](https://github.com/unoplatform/uno/files/14865678/CalendarViewIssue.zip)

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Tested on 5.2.0-dev.484 and 5.3.0-dev.12

### Affected platforms

Android, iOS, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Linux Framebuffer)

**Comment by Youssef1313** [comment]
It's crashing during measure:

```
      System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
         at System.Collections.Generic.List`1.get_Item(Int32 index)
         at Microsoft.UI.Xaml.Controls.Primitives.CalendarPanel.ContainersCache.GetOrCreate(Int32 index) in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/CalendarView/Primitives/CalendarPanel.ModernCollectionBasePanel.cs:line 252
         at Microsoft.UI.Xaml.Controls.Primitives.CalendarPanel.base_MeasureOverride(Size availableSize) in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/CalendarView/Primitives/CalendarPanel.ModernCollectionBasePanel.cs:line 590
```

**Comment by FrozDark** [comment]
> NOTE: There is this piece of code:
> 
> ```cs
> #if HAS_UNO
>         static readonly Dictionary<Type, WeakReference<ContentDialog>> DialogInstances = new();
>         public static T GetDialog<T>(XamlRoot xamlRoot) where T : ContentDialog
>         {
>             T dialog;
>             if (!DialogInstances.TryGetValue(typeof(T), out var dialogRef))
>             {
>                 dialog = (T)Activator.CreateInstance(typeof(T), true);
> 
>                 DialogInstances[typeof(T)] = new(dialog);
>             }
>             else if (!dialogRef.TryGetTarget(out var target))
>             {
>                 dialog = (T)Activator.CreateInstance(typeof(T), true);
>                 dialogRef.SetTarget(dialog);
>             }
>             else
>             {
>                 dialog = (T)target;
>             }
> 
>             dialog.XamlRoot = xamlRoot;
> 
>             return dialog;
>         }
> #else
>         public static T GetDialog<T>(XamlRoot xamlRoot) where T : ContentDialog
>         {
>             var dialog = (T)Activator.CreateInstance(typeof(T), true);
>             dialog.XamlRoot = xamlRoot;
> 
>             return dialog;
>         }
> #endif
> ```
> 
> Using the "else" path in Uno makes it not crash. Investigating further as using the HAS_UNO path in WinUI doesn't crash in WinUI.

As a workaround

It's been expected to have a new instance of the dialog to be working correctly as it will always show the control for the first time it's initialized

**Comment by Youssef1313** [comment]
The main root cause is that MaxDate changes between the two shows of the CalendarView. This is breaking the ContainersCache (it doesn't get cleared properly). Working

**Comment by MartinZikmund** [comment]
This should be fixed now

**Comment by Youssef1313** [comment]
@MartinZikmund Issue was fixed but was kept open to track the skipped test (#16194)
