### ISSUE TITLE
Error on everything but windows - System.MissingMethodException: Method not found: void Microsoft.UI.Xaml.Controls.Grid.SetColumn(Microsoft.UI.Xaml.UIElement,int)

### ISSUE THREAD

**Issue by cconner100** [unoplatform/uno#16184]
### Current behavior

I have a fairly basic xaml file, it works fine on winui3 but when i try it in Maccatalyst, iOS or android i get the following error

`Microsoft.UI.Xaml.UIElement: Error: Failed to raise 'PointerReleasedEvent': System.InvalidOperationException: Failed to load ZiiDMSPhoneApp.PartsSearch: System.MissingMethodException: Method not found: void Microsoft.UI.Xaml.Controls.Grid.SetColumn(Microsoft.UI.Xaml.UIElement,int)
   at Uno.UI.Helpers.Xaml.ApplyExtensions.GenericApply[ZtLabel,PartsSearch,NameScope](ZtLabel instance, PartsSearch arg1, NameScope arg2, Action`3 apply)
   at ZiiDMSPhoneApp.PartsSearch.InitializeComponent() in /Users/curtisconner/ZiiDMSV2/Client/Mobile/ZiiDMSPhoneApp/ZiiDMSPhoneApp/Uno.UI.SourceGenerators/Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator/PartsSearch_3cb178e422e1aa7286746267d426acc3.cs:line 77
   at ZiiDMSPhoneApp.PartsSearch..ctor() in /Users/curtisconner/ZiiDMSV2/Client/Mobile/ZiiDMSPhoneApp/ZiiDMSPhoneApp/Views/Parts/PartsSearch.xaml.cs:line 12
   at ZiiDMSPhoneApp.Mobile.MetadataBuilder_722.CreateInstance() in /Users/curtisconner/ZiiDMSV2/Client/Mobile/ZiiDMSPhoneApp/ZiiDMSPhoneApp.Mobile/Uno.UI.SourceGenerators/Uno.UI.SourceGenerators.BindableTypeProviders.BindableTypeProvidersSourceGenerator/BindableMetadata.g.cs:line 29382
   at Microsoft.UI.Xaml.Controls.Frame.CreatePageInstance(Type sourcePageType)
   at Microsoft.UI.Xaml.PagePool.DequeuePage(Type pageType)
   at Microsoft.UI.Xaml.Controls.Frame.CreatePageInstanceCached(Type sourcePageType)
   at Microsoft.UI.Xaml.Controls.Frame.EnsurePageInitialized(PageStackEntry entry)
   at Microsoft.UI.Xaml.Controls.Frame.InnerNavigate(PageStackEntry entry, NavigationMode mode)
   at ZiiDMSPhoneApp.App.OnNavigationFailed(Object sender, NavigationFailedEventArgs e) in /Users/curtisconner/ZiiDMSV2/Client/Mobile/ZiiDMSPhoneApp/ZiiDMSPhoneApp/App.cs:line 258
   at Microsoft.UI.Xaml.Controls.Frame.InnerNavigate(PageStackEntry entry, NavigationMode mode)
   at Microsoft.UI.Xaml.Controls.Frame.Navigate(Type sourcePageType, Object parameter, NavigationTransitionInfo infoOverride)
   at Microsoft.UI.Xaml.Controls.Frame.Navigate(Type sourcePageType)
   at ZiiDMSPhoneApp.MainMenuViewModel.NavigateToPage(Type page) in /Users/curtisconner/ZiiDMSV2/Client/Mobile/ZiiDMSPhoneApp/ZiiDMSPhoneApp/MainMenuViewModel.cs:line 59
   at ZiiDMSPhoneApp.MainMenuViewModel.Parts() in /Users/curtisconner/ZiiDMSV2/Client/Mobile/ZiiDMSPhoneApp/ZiiDMSPhoneApp/MainMenuViewModel.cs:line 29
   at CommunityToolkit.Mvvm.Input.RelayCommand.Execute(Object parameter)
   at Microsoft.UI.Xaml.Controls.Primitives.ButtonBase.ExecuteCommand()
   at Microsoft.UI.Xaml.Controls.Primitives.ButtonBase.OnClick()
   at Microsoft.UI.Xaml.Controls.Button.OnClick()
   at Microsoft.UI.Xaml.Controls.Primitives.ButtonBase.PerformPointerUpAction()
   at Microsoft.UI.Xaml.Controls.Primitives.ButtonBase.OnPointerReleased(PointerRoutedEventArgs args)
   at Microsoft.UI.Xaml.Controls.Control.<>c.<.cctor>b__366_10(Object sender, PointerRoutedEventArgs args)
   at Microsoft.UI.Xaml.UIElement.InvokeHandler(Object handler, RoutedEventArgs args)
   at Microsoft.UI.Xaml.UIElement.RaiseEvent(RoutedEvent routedEvent, RoutedEventArgs args, BubblingContext ctx)
   at Microsoft.UI.Xaml.UIElement.RaisePointerEvent(RoutedEvent evt, PointerRoutedEventArgs args, BubblingContext ctx)`

the xaml file is simple

`<Page
  xmlns:utu="using:Uno.Toolkit.UI"
  xmlns:muxc="using:Microsoft.UI.Xaml.Controls"
  xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
  xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
  xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
  xmlns:local="using:ZiiDMSPhoneApp"
  xmlns:ztcf="using:ZtClientFramework"
  x:Class="ZiiDMSPhoneApp.PartsSearch"
  mc:Ignorable="d"
  Background="{ThemeResource ApplicationPageBackgroundThemeBrush}"
  xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation">

  <Page.Resources>
    <x:String x:Key="Icon_Arrow_Back">F1 M 16 7 L 3.8299999237060547 7 L 9.420000076293945 1.4099998474121094 L 8 0 L 0 8 L 8 16 L 9.40999984741211 14.59000015258789 L 3.8299999237060547 9 L 16 9 L 16 7 Z</x:String>
  </Page.Resources>

  <StackPanel>

    <utu:NavigationBar HorizontalContentAlignment="Left" Content="Parts Inventory" utu:AutoLayout.CounterAlignment="Stretch">
      <utu:NavigationBar.MainCommand>
        <AppBarButton>
          <AppBarButton.Icon>
            <PathIcon Data="{StaticResource Icon_Arrow_Back}" />
          </AppBarButton.Icon>
        </AppBarButton>
      </utu:NavigationBar.MainCommand>
    </utu:NavigationBar>

    <ztcf:ZtLabel HorizontalAlignment="Center" TextWrapping="Wrap" Text="{x:Bind ViewModel.DealershipName, Mode=OneWay}" utu:AutoLayout.PrimaryAlignment="Stretch"  />
    
    <ztcf:ZtAutoSuggestBox TextChanged="ZtAutoSuggestBox_TextChanged"
                           WaterMark="Enter part no or number"
                           QuerySubmitted="ZtAutoSuggestBox_QuerySubmitted"
                           CornerRadius="12"                           
                           HorizontalAlignment="Stretch"/>
    <Grid>
      <Grid.ColumnDefinitions>
        <ColumnDefinition Width="*"/>
        <ColumnDefinition Width="Auto"/>
      </Grid.ColumnDefinitions>
      <Grid.RowDefinitions>
        <RowDefinition Height="Auto"/>
      </Grid.RowDefinitions>
      <ztcf:ZtLabel Text="{x:Bind ViewModel.ResultCount, Mode=OneWay}" HorizontalAlignment="Left" Grid.Column="0" Grid.Row="0" utu:AutoLayout.CounterAlignment="Stretch" />
      <HyperlinkButton Content="Filters" Grid.Column="1" Grid.Row="0" HorizontalAlignment="Right" Command="{x:Bind ViewModel.FiltersCommand}"/>
    </Grid>

    <utu:Divider utu:AutoLayout.CounterAlignment="Stretch" />
    <ListView ItemsSource="{x:Bind ViewModel.SearchResults}" ItemClick="ListView_ItemClick"  IsItemClickEnabled="True" SelectionMode="Single">
      <ListView.ItemTemplate>
        <DataTemplate x:Name="PartsSearchTemplate" x:DataType="local:SearchResultTemplate">
          <Grid>
            <Grid.ColumnDefinitions>
              <ColumnDefinition Width="Auto"/>
              <ColumnDefinition Width="*"/>
            </Grid.ColumnDefinitions>
            <Grid.RowDefinitions>
              <RowDefinition Height="Auto"/>
              <RowDefinition Height="Auto"/>
              <RowDefinition Height="Auto" />
            </Grid.RowDefinitions>
            <ztcf:ZtLabel Text="{x:Bind PartNo}" Grid.Column="0" Grid.Row="0" TextAlignment="Left" FontSize="10" FontStyle="Normal" utu:AutoLayout.CounterAlignment="Stretch" />
            <ztcf:ZtLabel Text="{x:Bind Vendor}" Grid.Column="1" Grid.Row="0" TextAlignment="Right" FontSize="10" FontStyle="Normal" utu:AutoLayout.CounterAlignment="Stretch" />

            <ztcf:ZtLabel Text="{x:Bind Description}" Grid.Column="0" Grid.Row="1" TextAlignment="Left" FontSize="14" FontStyle="Italic" utu:AutoLayout.CounterAlignment="Stretch" />
            <ztcf:ZtLabel Text="{x:Bind QtyAvailable}" Grid.Column="1" Grid.Row="1" TextAlignment="Right" FontSize="14" FontStyle="Italic" utu:AutoLayout.CounterAlignment="Stretch" />

            <ztcf:ZtLabel Text="{x:Bind Location}" Grid.Column="0" Grid.Row="2" TextAlignment="Left" FontSize="10" FontStyle="Normal" utu:AutoLayout.CounterAlignment="Stretch" />
            <ztcf:ZtLabel Text="{x:Bind Price}" Grid.Column="1" Grid.Row="2" TextAlignment="Right" FontSize="10" FontStyle="Normal" utu:AutoLayout.CounterAlignment="Stretch" />
          </Grid>
        </DataTemplate>
      </ListView.ItemTemplate>
    </ListView>
  </StackPanel>
</Page>
`

Is there anything obvious i am doing wrong?

### Expected behavior

Should work the same on other platforms as it does on windows Winui3

### Works on UWP/WinUI

Yes

**Comment by Youssef1313** [comment]
Thanks for the report @cconner100 

Can you attach the project as a zip file? Thank you!

**Comment by jeromelaban** [comment]
Also, in general, this means that there's an Uno 4.x reference somewhere.
