### ISSUE TITLE
ListView Drag and Drop Items - Error when CompleteReordering

### ISSUE THREAD

**Issue by rafael-rosa-knowcode** [unoplatform/uno#16799]
### Current behavior

When we created some ListView using some list of Records.
And tryed to Reorder the Items on the ListView we are getting some errors

```
fail: Microsoft.UI.Xaml.UIElement[0]
      Failed to raise 'DropEvent': System.NullReferenceException: Object reference not set to an instance of an object.
         at Microsoft.UI.Xaml.Controls.VirtualizingPanelLayout.RecycleLine(Line line, Boolean clearContainer) in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.managed.cs:line 558
         at Microsoft.UI.Xaml.Controls.VirtualizingPanelLayout.ClearLines(Boolean clearContainer) in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.managed.cs:line 835
         at Microsoft.UI.Xaml.Controls.VirtualizingPanelLayout.Refresh() in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.managed.cs:line 818
         at Microsoft.UI.Xaml.Controls.VirtualizingPanelLayout.CompleteReorderingItem(FrameworkElement element, Object item) in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.managed.cs:line 1158
         at Microsoft.UI.Xaml.Controls.ListViewBase.CompleteReordering(FrameworkElement draggedContainer, Object draggedItem) in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.DragDrop.cs:line 392
         at Microsoft.UI.Xaml.Controls.ListViewBase.OnReorderCompleted(Object sender, DragEventArgs dragEventArgs) in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.DragDrop.cs:line 261
         at Microsoft.UI.Xaml.UIElement.InvokeHandler(Object handler, RoutedEventArgs args) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.RoutedEvents.cs:line 982
         at Microsoft.UI.Xaml.UIElement.InvokeHandlers(IList`1 handlers, RoutedEventArgs args, Boolean& isHandled) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.RoutedEvents.cs:line 933
         at Microsoft.UI.Xaml.UIElement.RaiseEvent(RoutedEvent routedEvent, RoutedEventArgs args, BubblingContext ctx) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.RoutedEvents.cs:line 688
         at Microsoft.UI.Xaml.UIElement.RaiseOnParent(RoutedEvent routedEvent, RoutedEventArgs args, UIElement parent, BubblingContext ctx) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.RoutedEvents.cs:line 757
         at Microsoft.UI.Xaml.UIElement.RaiseEvent(RoutedEvent routedEvent, RoutedEventArgs args, BubblingContext ctx) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.RoutedEvents.cs:line 688
         at Microsoft.UI.Xaml.UIElement.RaiseOnParent(RoutedEvent routedEvent, RoutedEventArgs args, UIElement parent, BubblingContext ctx) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.RoutedEvents.cs:line 757
         at Microsoft.UI.Xaml.UIElement.RaiseEvent(RoutedEvent routedEvent, RoutedEventArgs args, BubblingContext ctx) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.RoutedEvents.cs:line 688
         at Microsoft.UI.Xaml.UIElement.RaiseOnParent(RoutedEvent routedEvent, RoutedEventArgs args, UIElement parent, BubblingContext ctx) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.RoutedEvents.cs:line 757
         at Microsoft.UI.Xaml.UIElement.RaiseEvent(RoutedEvent routedEvent, RoutedEventArgs args, BubblingContext ctx) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.RoutedEvents.cs:line 688
         at Microsoft.UI.Xaml.UIElement.RaiseOnParent(RoutedEvent routedEvent, RoutedEventArgs args, UIElement parent, BubblingContext ctx) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.RoutedEvents.cs:line 757
         at Microsoft.UI.Xaml.UIElement.RaiseEvent(RoutedEvent routedEvent, RoutedEventArgs args, BubblingContext ctx) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.RoutedEvents.cs:line 688
         at Microsoft.UI.Xaml.UIElement.RaiseOnParent(RoutedEvent routedEvent, RoutedEventArgs args, UIElement parent, BubblingContext ctx) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.RoutedEvents.cs:line 757
         at Microsoft.UI.Xaml.UIElement.RaiseEvent(RoutedEvent routedEvent, RoutedEventArgs args, BubblingContext ctx) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.RoutedEvents.cs:line 688
         at Microsoft.UI.Xaml.UIElement.SafeRaiseEvent(RoutedEvent routedEvent, RoutedEventArgs args, BubblingContext ctx) in /__w/1/s/src/Uno.UI/UI/Xaml/UIElement.RoutedEvents.cs:line 580
```

Or in Debug.

![image](https://github.com/unoplatform/uno/assets/116665025/3a6b26dd-c6c3-4f21-b580-6d02ad051e4b)

Works fine on WinAppSDK but not on Desktop platform.

When Start.

![image](https://github.com/unoplatform/uno/assets/116665025/a13e3c43-d26c-4488-b125-00442bceb700)

When Drag.

![image](https://github.com/unoplatform/uno/assets/116665025/30c2130c-f4d2-4a5f-9810-83cfea843353)

When Drop
![image](https://github.com/unoplatform/uno/assets/116665025/eb0d6143-6663-4f22-85b6-00e2108f247a)

### Expected behavior

The expectation is that the list is reordered correctly.
We need to use the event that observes the order of the elements in the list.

### How to reproduce it (as minimally and precisely as possible)

There is a project with the scenario in which the error happens.

[UnoAppListViewDrag.zip](https://github.com/unoplatform/uno/files/15380761/UnoAppListViewDrag.zip)

Using UnoApp.
Creating a ListView on the Main page.
Including a list that has record as one of its attributes.

### Works on UWP/WinUI

Yes

### NuGet package version(s)

  <PropertyGroup>
    <UnoExtensionsVersion>4.2.0-dev.77</UnoExtensionsVersion>
    <UnoToolkitVersion>6.1.0-dev.24</UnoToolkitVersion>
    <UnoThemesVersion>5.1.0-dev.26</UnoThemesVersion>
    <UnoCSharpMarkupVersion>5.3.0-dev.70</UnoCSharpMarkupVersion>
  </PropertyGroup>

### IDE

Visual Studio 2022

### IDE version

Microsoft Visual Studio Community 2022 (2) (64-bit) - Current Version 17.9.0

**Comment by nickrandolph** [comment]
@jeromelaban @MartinZikmund is this something that the team is going to get a chance to look at?

**Comment by MartinZikmund** [comment]
@nickrandolph Depends on the urgency, how crucial is it currently?

**Comment by nickrandolph** [comment]
@MartinZikmund it's blocking the ability to reorder items in one of the editors we have, so pretty important as we don't have an acceptable workaround.

**Comment by jeromelaban** [comment]
https://github.com/unoplatform/uno/pull/16980 will fix this.
