### ISSUE TITLE
Binding - Error when Set Blank Value for double  in Binding

### ISSUE THREAD

**Issue by rafael-rosa-knowcode** [unoplatform/uno#16798]
### Current behavior

Error when setting a blank value in a double field, using a list from a Record that has a Field with type "double?".

```
fail: Uno.UI.DataBinding.BindingPath+BindingItem[0]
      Failed to set the source value for [Min]
      System.FormatException: The input string '' was not in a correct format.
         at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
         at System.String.System.IConvertible.ToDouble(IFormatProvider provider)
         at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
         at Uno.UI.DataBinding.BindingPropertyHelper.ConvertPrimitiveToPrimitive(Type type, Object value) in /__w/1/s/src/Uno.UI/DataBinding/BindingPropertyHelper.cs:line 1294
         at Uno.UI.DataBinding.BindingPropertyHelper.Convert(Type propertyType, Object value) in /__w/1/s/src/Uno.UI/DataBinding/BindingPropertyHelper.cs:line 1385
         at Uno.UI.DataBinding.BindingPropertyHelper.Convert(Func`1 propertyType, Object value) in /__w/1/s/src/Uno.UI/DataBinding/BindingPropertyHelper.cs:line 1355
         at Uno.UI.DataBinding.BindingPropertyHelper.<>c__DisplayClass45_12.<InternalGetValueSetter>b__24(Object instance, Object value) in /__w/1/s/src/Uno.UI/DataBinding/BindingPropertyHelper.cs:line 1057
         at Uno.UI.DataBinding.BindingPath.BindingItem.SetSourceValue(ValueSetterHandler setter, Object value) in /__w/1/s/src/Uno.UI/DataBinding/BindingPath.BindingItem.cs:line 278 

```

When using the type double the value can be set as NaN. But with double**?** we get the error.

Tracked to [BindingPropertyHelper.cs](https://github.com/unoplatform/uno/blob/38d8cf5b00033ac28b327664ab10a983606c7e21/src/Uno.UI/DataBinding/BindingPropertyHelper.cs#L1286)

### Expected behavior

I understand that the expected result would be the NaN value, for the "double?" type also.

### How to reproduce it (as minimally and precisely as possible)

Create a new UnoApp.
Create an ItemsControl that list a record with some double and double? value.
Update the ItemsControl to change the value when Mode=TwoWay, UpdateSourceTrigger=PropertyChanged.

There is a project to reproduce the case attached about this issue.

![image](https://github.com/unoplatform/uno/assets/116665025/6e12cd1b-76bb-4e33-b86c-d89749ce186c)

[UnoAppBindingRecord.zip](https://github.com/unoplatform/uno/files/15380829/UnoAppBindingRecord.zip)

### Workaround

None. (or change the double? for double).

### Works on UWP/WinUI

None

### Environment

Other

### NuGet package version(s)

  <PropertyGroup>
    <UnoExtensionsVersion>4.2.0-dev.77</UnoExtensionsVersion>
    <UnoToolkitVersion>6.1.0-dev.24</UnoToolkitVersion>
    <UnoThemesVersion>5.1.0-dev.26</UnoThemesVersion>
    <UnoCSharpMarkupVersion>5.3.0-dev.70</UnoCSharpMarkupVersion>
  </PropertyGroup>

    <PackageVersion Include="Uno.Microsoft.Xaml.Behaviors.WinUI.Managed" Version="2.4.2" />

### IDE

Visual Studio 2022

### IDE version

Microsoft Visual Studio Community 2022 (2) (64-bit) - Current Version 17.9.0

**Comment by Youssef1313** [comment]
@rafael-rosa-knowcode Can you update the repro to start off from latest blank template, and include both WinAppSDK and Skia?

**Comment by rafael-rosa-knowcode** [comment]
Repro.

Create new Blank Project.

add on Directory.Packages.props
```xaml
  <ItemGroup>
    <PackageVersion Include="CommunityToolkit.WinUI.Behaviors" Version="8.1.240606-rc" />
    <PackageVersion Include="Uno.Microsoft.Xaml.Behaviors.Interactivity.WinUI" Version="2.4.2" />
    <PackageVersion Include="Uno.Microsoft.Xaml.Behaviors.WinUI.Managed" Version="2.4.2" />
  </ItemGroup>
```  
  
add on the CSProj
```xaml
  <PropertyGroup>
    <UnoFeatures>
      Toolkit;
      Mvvm;
    </UnoFeatures>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.WinUI.Behaviors" />
    <PackageReference Include="Uno.Microsoft.Xaml.Behaviors.Interactivity.WinUI" />
    <PackageReference Include="Uno.Microsoft.Xaml.Behaviors.WinUI.Managed" />
  </ItemGroup>
 
```
From this file [UnoApp179.zip](https://github.com/user-attachments/files/16415767/UnoApp179.zip)

Copy the EditableList.cs, ListDefinition.cs and MainViewModel.cs files and add to the project, adjust the namespace.

on the MainPage.xaml.cs add the DataContext = new MainViewModel();

on the MainPage.xaml add 

```xaml
 <Grid>
   <Grid.RowDefinitions>
     <RowDefinition Height="Auto" />
     <RowDefinition />
   </Grid.RowDefinitions>

   <StackPanel Grid.Row="1"
         HorizontalAlignment="Center"
         VerticalAlignment="Center"
         Spacing="16">

     <ScrollViewer MaxHeight="400"
		  HorizontalScrollBarVisibility="Disabled"
		  HorizontalScrollMode="Disabled"
		  VerticalScrollBarVisibility="Auto"
		  Grid.Row="1">
       <ItemsControl ItemsSource="{Binding ItemsSource, Mode=TwoWay}"
			   AllowDrop="True"
			   CanDrag="True" >
         <!--Drop="ItemsList_Drop"-->
         <ItemsControl.ItemTemplate>
           <DataTemplate>
             <Grid ColumnDefinitions="44,*,66"
				  Margin="5"
				  AllowDrop="True"
				  CanDrag="True"
				  ColumnSpacing="10">
               <Grid ColumnDefinitions="*,*,*,*"
					  Grid.Column="1"
					  ColumnSpacing="10">
                 <TextBox Grid.Column="0"
						 x:Name="TextBoxMin"
						 HorizontalAlignment="Stretch"
						 Text="{Binding Min, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}">
                   <i:Interaction.Behaviors>
                     <core:EventTriggerBehavior EventName="LostFocus">
                       <core:InvokeCommandAction Command="{Binding ElementName=EditorRoot, Path=DataContext.LostFocusItemsSourceValidateDoubleCommand}"
													  CommandParameter="{Binding ElementName=TextBoxMin}" />
                     </core:EventTriggerBehavior>
                   </i:Interaction.Behaviors>
                 </TextBox>
                 <TextBox Grid.Column="1"
						 x:Name="TextBoxMeasureValue"
						 Text="{Binding MeasureValue, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"
						 HorizontalAlignment="Stretch">
                   <i:Interaction.Behaviors>
                     <core:EventTriggerBehavior EventName="LostFocus">
                       <core:InvokeCommandAction Command="{Binding ElementName=EditorRoot, Path=DataContext.LostFocusItemsSourceValidateMeasureValueCommand}"
													  CommandParameter="{Binding ElementName=TextBoxMeasureValue}" />
                     </core:EventTriggerBehavior>
                   </i:Interaction.Behaviors>
                 </TextBox>
                 <ComboBox Grid.Column="2"
						  ItemsSource="{Binding DataContext.GridUnitTypes, ElementName=EditorRoot}"
						  SelectedItem="{Binding GridUnitType, Mode=TwoWay}"
						  HorizontalAlignment="Stretch" />
                 <TextBox Grid.Column="3"
						 x:Name="TextBoxMax"
						 Text="{Binding Max, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"
						 HorizontalAlignment="Stretch">
                   <i:Interaction.Behaviors>
                     <core:EventTriggerBehavior EventName="LostFocus">
                       <core:InvokeCommandAction Command="{Binding ElementName=EditorRoot, Path=DataContext.LostFocusItemsSourceValidateDoubleCommand}"
													  CommandParameter="{Binding ElementName=TextBoxMax}" />
                     </core:EventTriggerBehavior>
                   </i:Interaction.Behaviors>
                 </TextBox>

               </Grid>
             </Grid>
           </DataTemplate>
         </ItemsControl.ItemTemplate>
       </ItemsControl>
     </ScrollViewer>
   </StackPanel>
 </Grid>


```

run the project.

Select the first item and change to some number [eg 0] and clear the textBox.

![image](https://github.com/user-attachments/assets/aa649042-109c-4713-bf19-a8d9e12dead2)


```
     System.FormatException: The input string '' was not in a correct format.
         at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
         at System.String.System.IConvertible.ToDouble(IFormatProvider provider)
         at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
         at Uno.UI.DataBinding.BindingPropertyHelper.ConvertPrimitiveToPrimitive(Type type, Object value) in /__w/1/s/src/Uno.UI/DataBinding/BindingPropertyHelper.cs:line 1294
         at Uno.UI.DataBinding.BindingPropertyHelper.Convert(Type propertyType, Object value) in /__w/1/s/src/Uno.UI/DataBinding/BindingPropertyHelper.cs:line 1385
         at Uno.UI.DataBinding.BindingPropertyHelper.Convert(Func`1 propertyType, Object value) in /__w/1/s/src/Uno.UI/DataBinding/BindingPropertyHelper.cs:line 1355
         at Uno.UI.DataBinding.BindingPropertyHelper.<>c__DisplayClass45_12.<InternalGetValueSetter>b__24(Object instance, Object value) in /__w/1/s/src/Uno.UI/DataBinding/BindingPropertyHelper.cs:line 1057
         at Uno.UI.DataBinding.BindingPath.BindingItem.SetSourceValue(ValueSetterHandler setter, Object value) in /__w/1/s/src/Uno.UI/DataBinding/BindingPath.BindingItem.cs:line 278

```


or just download the file [UnoApp179.zip](https://github.com/user-attachments/files/16415767/UnoApp179.zip) and run the project from it.

**Comment by nickrandolph** [comment]
cc @Youssef1313 is this what you need?

**Comment by Youssef1313** [comment]
I'll re-take a look

**Comment by Youssef1313** [comment]
@rafael-rosa-knowcode The bindings should use a converter.

Minimal repro:

```xaml
<Page x:Class="UnoApp179.MainPage"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:local="using:UnoApp179"
      xmlns:core="using:Microsoft.Xaml.Interactions.Core"
      xmlns:i="using:Microsoft.Xaml.Interactivity"
      Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

  <StackPanel>
    <TextBox x:Name="myTb" Text="{Binding P, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" />
  </StackPanel>
  
</Page>

```

```csharp
using System.ComponentModel;

namespace UnoApp179;

public sealed partial class MainPage : Page
{
    public MainPage()
    {
        this.InitializeComponent();
        myTb.DataContext = new MyDC();
    }

    private partial class MyDC : INotifyPropertyChanged
    {
        private double? _p;

        public double? P
        {
            get => _p;
            set
            {
                if (_p != value)
                {
                    _p = value;
                    PropertyChanged?.Invoke(this, new(nameof(P)));
                }
            }
        }

        public event PropertyChangedEventHandler? PropertyChanged;
    }
}

```

To give an idea on WinAppSDK behavior:

The binding is set through [CustomManagedProperty](https://github.com/microsoft/CsWinRT/blob/9cf98477de24a7eab7e6a5412cbe5a51e5afe79e/src/WinRT.Runtime/Projections/ICustomPropertyProvider.net5.cs#L238) which is basically just uses reflection. The conversion is then handled by whatever logic reflection uses to convert the given argument from its type to the parameter type.

In this specific case, reflection can't convert from string to `double?` even when the value is valid. So, the binding completely doesn't work on WinAppSDK.

In the case of Uno, the binding partially works, which is actually an even better behavior than WinAppSDK.

NOTE: For the case of `double` instead of `double?`, WinUI is able to convert it when it's a numerical non-empty value (it's somehow able to convert string to double on the native C++ side first, then reflection is passed double right away).
In case of Uno and `double`, we handle all cases, and produce `NaN` for empty.

**Comment by rafael-rosa-knowcode** [comment]
Thank you @Youssef1313 , we can Close this issue.

Because we followed your suggestion and the converter was implemented successfully.

Thank you very much.
