### ISSUE TITLE
Binding in Style Doesn't Compile

### ISSUE THREAD

**Issue by alove-kahua** [unoplatform/uno#17040]
### Current behavior

Style with a Binding fails to compile.

Build log shows this error:
```
CSC error UXAML0001: The property Microsoft.UI.Xaml.Data.Binding.Value is unknown. Line number: 28, Line position: 10, Caller: BuildBindingOption

at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GetPropertyTypeByOwnerSymbol(INamedTypeSymbol ownerType, String propertyName, Int32 lineNumber, Int32 linePosition, String caller)
at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildBindingOption(XamlMemberDefinition m, INamedTypeSymbol propertyType, Boolean isTemplateBindingAttachedProperty)
at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildPropertySetter(IIndentedStringBuilder writer, String fullTargetType, String lineEnding, String property, XamlMemberDefinition valueNode, String targetInstance)
```
### Expected behavior

Code compiles and runs.

### How to reproduce it (as minimally and precisely as possible)

[UnoStyleBinding.zip](https://github.com/user-attachments/files/15741839/UnoStyleBinding.zip)

The example style in the project is the one below:
```
<Style x:Key="ButtonStyle" TargetType="Button">
    <Setter Property="ToolTipService.ToolTip" Value="{Binding Label}" />
</Style>
```

### Works on UWP/WinUI

Yes

### Affected platforms

Build tasks

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
Thanks for the report. This likely was fixed in 5.3-dev builds with https://github.com/unoplatform/uno/issues/4826. It's generally best to try out previews, just in case it was fixed :) Can you let us know if this is the case for you?
