### ISSUE TITLE
ListView tests on iOS crash on 17.0+ simulators

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#17101]
Frequent crashes with the following stacks:

```
2024-06-12 08:03:59.029761+0000  localhost apsd[7262]: Looking up connection on peer: e4206d40   found <APSConnectionServer: 0x7f81e4207150; development/com.apple.aps.amsengagementd/amsengagementd 0>
2024-06-12 08:03:59.030122+0000  localhost SamplesApp[12759]: (libSystem.Native.dylib) ListViewBaseInternalContainer set failed: System.NullReferenceException: Object reference not set to an instance of an object
   at Uno.UI.Controls.BindableUIView.OnTemplatedParentChanged(DependencyPropertyChangedEventArgs e)
2024-06-12 08:03:59.030153+0000  localhost apsd[7262]: Looking up connection on peer: e4105a70   found <APSConnectionServer: 0x7f81e41077f0; development/com.apple.aps.photos.cloud.datarepair/cloudphotod 0>
2024-06-12 08:03:59.030341+0000  localhost SamplesApp[12759]: (libSystem.Native.dylib)    at Microsoft.UI.Xaml.Controls.ListViewBaseInternalContainer.UpdateContentViewFrame()
   at Microsoft.UI.Xaml.Controls.ListViewBaseInternalContainer.set_Frame(CGRect value)
2024-06-12 08:03:59.030509+0000  localhost cloudphotod[7281]: (ApplePushService) [com.apple.apsd:connection] <APSConnection: 0x600002110000> Delivering connectionStatusChange from apsd: NO
2024-06-12 08:03:59.030685+0000  localhost SamplesApp[12759]: (libxamarin-dotnet.dylib) error: Why are we accessing an entry that is not allocated
```

Related crash info:

[SamplesApp-2024-06-12-080431.json](https://github.com/user-attachments/files/15803947/SamplesApp-2024-06-12-080431.json)

**Comment by MartinZikmund** [comment]
Specific to native iOS, does not apply to Skia iOS
