### ISSUE TITLE
Wasm Release can't run

### ISSUE THREAD

**Issue by lld1995** [unoplatform/uno#17269]
### Current behavior

Wasm Release can't run,but debug is ok

Unhandled Exception:
Newtonsoft.Json.JsonSerializationException: Unable to find a constructor to use for type Model.StgRecord. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path '[0].Id'.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[List`1]()
   at UnoApp2.Pages.StgManagePage.LoadData(Boolean needClear)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.ThreadPool.BackgroundJobHandler()
Aborted(native code called abort())
Uncaught RuntimeError RuntimeError: unreachable
    at $__trap (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:2360306)
    at ___trap (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.js:8:194817)
    at abort (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.js:8:20579)
    at _abort (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.js:8:98449)
    at $func11147 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5495770)
    at $func10056 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5127167)
    at $func9953 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5110682)
    at $func9946 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5057258)
    at $func10013 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5122116)
    at $func10034 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5124188)
    at $func470 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:100953)
    at $mono_background_exec (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5283266)
    at mono_background_exec_until_done (d:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\mono\wasm\runtime\scheduling.ts:47:16)
    at callUserCallback (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.js:8:156452)
    at <anonymous> (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.js:8:156567)
    --- setTimeout ---
    at safeSetTimeout (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.js:8:156545)
    at schedule_background_exec (d:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\mono\wasm\runtime\scheduling.ts:53:12)
    at $func10452 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5283157)
    at $func10521 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5298529)
    at $func10519 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5296041)
    at $func10517 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5295636)
    at $func10516 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5295540)
    at $func10504 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5292652)
    at $func12312 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5805977)
    at $func9946 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5079330)
    at $func9980 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5116167)
    at $func12473 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5857865)
    at $func11792 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5679193)
    at $func11798 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5681314)
    at $func11822 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5691539)
    at $mono_wasm_invoke_method_bound (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:82156)
    at <anonymous> (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.js:8:21193)
    at ccall (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.js:8:152727)
    at <anonymous> (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.js:8:152929)
    at invoke_method_and_handle_exception (d:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\mono\wasm\runtime\invoke-cs.ts:273:29)
    at runtimeHelpers.javaScriptExports.complete_task (d:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\mono\wasm\runtime\managed-exports.ts:142:13)
    at <anonymous> (d:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\mono\wasm\runtime\marshal-to-cs.ts:335:46)
    --- Promise.then ---
    at _marshal_task_to_cs (d:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\mono\wasm\runtime\marshal-to-cs.ts:329:11)
    at <anonymous> (d:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\mono\wasm\runtime\marshal-to-cs.ts:83:9)
    at <anonymous> (d:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\mono\wasm\runtime\invoke-js.ts:177:13)
    at mono_wasm_invoke_import (d:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\mono\wasm\runtime\invoke-js.ts:276:5)
    at $func10056 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5127121)
    at $func9953 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5110682)
    at $func9946 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5057258)
    at $func9980 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5116167)
    at $func12473 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5857865)
    at $func11792 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5679193)
    at $func11798 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5681314)
    at $func11822 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5691539)
    at $mono_wasm_invoke_method_bound (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:82156)
    at <anonymous> (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.js:8:21193)
    at ccall (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.js:8:152727)
    at <anonymous> (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.js:8:152929)
    at invoke_method_and_handle_exception (d:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\mono\wasm\runtime\invoke-cs.ts:273:29)
    at runtimeHelpers.javaScriptExports.complete_task (d:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\mono\wasm\runtime\managed-exports.ts:142:13)
    at <anonymous> (d:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\mono\wasm\runtime\marshal-to-cs.ts:335:46)
    --- Promise.then ---
    at _marshal_task_to_cs (d:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\mono\wasm\runtime\marshal-to-cs.ts:329:11)
    at <anonymous> (d:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\mono\wasm\runtime\marshal-to-cs.ts:83:9)
    at <anonymous> (d:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\mono\wasm\runtime\invoke-js.ts:236:17)
    at mono_wasm_invoke_import (d:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\mono\wasm\runtime\invoke-js.ts:276:5)
    at $func10056 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5127121)
    at $func9953 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5110682)
    at $func9946 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5057258)
    at $func9980 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5116167)
    at $func12473 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5857865)
    at $func11792 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5679193)
    at $func11798 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5681314)
    at $func11822 (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:5691539)
    at $mono_wasm_invoke_method_bound (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.wasm:1:82156)
    at <anonymous> (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.js:8:21193)
    at ccall (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.js:8:152727)
    at <anonymous> (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/dotnet.native.js:8:152929)
    at invoke_method_and_handle_exception (d:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\mono\wasm\runtime\invoke-cs.ts:273:29)
    at <anonymous> (d:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\mono\wasm\runtime\invoke-cs.ts:247:13)
    at dispatchPointerEvent (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/Uno.UI.js:4667:36)
    at onPointerEventReceived (localhost꞉5000/package_b5debb5045ebb3e6507265827b8c27c087eeb5e5/Uno.UI.js:4587:36)

### How to reproduce it (as minimally and precisely as possible)

Use Newtonjson,and build release version

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

**Comment by jojorne** [comment]
> Unable to find a constructor to use for type Model.StgRecord.

Is debugging ignoring the constructor error? Do you have a \#pragma check there?
