### ISSUE TITLE
[Wasm] Livecharts2 can only run at 127.0.0.1

### ISSUE THREAD

**Issue by lld1995** [unoplatform/uno#17276]
### Current behavior

If i visit web by 192.168.0.2 ,livecharts2 can't render and give errors:

Unhandled Exception:
put_char @ dotnet.native.js:8
dotnet.native.js:8  IndexSizeError: Failed to construct 'ImageData': The input data length is not a multiple of (4 * width).
put_char @ dotnet.native.js:8
dotnet.native.js:8  Aborted(native code called abort())
abort @ dotnet.native.js:8
dotnet.native.js:8  Uncaught RuntimeError: unreachable
    at dotnet.native.wasm:0x2403f1
    at ___trap (dotnet.native.js:8:194817)
    at abort (dotnet.native.js:8:20579)
    at _abort (dotnet.native.js:8:98449)
    at dotnet.native.wasm:0x53dbd9
    at dotnet.native.wasm:0x4e3bfe
    at dotnet.native.wasm:0x4dfb99
    at dotnet.native.wasm:0x4d2ae9
    at dotnet.native.wasm:0x4e2843
    at dotnet.native.wasm:0x4e305b

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
Thanks, this is a very curious error, most likely not related to localhost. If you can provide a repro of the issue, it will be further troubleshooting.

**Comment by MateralCMX** [comment]
@jeromelaban 
I'm also encountering this issue. The reproduction demo can be found here:：
https://github.com/MateralCMX/LiveChatsUnoDemo

Where：
[LiveChatsDemo](https://github.com/MateralCMX/LiveChatsUnoDemo/tree/master/LiveChatsDemo)uses SkiaRenderer not exhibit this issue
[LiveChatsDemo2](https://github.com/MateralCMX/LiveChatsUnoDemo/tree/master/LiveChatsDemo2)does not use SkiaRenderer this issue:[IndexSizeError: Failed to construct 'ImageData': The input data length is not a multiple of (4 * width).]

<img width="1455" height="60" alt="Image" src="https://github.com/user-attachments/assets/77cfecc7-c816-4d28-b8e6-7bf72604c65f" />

Specific reproduction steps are demonstrated in the video:
[LiveChatsDemo.mp4](https://github.com/MateralCMX/LiveChatsUnoDemo/blob/master/LiveChatsDemo.mp4)
Due to network restrictions, I was unable to upload the video directly.

However, SkiaRenderer cannot be used due to issue:
#20292

**Comment by jeromelaban** [comment]
Thanks for the update. I'm still not able to reproduce with your samples. This feels like a device or platform specific behavior. Could you place a breakpoint at these locations:

<img width="1508" height="1436" alt="Image" src="https://github.com/user-attachments/assets/17d46d5f-4d94-43cf-b577-36de97a0e69d" />

And tell us what the values of the buffer are? (e.g. width/height/byteLength)

**Comment by MateralCMX** [comment]
Here is my debugging result:
Line 39: Not hit
Line 44: buffer.length->198969088 width->600 height->600
<img width="1700" height="693" alt="Image" src="https://github.com/user-attachments/assets/098175e1-9785-4ccb-98f3-f1aa97128926" />

I found this issue is related to HTTPS, as the error disappeared when I accessed it via HTTPS.
[I hosted the generated program using nginx, configured with both HTTPS (SSL certificate) and HTTP. The issue persists under HTTP but disappears under HTTPS.]

**Comment by jeromelaban** [comment]
I see. This feels like a security issue then. Not running with https is probably triggering some counter measure that generate this error. 

Interestingly, the buffer size is explicitly [the right size](https://github.com/mono/SkiaSharp/blob/080e31cf319624dbccc2103b91aabb54398b93c1/source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.WinUI.Wasm/WasmScripts/SkiaSharp.Views.Uno.Wasm.js#L25) of the error message, so I'm not sure how we can fix this.

**Comment by SongOfYouth** [comment]
@lld1995 Maybe the problem is gone now?
