### ISSUE TITLE
[Skia(macos)] TokenizingTextBox is crashing

### ISSUE THREAD

**Issue by TopperDEL** [unoplatform/uno#17373]
### Current behavior

If I use a TokenizingTextBox from the WindowsCommunityToolki, it crashes on MacOS using the desktop target (skia). It fails with this exception:

`Method not found: 'Void Microsoft.UI.Xaml.UIElement.set_Name(System.String)'.`

And has this StackTrace:

   ```
 at
CommunityToolkit.WinUI.Controls.TokenizingTextBoxRns.__Resources._TokenizingTextBox_b88242d792f78ce55c1b83d238329dca_TokenizingTextBoxRDSC1.Build(Object
__ResourceOwner_1)
    at
CommunityToolkit.WinUI.Controls.TokenizingTextBoxRns.GlobalStaticResources.ResourceDictionarySingleton__TokenizingTextBox_b88242d792f78ce55c1b83d238329dca.<>c.<Get_7>b__11_0(Object
__owner)
    at
Microsoft.UI.Xaml.FrameworkTemplate.Microsoft.UI.Xaml.IFrameworkTemplateInternal.LoadContent()
in /__w/1/s/src/Uno.UI/UI/Xaml/FrameworkTemplate.cs:line 89
    at
Microsoft.UI.Xaml.FrameworkTemplatePool.DequeueTemplate(FrameworkTemplate
template) in /__w/1/s/src/Uno.UI/UI/Xaml/FrameworkTemplatePool.cs:line
265
    at Microsoft.UI.Xaml.Controls.Control.UpdateTemplate() in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/Control/Control.cs:line 581
    at Microsoft.UI.Xaml.Controls.Control.OnLoaded() in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/Control/Control.cs:line 462
    at
Microsoft.UI.Xaml.FrameworkElement.<OnFwEltLoaded>g__InvokeLoadedWithTry|24_1()
in /__w/1/s/src/Uno.UI/UI/Xaml/FrameworkElement.crossruntime.cs:line 95

```

### Expected behavior

The TokenizingTextBox should work with Skia on MacOs, too.

### Workaround

None yet

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

5.2

### Affected platforms

Skia (macOS)

### IDE

Visual Studio Code

### IDE version

latest

**Comment by jeromelaban** [comment]
This particular error means that you're using a dependency that was built using Uno 4.x. You'll need to upgrade to a later version of that package.

**Comment by TopperDEL** [comment]
Hm, I do not find any old reference.

This is my csproj:

```
<Project Sdk="Uno.Sdk">
  <PropertyGroup>
    <TargetFrameworks>
      <!--net8.0-maccatalyst;-->
      net8.0-windows10.0.19041;
      net8.0-desktop;
      <!--net8.0-browserwasm;-->
    </TargetFrameworks>

    <OutputType>Exe</OutputType>
    <UnoSingleProject>true</UnoSingleProject>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>

    <!-- Display name -->
    <ApplicationTitle>MyApp</ApplicationTitle>
    <!-- App Identifier -->
    <ApplicationId>com.myapp</ApplicationId>
    <!-- Versions -->
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>

    <UnoFeatures>
      Material;
      Hosting;
      Toolkit;
      Logging;
      Mvvm;
      ExtensionsCore;
    </UnoFeatures>
  </PropertyGroup>
  <ItemGroup>
    <UnoIcon Include="Assets\Icons\icon.png" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="MonkeyCache.FileStore" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.Primitives" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.TokenizingTextBox" />
  </ItemGroup>
   <ItemGroup Condition="'$(TargetFramework)' == 'net8.0-windows10.0.19041'">
    <PackageReference Include="SkiaSharp.Views.WinUI" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' != 'net8.0-windows10.0.19041'">
    <PackageReference Include="SkiaSharp.Views.Uno.WinUI" />
  </ItemGroup>
  
  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0-windows10.0.19041'">
    <PackageReference Include="uplink.NET.Win" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' != 'net8.0-windows10.0.19041'">
    <PackageReference Include="uplink.NET.Mac" />
  </ItemGroup>
</Project>
```

This is the Directory.Packages.props:

```
<Project ToolsVersion="15.0">
  <!--
    To update the version of Uno, you should instead update the Sdk version in the global.json file.

    See https://aka.platform.uno/using-uno-sdk for more information.
  -->
  <ItemGroup>
    <PackageVersion Include="Bsa.Search.Core" Version="2.1.1" />
    <PackageVersion Include="Flurl" Version="4.0.0" />
    <PackageVersion Include="Flurl.Http" Version="4.0.2" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageVersion Include="SharpHash" Version="1.2.0" />
    <PackageVersion Include="MvvmGen" Version="1.3.0" />
    <PackageVersion Include="MessagePack" Version="2.5.124" />
    <PackageVersion Include="CommunityToolkit.WinUI.Controls.Primitives" Version="8.0.240109" />
    <PackageVersion Include="CommunityToolkit.WinUI.Controls.TokenizingTextBox" Version="8.0.240109" />
    <PackageVersion Include="MonkeyCache.FileStore" Version="2.0.1" />
    <PackageVersion Include="uplink.NET" Version="2.12.3434-pre" />
    <PackageVersion Include="uplink.NET.Win" Version="2.12.3434-pre" />
    <PackageVersion Include="uplink.NET.Linux" Version="2.12.3434-pre" />
    <PackageVersion Include="uplink.NET.Mac" Version="2.12.3434-pre" />
    <PackageVersion Include="Serilog" Version="3.0.1" />
    <PackageVersion Include="Serilog.Sinks.File" Version="5.0.0" />
    <PackageVersion Include="SkiaSharp" Version="2.88.8" />
    <PackageVersion Include="SkiaSharp.Views.WinUI" Version="2.88.8" />
    <PackageVersion Include="SkiaSharp.NativeAssets.Linux" Version="2.88.8" />
    <PackageVersion Include="SkiaSharp.Views.Uno.WinUI" Version="2.88.8" />
    <PackageVersion Include="Effortless.Net.Encryption" Version="4.0.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageVersion Include="Moq" Version="4.20.70" />
    <PackageVersion Include="MSTest.TestAdapter" Version="3.1.1" />
    <PackageVersion Include="MSTest.TestFramework" Version="3.1.1" />
    <PackageVersion Include="MailKit" Version="4.0.0" />
    <PackageVersion Include="ncalc" Version="1.3.8" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="8.0.0" />
    <PackageVersion Include="OfficeIMO.Word" Version="0.15.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="7.0.13" />
    <PackageVersion Include="Microsoft.Playwright" Version="1.38.0" />
    <PackageVersion Include="Microsoft.Playwright.MSTest" Version="1.38.0" />
    <PackageVersion Include="coverlet.collector" Version="3.1.2" />
    <PackageVersion Include="ExceptionAInalyzer" Version="3.0.2" />
    <PackageVersion Include="Htmx" Version="1.7.0" />
    <PackageVersion Include="Htmx.TagHelpers" Version="1.7.0" />
    <PackageVersion Include="NCalcSync" Version="3.12.0" />
    <PackageVersion Include="NLog.Web.AspNetCore" Version="5.3.8" />
    <PackageVersion Include="OpenAI" Version="1.11.0" />
  </ItemGroup>
  <ItemGroup Condition="$(UsingUnoSdk) != 'true'">
    <PackageVersion Include="Uno.Wasm.Bootstrap.Server" Version="8.0.14" />
  </ItemGroup>
</Project>
```

It works on Windows but crashes on MacOS. Which dependency should/could I check?

**Comment by jeromelaban** [comment]
I see, the community toolkit 8.0.x is not compatible with Uno 5+, you need to upgrade to the latest 8.1 prerelease builds which do.

**Comment by TopperDEL** [comment]
Yep, that has been the reason. Thank you! Closing this issue.
