### ISSUE TITLE
Skia rendering issues in Windows 10 and Windows 11

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#17526]
### Discussed in https://github.com/unoplatform/uno/discussions/17411

<div type='discussions-op-text'>

<sup>Originally posted by **lemalcs** July  8, 2024</sup>
Hello, I have a Skia project built with Uno Platform but I'm finding rendering issues when running it on some Windows versions.

When you click outside the dark rectangle, it disappears, but shows up again, when you focus on the text boxes.

The expected behavior is that the **whole window background** is light or dark, depending on the current OS theme.

On Windows 10 x64 Version 1507 (RTM) (OS build 10240)
![image](https://github.com/unoplatform/uno/assets/48371435/2e8ba173-3799-4502-838e-06040c5c0a58)

On Windows 11 Pro (x64) Version 23H2 build 22631.3593:
![image](https://github.com/unoplatform/uno/assets/48371435/a61a0971-56ff-4a76-978c-35d6177e1893)

Interestingly on Windows 7 SP1 x64, it is rendered with any issues:
![image](https://github.com/unoplatform/uno/assets/48371435/d7e8e262-c09d-4083-83d4-21da579ab460)

This is the command I used to publish the project (.NET desktop runtime 8 dependant):

`dotnet publish -f net8.0-desktop -c Release -o ./publish`

## My development environment
- Uno Platform 5.2.56.70
- Visual Studio 2022 (64 bits) Version 17.10.3
- Windows 11 Pro (x64) Version 23H2 build 22631.3737

dotnet --list-sdks:

```
5.0.416 [C:\Program Files\dotnet\sdk]
7.0.120 [C:\Program Files\dotnet\sdk]
8.0.106 [C:\Program Files\dotnet\sdk]
8.0.206 [C:\Program Files\dotnet\sdk]
8.0.300 [C:\Program Files\dotnet\sdk]
8.0.302 [C:\Program Files\dotnet\sdk]
9.0.100-preview.5.24307.3 [C:\Program Files\dotnet\sdk]
```

When I run the same application in my development environment, it renders as expected:

With dark theme
![image](https://github.com/unoplatform/uno/assets/48371435/fb3e93cb-7bdc-422f-87a2-a9d9f021cba2)

With light theme
![image](https://github.com/unoplatform/uno/assets/48371435/2e3802af-5df8-4a56-b421-b8c084e28c23)

Here is the [sample project](https://github.com/lemalcs/UnoAppSkiaDesktop) I used for the tests; it's an almost fresh project I just added two text boxes, two labels, and one button.

Is there any workaround for this problem or something I'm missing around? 

I appreciate any help you can provide. 

Thanks in advance.</div>

**Comment by jeromelaban** [comment]
@MartinZikmund do you know if it still happens? I don't recall seeing this recently.

**Comment by MartinZikmund** [comment]
@lemalcs can you please test against the latest releases of Uno Platform to see if this is still a problem?

**Comment by lemalcs** [comment]
Hi @MartinZikmund , I made these upgrades to the [sample project](https://github.com/lemalcs/UnoAppSkiaDesktop):
- Uno SDK: 5.5.43
- .NET 9.0

I built the project using Visual Studio 2022 Preview 17.13.0.
I published the application with:
```
dotnet publish -f net9.0-desktop -r win-x64 -p:SelfContained=true
```
However, there are still issues in rendering.
- Text boxes change to a black background when focused, 
- Buttons don't have borders.

The same happens with fresh Uno projects.

> I'm using Virtual Machines to test the application.

## On Windows 10 x64 (RTM) (Virtual machine)

![image](https://github.com/user-attachments/assets/17e9c219-654c-41a6-a9d9-d52f1fbc0e7e)

## On Windows 11 x64 (RTM) (Virtual machine)
![image](https://github.com/user-attachments/assets/c26b61c5-06b9-4c59-a1a9-7dbd4fb54e21)


## On Windows 7 x64 (Virtual machine)
The application crashed with this message:

```
Application: UnoAppSkiaDesktop.exe
CoreCLR Version: 9.0.24.52809
.NET Version: 9.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for 'Windows.Globalization.ApplicationLanguages' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'winlangdb.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at Windows.System.UserProfile.GlobalizationPreferences.NativeMethods.EnsureLanguageProfileExists()
   at Windows.System.UserProfile.GlobalizationPreferences.GetWinUserLanguageList() in /__w/1/s/src/Uno.UWP/System/UserProfile/GlobalizationPreferences.cs:line 33
   at Windows.System.UserProfile.GlobalizationPreferences.get_Languages() in /__w/1/s/src/Uno.UWP/System/UserProfile/GlobalizationPreferences.cs:line 26
   at Windows.Globalization.ApplicationLanguages.ApplyLanguages() in /__w/1/s/src/Uno.UWP/Globalization/ApplicationLanguages.cs:line 157
   at Windows.Globalization.ApplicationLanguages..cctor() in /__w/1/s/src/Uno.UWP/Globalization/ApplicationLanguages.cs:line 63
```

## On Development Machine
I used a machine with Windows 11 23H2 to build and test the project. Here, the application renders well.
![image](https://github.com/user-attachments/assets/6ebb8c76-f4c9-430a-a5ed-ebf10b18212b)

Thanks in advance for your help.

**Comment by jeromelaban** [comment]
Thanks for the update. Could you provide the VM software that you are using? This looks like an incorrect OpenGL implementation of some kind.

**Comment by lemalcs** [comment]
> Thanks for the update. Could you provide the VM software that you are using? This looks like an incorrect OpenGL implementation of some kind.

I'm using VMWare Workstation 17 Pro, version 17.0.0 build-20800274.

**Comment by jeromelaban** [comment]
Thanks. It is likely that VMWare contains faulty or outdated graphics drivers that cause this OpenGL issue to happen, we've seen that a while back for virtualbox and other related hypervisors.

Do you know if this happens in Hyper-V ?

**Comment by lemalcs** [comment]
I tested the same application on Windows Sandbox, which comes with Windows 11, and it renders the application correctly:

![image](https://github.com/user-attachments/assets/29020336-023d-4162-a0a3-e30791926085)

Is it a valid test of Hyper-V?

**Comment by lemalcs** [comment]
I applied the software rendering as workaround for the `WpfHost` and it fixes the rendering issue in both virtual machines:

## Windows 11 x64 (Virtual Machine)
![image](https://github.com/user-attachments/assets/9a47f435-2fb7-4817-b8f8-8a95d34e04ed)


## Windows 10 x64 (Virtual Machine)
![image](https://github.com/user-attachments/assets/e21a4d91-a3ae-4d3b-8e8c-38a024cf614b)

I verified that disabling the 3D rendering feature in VMware Workstation also fixes the issue without any code changes to the application.
![image](https://github.com/user-attachments/assets/a40c3e28-ad7e-42eb-9d1d-bbf3c009ada0)

For now, software rendering fixes the rendering issue regarding whether the 3D rendering feature is enabled or not.

Thanks for your help.
