### ISSUE TITLE
[skia] HyperlinkButton does not work on Linux

### ISSUE THREAD

**Issue by ArchieCoder** [unoplatform/uno#17726]
### Current behavior

Clicking on the hyperlink does nothing.

In the debug output:

System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'https://platform.uno/' with working directory '/mnt/d/Projects/UnoAppHyperlink/UnoAppHyperlink/bin/Debug/net8.0-windows10.0.19041'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at Uno.UI.Runtime.Skia.Extensions.System.LinuxLauncherExtension.LaunchUriAsync(Uri uri) in /__w/1/s/src/Uno.UWP/System/LinuxLauncherExtension.skia.cs:line 30
   at Windows.System.Launcher.LaunchUriPlatformAsync(Uri uri) in /__w/1/s/src/Uno.UWP/System/Launcher.skia.cs:line 29
   at Windows.Foundation.AsyncOperation`1.BuildTaskAsync(FuncAsync`2 taskBuilder) in /__w/1/s/src/Uno.Foundation/Internal/AsyncOperation.TResult.cs:line 70
   at System.WindowsRuntimeSystemExtensions.AsTaskCore[TResult](IAsyncOperation`1 source, CancellationToken ct) in /__w/1/s/src/Uno.UWP/System.Runtime/WindowsRuntimeSystemExtensions.cs:line 66
   at Microsoft.UI.Xaml.Controls.HyperlinkButton.OnClick() in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/Button/HyperlinkButton.mux.cs:line 123
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Uno.UI.Dispatching.NativeDispatcherSynchronizationContext.<>c__DisplayClass3_0.<Post>b__0() in /__w/1/s/src/Uno.UI.Dispatching/Native/NativeDispatcherSynchronizationContext.cs:line 21
   at Uno.UI.Dispatching.NativeDispatcher.DispatchItems() in /__w/1/s/src/Uno.UI.Dispatching/Native/NativeDispatcher.cs:line 134

### Expected behavior

Webpage should open

### How to reproduce it (as minimally and precisely as possible)

[UnoAppHyperlink.zip](https://github.com/user-attachments/files/16396578/UnoAppHyperlink.zip)

### Works on UWP/WinUI

Yes

### Affected platforms

Skia (Linux X11), Skia (Linux Framebuffer)

**Comment by ramezgerges** [comment]
@ArchieCoder Are you sure you're running the correct target? Your log shows `/mnt/d/Projects/UnoAppHyperlink/UnoAppHyperlink/bin/Debug/net8.0-windows10.0.19041` which looks like it's running the windows target in a WSL environment. You're supposed to build and run with `net8-.0-desktop` on Linux. I tested your repro on Linux and it's working fine.

P.S. Make sure to mark your future issues with [WSL] when you repro with WSL.

**Comment by ArchieCoder** [comment]
@ArchieCoder thanks for the information, this was mostly due to my inexperience with Linux. Noted for next time.
