### ISSUE TITLE
[Gallery][WASM] Canary not getting loaded

### ISSUE THREAD

**Issue by jhanvi03** [unoplatform/uno#17794]
### Current behavior

WASM Gallery canaries are stuck on splashscreen with this in the logs:

invoke-js.ts:176  fail: Uno.UI.Dispatching.NativeDispatcher[0]
      NativeDispatcher unhandled exception
System.NullReferenceException: Arg_NullReferenceException
   at Uno.Gallery.Sample.CreateData(Type dataType)
   at Uno.Gallery.Sample..ctor(SamplePageAttribute attribute, Type viewType)
   at Uno.Gallery.App.GetSamples()
   at Uno.Gallery.App.AddNavigationItems(NavigationView nv)
   at Uno.Gallery.App.BuildShell()
   at Uno.Gallery.App.OnLaunchedOrActivated()
   at Uno.Gallery.App.OnLaunched(LaunchActivatedEventArgs e)
   at Microsoft.UI.Xaml.Application.Initialize()
   at Uno.UI.Dispatching.NativeDispatcher.<>c__DisplayClass14_1.<EnqueueOperation>b__0()
   at Uno.UI.Dispatching.NativeDispatcher.DispatchItems()
(anonymous) @ invoke-js.ts:176
dotnet.native.js:8  Aborted(native code called abort())
abort @ dotnet.native.js:8
invoke-js.ts:116  RuntimeError: unreachable
mono_wasm_bind_js_function @ invoke-js.ts:116
invoke-js.ts:176  fail: Uno.UI.Dispatching.NativeDispatcher[0]
      NativeDispatcher unhandled exception
RuntimeError: unreachable
    at https://unogallerycanary.z27.web.core.windows.net/package_cf6a92a1776f8d94fc5c0ba2a0cbe64671b956ca/dotnet.native.wasm:wasm-function[5305]:0x23fae2
    at ___trap (https://unogallerycanary.z27.web.core.windows.net/package_cf6a92a1776f8d94fc5c0ba2a0cbe64671b956ca/dotnet.native.js:8:194817)
    at abort (https://unogallerycanary.z27.web.core.windows.net/package_cf6a92a1776f8d94fc5c0ba2a0cbe64671b956ca/dotnet.native.js:8:20579)
    at _abort (https://unogallerycanary.z27.web.core.windows.net/package_cf6a92a1776f8d94fc5c0ba2a0cbe64671b956ca/dotnet.native.js:8:98449)
    at https://unogallerycanary.z27.web.core.windows.net/package_cf6a92a1776f8d94fc5c0ba2a0cbe64671b956ca/dotnet.native.wasm:wasm-function[289]:0x154a7
    at https://unogallerycanary.z27.web.core.windows.net/package_cf6a92a1776f8d94fc5c0ba2a0cbe64671b956ca/dotnet.native.js:8:21193
    at ccall (https://unogallerycanary.z27.web.core.windows.net/package_cf6a92a1776f8d94fc5c0ba2a0cbe64671b956ca/dotnet.native.js:8:152727)
    at Object.mono_wasm_abort (https://unogallerycanary.z27.web.core.windows.net/package_cf6a92a1776f8d94fc5c0ba2a0cbe64671b956ca/dotnet.native.js:8:152929)
    at runtimeHelpers.abort (https://unogallerycanary.z27.web.core.windows.net/package_cf6a92a1776f8d94fc5c0ba2a0cbe64671b956ca/dotnet.runtime.js:3:281948)
    at mono_assert (https://unogallerycanary.z27.web.core.windows.net/package_cf6a92a1776f8d94fc5c0ba2a0cbe64671b956ca/dotnet.runtime.js:3:2302)
(anonymous) @ invoke-js.ts:176
        Failed to load resource: the server responded with a status of 404 (The requested content does not exist.)

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

**Comment by agneszitte** [comment]
fyi @jeromelaban, @kazo0
