### ISSUE TITLE
Resizetizer can't locate SkiaSharp libraries

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno#18211]
### Current behavior

Use wizard to create new application targeting uno5.5 (version 5.5.0-dev.17)
Rebuild all

```
Rebuild started at 12:44 PM...
1>------ Rebuild All started: Project: UnoApp29, Configuration: Debug Any CPU ------
Restored c:\temp\UnoApp29\UnoApp29\UnoApp29.csproj (in 978 ms).
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): warning : Uno.Resizetizer0000
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000: System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'libSkiaSharp': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at SkiaSharp.SkiaApi.sk_colortype_get_default_8888()
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at SkiaSharp.SKImageInfo..cctor()
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    --- End of inner exception stack trace ---
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Svg.Skia.SKSvgSettings..ctor() in /_/src/Svg.Skia/SKSvgSettings.cs:line 22
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Svg.Skia.SKSvg..ctor() in /_/src/Svg.Skia/SKSvg.Model.cs:line 55
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Uno.Resizetizer.SkiaSharpSvgTools..ctor(String filename, Nullable`1 baseSize, Nullable`1 backgroundColor, Nullable`1 tintColor, ILogger logger)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Uno.Resizetizer.SkiaSharpTools.Create(Boolean isVector, String filename, Nullable`1 baseSize, Nullable`1 backgroundColor, Nullable`1 tintColor, ILogger logger)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Uno.Resizetizer.Resizer.Rasterize(DpiPath dpi, String destination)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Uno.Resizetizer.Resizer.Resize(DpiPath dpi, String inputsFile)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Uno.Resizetizer.ResizetizeImages_fe37862be6f8fb908991583ae0de30f0a4023685.ProcessImageResize(ResizeImageInfo img, DpiPath[] dpis, ConcurrentBag`1 resizedImages)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Uno.Resizetizer.ResizetizeImages_fe37862be6f8fb908991583ae0de30f0a4023685.<>c__DisplayClass58_0.<ExecuteAsync>b__0(ResizeImageInfo img)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Uno.Resizetizer.AsyncTaskExtensions.<>c__DisplayClass0_0`1.<ParallelForEach>b__0(TSource s)
1>Done building project "UnoApp29.csproj" -- FAILED.
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.android.targets(11,3): error MSB4018: The "GenerateSplashAndroidResources_fe37862be6f8fb908991583ae0de30f0a4023685" task failed unexpectedly.
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.android.targets(11,3): error MSB4018: System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'libSkiaSharp': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.android.targets(11,3): error MSB4018:    at SkiaSharp.SkiaApi.sk_colortype_get_default_8888()
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.android.targets(11,3): error MSB4018:    at SkiaSharp.SKImageInfo..cctor()
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.android.targets(11,3): error MSB4018:    --- End of inner exception stack trace ---
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.android.targets(11,3): error MSB4018:    at Svg.Skia.SKSvgSettings..ctor() in /_/src/Svg.Skia/SKSvgSettings.cs:line 22
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.android.targets(11,3): error MSB4018:    at Svg.Skia.SKSvg..ctor() in /_/src/Svg.Skia/SKSvg.Model.cs:line 55
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.android.targets(11,3): error MSB4018:    at Uno.Resizetizer.SkiaSharpSvgTools..ctor(String filename, Nullable`1 baseSize, Nullable`1 backgroundColor, Nullable`1 tintColor, ILogger logger)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.android.targets(11,3): error MSB4018:    at Uno.Resizetizer.SkiaSharpTools.Create(Boolean isVector, String filename, Nullable`1 baseSize, Nullable`1 backgroundColor, Nullable`1 tintColor, ILogger logger)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.android.targets(11,3): error MSB4018:    at Uno.Resizetizer.GenerateSplashAndroidResources_fe37862be6f8fb908991583ae0de30f0a4023685.Execute()
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.android.targets(11,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.android.targets(11,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
1>Done building project "UnoApp29.csproj" -- FAILED.
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): warning : Uno.Resizetizer0000
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000: System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'libSkiaSharp': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at SkiaSharp.SkiaApi.sk_colortype_get_default_8888()
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at SkiaSharp.SKImageInfo..cctor()
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    --- End of inner exception stack trace ---
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Svg.Skia.SKSvgSettings..ctor() in /_/src/Svg.Skia/SKSvgSettings.cs:line 22
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Svg.Skia.SKSvg..ctor() in /_/src/Svg.Skia/SKSvg.Model.cs:line 55
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Uno.Resizetizer.SkiaSharpSvgTools..ctor(String filename, Nullable`1 baseSize, Nullable`1 backgroundColor, Nullable`1 tintColor, ILogger logger)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Uno.Resizetizer.SkiaSharpTools.Create(Boolean isVector, String filename, Nullable`1 baseSize, Nullable`1 backgroundColor, Nullable`1 tintColor, ILogger logger)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Uno.Resizetizer.Resizer.Rasterize(DpiPath dpi, String destination)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Uno.Resizetizer.Resizer.Resize(DpiPath dpi, String inputsFile)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Uno.Resizetizer.ResizetizeImages_fe37862be6f8fb908991583ae0de30f0a4023685.ProcessImageResize(ResizeImageInfo img, DpiPath[] dpis, ConcurrentBag`1 resizedImages)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Uno.Resizetizer.ResizetizeImages_fe37862be6f8fb908991583ae0de30f0a4023685.<>c__DisplayClass58_0.<ExecuteAsync>b__0(ResizeImageInfo img)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Uno.Resizetizer.AsyncTaskExtensions.<>c__DisplayClass0_0`1.<ParallelForEach>b__0(TSource s)
1>Done building project "UnoApp29.csproj" -- FAILED.
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): warning : Uno.Resizetizer0000
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000: System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'libSkiaSharp': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at SkiaSharp.SkiaApi.sk_colortype_get_default_8888()
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at SkiaSharp.SKImageInfo..cctor()
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    --- End of inner exception stack trace ---
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Svg.Skia.SKSvgSettings..ctor() in /_/src/Svg.Skia/SKSvgSettings.cs:line 22
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Svg.Skia.SKSvg..ctor() in /_/src/Svg.Skia/SKSvg.Model.cs:line 55
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Uno.Resizetizer.SkiaSharpSvgTools..ctor(String filename, Nullable`1 baseSize, Nullable`1 backgroundColor, Nullable`1 tintColor, ILogger logger)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Uno.Resizetizer.SkiaSharpTools.Create(Boolean isVector, String filename, Nullable`1 baseSize, Nullable`1 backgroundColor, Nullable`1 tintColor, ILogger logger)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Uno.Resizetizer.Resizer.Rasterize(DpiPath dpi, String destination)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Uno.Resizetizer.Resizer.Resize(DpiPath dpi, String inputsFile)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Uno.Resizetizer.ResizetizeImages_fe37862be6f8fb908991583ae0de30f0a4023685.ProcessImageResize(ResizeImageInfo img, DpiPath[] dpis, ConcurrentBag`1 resizedImages)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Uno.Resizetizer.ResizetizeImages_fe37862be6f8fb908991583ae0de30f0a4023685.<>c__DisplayClass58_0.<ExecuteAsync>b__0(ResizeImageInfo img)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Uno.Resizetizer.AsyncTaskExtensions.<>c__DisplayClass0_0`1.<ParallelForEach>b__0(TSource s)
1>Done building project "UnoApp29.csproj" -- FAILED.
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): warning : Uno.Resizetizer0000
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): warning : Uno.Resizetizer0000
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): warning : Uno.Resizetizer0000
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000: System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'libSkiaSharp': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at SkiaSharp.SkiaApi.sk_colortype_get_default_8888()
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at SkiaSharp.SKImageInfo..cctor()
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    --- End of inner exception stack trace ---
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Svg.Skia.SKSvgSettings..ctor() in /_/src/Svg.Skia/SKSvgSettings.cs:line 22
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Svg.Skia.SKSvg..ctor() in /_/src/Svg.Skia/SKSvg.Model.cs:line 55
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Uno.Resizetizer.SkiaSharpSvgTools..ctor(String filename, Nullable`1 baseSize, Nullable`1 backgroundColor, Nullable`1 tintColor, ILogger logger)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Uno.Resizetizer.SkiaSharpTools.Create(Boolean isVector, String filename, Nullable`1 baseSize, Nullable`1 backgroundColor, Nullable`1 tintColor, ILogger logger)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Uno.Resizetizer.SkiaSharpAppIconTools..ctor(ResizeImageInfo info, ILogger logger)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Uno.Resizetizer.Utils.GenerateIcoFile(String intermediateOutputPath, ILogger logger, ResizeImageInfo info, String iconName)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Uno.Resizetizer.ResizetizeImages_fe37862be6f8fb908991583ae0de30f0a4023685.ProcessAppIcon(ResizeImageInfo img, ConcurrentBag`1 resizedImages)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Uno.Resizetizer.ResizetizeImages_fe37862be6f8fb908991583ae0de30f0a4023685.<>c__DisplayClass58_0.<ExecuteAsync>b__0(ResizeImageInfo img)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.targets(485,3): error Uno.Resizetizer0000:    at Uno.Resizetizer.AsyncTaskExtensions.<>c__DisplayClass0_0`1.<ParallelForEach>b__0(TSource s)
1>Done building project "UnoApp29.csproj" -- FAILED.
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.windows.skia.targets(36,3): error MSB4018: The "GenerateSplashAssets_fe37862be6f8fb908991583ae0de30f0a4023685" task failed unexpectedly.
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.windows.skia.targets(36,3): error MSB4018: System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'libSkiaSharp': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.windows.skia.targets(36,3): error MSB4018:    at SkiaSharp.SkiaApi.sk_colortype_get_default_8888()
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.windows.skia.targets(36,3): error MSB4018:    at SkiaSharp.SKImageInfo..cctor()
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.windows.skia.targets(36,3): error MSB4018:    --- End of inner exception stack trace ---
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.windows.skia.targets(36,3): error MSB4018:    at Svg.Skia.SKSvgSettings..ctor() in /_/src/Svg.Skia/SKSvgSettings.cs:line 22
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.windows.skia.targets(36,3): error MSB4018:    at Svg.Skia.SKSvg..ctor() in /_/src/Svg.Skia/SKSvg.Model.cs:line 55
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.windows.skia.targets(36,3): error MSB4018:    at Uno.Resizetizer.SkiaSharpSvgTools..ctor(String filename, Nullable`1 baseSize, Nullable`1 backgroundColor, Nullable`1 tintColor, ILogger logger)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.windows.skia.targets(36,3): error MSB4018:    at Uno.Resizetizer.SkiaSharpTools.Create(Boolean isVector, String filename, Nullable`1 baseSize, Nullable`1 backgroundColor, Nullable`1 tintColor, ILogger logger)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.windows.skia.targets(36,3): error MSB4018:    at Uno.Resizetizer.SkiaSharpAppIconTools..ctor(ResizeImageInfo info, ILogger logger)
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.windows.skia.targets(36,3): error MSB4018:    at Uno.Resizetizer.GenerateSplashAssets_fe37862be6f8fb908991583ae0de30f0a4023685.Execute()
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.windows.skia.targets(36,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
1>C:\Users\NickRandolph\.nuget\packages\uno.resizetizer\1.6.0-dev.26\build\Uno.Resizetizer.windows.skia.targets(36,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
1>Done building project "UnoApp29.csproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
========== Rebuild completed at 12:44 PM and took 08.947 seconds ==========
```

### Works on UWP/WinUI

None

**Comment by nickrandolph** [comment]
Workaround:
- Downgrade to Uno.Resizetizer 1.6.0-dev.22
- Disable Android TFM to avoid issue with Uno.Resizetizer 1.6.0-dev.222
