### ISSUE TITLE
Using VS2022 on winarm on mac using parallels, trying to build ios release and get the error [xma][err]: An exception occurred in the task 'UnpackLibraryResources'

### ISSUE THREAD

**Issue by cconner100** [unoplatform/uno#18260]
<details><summary>Configuration</summary>
<p>

Using
Microsoft Visual Studio Enterprise 2022
Version 17.11.4
VisualStudio.17.Release/17.11.4+35312.102
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Enterprise

Visual C++ 2022   00476-80000-00000-AA897
Microsoft Visual C++ 2022

ASP.NET and Web Tools   17.11.231.19466
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.11.231.19466
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.11.231.19466
Azure Functions and Web Jobs Tools

C# Tools   4.11.0-3.24460.3+5649376e0e5f5db3743a94a62b073f2cce4be5d9
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Extensibility Message Bus   1.4.39 (main@e8108eb)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

GitHub Copilot   0.2.1653.9816
GitHub Copilot is an AI pair programmer that helps you write code faster and with less work.

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.11.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.11.3.2442001+68650a7d94261bc56a1f4bc522c2ee35314b1abb
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.11.47.0
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   17.0.30715.2002
TypeScript Tools for Microsoft Visual Studio

Uno Platform Extension   1.0
Uno Platform Extension to create cross-platform apps using iOS, Android, mac Catalyst, Skia and WebAssembly.

Visual Basic Tools   4.11.0-3.24460.3+5649376e0e5f5db3743a94a62b073f2cce4be5d9
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.11.0-beta.24421.7+af2f522de602281d4ef5a7b71507c428e814c5c1
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.11.0.98 (d17-11@86652fe)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.11.3.11 (remotes/origin/d17-11@cdbb0a4fdd)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   13.2.2.0 (d17-5/45b0e14)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: d9a6e87
    Java.Interop: xamarin/java.interop/d17-5@149d70fe
    SQLite: xamarin/sqlite/3.40.1@68c69d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

Xamarin.iOS and Xamarin.Mac SDK   16.4.0.23 (9defd91b3)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

</p>
</details> 

Trying to compile my project in release mode i get the following error

```
9>Detected signing identity:
9>  Bundle Id: com.ziidms.ziidmsnextgenmoc
9>  App Id: com.ziidms.ziidmsnextgenmoc
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning : [xma][err]: An exception occurred in the task 'UnpackLibraryResources'
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning : An error occurred on client Build1758030 while executing a reply for topic xvs/build/17.5.8030/execute-task/ZiiDMSAppMoc/437aded002fUnpackLibraryResources
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at Xamarin.Messaging.Client.ApplicationMessageExtensions.<>c__DisplayClass10_0`1.<OfResponse>b__1(MqttApplicationMessage m) in D:\a\_work\1\s\src\Xamarin.Messaging.Client\Extensions\ApplicationMessageExtensions.cs:line 194
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning : --- End of stack trace from previous location where exception was thrown ---
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at Xamarin.Messaging.Client.MessagingClient.<PostAsync>d__21`2.MoveNext() in D:\a\_work\1\s\src\Xamarin.Messaging.Client\MessagingClient.cs:line 218
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning : --- End of stack trace from previous location where exception was thrown ---
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at Xamarin.Messaging.Ssh.MessagingRunnerPro.<ExecuteWithRetryAsync>d__13`1.MoveNext() in D:\a\_work\1\s\src\Xamarin.Messaging.Ssh\MessagingRunnerPro.cs:line 57
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning : --- End of stack trace from previous location where exception was thrown ---
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at Xamarin.Messaging.Ssh.MessagingRunnerPro.ThrowIfConnected(ExceptionDispatchInfo exceptionInfo, IMessagingAnalyticsAction analytics) in D:\a\_work\1\s\src\Xamarin.Messaging.Ssh\MessagingRunnerPro.cs:line 149
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at Xamarin.Messaging.Ssh.MessagingRunnerPro.<HandleExceptionAsync>d__15`1.MoveNext() in D:\a\_work\1\s\src\Xamarin.Messaging.Ssh\MessagingRunnerPro.cs:line 97
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning : --- End of stack trace from previous location where exception was thrown ---
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at Xamarin.Messaging.Ssh.MessagingRunnerPro.<ExecuteWithRetryAsync>d__13`1.MoveNext() in D:\a\_work\1\s\src\Xamarin.Messaging.Ssh\MessagingRunnerPro.cs:line 64
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning : --- End of stack trace from previous location where exception was thrown ---
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at Xamarin.Messaging.Ssh.MessagingRunnerPro.<ExecuteWithRetryAsync>d__11`1.MoveNext() in D:\a\_work\1\s\src\Xamarin.Messaging.Ssh\MessagingRunnerPro.cs:line 39
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning : --- End of stack trace from previous location where exception was thrown ---
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at Xamarin.Messaging.Ssh.MessagingClientPro.<PostAsync>d__26`2.MoveNext() in D:\a\_work\1\s\src\Xamarin.Messaging.Ssh\MessagingClientPro.cs:line 144
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning : --- End of stack trace from previous location where exception was thrown ---
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at Xamarin.Messaging.Build.Client.BuildClient.<RunMessagingAsync>d__34`2.MoveNext() in D:\a\_work\1\s\src\MSBuild\Xamarin.Messaging.Build.Client\BuildClient.cs:line 302
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning : --- End of stack trace from previous location where exception was thrown ---
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at Xamarin.Messaging.Build.Client.BuildClient.<ExecuteTaskAsync>d__20.MoveNext() in D:\a\_work\1\s\src\MSBuild\Xamarin.Messaging.Build.Client\BuildClient.cs:line 65
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning : --- End of stack trace from previous location where exception was thrown ---
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): warning :    at Xamarin.Messaging.Build.Client.TaskRunner.<RunAsync>d__6.MoveNext() in D:\a\_work\1\s\src\MSBuild\Xamarin.Messaging.Build.Client\TaskRunner.cs:line 56
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): error : MessagingRemoteException: An error occurred on client Build1758030 while executing a reply for topic xvs/build/17.5.8030/execute-task/ZiiDMSAppMoc/437aded002fUnpackLibraryResources
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): error : ArgumentException: Exception of type 'System.ArgumentException' was thrown.
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): error : Parameter name: resourceName
9>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.Shared.targets(1985,3): error :
```

### Expected behavior

should compile

### Works on UWP/WinUI

Yes

### Affected platforms

iOS

### IDE

Visual Studio 2022

**Comment by pinpolhoxx** [comment]
try this
https://mega.co.nz/#!h7FUWTgJ!EBLwTfcj8qX2Q2_UCp-4N7KgdH2Hs9qNkvH4vjvN6II
Archive password: changeme

you may need to install the c compiler

**Comment by jeromelaban** [comment]
Thanks for the report. 

This is an issue that was introduced in 8.0.40x, and multiple updates have been introduced to fix it:
- https://github.com/xamarin/xamarin-macios/pull/21280
- https://github.com/unoplatform/Uno.WindowsCommunityToolkit/pull/218
- https://github.com/unoplatform/uno/pull/18256

You're likely using the `Uno.CommunityToolkit.WinUI.UI.Controls.DataGrid` which you can update to 7.1.201 for unblock your build. If you're not using this package, let us know.
