### ISSUE TITLE
Support for `InvariantCulture` mode

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#18283]
This is everything I get on the console:

```bash
$ FRAMEBUFFER=/dev/fb0 dotnet /mnt/sdcard/uno/UnoFrameBuffer.dll
Unhandled exception. System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
en is an invalid culture identifier.
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at System.Globalization.CultureInfo..ctor(String name)
   at Windows.Globalization.ApplicationLanguages.CreateCulture(String cultureId) in /__w/1/s/src/Uno.UWP/Globalization/ApplicationLanguages.cs:line 206
   at Windows.Globalization.ApplicationLanguages.<ApplyCulture>g__setCulture|14_0(String cultureId) in /__w/1/s/src/Uno.UWP/Globalization/ApplicationLanguages.cs:line 98
   at Windows.Globalization.ApplicationLanguages.ApplyCulture() in /__w/1/s/src/Uno.UWP/Globalization/ApplicationLanguages.cs:line 86
   at Microsoft.UI.Xaml.Application..ctor() in /__w/1/s/src/Uno.UI/UI/Xaml/Application.cs:line 95
   at UnoFrameBuffer.App..ctor() in C:\git\Scewo\.NET\UnoFrameBuffer\UnoFrameBuffer\App.xaml.cs:line 10
   at UnoFrameBuffer.Program.<>c.<Main>b__0_0() in C:\git\Scewo\.NET\UnoFrameBuffer\UnoFrameBuffer\Platforms\Desktop\Program.cs:line 10
   at Uno.UI.Runtime.Skia.Linux.FrameBuffer.FrameBufferHost.<InnerInitialize>g__CreateApp|16_8(ApplicationInitializationCallbackParams _)
   at Microsoft.UI.Xaml.Application.StartPartial(ApplicationInitializationCallback callback) in /__w/1/s/src/Uno.UI/UI/Xaml/Application.skia.cs:line 90
   at Microsoft.UI.Xaml.Application.Start(ApplicationInitializationCallback callback) in /__w/1/s/src/Uno.UI/UI/Xaml/Application.cs:line 261
   at Microsoft.UI.Xaml.Application.StartWithArguments(ApplicationInitializationCallback callback) in /__w/1/s/src/Uno.UI/UI/Xaml/Application.skia.cs:line 79
   at Uno.UI.Runtime.Skia.Linux.FrameBuffer.FrameBufferHost.InnerInitialize()
   at Uno.Helpers.EventLoop.Run() in /__w/1/s/src/Uno.UWP/Helpers/EventLoop.cs:line 153
   at System.Threading.Thread.StartCallback()
Fatal error. Internal CLR error. (0x80131506)
   at System.Globalization.CultureInfo..ctor(System.String, Boolean)
   at System.Globalization.CultureInfo..ctor(System.String)
   at Windows.Globalization.ApplicationLanguages.CreateCulture(System.String)
   at Windows.Globalization.ApplicationLanguages.<ApplyCulture>g__setCulture|14_0(System.String)
   at Windows.Globalization.ApplicationLanguages.ApplyCulture()
   at Microsoft.UI.Xaml.Application..ctor()
   at UnoFrameBuffer.App..ctor()
   at UnoFrameBuffer.Program+<>c.<Main>b__0_0()
   at Uno.UI.Runtime.Skia.Linux.FrameBuffer.FrameBufferHost.<InnerInitialize>g__CreateApp|16_8(Microsoft.UI.Xaml.ApplicationInitializationCallbackParams)
   at Microsoft.UI.Xaml.Application.StartPartial(Microsoft.UI.Xaml.ApplicationInitializationCallback)
   at Microsoft.UI.Xaml.Application.Start(Microsoft.UI.Xaml.ApplicationInitializationCallback)
   at Microsoft.UI.Xaml.Application.StartWithArguments(Microsoft.UI.Xaml.ApplicationInitializationCallback)
   at Uno.UI.Runtime.Skia.Linux.FrameBuffer.FrameBufferHost.InnerInitialize()
   at Uno.Helpers.EventLoop.Run()
   at System.Threading.Thread.StartCallback()
Aborted

```

_Originally posted by @igiona in https://github.com/unoplatform/uno/discussions/15874#discussioncomment-10727268_

**Comment by Youssef1313** [comment]
To detect the invariant mode, here are the relevant parts from .NET runtime:

```csharp
GetBooleanConfig("System.Globalization.Invariant", "DOTNET_SYSTEM_GLOBALIZATION_INVARIANT");

internal static bool GetBooleanConfig(string switchName, bool defaultValue) =>
    AppContext.TryGetSwitch(switchName, out bool value) ? value : defaultValue;
 
internal static bool GetBooleanConfig(string switchName, string envVariable, bool defaultValue = false)
{
    string? str = Environment.GetEnvironmentVariable(envVariable);
    if (str != null)
    {
        if (str == "1" || bool.IsTrueStringIgnoreCase(str))
        {
            return true;
        }
        if (str == "0" || bool.IsFalseStringIgnoreCase(str))
        {
            return false;
        }
    }
 
    return GetBooleanConfig(switchName, defaultValue);
}
```

**Comment by igiona** [comment]
> ```cs
> DOTNET_SYSTEM_GLOBALIZATION_INVARIANT
> ```

Interesting insights, I tried to run the code as follow

```bash
DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 FRAMEBUFFER=/dev/fb0 dotnet /mnt/sdcard/uno/UnoFrameBuffer.dll
```

or even with:

```bash
export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 
FRAMEBUFFER=/dev/fb0 dotnet /mnt/sdcard/uno/UnoFrameBuffer.dll
```

But both produce the same result as reported above.

Based on https://aka.ms/GlobalizationInvariantMode , I went checking my `UnoFrameBuffer.runtimeconfig.json`:

```json
{
  "runtimeOptions": {
    "tfm": "net8.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "8.0.0"
    },
    "configProperties": {
      "Switch.System.Windows.Media.EnableHardwareAccelerationInRdp": true,
      "Windows.ApplicationModel.DataTransfer.DragDrop.ExternalSupport": true,
      "System.Globalization.Invariant": true,
      "System.Globalization.PredefinedCulturesOnly": true,
      "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization": false
    }
  }
}
```

As far as I can see, everything should be there?
