### ISSUE TITLE
[Android/iOS] InvalidOperationException when using AppBarButton.Icon in NavigationBar in Debug Output

### ISSUE THREAD

**Issue by agneszitte** [unoplatform/uno#18545]
### Current behavior

When using `AppBarButton.Icon` in a `NavigationBar`, an exception is thrown in the Visual Studio debug output. 
These exceptions occur only when the `AppBarButton` is used within the NavigationBar. No exception is seen if the `AppBarButton` is used without the `NavigationBar`.

### Expected behavior

No exceptions should occur in the Visual Studio debug output like for the other platforms.

### How to reproduce it (as minimally and precisely as possible)

**Sample app to repro: [NavigationBarSampleApp.zip](https://github.com/user-attachments/files/17483172/NavigationBarSampleApp.zip)**

Launch the application for Android / iOS (no build errors), then notice the exception mentioned in VS Debug Output when the application is loaded.

With:
```
      <utu:NavigationBar Background="Orange"
                         Content="TEST">
        <utu:NavigationBar.PrimaryCommands>
          <AppBarButton Click="AppBarButton_Click">
            <AppBarButton.Icon>
              <FontIcon Glyph="&#xE109;" />
            </AppBarButton.Icon>
            <ToolTipService.ToolTip>
              <ToolTip Content="Add new row" />
            </ToolTipService.ToolTip>
          </AppBarButton>
        </utu:NavigationBar.PrimaryCommands>
      </utu:NavigationBar>
```

In  VS Debug Ouput:
- For Android:
```
[DOTNET] warn: Uno.Toolkit.UI.DependencyObjectExtensions[0]
[DOTNET]       Error attempting to read property:
[DOTNET]       System.InvalidOperationException: The Dependency Property [UriSource] is owned by [Microsoft.UI.Xaml.Controls.BitmapIcon] and cannot be used on [Microsoft.UI.Xaml.Controls.FontIcon]
[DOTNET]          at Microsoft.UI.Xaml.DependencyObjectStore.GetValue(DependencyProperty property, DependencyPropertyDetails propertyDetails, Nullable1 precedence, Boolean isPrecedenceSpecific) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 281
[DOTNET]          at Microsoft.UI.Xaml.DependencyObjectStore.GetValue(DependencyProperty property) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 249
[DOTNET]          at Uno.UI.Controls.BindableView.GetValue(DependencyProperty dp) in C:\a\1\s\src\Uno.UI\obj\Uno.UI.netcoremobile\Release
et8.0-android\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.DependencyObject.DependencyObjectGenerator\Uno.UI.Controls.BindableView.cs:line 51
[DOTNET]          at Uno.Toolkit.UI.DependencyObjectExtensions.TryGetValue(DependencyObject dependencyObject, DependencyProperty dependencyProperty, DependencyObject& value) in D:\a\1\s\src\Uno.Toolkit.UI\Extensions\DependencyObjectExtensions.cs:line 267
```
- For iOS
```
2024-10-22 19:27:35.452575-0400 NavigationBarSampleApp[44932:35292242] warn: Uno.Toolkit.UI.DependencyObjectExtensions[0] Error attempting to read property:
System.InvalidOperationException: The Dependency Property [UriSource] is owned by [Microsoft.UI.Xaml.Controls.BitmapIcon] and cannot be used on [Microsoft.UI.Xaml.Controls.FontIcon]
   at Microsoft.UI.Xaml.DependencyObjectStore.GetValue(DependencyProperty property, DependencyPropertyDetails propertyDetails, Nullable1 precedence, Boolean isPrecedenceSpecific)
   at Microsoft.UI.Xaml.DependencyObjectStore.GetValue(DependencyProperty property)
   at Uno.UI.Controls.BindableUIView.GetValue(DependencyProperty dp)
   at Uno.Toolkit.UI.DependencyObjectExtensions.TryGetValue(DependencyObject dependencyObject, DependencyProperty dependencyProperty, DependencyObject& value)
Loaded assembly: Anonymously Hosted DynamicMethods Assembly [External]
2024-10-22 19:27:36.239099-0400 NavigationBarSampleApp[44932:35292242] warn: Uno.UI.Xaml.FontHelper[0] Failed to get system font based on XamlAutoFontFamily
```

---

With:
```
      <utu:NavigationBar Background="DeepPink"
                         Content="TEST">
        <utu:NavigationBar.PrimaryCommands>
          <AppBarButton Icon="Favorite"
                        Click="AppBarButton_Click" />
        </utu:NavigationBar.PrimaryCommands>
      </utu:NavigationBar>
```

In  VS Debug Ouput:
- For Android
```
[DOTNET] warn: Uno.Toolkit.UI.DependencyObjectExtensions[0]
[DOTNET]       Error attempting to read property:
[DOTNET]       System.InvalidOperationException: The Dependency Property [UriSource] is owned by [Microsoft.UI.Xaml.Controls.BitmapIcon] and cannot be used on [Microsoft.UI.Xaml.Controls.SymbolIcon]
[DOTNET]          at Microsoft.UI.Xaml.DependencyObjectStore.GetValue(DependencyProperty property, DependencyPropertyDetails propertyDetails, Nullable1 precedence, Boolean isPrecedenceSpecific) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 281
[DOTNET]          at Microsoft.UI.Xaml.DependencyObjectStore.GetValue(DependencyProperty property) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 249
[DOTNET]          at Uno.UI.Controls.BindableView.GetValue(DependencyProperty dp) in C:\a\1\s\src\Uno.UI\obj\Uno.UI.netcoremobile\Release
et8.0-android\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.DependencyObject.DependencyObjectGenerator\Uno.UI.Controls.BindableView.cs:line 51
[DOTNET]          at Uno.Toolkit.UI.DependencyObjectExtensions.TryGetValue(DependencyObject dependencyObject, DependencyProperty dependencyProperty, DependencyObject& value) in D:\a\1\s\src\Uno.Toolkit.UI\Extensions\DependencyObjectExtensions.cs:line 267
```
- For iOS
```
2024-10-22 19:29:32.907004-0400 NavigationBarSampleApp[45710:35296071] warn: Uno.Toolkit.UI.DependencyObjectExtensions[0] Error attempting to read property:
System.InvalidOperationException: The Dependency Property [UriSource] is owned by [Microsoft.UI.Xaml.Controls.BitmapIcon] and cannot be used on [Microsoft.UI.Xaml.Controls.SymbolIcon]
   at Microsoft.UI.Xaml.DependencyObjectStore.GetValue(DependencyProperty property, DependencyPropertyDetails propertyDetails, Nullable1 precedence, Boolean isPrecedenceSpecific)
   at Microsoft.UI.Xaml.DependencyObjectStore.GetValue(DependencyProperty property)
   at Uno.UI.Controls.BindableUIView.GetValue(DependencyProperty dp)
   at Uno.Toolkit.UI.DependencyObjectExtensions.TryGetValue(DependencyObject dependencyObject, DependencyProperty dependencyProperty, DependencyObject& value)
Loaded assembly: Anonymously Hosted DynamicMethods Assembly [External]
2024-10-22 19:29:33.647655-0400 NavigationBarSampleApp[45710:35296071] warn: Uno.UI.Xaml.FontHelper[0] Failed to get system font based on XamlAutoFontFamily
```

### Workaround

N/A

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

**Uno.Sdk**: Reproducible in stable **5.4.10**, but also with older versions like **5.3.31** for example.

### Affected platforms

Android, iOS

### IDE

Visual Studio 2022

### IDE version

Microsoft Visual Studio Professional 2022 (64-bit) - Current Version 17.11.4

**Comment by agneszitte** [comment]
fyi @MartinZikmund, @kazo0

**Comment by MartinZikmund** [comment]
Does `NavigationBar` support non-`BitmapIcons` @kazo0

**Comment by ramezgerges** [comment]
I can repro with Uno.Sdk=5.4.10 but I can no longer repro with the latest Uno.Sdk or even with the latest 5.5.0-dev version, so it seems like this is already fixed? @agneszitte

**Comment by agneszitte** [comment]
@jhanvi03, @Darsh0307 if you can test this issue with latest internal 5.6 stable please

**Comment by agneszitte** [comment]
@ramezgerges (cc @MartinZikmund, @kazo0, @jeromelaban)

- **For Android:**
  I am still able to see the **InvalidOperationException** with latest **uno.sdk 5.6.20** or latest **uno.sdk 5.7.0-dev.29**
  ![Image](https://github.com/user-attachments/assets/3775c256-d487-47b7-9424-e9ec98341ddb)

- **For iOS:**
  I don't see the **InvalidOperationException** anymore with the latest **uno.sdk 5.6.20** or latest **uno.sdk 5.7.0-dev.29** but I am not able to see the `AppBarButton` Icons. Let me know if I need to open a separate issue for iOS based on the latest details details here.
Current errors in the debug output:
	```
	 2025-01-30 10:17:43.938381-0500 RecommendedAppVSWizardNet9[32483:91728997] GSFontRegisterCGFont(<CGFont (0x600002cb8000): Roboto-Medium>) failed 305
	[0:] The Bindable attribute is missing and the type [Microsoft.UI.Xaml.Controls.ToolTipService] is not known by the MetadataProvider. Reflection was used instead of the binding engine and generated static metadata. Add the Bindable attribute to prevent this message and performance issues.
	2025-01-30 10:17:44.776996-0500 RecommendedAppVSWizardNet9[32483:91728997] warn: Uno.UI.Xaml.FontHelper[0] Failed to get system font based on XamlAutoFontFamily
	[0:] Uno.UI.Xaml.FontHelper: Warning: Failed to get system font based on XamlAutoFontFamily
	```
	![Image](https://github.com/user-attachments/assets/cf2f4b1a-de57-4f5d-8bf0-124dd5664de8)
	*[Toolkit documentation for reference](https://platform.uno/docs/articles/external/uno.toolkit.ui/doc/controls/NavigationBar.html#icon-1):
	![Image](https://github.com/user-attachments/assets/24e26cc3-d17c-4df3-ae32-96f40e6502a8)

--- 
Tested with:
- SDK/Templates: **5.6.20** or **5.7.0-dev.29**
- VS version: VS 2022 (64-bit) - Version 17.12.4
- VS vsix: [5.6.13](https://dev.azure.com/uno-platform/uno-private/_build/results?buildId=153440&view=results)
- Repro solution: [RecommendedAppVSWizardNet9.zip](https://github.com/user-attachments/files/18605298/RecommendedAppVSWizardNet9.zip)

**Comment by agneszitte** [comment]
@jeromelaban, @kazo0 I am still able to repro with latest **uno.sdk 5.6.25** (exact same details as mentioned in https://github.com/unoplatform/uno/issues/18545#issuecomment-2624880529).

I imagine https://github.com/unoplatform/uno.toolkit.ui/pull/1333 should be backported.

**Comment by kazo0** [comment]
@agneszitte the backport is now merged: https://github.com/unoplatform/uno.toolkit.ui/pull/1348

**Comment by agneszitte** [comment]
I am **not** able to reproduce the **InvalidOperationException** anymore with latest **Uno.Sdk 5.6.36** for **iOS** and **Android**.

--- 
Tested with:
- Templates/SDK: **5.6.36**
- VS version: VS 2022 (64-bit) - Version **17.13.1**
- VS VSIX: [5.6.31](https://dev.azure.com/uno-platform/uno-private/_build/results?buildId=155709&view=results)
- [RecommendedAppVsWizardNet9.zip](https://github.com/user-attachments/files/18876666/RecommendedAppVsWizardNet9.zip)
- Platform: **iOS, Android**
- OS: **Windows**
