### ISSUE TITLE
Rider plugin

### ISSUE THREAD

**Issue by JavierMarcuzzi** [unoplatform/uno#18664]
### Current behavior

Hello
After updating rider, I have this report and it cannot be sent to you in the usual way.

java.lang.IllegalArgumentException: Can't register uno.rider.model.NotificationType with id: 4364162870572604664, already registered: uno.rider.model.NotificationType
at com.jetbrains.rd.framework.Serializers.register(Serializers.kt:57)
at uno.rider.model.TemplatePluginModel$Companion.registerSerializersCore(TemplatePluginModel.Generated.kt:37)
at com.jetbrains.rd.framework.Serializers$registerSerializersOwnerOnce$1.invoke(Serializers.kt:30)
at com.jetbrains.rd.framework.Serializers$registerSerializersOwnerOnce$1.invoke(Serializers.kt:26)
at com.jetbrains.rd.util.threading.SingleThreadSchedulerBase.queue$lambda$3(SingleThreadScheduler.kt:45)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)

### Works on UWP/WinUI

None

### IDE

Rider macOS

### Relevant plugins

Uno Platform 1.2.12

**Comment by jeromelaban** [comment]
Thanks for the report. This will be fixed when 1.2.15 will be released (should be shortly).
