### ISSUE TITLE
Error on Build in Latest Uno dev releases

### ISSUE THREAD

**Issue by NGame1** [unoplatform/uno#1870]
## Current behavior

```
Generation failed: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Generation failed for Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator. System.AggregateException: One or more errors occurred. ---> System.Exception: Processing failed for file C:\Users\{username}\source\repos\ThreeIdiots\HomeControlApp\HomeControlApp\HomeControlApp.Shared\App.xaml ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.ImportResourceDictionary(IIndentedStringBuilder writer, XamlObjectDefinition topLevelControl)
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildResourceDictionary(IIndentedStringBuilder writer, XamlObjectDefinition topLevelControl)
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.InnerGenerateFile()
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GenerateFile()
   --- End of inner exception stack trace ---
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GenerateFile()
   at Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGeneration.<>c__DisplayClass23_0.<Generate>b__0(XamlFileDefinition file)
   at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.QueryOpeningEnumerator`1.OpenQuery()
   at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
   at System.Linq.ParallelEnumerable.ToList[TSource](ParallelQuery`1 source)
   at Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGeneration.Generate()
   at Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator.Execute(SourceGeneratorContext context)
   at Uno.SourceGeneration.Host.SourceGeneratorEngine.<>c__DisplayClass4_1.<Generate>b__13(ValueTuple`2 generatorDef)
---> (Inner Exception #0) System.Exception: Processing failed for file C:\Users\ngame\source\repos\ThreeIdiots\HomeControlApp\HomeControlApp\HomeControlApp.Shared\App.xaml ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.ImportResourceDictionary(IIndentedStringBuilder writer, XamlObjectDefinition topLevelControl)
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildResourceDictionary(IIndentedStringBuilder writer, XamlObjectDefinition topLevelControl)
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.InnerGenerateFile()
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GenerateFile()
   --- End of inner exception stack trace ---
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GenerateFile()
   at Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGeneration.<>c__DisplayClass23_0.<Generate>b__0(XamlFileDefinition file)
   at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.Tasks.Task.Execute()<---

   at Uno.SourceGeneration.Host.SourceGeneratorEngine.<>c__DisplayClass4_1.<Generate>b__13(ValueTuple`2 generatorDef)
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---

Server stack trace: 
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.ScanQueryOperator`1.ScanEnumerableQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.ExecuteAndGetResultsAsArray()
   at Uno.SourceGeneration.Host.SourceGeneratorEngine.Generate()
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Uno.SourceGeneratorTasks.RemoteSourceGeneratorEngine.Generate(RemotableLogger2 logger, BuildEnvironment environment)
   at Uno.SourceGeneration.Host.Server.GenerationServerHost.GenerateForCollection(EnvironmentPool collection, BuildEnvironment environment)
   at Uno.SourceGeneration.Host.Server.GenerationServerHost.RunGeneration(RunRequest request, CancellationToken cancellationToken)
---> (Inner Exception #0) System.InvalidOperationException: Generation failed for Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator. System.AggregateException: One or more errors occurred. ---> System.Exception: Processing failed for file C:\Users\ngame\source\repos\ThreeIdiots\HomeControlApp\HomeControlApp\HomeControlApp.Shared\App.xaml ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.ImportResourceDictionary(IIndentedStringBuilder writer, XamlObjectDefinition topLevelControl)
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildResourceDictionary(IIndentedStringBuilder writer, XamlObjectDefinition topLevelControl)
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.InnerGenerateFile()
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GenerateFile()
   --- End of inner exception stack trace ---
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GenerateFile()
   at Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGeneration.<>c__DisplayClass23_0.<Generate>b__0(XamlFileDefinition file)
   at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.QueryOpeningEnumerator`1.OpenQuery()
   at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
   at System.Linq.ParallelEnumerable.ToList[TSource](ParallelQuery`1 source)
   at Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGeneration.Generate()
   at Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator.Execute(SourceGeneratorContext context)
   at Uno.SourceGeneration.Host.SourceGeneratorEngine.<>c__DisplayClass4_1.<Generate>b__13(ValueTuple`2 generatorDef)
---> (Inner Exception #0) System.Exception: Processing failed for file C:\Users\ngame\source\repos\ThreeIdiots\HomeControlApp\HomeControlApp\HomeControlApp.Shared\App.xaml ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.ImportResourceDictionary(IIndentedStringBuilder writer, XamlObjectDefinition topLevelControl)
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildResourceDictionary(IIndentedStringBuilder writer, XamlObjectDefinition topLevelControl)
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.InnerGenerateFile()
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GenerateFile()
   --- End of inner exception stack trace ---
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GenerateFile()
   at Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGeneration.<>c__DisplayClass23_0.<Generate>b__0(XamlFileDefinition file)
   at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.Tasks.Task.Execute()<---

   at Uno.SourceGeneration.Host.SourceGeneratorEngine.<>c__DisplayClass4_1.<Generate>b__13(ValueTuple`2 generatorDef)
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.Tasks.Task.Execute()<---	HomeControlApp.Droid				
```

## How to reproduce it (as minimally and precisely as possible)

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [x] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

**Comment by jeromelaban** [comment]
Thanks for the report! Are you able to share the content of the `App.xaml` resources section ?

**Comment by NGame1** [comment]
yes. There's really nothing because they are all commented
<Application
    x:Class="HomeControlApp.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:HomeControlApp"
    RequestedTheme="Light">
    

    
    
    

    
    
    
    
    
</Application>
