### ISSUE TITLE
`When_ShapeVisual_ViewBox_Shape_Combinations` is unstable

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#18752]
```
Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Assert.Fail failed. The bitmaps are not the same
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.ThrowAssertFailed(String assertionName, String message) in /_/src/TestFramework/TestFramework/Assertions/Assert.cs:line 60
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.Fail(String message, Object[] parameters) in /_/src/TestFramework/TestFramework/Assertions/Assert.Fail.cs:line 54
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.Fail(String message) in /_/src/TestFramework/TestFramework/Assertions/Assert.Fail.cs:line 37
   at Uno.UI.RuntimeTests.Helpers.ImageAssert.AreEqualAsync(RawBitmap actual, RawBitmap expected) in C:\a\1\s\src\Uno.UI.RuntimeTests\Helpers\ImageAssert.cs:line 220
   at Uno.UI.RuntimeTests.Tests.Windows_UI_Composition.Given_ShapeVisual.When_ShapeVisual_ViewBox_Shape_Combinations() in C:\a\1\s\src\Uno.UI.RuntimeTests\Tests\Windows_UI_Composition\Given_ShapeVisual.cs:line 80
   at Uno.UI.Samples.Tests.UnitTestsControl.<>c__DisplayClass63_1.<<ExecuteTestsForInstance>g__InvokeTestMethod|5>d.MoveNext() in C:\a\1\s\src\SamplesApp\SamplesApp.UnitTests.Shared\Controls\UnitTest\UnitTestsControl.cs:line 902
```

**Comment by MartinZikmund** [comment]
Added in #9080
