### ISSUE TITLE
Numerous Exceptions While Attaching Debugger

### ISSUE THREAD

**Issue by Mike-E-angelo** [unoplatform/uno#18783]
### Current behavior

I am using a very basic and simple SLN:
https://github.com/unoplatform/Uno.Samples/blob/master/reference/Counter/XAML-MVVM/Counter-XAML-MVVM.sln

While pressing `F5` to launch the application into an Android emulator, I am finding that it works as expected 1 out of 10 times.  Most of the time the emulator sits there waiting to be attached:

![image](https://github.com/user-attachments/assets/caf58680-deab-462f-b910-a36825b3802a)

But other times there are errors:

```
 warning: Could not connect Jdwp. System.Exception: Process Not Found.
   at Xamarin.AndroidTools.Debugging.DebuggingExtensions.<ConnectJdwpAsync>d__8.MoveNext() in D:\a\_work\1\s\External\androidtools\Xamarin.AndroidTools\Debugging\DebuggingExtensions.cs:line 198
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.AndroidTools.Debugging.DebuggingExtensions.<StartWithDebuggingAsync>d__2.MoveNext() in D:\a\_work\1\s\External\androidtools\Xamarin.AndroidTools\Debugging\DebuggingExtensions.cs:line 63
```

And:

```
> warning: Could not connect Jdwp. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'AdbClient'.
   at Mono.AndroidTools.Adb.AdbClient.CheckDisposed() in D:\a\_work\1\s\External\androidtools\Mono.AndroidTools\Adb\AdbClient.cs:line 104
   at Mono.AndroidTools.Adb.AdbClient.CreateClient() in D:\a\_work\1\s\External\androidtools\Mono.AndroidTools\Adb\AdbClient.cs:line 96
   at Mono.AndroidTools.Adb.AdbClient.BeginConnect(AsyncCallback callback, Object state) in D:\a\_work\1\s\External\androidtools\Mono.AndroidTools\Adb\AdbClient.cs:line 128
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at Mono.AndroidTools.Internal.AdbClientTaskExtensions.ConnectAsync(AdbClient client, TaskCreationOptions options) in D:\a\_work\1\s\External\androidtools\Mono.AndroidTools\Internal\AdbClientTaskExtensions.cs:line 50
   at Mono.AndroidTools.AdbServer.RunCommandWithStatus(String command, CancellationToken cancellationToken)
   at Mono.AndroidTools.AdbServer.KillForward(AndroidDevice device, String localProtocol, Int32 localPort, CancellationToken cancellationToken) in D:\a\_work\1\s\External\androidtools\Mono.AndroidTools\AdbServer.cs:line 202
   at Xamarin.AndroidTools.Debugging.DebuggingExtensions.<ConnectJdwpAsync>d__8.MoveNext() in D:\a\_work\1\s\External\androidtools\Xamarin.AndroidTools\Debugging\DebuggingExtensions.cs:line 196
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.AndroidTools.Debugging.DebuggingExtensions.<StartWithDebuggingAsync>d__2.MoveNext() in D:\a\_work\1\s\External\androidtools\Xamarin.AndroidTools\Debugging\DebuggingExtensions.cs:line 63
```

Also, it takes nearly 100 seconds from pressing F5 to seeing the very basic application load in the Android emulator.  This seems like a really long time. 

### Expected behavior

Pressing F5 quickly launches the application without error.

### Works on UWP/WinUI

None

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

17.12

### Anything else we need to know?

Thank you for your efforts out there. :)🙏

**Comment by jeromelaban** [comment]
Thanks for the report. Those issues are coming from Visual Studio, it would be best for your to open an issue directly here: https://developercommunity.visualstudio.com/VisualStudio.

Are you able to reproduce the same behavior [using vscode](https://platform.uno/docs/articles/get-started-vscode.html)?

**Comment by Mike-E-angelo** [comment]
I appreciate your patience here @jeromelaban as I learn all the moving pieces.  I was indeed also encountering this with Maui and this appears to be Visual Studio-related.  Taking this off your plate.  I appreciate all your efforts and impressive accomplishments out there. 🙏
