### ISSUE TITLE
Critical GREF Accumulation Issue with StaticLayout and String in Uno Platform on Android

### ISSUE THREAD

**Issue by NerijusN** [unoplatform/uno#18951]
### Current behavior

We are experiencing a critical issue in our Android application using Uno Platform (version `4.10.39`). After extended usage, the app enters a loop where the garbage collector (GC) struggles to free memory, and objects accumulate in the GREF table until it exceeds the limit, causing performance degradation and eventual crashes.

1. GREF Table Growth:
`android/text/StaticLayout` is the primary contributor:
Logs indicate 30936+17+273=31226 references.
`java/lang/String` is also significant:
Logs show 8293+63+83=8439 references.
Both grow steadily under normal app usage and are not released.
1. GC Logs:
Massive GC attempts are logged continuously:
```
[monodroid-gc] 46104 outstanding GREFs. Performing a full GC!
[ernal.tradezer] Explicit concurrent copying GC freed 10(47KB) AllocSpace objects, 0(0B) LOS objects, 32% free, 49MB/73MB, paused 32us total 130.155ms
[monodroid-gc] 46105 outstanding GREFs. Performing a full GC!
```
Despite frequent GC, the GREF count continues to grow.
1. Reproduction Steps:
```
Set adb shell setprop debug.mono.max_grefc 10000.
```
Run an isolated page that updates a `TextBlock` with price changes.
The GREF limit is reached within minutes.
1. Profiling:
Attempts to profile have not provided actionable insights.
Observations suggest `StaticLayout` and String instances are created frequently during `TextBlock.Measure` and layout calculations but are not cleaned up.
# Impact
This issue significantly impacts the app’s stability and makes it unsustainable for production environments.
# Request
Could you provide insights or guidance on addressing this GREF accumulation issue?
Are there known workarounds for managing `StaticLayout` or `String` references more effectively in the Uno Platform?

### Expected behavior

GC works as expected and Android app never experiences ANR because of intense GC calls.

### Works on UWP/WinUI

None

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

CollectionTracking 1.0.0
CollectionTracking.DynamicData 1.0.1
DynamicData 7.1.1
GeneratedSerializers.Json 1.0.0-dev.38
Analytics 3.8.0
FluentValidation.DependencyInjectionExtensions 9.5.4
Microsoft.AppCenter.Analytics 5.0.1
Microsoft.AppCenter.Crashes 5.0.1
Microsoft.Extensions.Hosting 3.1.0
Microsoft.Extensions.Http 8.0.1
Microsoft.Extensions.Localization.Abstractions 3.1.0
Microsoft.Extensions.Logging.Filter 1.1.2
Microsoft.Maui.Essentials 8.0.7
Serilog.Settings.Configuration 8.0.0
Serilog.Extensions.Hosting 8.0.0
Serilog.Sinks.File 5.0.0
System.Diagnostics.DiagnosticSource 8.0.0
Refit 8.0.0
Refit.Newtonsoft.Json 8.0.0
Scrutor 4.2.0
Portable.System.DateTimeOnly 8.0.1
Uno.UniversalImageLoader 1.9.37
Mono.AotProfiler.Android 9.0.0-preview1
Xamarin.Kotlin.StdLib.Jdk8 2.0.21.1
BiometryService 1.1.0
Uno.Fonts.Fluent 2.3.0
Uno.WinUI 4.10.39
Uno.WinUI.RemoteControl 4.10.39
Uno.UI.Adapter.Microsoft.Extensions.Logging 4.10.39
Uno.Microsoft.Xaml.Behaviors.Interactivity.WinUI 2.3.1-uno.2
Uno.Microsoft.Xaml.Behaviors.WinUI.Managed 2.3.1-uno.2
Reactive.Annex.Uno.WinUI 1.0.2
Microsoft.Extensions.Logging.Console 8.0.1
Chinook.BackButtonManager 1.1.4
Chinook.BackButtonManager.Uno.WinUI 1.1.4
Chinook.DataLoader.Uno.WinUI 1.2.0
Chinook.DataLoader.DynamicMvvm 1.2.0
Chinook.DynamicMvvm.Uno.WinUI 1.4.3
Chinook.DynamicMvvm 1.4.3
Chinook.DynamicMvvm.CollectionTracking 1.4.3
Chinook.DynamicMvvm.Reactive 1.4.3
Chinook.DynamicMvvm.FluentValidation 1.4.3
Serilog.Sinks.Xamarin 1.0.0
Uno.CodeGen 2.0.0-dev.10
Uno.Injectable 2.0.0-dev.10
Uno.SourceGenerationTasks 4.2.0
MallardMessageHandlers 1.2.0
Chinook.StackNavigation.Abstractions 2.1.2
Chinook.SectionsNavigation.Uno.WinUI 2.1.2
Chinook.SectionsNavigation.Reactive 2.1.2
MessageDialogService.Uno.WinUI 1.0.2
Uno.Material.WinUI 2.6.1
Uno.Toolkit.WinUI 3.0.4
Uno.Toolkit.WinUI.Material 3.0.4
Nventive.Persistence.Reactive 0.4.0-dev.43
Nventive.Persistence.Uno.WinUI 0.4.0-dev.43
Nventive.View.Uno.WinUI 0.5.0-dev.74
ExtendedSplashScreen.Uno.WinUI 1.0.2
Uno.WinUI.Lottie 4.10.39
Uno.CommunityToolkit.WinUI.DeveloperTools 7.1.100
Uno.CommunityToolkit.WinUI.UI.Controls 7.1.100
Uno.WinUI.Svg 4.10.39
Svg.Skia 2.0.0.2

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

17.11.3

**Comment by jeromelaban** [comment]
Thanks for the report.

This is likely an issue coming from Xamarin, which may be related to https://github.com/dotnet/android/issues/9377 and https://github.com/dotnet/runtime/issues/106410#issuecomment-2391391866. You can try adjusting the GC bridge and see if it helps.

**Comment by NerijusN** [comment]
We updated our `MONO_GC_PARAMS` settings to:
```
MONO_GC_PARAMS=bridge-implementation=new,nursery-size=128m,soft-heap-limit=512m
```
This change provided some improvement, as the GC freeze now occurs slightly later compared to our previous configuration:
```
MONO_GC_PARAMS=bridge-implementation=tarjan,nursery-size=32m,soft-heap-limit=256m
```
However, the core issue persists, and the GC still freezes during intensive application usage. Any guidance or additional suggestions for tuning these parameters would be greatly appreciated.

**Comment by jeromelaban** [comment]
Thanks. We'll try to reproduce.

**Comment by jeromelaban** [comment]
@NerijusN Could you provide the code that you use to reproduce the issue in standalone app?

**Comment by NerijusN** [comment]
Would like to re-open this ticket due to persistent GREF issues involving the following objects:

| Count   | Object Name                 | MCW Type                   |
|---------|-----------------------------|----------------------------|
| 30,936  | android/text/StaticLayout   | Android.Text.StaticLayout  |
| 8,293   | java/lang/String            | Java.Lang.String           |
| 5,198   | android/graphics/Rect       | Android.Graphics.Rect      |

While the fix mentioned in [PR #18956](https://github.com/unoplatform/uno/pull/18956) addresses Java.Lang.String by implementing limits on the JavaStringCache, the issue with android/text/StaticLayout remains unresolved and contributes significantly to GREF accumulation.

# Observations

We tested the benefits of the workaround provided in  [PR #18956](https://github.com/unoplatform/uno/pull/18956) by calculating the accumulation of Java.Lang.String objects using the snippet below.

```
		private void InitializeJavaStringWorkaround()
		{
#if __ANDROID__
			var thread = new Thread(() =>
			{
				try
				{
					var javaStringCacheType = typeof(Application).Assembly.GetType("Microsoft.UI.Xaml.Controls.JavaStringCache");
					if (javaStringCacheType == null)
					{
						throw new Exception("JavaStringCache was not found.");
					}

					var tableField = javaStringCacheType.GetField("_table", BindingFlags.NonPublic | BindingFlags.Static);
					if (tableField == null)
					{
						throw new Exception("JavaStringCache._table was not found.");
					}

					var table = tableField.GetValue(null);
					if (table == null)
					{
						throw new Exception("JavaStringCache._table is null.");
					}

					var tableType = table.GetType();

					var countProp = tableType.GetProperty("Count");
					if (countProp == null)
					{
						throw new Exception("JavaStringCache._table.Count was not found.");
					}

					while (true)
					{
						var countVal = countProp.GetValue(table); // HashtableEx.Count returns a field, accessing it should be thread-safe, so we don't need to lock JavaStringCache._gate.
						if (countVal is not int count)
						{
							throw new Exception("JavaStringCache._table.Count is not System.Int32.");
						}

						Trace.WriteLine($"JavaStringCache._table.Count = {count}");

						Thread.Sleep(TimeSpan.FromSeconds(30));
					}
				}
				catch (Exception ex)
				{
					Trace.WriteLine($"Error in Java string workaround: {ex}");
				}
			})
			{
				Name = "Java String Cleaner (Workaround)",
				IsBackground = true
			};

			thread.Start();
#endif
		}
```

This workaround may successfully reduce the count of java/lang/String objects during heavy GC operations, as evidenced by logs showing a manageable count of 509 before the GC loop.

# Concern

However, the GREF counts for android/text/StaticLayout are far greater—over 30,000 instances. This dwarfs the java/lang/String improvements and suggests that StaticLayout needs a similar approach or another resolution to handle its excessive references effectively.

```
handle 0x26e6e; key_handle 0x4c5a95a: Java Type: `android/text/StaticLayout`; MCW type: `Android.Text.StaticLayout`
+g+ grefc 8869 gwrefc 0 obj-handle 0xd5/I -> new-handle 0x26e02/G from thread '(null)'(1)
   at Android.Runtime.AndroidObjectReferenceManager.CreateGlobalReference(JniObjectReference ) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/AndroidRuntime.cs:line 179
   at Java.Interop.JniObjectReference.NewGlobalRef() in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniObjectReference.cs:line 139
   at Android.Runtime.JNIEnv.NewGlobalRef(IntPtr ) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNIEnv.cs:line 436
   at Android.Runtime.AndroidValueManager.AddPeer(IJavaPeerable , IntPtr , JniHandleOwnership , IntPtr& ) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/AndroidRuntime.cs:line 689
   at Java.Lang.Object.SetHandle(IntPtr value, JniHandleOwnership transfer) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Object.cs:line 252
   at Java.Lang.Object..ctor(IntPtr , JniHandleOwnership ) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Object.cs:line 80
   at Java.Lang.String..ctor(String ) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/String.cs:line 42
   at Microsoft.UI.Xaml.Controls.JavaStringCache.GetNativeString(String ) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\TextBlock\JavaStringCache.Android.cs:line 88
   at Microsoft.UI.Xaml.Controls.TextBlock.GetTextFormatted() in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\TextBlock\TextBlock.Android.cs:line 272
   at Microsoft.UI.Xaml.Controls.TextBlock.UpdateTextFormatted() in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\TextBlock\TextBlock.Android.cs:line 261
   at Microsoft.UI.Xaml.Controls.TextBlock.Update() in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\TextBlock\TextBlock.Android.cs:line 170
   at Microsoft.UI.Xaml.Controls.TextBlock.MeasureOverride(Size ) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\TextBlock\TextBlock.Android.cs:line 308
   at Microsoft.UI.Xaml.FrameworkElement.FrameworkElementLayouter.MeasureOverride(Size ) in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.cs:line 1034
   at Microsoft.UI.Xaml.Controls.Layouter.Measure(Size ) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Layouter\Layouter.cs:line 115
   at Microsoft.UI.Xaml.FrameworkElement.OnMeasure(Int32 , Int32 ) in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.Android.cs:line 194
   at Android.Views.View.n_OnMeasure_II(IntPtr jnienv, IntPtr native__this, Int32 widthMeasureSpec, Int32 heightMeasureSpec) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.Views.View.cs:line 19598
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPII_V(_JniMarshal_PPII_V callback, IntPtr jnienv, IntPtr klazz, Int32 p0, Int32 p1) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 154
   at Java.Interop.JniNativeMethods.wrapper_native_indirect_void_intptr_intptr_intptr_intptr_intptr(IntPtr& , IntPtr , IntPtr , IntPtr , IntPtr , IntPtr )
   at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference , JniObjectReference , JniMethodInfo , JniArgumentValue* ) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 20825
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeNonvirtualVoidMethod(String , IJavaPeerable , JniArgumentValue* ) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 93
   at Android.Views.View.Measure(Int32 , Int32 ) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.Views.View.cs:line 18377
   at Microsoft.UI.Xaml.FrameworkElement.FrameworkElementLayouter.MeasureChild(View , Int32 , Int32 ) in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.cs:line 1031
   at Microsoft.UI.Xaml.Controls.Layouter.MeasureChildOverride(View , Size ) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Layouter\Layouter.Android.cs:line 40
   at Microsoft.UI.Xaml.Controls.Layouter.MeasureChild(View , Size ) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Layouter\Layouter.cs:line 398
   at Microsoft.UI.Xaml.Controls.Layouter.Microsoft.UI.Xaml.Controls.ILayouter.MeasureChild(View , Size ) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Layouter\Layouter.cs:line 775
   at Microsoft.UI.Xaml.FrameworkElement.OnMeasure(Int32 , Int32 ) in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.Android.cs:line 194
   at Android.Views.View.n_OnMeasure_II(IntPtr jnienv, IntPtr native__this, Int32 widthMeasureSpec, Int32 heightMeasureSpec) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.Views.View.cs:line 19598
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPII_V(_JniMarshal_PPII_V callback, IntPtr jnienv, IntPtr klazz, Int32 p0, Int32 p1) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 154
   at Java.Interop.JniNativeMethods.wrapper_native_indirect_void_intptr_intptr_intptr_intptr_intptr(IntPtr& , IntPtr , IntPtr , IntPtr , IntPtr , IntPtr )
   at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference , JniObjectReference , JniMethodInfo , JniArgumentValue* ) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 20825
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeNonvirtualVoidMethod(String , IJavaPeerable , JniArgumentValue* ) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 93
   at Android.Views.View.Measure(Int32 , Int32 ) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.Views.View.cs:line 18377
   at Microsoft.UI.Xaml.FrameworkElement.FrameworkElementLayouter.MeasureChild(View , Int32 , Int32 ) in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.cs:line 1031
   at Microsoft.UI.Xaml.Controls.Layouter.MeasureChildOverride(View , Size ) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Layouter\Layouter.Android.cs:line 40
   at Microsoft.UI.Xaml.Controls.Layouter.MeasureChild(View , Size ) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Layouter\Layouter.cs:line 398
   at Microsoft.UI.Xaml.Controls.Layouter.Microsoft.UI.Xaml.Controls.ILayouter.MeasureChild(View , Size ) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Layouter\Layouter.cs:line 775
   at Microsoft.UI.Xaml.FrameworkElement.OnMeasure(Int32 , Int32 ) in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.Android.cs:line 194
   at Android.Views.View.n_OnMeasure_II(IntPtr jnienv, IntPtr native__this, Int32 widthMeasureSpec, Int32 heightMeasureSpec) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.Views.View.cs:line 19598
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPII_V(_JniMarshal_PPII_V callback, IntPtr jnienv, IntPtr klazz, Int32 p0, Int32 p1) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 154
   at Java.Interop.JniNativeMethods.wrapper_native_indirect_void_intptr_intptr_intptr_intptr_intptr(IntPtr& , IntPtr , IntPtr , IntPtr , IntPtr , IntPtr )
   at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference , JniObjectReference , JniMethodInfo , JniArgumentValue* ) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 20825
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeNonvirtualVoidMethod(String , IJavaPeerable , JniArgumentValue* ) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 93
   at Android.Views.View.Measure(Int32 , Int32 ) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.Views.View.cs:line 18377
   at Microsoft.UI.Xaml.IFrameworkElementHelper.Measure(IFrameworkElement , Size ) in C:\a\1\s\src\Uno.UI\UI\Xaml\IFrameworkElement.cs:line 320
   at Uno.UI.Services.LayoutManager.Arrange() in C:\a\1\s\src\Uno.UI\Services\LayoutManager.Android.cs:line 53
   at Uno.UI.Dispatching.CoreDispatcher.DispatchItemsToChoreographer() in C:\a\1\s\src\Uno.UI.Dispatching\Core\CoreDispatcher.Android.cs:line 96
   at Uno.UI.Dispatching.CoreDispatcher.FrameCallbackImplementor.DoFrame(Int64 ) in C:\a\1\s\src\Uno.UI.Dispatching\Core\CoreDispatcher.Android.cs:line 159
   at Android.Views.Choreographer.IFrameCallbackInvoker.n_DoFrame_J(IntPtr jnienv, IntPtr native__this, Int64 frameTimeNanos) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.Views.Choreographer.cs:line 97
   at Android.Runtime.DynamicMethodNameCounter.1(IntPtr , IntPtr , Int64 )
```

Given the impact of StaticLayout on GREF counts, further investigation and action are required to address this issue comprehensively.

**Comment by dlbd** [comment]
We were able to get accurate GREF counts using `dalvik.system.VMDebug.dumpReferenceTables`. Previously reported counts were from analyzing grefs.txt (produced by running the app after `adb shell setprop debug.mono.log gref`) with a custom tool and are not entirely accurate.

It appears that GREFs to UI elements are retained after navigating away from a page. It's not just GREFs to TextBlocks and their StaticLayouts that are accumulating, it's all UI elements (Grids, Borders, etc).

We also found that finalizers of Pages or objects referenced by Pages (added for testing) are never called on Android, but are called on Windows. This could mean that GREFs are accumulating because Pages (and their controls) are not garbage collected.

Attached is a separate project that tries to reproduce this issue. [FinalizeBug.zip](https://github.com/user-attachments/files/18129162/FinalizeBug.zip)

Test scenario 1: click "Go to page 1/2" a few times, then click "GC" twice. On Windows trace output contains `~FinalizeLogger() from MainPage`, `~MainPage()`. On Android it does not.
Test scenario 2: click "Go to page 1/2" a few times, then click "Dump refs" (available only on Android). Find Grid global reference count in VS output or logcat. Repeat. The number will be growing after each navigation.

**Comment by jeromelaban** [comment]
Thanks for the repro.

In all cases, make sure to test also on Uno Platform latest, the issues may have already been fixed.

> It appears that GREFs to UI elements are retained after navigating away from a page. It's not just GREFs to TextBlocks and their StaticLayouts that are accumulating, it's all UI elements (Grids, Borders, etc).

Forward navigation will always keep previous instances in memory in this version of Uno, which is the equivalent of the `CacheMode=Required` in `Frame`, this cannot be changed in Uno 4.10.

> Test scenario 1: click "Go to page 1/2" a few times, then click "GC" twice. On Windows trace output contains ~FinalizeLogger() from MainPage, ~MainPage(). On Android it does not.

Note that `Trace.WriteLine` does not show in the console, `Console.WriteLine` does. You'll notice that some finalizers are called, but still not all of them.

Still, there's an issue left when clearing the back stack manually which does not clear the underlying `NativeFramePresenter` properly, which your sample uses. Collection only happens when navigating backwards and forwards, and not when always going forward like your sample does. We'll make upcoming changes to the `NativeFramePresenter` to remove elements properly.

In all cases, you'll need to add `App.RootFrame?.BackStack.Clear();` to clean the backstack, or to manipulate the elements properly (using `RemoveAt` and alike).

**Comment by dlbd** [comment]
In the repro project with Uno 4.10, adding `App.RootFrame?.BackStack.Clear();`, setting `FeatureConfiguration.NativeFramePresenter.AndroidUnloadInactivePages = true;` or not using `NativeFramePresenter` does not appear to change anything. The number of page instances reported by `dumpReferenceTables()` keeps increasing.

**Comment by jeromelaban** [comment]
> In the repro project with Uno 4.10, adding `App.RootFrame?.BackStack.Clear();`, setting `FeatureConfiguration.NativeFramePresenter.AndroidUnloadInactivePages = true;`.

Correct, that's the issue I've mentioned. We'll be fixing this in 5.6 with #19094.

> or not using `NativeFramePresenter` does not appear to change anything.

This part has already been fixed in 5.x and later.

**Comment by NerijusN** [comment]
@jeromelaban 

> This part has already been fixed in 5.x and later.

Could you refer PR that was fixed in, please?

**Comment by NerijusN** [comment]
We have pulled `NativeFramePresenter.Android.cs` and modified the code able to access private/internal properties (attached).
TBH there is not much improvement, GREF accumulated maybe a few seconds later though. 

[NativeFramePresenter.Android.cs.zip](https://github.com/user-attachments/files/18323393/NativeFramePresenter.Android.cs.zip)

**Comment by francoistanguay** [comment]
Hi @NerijusN, we'll need more info to help. Were you able to bring all the NativeFramePresenter code from Uno into the app? DId you reference your new NativeFramePresenter in the Style?

Now that we've possibly narrowed down the issue to some leaks in NativeFramePresenter when Navigating forward always (and clearing backstack), you should be able to create a SIMPLE repro with just one frame, one page and your new NativeFramePresenter.

We need that in order to make sure we're all looking at the same thing.

We'll continue our own tests in the meantime but our initial results show that it fixed the original problem but that is not to say there isn`t something else going on with page pooling or something else.

So as discussed previously, please provide a simple repro so the team can look into it.

**Comment by NerijusN** [comment]
Following our meeting, we applied the suggestion to utilize the NativeFramePresenter.Android implementation from [this source](https://github.dev/unoplatform/uno/blob/81f442b38354b933cbcdc058a7629652c6e79b1b/src/Uno.UI/NativeFramePresenter.Android.cs). However, a direct copy-paste did not work due to access limitations with private constructors and properties. To proceed, we modified the code to access those members via reflection. 

[2024-01-07 FinalizeBug-with-NativeFramePresenter.zip](https://github.com/user-attachments/files/18333122/2024-01-07.FinalizeBug-with-NativeFramePresenter.zip)


# Setup Details:

 1. Code Adjustments:
The `/Controls/NativeFramePresenter.Android.cs` file was modified to include reflection-based access for private constructors and properties.
Attached is the modified code for your reference.

 2. Configuration Variations Tested:
We tested with both
```
#if __ANDROID__
    FeatureConfiguration.NativeFramePresenter.AndroidUnloadInactivePages = true; // Also tested with false
#endif
```
Outputs were nearly identical across both configurations. 

 3. XAML Implementation:
We used the following setup in `Frame.xml`
```
...
xmlns:controls="clr-namespace:FinalizeBug.Controls"
...
<android:Style x:Key="NativeDefaultFrame"
               TargetType="Frame">
    <Setter Property="Template">
        <Setter.Value>
            <ControlTemplate TargetType="Frame">
                <controls:NativeFramePresenter Background="{TemplateBinding Background}" />
            </ControlTemplate>
        </Setter.Value>
    </Setter>
</android:Style>
```
# Observations:
The Android logs remain largely unchanged:

Finalization logs (e.g., ~FinalizeLogger() from MainPage, SecondPage, and CollectGarbage test) appear as expected, indicating that finalizers are invoked, but memory is not being reclaimed effectively.  

### Win
```
~FinalizeLogger() from SecondPage
~SecondPage()
~FinalizeLogger() from MainPage
~MainPage()
~FinalizeLogger() from SecondPage
~SecondPage()
~FinalizeLogger() from MainPage
~MainPage()
~FinalizeLogger() from CollectGarbage test
```

### Android
```
[ame.FinalizeBu] Accessing hidden method Ldalvik/system/VMDebug;->dumpReferenceTables()V (greylist,core-platform-api, reflection, allowed)
[ame.FinalizeBu] Explicit concurrent copying GC freed 8660(398KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 3709KB/7418KB, paused 19us total 11.005ms
[memtrack] Couldn't load memtrack module
[monodroid-assembly] open_from_bundles: failed to load assembly System.Collections.Specialized.dll
Loaded assembly: /data/data/com.companyname.FinalizeBug/files/.__override__/System.Collections.Specialized.dll [External]
[0:] ~FinalizeLogger() from CollectGarbage test
[ame.FinalizeBu] Explicit concurrent copying GC freed 894(55KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 3685KB/7371KB, paused 23us total 9.759ms
```
The problem persists irrespective of the `AndroidUnloadInactivePages` flag value and code we applied.

**Comment by jeromelaban** [comment]
@NerijusN A few things about this repro:

- Comparing to Windows is not appropriate for this repro, since the cache default mode for `Page.NavigationCacheMode` is `Disabled` on pages instances from memory, and this is not the mode that the Android `NativeFramePresenter` is using. If you keep navigating forward in an app, pages *will* always stay in memory. You'll need to clear or remove pages from the back stack to reclaim the memory.
- Can you validate that you have `FrameworkTemplatePool.IsPoolingEnabled` set to `false` in your app? The template pooling feature does cause such issues in 4.x builds, this was fixed in 5.x.

Here's a fixed repro for android, which includes the following changes:
- Change all `Trace.WriteLine` to `Console.WriteLine` so they show properly on android
- Add a `Clear backstack` button
- Add `Uno.UI.FeatureConfiguration.FrameworkTemplate.IsPoolingEnabled = false;`  in `App.cs`.

[2024-01-08.FinalizeBug-with-NativeFramePresenter-fixed.zip](https://github.com/user-attachments/files/18348752/2024-01-08.FinalizeBug-with-NativeFramePresenter-fixed.zip)

**Comment by jeromelaban** [comment]
@NerijusN would you have an update for this issue?

**Comment by MartinZikmund** [comment]
This is no longer an issue for Skia-based apps
