### ISSUE TITLE
[DSP] Failure building in visual studio

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#18986]
I'm encountering a build error in my project that appears to be related to Windows updates. The issue has been reproduced on two separate machines, both occurring after Windows updates were installed.

```
The "GenerateFileTask" task could not be instantiated from "C:\Users\wenhong.lau.DATGEL\.nuget\packages\uno.dsp.tasks\1.4.0\build\../tools/Uno.Dsp.Tasks.dll". 
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(IServiceCollection services, Action`1 configure)
   at Microsoft.Extensions.Hosting.HostBuilder.PopulateServiceCollection(IServiceCollection services, HostBuilderContext hostBuilderContext, HostingEnvironment hostingEnvironment, PhysicalFileProvider defaultFileProvider, IConfiguration appConfiguration, Func`1 serviceProviderGetter)
   at Microsoft.Extensions.Hosting.HostBuilder.InitializeServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Uno.Dsp.Tasks.TaskBase..ctor()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
	Datgel.Acquisition (net8.0)	C:\Users\wenhong.lau.DATGEL\.nuget\packages\uno.dsp.tasks\1.4.0\build\Uno.Dsp.Tasks.targets	20	
```

Logs: https://github.com/user-attachments/files/17974926/logs.zip

_Originally posted by @WenHong-Lau in https://github.com/unoplatform/uno/discussions/18980_

**Comment by ajpinedam** [comment]
Ran a few tests using the DSP Task to override a custom material theme json file and could not reproduce this error. Use the same configuration the OP had  and even waited for a Windows Update

From the logs:

```bash
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, 
Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file 
specified.
File name: 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=8.0.0.0, Culture=neutral, 
PublicKeyToken=adb9793829ddae60'
```

I found this error is common in many different scenarios of .NET applications: https://stackoverflow.com/questions/43995432/could-not-load-file-or-assembly-microsoft-extensions-dependencyinjection-abstrac

Solution found found on different forums is either delete the library from the nuget local cache (.nuget folder) or remove and re-add this package from the project dependencies, forcing it to re-download.

I vote for closing this issue since we validated this is not directly related to Uno.

cc: @jeromelaban

**Comment by jeromelaban** [comment]
Thanks for the update. Let's close for now until we can find a more appropriate repro.
