### ISSUE TITLE
Can't run apps after publish for Linux or Windows

### ISSUE THREAD

**Issue by brswan** [unoplatform/uno#19000]
### Current behavior

I created a new project using the Uno extensions for VisualStudio.  I am able to run the default sample app within Visual Studio debugger.  

![image](https://github.com/user-attachments/assets/e959971e-b196-46e2-bd44-108e02f75d9f)

1. Linux Publish Issue - Blank Screen

I am able to publish for linux-arm64 but when I run on my device, the screen remains blank.  

Please see attached for linux logs.

[linux-arm64-logs.txt](https://github.com/user-attachments/files/18009128/linux-arm64-logs.txt)

2. Window Publish Issue - SDK Issue?
When running the published version on Windows I get the following error in Windows Event Viewer:
CoreCLR Version: 8.0.1124.51707
.NET Version: 8.0.11
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException: Unable to find the Microsoft.WindowsDesktop.App framework. An Uno Platform update may be required (Expected path D:\dev\test\UnoLatestSingleProject_02\UnoLatestSingleProject_02\bin\Release\net8.0-desktop\Microsoft.WindowsDesktop.App\win-x64)
   at Uno.UI.Runtime.Skia.WpfHostBuilder.RegisterAssemblyResolver(Boolean useSharedFramework)
   at Uno.UI.Runtime.Skia.WpfHostBuilder..ctor()
   at Uno.UI.Runtime.Skia.HostBuilder.<>c__DisplayClass0_0.<UseWindows>b__0()
   at Uno.UI.Runtime.Skia.SkiaHostBuilder.Build()

I have performed uno-check and it appears I have no issues:
![image](https://github.com/user-attachments/assets/8b3eada6-708a-406f-9324-c90d96a18bdb)

### Expected behavior

Default app should be published to linux-arm64 and appear as normal.  Default app should be able to run on win x64

### How to reproduce it (as minimally and precisely as possible)

- Create a new project in Visual Studio 2022
- Select Uno Platform App
- 2. Platforms - only leave Desktop checked
- 3. Presentation - MVVM
- Select Create

Open Program.cs and add the following lines to set the ApplicationDataPathOverride and LocalCacheFolderPathOverride
        WinRTFeatureConfiguration.ApplicationData.ApplicationDataPathOverride = "/home/test/data";
        WinRTFeatureConfiguration.ApplicationData.LocalCacheFolderPathOverride = "/home/test/cache";

### Workaround

None at this time

### Works on UWP/WinUI

No

### NuGet package version(s)

![image](https://github.com/user-attachments/assets/6e276a77-e22b-4fb3-a1b2-0de1011dc162)
![image](https://github.com/user-attachments/assets/a5dfdb15-5807-4407-be3c-8cb38ddd4a13)
![image](https://github.com/user-attachments/assets/c913bfec-831f-4f4e-8c8f-9aa8aaf6603b)

### Affected platforms

Skia (GTK), Windows (WinAppSDK)

### IDE

Visual Studio 2022

### IDE version

17.12.3

**Comment by jeromelaban** [comment]
Thanks for the report. We'll likely split the issues as they are unrelated.

> I am able to publish for linux-arm64 but when I run on my device, the screen remains blank.

Can you provide the command line that you used to publish your app? Can you also provide the linux environmnt that you're using ? `uname -a` and `lsb_release -a` will help.

> When running the published version on Windows I get the following error in Windows Event Viewer:

By the looks of it, it seems that there's a mismatch in the versions used to run the app. Try building your app with net9.0 instead of net8.0.

**Comment by brswan** [comment]
@jeromelaban  Thanks for your assistance.  Please see responses below:

> Thanks for the report. We'll likely split the issues as they are unrelated.
> 
> > I am able to publish for linux-arm64 but when I run on my device, the screen remains blank.
> 

Copy.  Do you need me to make two separate issues?

> Can you provide the command line that you used to publish your app?

I'm using the Visual Studio GUI publishing tool:

Linux Publish
![image](https://github.com/user-attachments/assets/9bb27f3e-d54b-47e4-9c1d-9e31752a457d)


Windows Publish
![image](https://github.com/user-attachments/assets/29fc0b7f-4f70-4809-bbf3-9d52aaec431c)

>  Can you also provide the linux environmnt that you're using ? `uname -a` and `lsb_release -a` will help.
> 
> > When running the published version on Windows I get the following error in Windows Event Viewer:


We are building our system from scratch using Yacto - I'm not the linux guy but if you need more info I can get it for you.
uname -a
Linux 6.4.0-linaro-lt-qcom+ #1 SMP PREEMPT Fri Jul 28 19:37:37 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

lsb_release doesn't appear to be included in our build.


> By the looks of it, it seems that there's a mismatch in the versions used to run the app. Try building your app with net9.0 instead of net8.0.

I only have net8.0-desktop available to publish with from the drop down
![image](https://github.com/user-attachments/assets/30327b86-3e40-4a13-86cf-488316370de1)

**Comment by jeromelaban** [comment]
Thanks. Could you do the publish on the command line [using the documented steps](https://platform.uno/docs/articles/uno-publishing-desktop.html?tabs=windows#publish-using-the-cli) and let us know if it helps?

For linux, this may look like a distribution specific issue, which may be missing some packages that are implicitly required by Skia to run. This is the [list of dependencies](https://platform.uno/docs/articles/get-started-vscode.html?tabs=linux%2Cubuntu1804#linux) that are known to be required. Your distribution may require some more

> I only have net8.0-desktop available to publish with from the drop down

You need to change your csproj `TargetFrameworks` in order to do this.

**Comment by brswan** [comment]
Using the following command: dotnet publish -f net8.0-desktop -r win-x64 -p:SelfContained=true

Results
dotnet publish -f net8.0-desktop -r win-x64 -p:SelfContained=true
  Determining projects to restore...
  Restored D:\dev\test\UnoLatestSingleProject_02\UnoLatestSingleProject_02\UnoLatestSingleProject_02.csproj (in 436 ms).
  UnoLatestSingleProject_02 -> D:\dev\test\UnoLatestSingleProject_02\UnoLatestSingleProject_02\bin\Release\net8.0-desktop\win-x64\UnoLatestSingleProject_02.dll
  UnoLatestSingleProject_02 -> D:\dev\test\UnoLatestSingleProject_02\UnoLatestSingleProject_02\bin\Release\net8.0-desktop\win-x64\publish\

Workload updates are available. Run `dotnet workload list` for more information.

Running with this generates the following error - which does look like a .net mismatch.  Is there a way to force it to net8.0?  We are targeting this framework.

![image](https://github.com/user-attachments/assets/4670e241-41b3-438c-8f01-d28b8bdb46d8)

**Comment by brswan** [comment]
dotnet workload list

Installed Workload Id      Manifest Version       Installation Source            
---------------------------------------------------------------------------------
android                    35.0.7/9.0.100         SDK 9.0.100, VS 17.12.35527.113
aspire                     8.2.2/8.0.100          SDK 9.0.100, VS 17.12.35527.113
ios                        18.0.9617/9.0.100      SDK 9.0.100, VS 17.12.35527.113
maccatalyst                18.0.9617/9.0.100      SDK 9.0.100, VS 17.12.35527.113
macos                      15.0.9617/9.0.100      SDK 9.0.100                    
maui                       9.0.0/9.0.100          SDK 9.0.100                    
maui-windows               9.0.0/9.0.100          SDK 9.0.100, VS 17.12.35527.113
wasm-tools                 9.0.0/9.0.100          SDK 9.0.100

**Comment by jeromelaban** [comment]
You can force building with .NET 8 using a [global.json file](https://learn.microsoft.com/en-us/dotnet/core/tools/global-json#rollforward), and set the `rollForward` to `latestMinor`.

**Comment by brswan** [comment]
@jeromelaban  I should clarify that I can run on my linux box using the older style template where each platform has it's own project:
Skia.Linux.FrameBuffer
Skia.GTK
Skia.Wpf

I am able to publish to WPF and GTK and run without issues.  Does this new all-in-one solution style use new dependencies? 

FYI - We are using Wayland and not X11 on our Linux box.

**Comment by jeromelaban** [comment]
Thanks for the update.

It's best if you move to the newer project format, as it uses the latest backend that relies on X11 directly and not GTK (GTK causes a lot of issues). In your case, it will use XWayland to render. It does also build in a single target `net8.0-desktop`.
