### ISSUE TITLE
Cannot build Uno Wasm for .NET 8 with SDK 5.5

### ISSUE THREAD

**Issue by Juriyx** [unoplatform/uno#19029]
### Current behavior

I get these system exceptions in Visual Studio 2022:
```
1>C:\Users\juriy\.nuget\packages\uno.wasm.bootstrap\8.0.21\build\Uno.Wasm.Bootstrap.targets(226,3): error : System.Exception: Failed to generate wasm layout (More details are available in diagnostics mode or using the MSBuild /bl switch)
1>C:\Users\juriy\.nuget\packages\uno.wasm.bootstrap\8.0.21\build\Uno.Wasm.Bootstrap.targets(226,3): error :    at Uno.Wasm.Bootstrap.ShellTask_v038af955a9b67691b2e0a0ec4ebf87820919b6b1.RunPackager() in /_/src/Uno.Wasm.Bootstrap/ShellTask.cs:line 768
1>C:\Users\juriy\.nuget\packages\uno.wasm.bootstrap\8.0.21\build\Uno.Wasm.Bootstrap.targets(226,3): error :    at Uno.Wasm.Bootstrap.ShellTask_v038af955a9b67691b2e0a0ec4ebf87820919b6b1.Execute() in /_/src/Uno.Wasm.Bootstrap/ShellTask.cs:line 271
1>Done building project "Console.App.csproj" -- FAILED.
```

```1>C:\Users\juriy\.nuget\packages\uno.wasm.bootstrap\8.0.21\build\Uno.Wasm.Bootstrap.targets(226,3): error : [00:00:03.9086040] Unhandled exception. System.Exception: Could not resolve Uno.UI.RemoteControl
1>C:\Users\juriy\.nuget\packages\uno.wasm.bootstrap\8.0.21\build\Uno.Wasm.Bootstrap.targets(226,3): error : [00:00:03.9115385]    at Driver.Resolve(String asm_name, AssemblyKind& kind) in /_/src/Uno.Wasm.Packager/packager.cs:line 249
1>C:\Users\juriy\.nuget\packages\uno.wasm.bootstrap\8.0.21\build\Uno.Wasm.Bootstrap.targets(226,3): error : [00:00:03.9115601]    at Driver.Import(String ra, AssemblyKind kind) in /_/src/Uno.Wasm.Packager/packager.cs:line 320
1>C:\Users\juriy\.nuget\packages\uno.wasm.bootstrap\8.0.21\build\Uno.Wasm.Bootstrap.targets(226,3): error : [00:00:03.9115628]    at Driver.Import(String ra, AssemblyKind kind) in /_/src/Uno.Wasm.Packager/packager.cs:line 320
1>C:\Users\juriy\.nuget\packages\uno.wasm.bootstrap\8.0.21\build\Uno.Wasm.Bootstrap.targets(226,3): error : [00:00:03.9115652]    at Driver.Import(String ra, AssemblyKind kind) in /_/src/Uno.Wasm.Packager/packager.cs:line 320
1>C:\Users\juriy\.nuget\packages\uno.wasm.bootstrap\8.0.21\build\Uno.Wasm.Bootstrap.targets(226,3): error : [00:00:03.9115675]    at Driver.Run(String[] args) in /_/src/Uno.Wasm.Packager/packager.cs:line 788
1>C:\Users\juriy\.nuget\packages\uno.wasm.bootstrap\8.0.21\build\Uno.Wasm.Bootstrap.targets(226,3): error : [00:00:03.9116524]    at Driver.Main(String[] args) in /_/src/Uno.Wasm.Packager/packager.cs:line 414
1>Done building project "Models.fsproj".
```

### Expected behavior

The application builds successfully

### How to reproduce it (as minimally and precisely as possible)

Unknown, reproducible on our solution

### Works on UWP/WinUI

None

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Uno.UI.RemoteControl 5.5.87

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

17.12.3

**Comment by jeromelaban** [comment]
Thanks for the report.

This error generally means that there's a setup issue in your environment. You can follow the error and analyze the messages [in the binlogs](https://platform.uno/docs/articles/uno-builds-troubleshooting.html).
