### ISSUE TITLE
Can't run published apps on Windows 7

### ISSUE THREAD

**Issue by YueLengM** [unoplatform/uno#19118]
### Current behavior

Can't run published app on windows 7.
Event viewer shows the following log
```
Application: Counter.exe
CoreCLR Version: 8.0.1124.51707
.NET Version: 8.0.11
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for 'Windows.Globalization.ApplicationLanguages' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'winlangdb.dll' or one of its dependencies: The specified module could not be found.  (0x8007007E)
   at Windows.System.UserProfile.GlobalizationPreferences.NativeMethods.EnsureLanguageProfileExists()
   at Windows.System.UserProfile.GlobalizationPreferences.GetWinUserLanguageList() in /__w/1/s/src/Uno.UWP/System/UserProfile/GlobalizationPreferences.cs:line 33
   at Windows.System.UserProfile.GlobalizationPreferences.get_Languages() in /__w/1/s/src/Uno.UWP/System/UserProfile/GlobalizationPreferences.cs:line 26
   at Windows.Globalization.ApplicationLanguages.ApplyLanguages() in /__w/1/s/src/Uno.UWP/Globalization/ApplicationLanguages.cs:line 157
   at Windows.Globalization.ApplicationLanguages..cctor() in /__w/1/s/src/Uno.UWP/Globalization/ApplicationLanguages.cs:line 63
   --- End of inner exception stack trace ---
   at Windows.Globalization.ApplicationLanguages.ApplyCulture() in /__w/1/s/src/Uno.UWP/Globalization/ApplicationLanguages.cs:line 68
   at Microsoft.UI.Xaml.Application..ctor() in /__w/1/s/src/Uno.UI/UI/Xaml/Application.cs:line 95
   at Counter.App..ctor() in C:\Users\Administrator\source\repos\Uno.Samples-master\reference\Counter\XAML-MVVM\Counter\App.xaml.cs:line 13
   at Counter.Program.<>c.<Main>b__0_0() in C:\Users\Administrator\source\repos\Uno.Samples-master\reference\Counter\XAML-MVVM\Counter\Platforms\Desktop\Program.cs:line 13
   at Uno.UI.Runtime.Skia.Wpf.WpfHost.<StartApp>g__CreateApp|20_0(ApplicationInitializationCallbackParams _)
   at Microsoft.UI.Xaml.Application.StartPartial(ApplicationInitializationCallback callback) in /__w/1/s/src/Uno.UI/UI/Xaml/Application.skia.cs:line 85
   at Microsoft.UI.Xaml.Application.Start(ApplicationInitializationCallback callback) in /__w/1/s/src/Uno.UI/UI/Xaml/Application.cs:line 261
   at Uno.UI.Runtime.Skia.Wpf.WpfHost.StartApp()
   at Uno.UI.Runtime.Skia.Wpf.WpfHost.RunLoop()
   at Uno.UI.Runtime.Skia.SkiaHost.RunCore()
   at Uno.UI.Runtime.Skia.SkiaHost.Run()
   at Counter.Program.Main(String[] args) in C:\Users\Administrator\source\repos\Uno.Samples-master\reference\Counter\XAML-MVVM\Counter\Platforms\Desktop\Program.cs:line 12
```

### How to reproduce it (as minimally and precisely as possible)

- Download Counter\XAML-MVVM sample
- Publish using the CLI `dotnet publish -f net8.0-desktop -r win-x64 -p:SelfContained=true`
- Try running it on Windows 7 VM

### Works on UWP/WinUI

None

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### IDE

Visual Studio 2022

**Comment by YueLengM** [comment]
The exception log is from .net so I believe that .net 8 should work on Windows 7. But uno is using a dll that is not available on Windows 7.

https://github.com/unoplatform/uno/blob/d9bc2e2f0edf89f17782e70481d7ab19323c65b5/src/Uno.UWP/System/UserProfile/GlobalizationPreferences.cs#L30-L51

**Comment by jeromelaban** [comment]
Thanks for the report. Indeed, this is not available on windows 7. 

A change could be made to avoid using that function, or fallback when it fails so that the languages list returned is empty, or a least returns the default language.
