### ISSUE TITLE
`Error HRESULT e_fail has been returned from a call to a COM component` when double-clicking `Package.appxmanifest`

### ISSUE THREAD

**Issue by Mike-E-angelo** [unoplatform/uno#19137]
### Current behavior

Upon double-clicking the `Package.appxmanifest` file in an Uno project an error is thrown and dialog shown to user:

![image](https://github.com/user-attachments/assets/588d725d-fb24-4d7e-b2f2-cab1c244b667)

### Expected behavior

No error is thrown and  `Package.appxmanifest` is loaded.

### How to reproduce it (as minimally and precisely as possible)

Load this SLN:
https://github.com/DragonSpark/Framework/blob/issues/reported/uno/19066/The%20DragonSpark%20Framework.sln

Then double-click this file in Visual Studio:
https://github.com/DragonSpark/Framework/blob/issues/reported/uno/19066/UnoApp1/UnoApp1/Package.appxmanifest

### Workaround

None Known

### Works on UWP/WinUI

None

### Environment

Other

### NuGet package version(s)

SDK 5.5.56

### Affected platforms

Windows (WinAppSDK)

### IDE

Visual Studio 2022

### IDE version

Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.12.3

### Anything else we need to know?

Thank you for your efforts out there. 🙏

I have reported this here to Visual Studio:
https://developercommunity.visualstudio.com/t/Error-HRESULT-e_fail-has-been-returned/10819926

Upon searching I found this issue:
https://developercommunity.visualstudio.com/t/Continually-getting-Error-HRESULT-E_FAI/10733627

And this issue:
https://developercommunity.visualstudio.com/t/Double-clicking-on-a-PackageAppxmanifes/10658683

Seems like this is a recurring/common issue with Uno and upon creating a new SLN from the project generator everything works as expected and I am able to view/design the `Package.appxmanifest` file.  

Because of this I am wondering if there is something to do with my framework. 🤔  So, reporting here as well in case there is something Uno-related.

**Comment by Mike-E-angelo** [comment]
Welp this is weird.  In the SLN that was working, now I get an error there, too.  Only this time I had the file open and I got a stack trace:

```
An error occurred in 'UnoApp2' while attempting to open 'Package.appxmanifest'
System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.PlatformUI.Packages.ShellService.EditorFactories.EditorFactory.<CreateEditorInstanceAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.<>c__DisplayClass86_0.<<CreateEditorInstanceAsync>g__CreateEditorInstanceAsync|1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.<CreateEditorInstanceAsync>d__86.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.<LoadDocumentFrameInternalAsync>d__85.MoveNext()
```

**Comment by jeromelaban** [comment]
Thanks for the report. This is fixed in VS 17.13 previews.
