### ISSUE TITLE
[iOS] Displaying a MessageDialog on page navigation causes an exception

### ISSUE THREAD

**Issue by BrianDT** [unoplatform/uno#1952]
## Current behavior
On iOS displaying a MessageDialog in code triggered by the loaded event causes a NullReferenceException.

## Expected behavior

Should not crash

## How to reproduce it (as minimally and precisely as possible)

A sample that reproduces the issue can be found here:
https://github.com/BrianDT/UnoDialogIssues

Nuget Package:
Uno.UI: 2.0.512-dev.3570

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

**Comment by jeromelaban** [comment]
Thank you for the report! 

Could you paste the stack trace of the exception ?

**Comment by BrianDT** [comment]
Stack Trace is:

  at Windows.UI.Popups.MessageDialog+<>c__DisplayClass27_0.<ShowAsync>b__2 (System.Threading.CancellationToken ct) [0x000c5] in D:\a\1\s\src\Uno.UWP\UI\Popups\MessageDialog.iOS.cs:69 
  at Windows.UI.Popups.MessageDialog+<>c__DisplayClass27_0.<ShowAsync>b__2 (System.Threading.CancellationToken ct) [0x0016c] in D:\a\1\s\src\Uno.UWP\UI\Popups\MessageDialog.iOS.cs:76 
  at Windows.Foundation.AsyncOperation`1[TResult].BuildTaskAsync (System.Func`2[T,TResult] taskBuilder) [0x000a8] in <125e78f70a724a5581eeffdb32ea14fe>:0 
  at DialogIssues.MainPage.ShowMessageDialog (System.String message, System.Action yesAction, System.Action noAction, System.String title) [0x000dc] in D:\Engineering\GitHub\UnoDialogIssues\DialogIssues\DialogIssues.Shared\MainPage.xaml.cs:68 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021 
  at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.4.0.2/src/Xamarin.iOS/Foundation/NSAction.cs:178 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.4.0.2/src/Xamarin.iOS/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.4.0.2/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
  at UIKit.UIApplication.Main (System.String[] args, System.Type principalClass, System.Type delegateClass) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.4.0.2/src/Xamarin.iOS/UIKit/UIApplication.cs:75 
  at DialogIssues.iOS.Application.Main (System.String[] args) [0x00001] in D:\Engineering\GitHub\UnoDialogIssues\DialogIssues\DialogIssues.iOS\Main.cs:12

**Comment by BrianDT** [comment]
Exception is {System.NullReferenceException: Object reference not set to an instance of an object

**Comment by BrianDT** [comment]
Still an issue in version Uno.UI 3.6.6, sample updated.

**Comment by BrianDT** [comment]
Confirmed still an issue in 4.6.19
Sample has been updated to confirm this

Current stack is:
   at Windows.UI.Popups.MessageDialog.ShowNativeAsync(CancellationToken )
   at Windows.UI.Popups.MessageDialog.ShowInnerAsync(CancellationToken )
   at Windows.UI.Popups.MessageDialog.<ShowAsync>b__2_0(CancellationToken )
   at Windows.Foundation.AsyncOperation`1.<BuildTaskAsync>d__5[[Windows.UI.Popups.IUICommand, Uno, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.WindowsRuntimeSystemExtensions.<AsTaskCore>d__11`1[[Windows.UI.Popups.IUICommand, Uno, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at DialogIssues.MainPage.<>c__DisplayClass2_0.<<ShowMessageDialog>b__0>d.MoveNext() in D:\Development\GitHub\UnoDialogIssues\DialogIssues\DialogIssues.Shared\MainPage.xaml.cs:line 84
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object )
   at Foundation.NSAsyncSynchronizationContextDispatcher.Apply()

**Comment by MartinZikmund** [comment]
We suggest using `ContentDialog` instead, as `MessageDialog` is outdated

**Comment by BrianDT** [comment]
> We suggest using `ContentDialog` instead, as `MessageDialog` is outdated

Sample updated as suggested, confirm resolved.
