### ISSUE TITLE
update uno template to vs2019

### ISSUE THREAD

**Issue by beefsteak** [unoplatform/uno#1969]
1. compile error that vs2019 create uno template .
2.compiling error that switching android sdk 28 to 26.

**Comment by ghuntley** [comment]
howdy @beefsteak can you please provide more information and the specific errors?

**Comment by beefsteak** [comment]
![image](https://user-images.githubusercontent.com/14013918/67668655-53abc280-f9ab-11e9-89d7-71e1445fe658.png)
![image](https://user-images.githubusercontent.com/14013918/67668686-67572900-f9ab-11e9-9728-a8a13af2f001.png)

**Comment by beefsteak** [comment]
Create new project

**Comment by beefsteak** [comment]
Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error		Generation failed: Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project file "C:\Users\orange\Desktop\App1\App1\App1.Shared\App1.Shared.projitems" could not be loaded. Data at the root level is invalid. Line 1, position 1.  C:\Users\orange\Desktop\App1\App1\App1.Droid\App1.Droid.csproj

Server stack trace: 
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject[T1,T2](IElementLocation elementLocation, String resourceName, T1 arg0, T2 arg1)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpression(String directoryOfImportingFile, ProjectImportElement importElement, String unescapedExpression, Boolean throwOnFileNotExistsError, List`1& imports)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Uno.SourceGeneration.Host.ProjectLoader.LoadProjectDetails(BuildEnvironment environment, Dictionary`2 globalProperties)
   at Uno.SourceGeneration.Host.SourceGeneratorEngine.Generate()
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Uno.SourceGeneratorTasks.RemoteSourceGeneratorEngine.Generate(RemotableLogger2 logger, BuildEnvironment environment)
   at Uno.SourceGeneration.Host.Server.GenerationServerHost.GenerateForCollection(EnvironmentPool collection, BuildEnvironment environment)
   at Uno.SourceGeneration.Host.Server.GenerationServerHost.RunGeneration(RunRequest request, CancellationToken cancellationToken)	App1.Droid				


<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="App1" android:versionCode="1" android:versionName="1.0">
  <uses-sdk android:minSdkVersion="16" android:targetSdkVersion="26" />
  <application android:label="App1"></application>
</manifest>

**Comment by jeromelaban** [comment]
@beefsteak does a ["normal" xamarin.android project](https://docs.microsoft.com/en-us/xamarin/android/get-started/hello-android/hello-android-quickstart?pivots=windows) build properly ?

**Comment by beefsteak** [comment]
yse, create new xamarin.android project is ok.

**Comment by beefsteak** [comment]
@jeromelaban yse, create new xamarin.android project is ok.

**Comment by beefsteak** [comment]
@jeromelaban  Do you have any message?

**Comment by beefsteak** [comment]
Steps to restore
![image](https://user-images.githubusercontent.com/14013918/68101393-67ee4300-ff08-11e9-828a-c81b62614f50.png)
![image](https://user-images.githubusercontent.com/14013918/68101407-750b3200-ff08-11e9-8289-0c6734a4bf26.png)
![image](https://user-images.githubusercontent.com/14013918/68101435-90763d00-ff08-11e9-99bf-e66bf084298f.png)
![image](https://user-images.githubusercontent.com/14013918/68101450-a8e65780-ff08-11e9-9795-642a374da0fe.png)
![image](https://user-images.githubusercontent.com/14013918/68101456-b69bdd00-ff08-11e9-8a22-377884afb018.png)
![image](https://user-images.githubusercontent.com/14013918/68101469-c5828f80-ff08-11e9-97aa-5c7b2b14b5bf.png)

**Comment by beefsteak** [comment]
Android SDKs and Tools

**Comment by beefsteak** [comment]
![image](https://user-images.githubusercontent.com/14013918/68101520-f236a700-ff08-11e9-9637-b341043511da.png)

**Comment by beefsteak** [comment]
![image](https://user-images.githubusercontent.com/14013918/68101537-02e71d00-ff09-11e9-90e8-100c0e19b782.png)

**Comment by francoistanguay** [comment]
SHould be fixed with 3.0
