### ISSUE TITLE
Deploying on an Android 4.1 device causes a runtime crash on start

### ISSUE THREAD

**Issue by crogeniks** [unoplatform/uno#20]
# Runtime crash in Android 4.1

Targeting Android 4.1 with a default solution created with Uno's solution template results in a runtime crash on start

# Minimal Repro steps

- Download the latest UnoSolutionTemplate (UnoSolutionTemplate-1.30.3-wasm.vsix)
- Create a new Solution
- Select the Droid project as Startup Project
- Deploy on an Android 4.1 device

# Expectected Result

Application runs

# Actual Results

Runtime crash : 
```
E/AndroidRuntime: FATAL EXCEPTION: main
   java.lang.NoSuchMethodError: no method with name='isAttachedToWindow' signature='()Z' in class LUno/UI/UnoViewGroup;
      at md5bf4da100b2dbb022d895d9bb2c38dfa6.NativeApplication_ActivityCallbacks.n_onActivityStarted(Native Method)
      at md5bf4da100b2dbb022d895d9bb2c38dfa6.NativeApplication_ActivityCallbacks.onActivityStarted(NativeApplication_ActivityCallbacks.java:83)
      at android.app.Application.dispatchActivityStarted(Application.java:164)
      at android.app.Activity.onStart(Activity.java:1032)
      at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:552)
      at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
      at md567cff875f28d20379ac19e960a3af0b6.BaseActivity.n_onStart(Native Method)
      at md567cff875f28d20379ac19e960a3af0b6.BaseActivity.onStart(BaseActivity.java:609)
      at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1163)
      at android.app.Activity.performStart(Activity.java:5018)
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2032)
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
      at android.app.ActivityThread.access$600(ActivityThread.java:130)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
      at android.os.Handler.dispatchMessage(Handler.java:99)
      at android.os.Looper.loop(Looper.java:137)
      at android.app.ActivityThread.main(ActivityThread.java:4745)
      at java.lang.reflect.Method.invokeNative(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:511)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
      at dalvik.system.NativeStart.main(Native Method)
```

**Comment by ghuntley** [comment]
Confirming that this still reproducible w/templates@1.43.1.826, API@16 and UnoUI@1.43.1.

![image](https://user-images.githubusercontent.com/127353/58169385-f44ad780-7cd3-11e9-9d0e-2f1921b511c4.png)
