### ISSUE TITLE
Failed to download the mono-wasm SDK

### ISSUE THREAD

**Issue by chrisevans9629** [unoplatform/uno#2472]
## Current behavior
When I build, I get this error:
```
3>Target BuildDist:
3>  SDK: mono-wasm-a163e05d265
3>  SDK Path: C:\Users\cevans\AppData\Local\Temp\mono-wasm-a163e05d265
3>  C:\Users\cevans\.nuget\packages\uno.wasm.bootstrap\1.1.0-dev.395\build\Uno.Wasm.Bootstrap.targets(116,5): error MSB4018: The "UnoInstallSDKTask_v0858f93d42fc4b4c63c71084fb144d06917ac514" task failed unexpectedly.
3>  C:\Users\cevans\.nuget\packages\uno.wasm.bootstrap\1.1.0-dev.395\build\Uno.Wasm.Bootstrap.targets(116,5): error MSB4018: System.InvalidOperationException: Failed to download the mono-wasm SDK at https://unowasmbootstrap.blob.core.windows.net/runtime/mono-wasm-a163e05d265.zip, System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\cevans\.nuget\packages\uno.wasm.bootstrap\1.1.0-dev.395\build\packager'.
3>  C:\Users\cevans\.nuget\packages\uno.wasm.bootstrap\1.1.0-dev.395\build\Uno.Wasm.Bootstrap.targets(116,5): error MSB4018:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
3>  C:\Users\cevans\.nuget\packages\uno.wasm.bootstrap\1.1.0-dev.395\build\Uno.Wasm.Bootstrap.targets(116,5): error MSB4018:    at System.IO.FileSystemEnumerableIterator`1.CommonInit()
3>  C:\Users\cevans\.nuget\packages\uno.wasm.bootstrap\1.1.0-dev.395\build\Uno.Wasm.Bootstrap.targets(116,5): error MSB4018:    at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
3>  C:\Users\cevans\.nuget\packages\uno.wasm.bootstrap\1.1.0-dev.395\build\Uno.Wasm.Bootstrap.targets(116,5): error MSB4018:    at System.IO.Directory.EnumerateFiles(String path)
3>  C:\Users\cevans\.nuget\packages\uno.wasm.bootstrap\1.1.0-dev.395\build\Uno.Wasm.Bootstrap.targets(116,5): error MSB4018:    at Uno.Wasm.Bootstrap.UnoInstallSDKTask_v0858f93d42fc4b4c63c71084fb144d06917ac514.InstallSdk() in D:\a\1\s\src\Uno.Wasm.Bootstrap\UnoInstallSDKTask.cs:line 50
3>  C:\Users\cevans\.nuget\packages\uno.wasm.bootstrap\1.1.0-dev.395\build\Uno.Wasm.Bootstrap.targets(116,5): error MSB4018:    at Uno.Wasm.Bootstrap.UnoInstallSDKTask_v0858f93d42fc4b4c63c71084fb144d06917ac514.InstallSdk() in D:\a\1\s\src\Uno.Wasm.Bootstrap\UnoInstallSDKTask.cs:line 132
3>  C:\Users\cevans\.nuget\packages\uno.wasm.bootstrap\1.1.0-dev.395\build\Uno.Wasm.Bootstrap.targets(116,5): error MSB4018:    at Uno.Wasm.Bootstrap.UnoInstallSDKTask_v0858f93d42fc4b4c63c71084fb144d06917ac514.Execute() in D:\a\1\s\src\Uno.Wasm.Bootstrap\UnoInstallSDKTask.cs:line 43
3>  C:\Users\cevans\.nuget\packages\uno.wasm.bootstrap\1.1.0-dev.395\build\Uno.Wasm.Bootstrap.targets(116,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
3>  C:\Users\cevans\.nuget\packages\uno.wasm.bootstrap\1.1.0-dev.395\build\Uno.Wasm.Bootstrap.targets(116,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
3>Done building target "BuildDist" in project "Evans.XamlTemplates.Wasm.csproj" -- FAILED.
```

This build error occurs when I upgrade from Xamarin.Forms 3.5.0.129452 to 4.2.0.910310
## Expected behavior
The project should build

## How to reproduce it (as minimally and precisely as possible)

You can see a sample of the error here:
https://github.com/chrisevans9629/Evans.XamlTemplates/tree/updateXamarinForms

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [x] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: 16.4.2)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by chrisevans9629** [comment]
This actually seems to occur irregardless of Xamarin.Forms version.  It will still allow you to run, but you get the following error:

```
InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.
Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware+<>c__DisplayClass0_0.<Attach>b__1(HttpContext context, Func<Task> next)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by jeromelaban** [comment]
Hi @chrisevans9629, try using the latest stable version of the Uno.Wasm.Bootstrapper package (1.0.10) and let us know if that helps.

**Comment by chrisevans9629** [comment]
Looks like that worked.

The Labels and Editor are not rendering correctly:
![image](https://user-images.githubusercontent.com/33850520/72272017-89953600-35ed-11ea-88b2-f2ec2ecc934f.png)

This is what it should look like (UWP)
![image](https://user-images.githubusercontent.com/33850520/72272076-a7fb3180-35ed-11ea-974a-99ae57151b78.png)

It looks like the editor is not filling to the parent control (left) and the labels are not respecting my newlines/returns.  My guess is that the labels are rendered as <p/> and not ```<pre>test</pre>```

Should I submit this as another issue?

**Comment by jeromelaban** [comment]
Indeed, that's not right. Yes, please open another issue with a sample if you can. Thanks !
