### ISSUE TITLE
Uno Platform controls don't work in Xamarin.Forms on Android

### ISSUE THREAD

**Issue by artemious7** [unoplatform/uno#2519]
## Current behavior
I followed [these steps](https://platform.uno/docs/articles/howto-use-uno-in-xamarin-forms.html) to embed Uno.UI controls into a Xamarin.Forms XAML file or code-behind.
But I get this exception:
` Java.Lang.NullPointerException: 'Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference'`
```
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in <e7e2d009b69d4e5f9a00e6ee600b8a8e>:0 
  at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (System.IntPtr jobject, System.IntPtr jclass, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x00015] in <d706cf8faf5542949900cf6d57864528>:0 
  at Android.Runtime.JNIEnv.FinishCreateInstance (System.IntPtr instance, System.IntPtr jclass, System.IntPtr constructorId, Android.Runtime.JValue* constructorParameters) [0x00008] in <d706cf8faf5542949900cf6d57864528>:0 
  at Uno.UI.NativeInstanceHelper.CreateNativeInstance (System.Type type, Java.Lang.Object target, Android.Content.Context context, System.Action`2[T1,T2] setInstance) [0x00033] in D:\a\1\s\src\Uno.UI\Extensions\NativeViewInstanceHelper.Android.cs:109 
  at Uno.UI.Controls.BindableView..ctor (Android.Content.Context context) [0x00023] in D:\a\1\s\src\Uno.UI\Controls\BindableView.Android.cs:51 
  at Windows.UI.Xaml.UIElement..ctor () [0x00028] in D:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.Android.cs:22 
  at Windows.UI.Xaml.FrameworkElement..ctor () [0x00021] in D:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.Android.cs:28 
  at Windows.UI.Xaml.Controls.Control..ctor () [0x00000] in D:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Control\Control.Android.cs:19 
  at Windows.UI.Xaml.Controls.ContentControl..ctor () [0x00000] in D:\a\1\s\src\Uno.UI\UI\Xaml\Controls\ContentControl\ContentControl.Android.cs:22 
  at App2.MainPage..ctor () [0x00015] in C:\Users\artem\source\repos\App2\App2\App2.Android\MainPage.xaml.cs:25 
  at App2.App..ctor () [0x0000f] in C:\Users\artem\source\repos\App2\App2\App2.Android\App.xaml.cs:13 
  at App2.Droid.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x0002f] in C:\Users\artem\source\repos\App2\App2\App2.Android\MainActivity.cs:24 
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <d706cf8faf5542949900cf6d57864528>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.9(intptr,intptr,intptr)
  --- End of managed Java.Lang.NullPointerException stack trace ---
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
	at android.view.ViewConfiguration.get(ViewConfiguration.java:447)
	at android.view.View.<init>(View.java:4806)
	at android.view.View.<init>(View.java:4948)
	at android.view.ViewGroup.<init>(ViewGroup.java:659)
	at android.view.ViewGroup.<init>(ViewGroup.java:655)
	at android.view.ViewGroup.<init>(ViewGroup.java:651)
	at android.view.ViewGroup.<init>(ViewGroup.java:647)
	at Uno.UI.UnoViewGroup.<init>(UnoViewGroup.java:69)
	at crc6485314a2a4d7fccfc.BindableView.<init>(BindableView.java:33)
	at crc64122dcf5ad656876d.UIElement.<init>(UIElement.java:24)
	at crc64122dcf5ad656876d.FrameworkElement.<init>(FrameworkElement.java:28)
	at crc64a5a37c43dff01024.Control.<init>(Control.java:20)
	at crc64a5a37c43dff01024.ContentControl.<init>(ContentControl.java:20)
	at crc642b789bcd66d3f4e3.MainActivity.n_onCreate(Native Method)
	at crc642b789bcd66d3f4e3.MainActivity.onCreate(MainActivity.java:30)
	at android.app.Activity.performCreate(Activity.java:7136)
	at android.app.Activity.performCreate(Activity.java:7127)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

## Expected behavior
In an Android app built with Xamarin.Forms we should be able to use Uno.UI controls along with other Xamarin.Forms controls and native Android controls.

## How to reproduce it (as minimally and precisely as possible)
1. Create new Xamarin.Forms Android app from a blank template
2. Move .xaml files from .NetStandard library to Android project
3. Add Uno.UI latest stable NuGet to Android project
4. Add XAML or code-behind as in [these steps](https://platform.uno/docs/articles/howto-use-uno-in-xamarin-forms.html) to MainPage
5. Add Mono.Android.Export.dll (won't build without it)
6. Run

[App2.zip](https://github.com/unoplatform/uno/files/4098025/App2.zip)

## Environment

Nuget Package:
Uno.UI 2.0.530 (tried older stable versions with same result)
Xamarin.Forms 4.3.0.908675 (tried newest 4.4.0.991477+451-sha.6fab98710-azdo.3372777, and older stable versions from v3 with same result)

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: 16.4.3)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report! Which Android API level is your android head using ?

**Comment by artemious7** [comment]
It's API 28 (9.0)

**Comment by jeromelaban** [comment]
Thanks. So it looks like :
https://github.com/unoplatform/uno/blob/963ab1f8fecc285dd547af4c9a9349bc84b388bf/src/Uno.UI/UI/Xaml/UIElement.Android.cs#L48

Is providing a null value, which is causing the constructor to fail, most likely because:
https://github.com/unoplatform/uno/blob/5585c5878292d625acd008c423e3231fdbe64cfb/src/Uno.UWP/ContextHelper.cs#L40

is never called.

You may want to try to set the `Current` property to your current activity, and see where that leads.

**Comment by artemious7** [comment]
Have set it, but now it gives me 
```
System.NullReferenceException: Object reference not set to an instance of an object.
01-22 16:14:02.491 E/mono-rt (14413):   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.37(intptr,intptr)
01-22 16:14:02.491 E/mono-rt (14413):   at (wrapper native-to-managed) Android.Runtime.DynamicMethodNameCounter.37(intptr,intptr)
```
Here's full log

[log.zip](https://github.com/unoplatform/uno/files/4098331/log.zip)

**Comment by jeromelaban** [comment]
Thanks for the log.

There's an exception happening before this null reference, and you'll need to enable the Uno logging to see it:

https://github.com/unoplatform/uno/blob/963ab1f8fecc285dd547af4c9a9349bc84b388bf/src/SolutionTemplate/UnoSolutionTemplate/Shared/App.xaml.cs#L32

**Comment by artemious7** [comment]
Should I just add this line
`			ConfigureFilters(global::Uno.Extensions.LogExtensionPoint.AmbientLoggerFactory);`
to App constructor? It says there's no ConfigureFilters method in current context

![image](https://user-images.githubusercontent.com/16724889/72912820-df33b600-3d44-11ea-88eb-8e600ecc435e.png)

**Comment by jeromelaban** [comment]
The rest of that method is in the file I mentioned. You may also need to install those:

https://github.com/unoplatform/uno/blob/0e1931c3e9fe0024ffdb7418bd9b7aca183880e7/src/SolutionTemplate/UnoSolutionTemplate/Droid/UnoQuickStart.Droid.csproj#L67-L68

**Comment by artemious7** [comment]
[log2.zip](https://github.com/unoplatform/uno/files/4098472/log2.zip)

**Comment by jeromelaban** [comment]
This is most likely related to missing initialization that is automatically done through the App.InitializeComponent().

You may need to call this:
```
Windows.UI.Xaml.GenericStyles.Initialize();
Windows.ApplicationModel.Resources.ResourceLoader.DefaultLanguage = "en-US";
Windows.ApplicationModel.Resources.ResourceLoader.AddLookupAssembly(System.Reflection.Assembly.Load("Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null"));
```
during the app initialization.

**Comment by artemious7** [comment]
Didn't help :-(
[log3.zip](https://github.com/unoplatform/uno/files/4099710/log3.zip)

**Comment by artemious7** [comment]
I found a way to make it work!

**Comment by artemious7** [comment]
Putting this in the Xamarin Forms App constructor is enough

```
ContextHelper.Current = Xamarin.Essentials.Platform.CurrentActivity;
new Windows.UI.Xaml.Application(); //we have to create an instance of this type, otherwise Uno.UI controls won't work in Xamarin Forms
```

Also, you won't see anything on the screen if you use this XAML

```
  <StackLayout Margin="50">
        <Label Text="Xamarin.Forms Label"  />
        <ContentView x:Name="myContent"/>
    </StackLayout>
```

here, ContentView's size would be 0 because it's in StackLayout. Change the StackLayout to Grid, and you'll see it.

**Comment by jingliancui** [comment]
@artemious7 Is it obeolete way now?
`#if __ANDROID__` feature seem like not work at .net standard (Forms layer).
Want help here:
https://github.com/unoplatform/uno/issues/4065

**Comment by SnowPowerCore** [comment]
+1, seems that instructions doesn't work :(
