### ISSUE TITLE
TreeView control (C++-based, from Windows Universal Samples) can't be used in WASM app

### ISSUE THREAD

**Issue by danielkornev** [unoplatform/uno#3]
Here's the control code: 
https://github.com/Microsoft/Windows-universal-samples/tree/win10-1709/Samples/XamlTreeView/cpp/Control

Here's the error during building:

```Severity	Code	Description	Project	File	Line	Suppression State
Error		Generation failed for aa. System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: The type {using:TreeViewControl}IntegerToIndentationConverter could not be found
   at ad.a(ar A_0)
   at ad.q(ar A_0)
   at ad.a(IIndentedStringBuilder A_0, Boolean A_1, IEnumerable`1 A_2)
   at ad.a(IIndentedStringBuilder A_0, Dictionary`2 A_1, Boolean A_2)
   at ad.c()
   at ad.e()
   at z.a.e(ac A_0)
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorResults.GetElement(Int32 index)
   at System.Linq.Parallel.QueryResults`1.get_Item(Int32 index)
   at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.SpoolingTask.SpoolStopAndGo[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, SynchronousChannel`1[] channels, TaskScheduler taskScheduler)
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.QueryOpeningEnumerator`1.OpenQuery()
   at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
   at System.Linq.ParallelEnumerable.ToList[TSource](ParallelQuery`1 source)
   at z.c()
   at aa.Execute(SourceGeneratorContext context)
   at Uno.SourceGeneration.Host.SourceGeneratorHost.<>c__DisplayClass2_0.<Generate>b__13(ValueTuple`2 generatorDef) in C:\projects\uno-sourcegeneration\src\Uno.SourceGenerationHost.Shared\SourceGeneratorHost.cs:line 150
---> (Inner Exception #0) System.InvalidOperationException: The type {using:TreeViewControl}IntegerToIndentationConverter could not be found
   at ad.a(ar A_0)
   at ad.q(ar A_0)
   at ad.a(IIndentedStringBuilder A_0, Boolean A_1, IEnumerable`1 A_2)
   at ad.a(IIndentedStringBuilder A_0, Dictionary`2 A_1, Boolean A_2)
   at ad.c()
   at ad.e()
   at z.a.e(ac A_0)
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorResults.GetElement(Int32 index)
   at System.Linq.Parallel.QueryResults`1.get_Item(Int32 index)
   at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
	DomainEditor.Wasm	C:\Users\danielko\.nuget\packages\uno.sourcegenerationtasks\1.22.0-dev.32\build\net45\Uno.SourceGenerationTasks.targets	94	
```

**Comment by danielkornev** [comment]
I'm updating VS 2017 to 15.7, and will later update Windows to 1803 to see whether the built-in TreeView control will work or not

**Comment by weitzhandler** [comment]
Very essential control, please prioritize. Thanks!

**Comment by MartinZikmund** [comment]
Can we close this one in favor of #2771 ?

**Comment by jeromelaban** [comment]
Let's close this one indeed.
