### ISSUE TITLE
[Wasm] WebSockets close runtime error

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#3397]
## Current behavior

The following error may happen when closing a WebSocket:

```
dotnet.js:1482 Uncaught RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.
    at abort (package_8323d23ff694b5b242deecc9c1d5e40049d782a1/dotnet.js:1482:9)
    at _abort (package_8323d23ff694b5b242deecc9c1d5e40049d782a1/dotnet.js:6301:7)
    at free (package_8323d23ff694b5b242deecc9c1d5e40049d782a1/dotnet.wasm:wasm-function[149188]:0x34ddeb2)
    at Object.call_method (package_8323d23ff694b5b242deecc9c1d5e40049d782a1/dotnet.js:8455:13)
    at Object.dispatchClosedMethod (package_8323d23ff694b5b242deecc9c1d5e40049d782a1/dotnet.js:8533:22)
    at WebSocket.webSocket.onclose (package_8323d23ff694b5b242deecc9c1d5e40049d782a1/WasmWebSockets.js:35:30)
```

## Expected behavior

Closing a WebSocket does not fail.

## How to reproduce it (as minimally and precisely as possible)

TBD

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
This issue is fixed in https://www.nuget.org/packages/Uno.Wasm.WebSockets/1.0.0
