### ISSUE TITLE
Mono.Linker.MarkException in Wasm with ReactiveUI

### ISSUE THREAD

**Issue by ushenkodmitry** [unoplatform/uno#3651]
## Current behavior

Error building WASM project, created with Uno templates.
```
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8453782] Fatal error in Mono IL Linker
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8461295]
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473299] Unhandled Exception: Mono.Linker.MarkException: Error processing method: 'System.Void ReactiveUI.Uno.GlobalStaticResources::Initialize()' in assembly: 'ReactiveUI.Uno.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Uno.UI.Wasm.GlobalStaticResources::Initialize()
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473432] at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473452] at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473467] at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473479] at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473491] at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473502] at Mono.Linker.Steps.MarkStep.ProcessQueue()
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473513] --- End of inner exception stack trace ---
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473524] at Mono.Linker.Steps.MarkStep.ProcessQueue()
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473534] at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473553] at Mono.Linker.Steps.MarkStep.Process()
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473564] at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473575] at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473717] at Mono.Linker.Pipeline.Process(LinkContext context)
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473733] at Mono.Linker.Driver.Run(ILogger customLogger)
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473744] at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473756] at Mono.Linker.Driver.Main(String[] args)
Uno.Wasm.Bootstrap.targets(126,2): error : System.Exception: Failed to execute the linker
Uno.Wasm.Bootstrap.targets(126,2): error : at Uno.Wasm.Bootstrap.ShellTask_va92f3a69a92510bbb7feabd262d39abbfb9e137e.RunPackager() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 709
Uno.Wasm.Bootstrap.targets(126,2): error : at Uno.Wasm.Bootstrap.ShellTask_va92f3a69a92510bbb7feabd262d39abbfb9e137e.Execute() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 182
```

## Expected behavior

All projects in solution are built successfully.

## How to reproduce it (as minimally and precisely as possible)

1. Create new solution in VS2019 using Uno template
2. Add latest ReactiveUI.Uno package and update all Uno dependencies to the latest (include prerelease versions)
3. Build
## Environment

Nuget Package:
```
<PackageReference Include="ReactiveUI.Uno" Version="11.5.1" />
    <PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI.Controls" Version="6.1.0-build.186.g928c99f74d" />
    <PackageReference Include="Uno.UI.RemoteControl" Version="3.0.0-dev.1117" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.UI.WebAssembly" Version="3.0.0-dev.1117" />
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="1.4.0-dev.14" />
    <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="1.4.0-dev.14" />
```
Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

Same bug request was first created in [ReactiveUI](https://github.com/reactiveui/ReactiveUI/issues/2462) repo

**Comment by jeromelaban** [comment]
Thank you for the report. This is an expected error that is caused by breaking changes that were introduced in Uno 3.0.

Fixing the issue implies having a more recent build of ReactiveUI that targets Uno.UI 3.0.

**Comment by ushenkodmitry** [comment]
Hello again,
this may be closed, as ReactiveUI updated dependency on Uno to the latest. No errors on build.

**Comment by jeromelaban** [comment]
Thanks for the update!
