### ISSUE TITLE
Assigning a property on a user control via xaml causes a build error

### ISSUE THREAD

**Issue by kyleaj** [unoplatform/uno#4080]
## Current behavior

Setting a public property on a custom control causes the build to fail for Uno targets, though it does succeed for UWP.

## Expected behavior

Build succeeds, and the property is set correctly.

## How to reproduce it (as minimally and precisely as possible)

Minimal Repro Project: https://github.com/kyleaj/UnoBuildDebug

The project contains a new control extending UserControl, called CustomControl, that contains a public property, Text. This property is set in MainPage.xaml.

Build the project for UWP and run; the build succeeds and the correct text appears.
Build the project for Droid or WASM; the build fails.

## Workaround

Set the property value in the code-behind file.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
Uno.UI: 3.0.12

Affected platform(s):

- [ ] iOS
- [X] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [x] Build tasks
- [ ] Solution Templates

Other platforms may be affected. I was only able to build for Android and WebAssembly.

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: 16.7.3)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by kyleaj** [comment]
Here's the full build error:

Generation failed: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Generation failed for Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator. System.Exception: Processing failed for file C:\Users\Kyle\source\repos\UnoBuildDebug\UnoBuildDebug\UnoBuildDebug.Shared\MainPage.xaml ---> System.InvalidOperationException: An error occurred when processing Page at line 1:2 (C:\Users\Kyle\source\repos\UnoBuildDebug\UnoBuildDebug\UnoBuildDebug.Shared\MainPage.xaml) : An error occurred when processing Grid at line 10:6 (C:\Users\Kyle\source\repos\UnoBuildDebug\UnoBuildDebug\UnoBuildDebug.Shared\MainPage.xaml) : Object reference not set to an instance of an object. ---> System.InvalidOperationException: An error occurred when processing Grid at line 10:6 (C:\Users\Kyle\source\repos\UnoBuildDebug\UnoBuildDebug\UnoBuildDebug.Shared\MainPage.xaml) : Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.SourceIsAttachedProperty(INamedTypeSymbol type, String name) in C:\agent\_work\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.Reflection.cs:line 518
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildLiteralProperties(IIndentedStringBuilder writer, XamlObjectDefinition objectDefinition, String closureName) in C:\agent\_work\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 4051
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildChild(IIndentedStringBuilder writer, XamlMemberDefinition owner, XamlObjectDefinition xamlObjectDefinition, String outerClosure) in C:\agent\_work\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 4477
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildProperties(IIndentedStringBuilder writer, XamlObjectDefinition topLevelControl, Boolean isInline, Boolean returnsContent, String closureName) in C:\agent\_work\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 1712
   --- End of inner exception stack trace ---
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildProperties(IIndentedStringBuilder writer, XamlObjectDefinition topLevelControl, Boolean isInline, Boolean returnsContent, String closureName) in C:\agent\_work\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 1838
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildChild(IIndentedStringBuilder writer, XamlMemberDefinition owner, XamlObjectDefinition xamlObjectDefinition, String outerClosure) in C:\agent\_work\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 4479
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildProperties(IIndentedStringBuilder writer, XamlObjectDefinition topLevelControl, Boolean isInline, Boolean returnsContent, String closureName) in C:\agent\_work\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 1801
   --- End of inner exception stack trace ---
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildProperties(IIndentedStringBuilder writer, XamlObjectDefinition topLevelControl, Boolean isInline, Boolean returnsContent, String closureName) in C:\agent\_work\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 1838
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildGenericControlInitializerBody(IndentedStringBuilder writer, XamlObjectDefinition topLevelControl, Boolean isDirectUserControlChild) in C:\agent\_work\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 569
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.InnerGenerateFile() in C:\agent\_work\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 330
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GenerateFile() in C:\agent\_work\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 247
   --- End of inner exception stack trace ---
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GenerateFile() in C:\agent\_work\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 251
   at Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGeneration.<>c__DisplayClass35_0.<Generate>b__1(XamlFileDefinition file) in C:\agent\_work\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlCodeGeneration.cs:line 249
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGeneration.Generate() in C:\agent\_work\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlCodeGeneration.cs:line 289
   at Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator.Execute(SourceGeneratorContext context) in C:\agent\_work\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlCodeGenerator.cs:line 22
   at Uno.SourceGeneration.Host.SourceGeneratorEngine.<>c__DisplayClass4_1.<Generate>b__13(ValueTuple`2 generatorDef) in D:\a\1\s\src\Uno.SourceGeneration.Engine.Shared\SourceGeneratorEngine.cs:line 187
   at Uno.SourceGeneration.Host.SourceGeneratorEngine.<>c__DisplayClass4_1.<Generate>b__13(ValueTuple`2 generatorDef) in D:\a\1\s\src\Uno.SourceGeneration.Engine.Shared\SourceGeneratorEngine.cs:line 204
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---

Server stack trace: 
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.ScanQueryOperator`1.ScanEnumerableQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.ExecuteAndGetResultsAsArray()
   at Uno.SourceGeneration.Host.SourceGeneratorEngine.Generate() in D:\a\1\s\src\Uno.SourceGeneration.Engine.Shared\SourceGeneratorEngine.cs:line 166
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Uno.SourceGeneratorTasks.RemoteSourceGeneratorEngine.Generate(RemotableLogger2 logger, BuildEnvironment environment)
   at Uno.SourceGeneration.Host.Server.GenerationServerHost.GenerateForCollection(EnvironmentPool collection, BuildEnvironment environment) in D:\a\1\s\src\Uno.SourceGeneration.Host\Server\GenerationServerHost.netframework.cs:line 61
   at Uno.SourceGeneration.Host.Server.GenerationServerHost.RunGeneration(RunRequest request, CancellationToken cancellationToken) in D:\a\1\s\src\Uno.SourceGeneration.Host\Server\GenerationServerHost.cs:line 73
---> (Inner Exception #0) System.InvalidOperationException: Generation failed for Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator. System.Exception: Processing failed for file C:\Users\Kyle\source\repos\UnoBuildDebug\UnoBuildDebug\UnoBuildDebug.Shared\MainPage.xaml ---> System.InvalidOperationException: An error occurred when processing Page at line 1:2 (C:\Users\Kyle\source\repos\UnoBuildDebug\UnoBuildDebug\UnoBuildDebug.Shared\MainPage.xaml) : An error occurred when processing Grid at line 10:6 (C:\Users\Kyle\source\repos\UnoBuildDebug\UnoBuildDebug\UnoBuildDebug.Shared\MainPage.xaml) : Object reference not set to an instance of an object. ---> System.InvalidOperationException: An error occurred when processing Grid at line 10:6 (C:\Users\Kyle\source\repos\UnoBuildDebug\UnoBuildDebug\UnoBuildDebug.Shared\MainPage.xaml) : Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.SourceIsAttachedProperty(INamedTypeSymbol type, String name) in C:\agent\_work\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.Reflection.cs:line 518
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildLiteralProperties(IIndentedStringBuilder writer, XamlObjectDefinition objectDefinition, String closureName) in C:\agent\_work\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 4051
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildChild(IIndentedStringBuilder writer, XamlMemberDefinition owner, XamlObjectDefinition xamlObjectDefinition, String outerClosure) in C:\agent\_work\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 4477
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildProperties(IIndentedStringBuilder writer, XamlObjectDefinition topLevelControl, Boolean isInline, Boolean returnsContent, String closureName) in C:\agent\_work\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 1712
   --- End of inner exception stack trace ---
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildProperties(IIndentedStringBuilder writer, XamlObjectDefinition topLevelControl, Boolean isInline, Boolean returnsContent, String closureName) in C:\agent\_work\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 1838
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildChild(IIndentedStringBuilder writer, XamlMemberDefinition owner, XamlObjectDefinition xamlObjectDefinition, String outerClosure) in C:\agent\_work\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 4479
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildProperties(IIndentedStringBuilder writer, XamlObjectDefinition topLevelControl, Boolean isInline, Boolean returnsContent, String closureName) in C:\agent\_work\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 1801
   --- End of inner exception stack trace ---
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildProperties(IIndentedStringBuilder writer, XamlObjectDefinition topLevelControl, Boolean isInline, Boolean returnsContent, String closureName) in C:\agent\_work\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 1838
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildGenericControlInitializerBody(IndentedStringBuilder writer, XamlObjectDefinition topLevelControl, Boolean isDirectUserControlChild) in C:\agent\_work\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 569
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.InnerGenerateFile() in C:\agent\_work\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 330
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GenerateFile() in C:\agent\_work\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 247
   --- End of inner exception stack trace ---
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GenerateFile() in C:\agent\_work\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 251
   at Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGeneration.<>c__DisplayClass35_0.<Generate>b__1(XamlFileDefinition file) in C:\agent\_work\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlCodeGeneration.cs:line 249
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGeneration.Generate() in C:\agent\_work\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlCodeGeneration.cs:line 289
   at Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator.Execute(SourceGeneratorContext context) in C:\agent\_work\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlCodeGenerator.cs:line 22
   at Uno.SourceGeneration.Host.SourceGeneratorEngine.<>c__DisplayClass4_1.<Generate>b__13(ValueTuple`2 generatorDef) in D:\a\1\s\src\Uno.SourceGeneration.Engine.Shared\SourceGeneratorEngine.cs:line 187
   at Uno.SourceGeneration.Host.SourceGeneratorEngine.<>c__DisplayClass4_1.<Generate>b__13(ValueTuple`2 generatorDef) in D:\a\1\s\src\Uno.SourceGeneration.Engine.Shared\SourceGeneratorEngine.cs:line 204
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.Tasks.Task.Execute()<---	UnoBuildDebug.Droid

**Comment by kazo0** [comment]
Looks like this is specifically when you have write-only properties. Line 544 of `XamlFileGenerator.Reflection.cs` tries to check if the `GetMethod` is static which is throwing a null-ref

**Comment by kyleaj** [comment]
Thanks @kazo0 !
