### ISSUE TITLE
[Wasm][PG-AOT] assertion at mono/mono/mini/exceptions-wasm.c:52

### ISSUE THREAD

**Issue by alove-kahua** [unoplatform/uno#4507]
## Current behavior

Getting an exception while running with PG-AOT:

Stacktrace: 
:56592/package_e6b18117f857aa207e0fc9b9970917219d6f44db/dotnet.js:1540 Error
    at 2237 (:56592/package_e6b18117f857aa207e0fc9b9970917219d6f44db/dotnet.js:1540)
    at _emscripten_asm_const_int (:56592/package_e6b18117f857aa207e0fc9b9970917219d6f44db/dotnet.js:6540)
    at wasm_logger (:56592/<anonymous>:wasm-function[234]:0x29067)
    at eglib_log_adapter (:56592/<anonymous>:wasm-function[45220]:0x1ad50a5)
    at monoeg_g_logstr (:56592/<anonymous>:wasm-function[45722]:0x1ae28cb)
    at monoeg_g_logv_nofree (:56592/<anonymous>:wasm-function[45720]:0x1ae2876)
    at monoeg_g_logv (:56592/<anonymous>:wasm-function[45719]:0x1ae282c)
    at monoeg_g_log (:56592/<anonymous>:wasm-function[45723]:0x1ae28eb)
    at g_log_disabled (:56592/<anonymous>:wasm-function[45724]:0x1ae291d)
    at mono_arch_unwind_frame (:56592/<anonymous>:wasm-function[38565]:0x1a028f8)
:56592/package_e6b18117f857aa207e0fc9b9970917219d6f44db/dotnet.js:2181 ﻿/__w/1/s/mono/mono/mini/exceptions-wasm.c:52 <disabled>
put_char @ :56592/package_e6b18117f857aa207e0fc9b9970917219d6f44db/dotnet.js:2181
:56592/package_e6b18117f857aa207e0fc9b9970917219d6f44db/dotnet.js:1344 undefined
abort @ :56592/package_e6b18117f857aa207e0fc9b9970917219d6f44db/dotnet.js:1344
Uno.UI.js:97 Unhandled dispatcher exception: RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info. (RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.
    at abort (http://localhost:56592/package_e6b18117f857aa207e0fc9b9970917219d6f44db/dotnet.js:1354:11)
    at _abort (http://localhost:56592/package_e6b18117f857aa207e0fc9b9970917219d6f44db/dotnet.js:6505:7)
    at wasm_logger (<anonymous>:wasm-function[234]:0x2908f)
    at eglib_log_adapter (<anonymous>:wasm-function[45220]:0x1ad50a5)
    at monoeg_g_logstr (<anonymous>:wasm-function[45722]:0x1ae28cb)
    at monoeg_g_logv_nofree (<anonymous>:wasm-function[45720]:0x1ae2876)
    at monoeg_g_logv (<anonymous>:wasm-function[45719]:0x1ae282c)
    at monoeg_g_log (<anonymous>:wasm-function[45723]:0x1ae28eb)
    at g_log_disabled (<anonymous>:wasm-function[45724]:0x1ae291d)
    at mono_arch_unwind_frame (<anonymous>:wasm-function[38565]:0x1a028f8))

![image](https://user-images.githubusercontent.com/64799801/98964930-666e3800-24d7-11eb-9ccb-57cae33b6781.png)

## Expected behavior

Runs without error.

## How to reproduce it (as minimally and precisely as possible)

Generate profile.
Include profile and execute with InterpreterAndAot mode.
We are making an HttpClient call to sign-in, but not sure if that is the cause.

## Workaround

Don't use PG-AOT.

## Environment

Nuget Package:

- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Could you indicate which version of the Uno.Wasm.bootstrap and Uno.UI you were using to get this exception ? Thanks!

**Comment by alove-kahua** [comment]
Take your pick.  I've tried them all.  UI 3.1.6, 3.2, or 3.3.  Bootstrap 1.3.5, 1.4, and 2.0.  I can't find a combo that works for me.
