### ISSUE TITLE
Unable to run a fresh new project on linux

### ISSUE THREAD

**Issue by atrauzzi** [unoplatform/uno#4669]
## Current behavior

New project created via CLI on linux, .net 5 appears to have issues running.

## Expected behavior

Just a simple startup of the default project template.

## How to reproduce it (as minimally and precisely as possible)

```
mkdir gerty
cd gerty
dotnet new unoapp
cd gerty.Skia.Gtk 
dotnet run
```
![image](https://user-images.githubusercontent.com/115199/101265946-8f699d80-3710-11eb-9e68-aa78ab6b79d1.png)

## Anything else we need to know?

Everything was performed command line, but it's worth noting that I intend on using Rider on linux. I'm running on pop!_os (Ubuntu) 20.10 with snaps enabled. Using the official .net core snap.

**Comment by jeromelaban** [comment]
Thanks for trying Uno! 

The message in question explain that you need to have the .NET Core 3.1 SDK installed to get the project compiled. 

You have two choices, either:
- Install .NET Core 3.1 SDK: https://platform.uno/docs/articles/get-started-with-linux.html#setting-up-for-linux
- Update your project to use .NET 5 (change `netcoreapp3.1` to `net5.0` in your `gerty.Skia.Gtk` project)

**Comment by atrauzzi** [comment]
Updated to `net5.0`, next error is this in the template:

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'Gtk.Application' threw an exception.
 ---> System.DllNotFoundException: Gtk: libgtk-3-0.dll, libgtk-3.so.0, libgtk-3.0.dylib, gtk-3.dll
   at GLibrary.Load(Library library)
   at Gtk.Application..cctor()
   --- End of inner exception stack trace ---
   at Gtk.Application.Init()
   at Uno.UI.Runtime.Skia.GtkHost.Run()
   at gerty.Skia.Gtk.Program.Main(String[] args) in /home/atrauzzi/Development/atrauzzi/gerty/gerty.Skia.Gtk/Program.cs:line 19
```

**Comment by jeromelaban** [comment]
Thanks for the update. It looks like you're missing the installation of GTK3. Did you install it through apt ?

**Comment by atrauzzi** [comment]
This version of pop!_os uses gnome 3.38.1.  Safe to assume I have GTK? :laughing: 

```
apt list --installed | grep libgtk

...
libgtk-3-0/groovy,now 3.24.23-1ubuntu1 amd64 [installed,automatic]
libgtk-3-bin/groovy,now 3.24.23-1ubuntu1 amd64 [installed,automatic]
libgtk-3-common/groovy,groovy,now 3.24.23-1ubuntu1 all [installed,automatic]
libgtk2.0-0/groovy,now 2.24.32-4ubuntu4 amd64 [installed,automatic]
libgtk2.0-bin/groovy,now 2.24.32-4ubuntu4 amd64 [installed,automatic]
libgtk2.0-common/groovy,groovy,now 2.24.32-4ubuntu4 all [installed,automatic
...
```

**Comment by jeromelaban** [comment]
Thanks! What's the result of `whereis libgtk-3.so.0` ?

**Comment by atrauzzi** [comment]
```
whereis libgtk-3.so.0
libgtk-3.so: /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
```

**Comment by jeromelaban** [comment]
We'll search for the resolution our side, but in the meantime could you try installing the GTK dev package as well ? Could be ubuntu 20.04 related.

```
sudo apt-get install libgtk-3-dev
```

**Comment by atrauzzi** [comment]
Installed, and then got:

```
/home/atrauzzi/Development/atrauzzi/gerty/gerty.Skia.Gtk/gerty.Skia.Gtk.csproj : warning NU1701: Package 'SkiaSharp.Views 2.80.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.
/home/atrauzzi/Development/atrauzzi/gerty/gerty.Skia.Gtk/gerty.Skia.Gtk.csproj : warning NU1701: Package 'SkiaSharp.Views 2.80.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.
Unhandled exception. System.TypeInitializationException: The type initializer for 'Gtk.Application' threw an exception.
 ---> System.DllNotFoundException: Gtk: libgtk-3-0.dll, libgtk-3.so.0, libgtk-3.0.dylib, gtk-3.dll
   at GLibrary.Load(Library library)
   at Gtk.Application..cctor()
   --- End of inner exception stack trace ---
   at Gtk.Application.Init()
   at Uno.UI.Runtime.Skia.GtkHost.Run()
   at gerty.Skia.Gtk.Program.Main(String[] args) in /home/atrauzzi/Development/atrauzzi/gerty/gerty.Skia.Gtk/Program.cs:line 19
```

**Comment by microhobby** [comment]
@atrauzzi Could you try to use .NET without snaps? As the pop!_os is derived from Ubuntu following this here (https://docs.microsoft.com/pt-br/dotnet/core/install/linux-ubuntu#2010-) shouldn't cause any issues.

Snaps use a type of containerization, I'm not sure if this is the cause but probably inside the snap container you don't have access to the host GTK dependencies. Let me know if without snaps this works.

**Comment by atrauzzi** [comment]
I recently moved back to Ubuntu 20.10, however I'm experiencing the same issue, with `dotnet` installed via apt:

![image](https://user-images.githubusercontent.com/115199/103908597-3f437980-50c8-11eb-9e01-e8de8f7c9cd6.png)

**Comment by microhobby** [comment]
@atrauzzi interesting, and the path of the lib is the same from here?

![image](https://user-images.githubusercontent.com/2633321/103911074-5abc7d80-50e4-11eb-9979-eea6d761b84b.png)

I'm using the Ubuntu 21.04 without issues so far. I will try this behavior with Ubuntu 20.10 in a Docker container to see if I can reproduce

**Comment by atrauzzi** [comment]
This look okay to you?

![image](https://user-images.githubusercontent.com/115199/103911772-11603400-50cc-11eb-857c-639a40712903.png)

**Comment by microhobby** [comment]
@atrauzzi could you also share the return from `ls -lah /usr/lib/x86_64-linux-gnu/libgtk*`:

![image](https://user-images.githubusercontent.com/2633321/103914429-93f6ec80-50e8-11eb-980a-34ab4a944d3f.png)

and also from `ldd /usr/lib/x86_64-linux-gnu/libgtk-3.so.0` (this must have many lines, better send text instead image)

thanks

**Comment by microhobby** [comment]
I can't reproduce on my side using Ubuntu 20.10 (using Docker container and remote X Server) 🤷‍♂️

![image](https://user-images.githubusercontent.com/2633321/103921428-4468ee80-50f1-11eb-8ff7-ff1e9cfb9ae5.png)

**Comment by atrauzzi** [comment]
Here's the output from those two commands:

```
~ ▓▒░                                                  ░▒▓ 13:32:57
❯ ls -lah /usr/lib/x86_64-linux-gnu/libgtk*~
zsh: no matches found: /usr/lib/x86_64-linux-gnu/libgtk*~

~ ▓▒░                                                  ░▒▓ 13:32:59
❯ ldd /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
	linux-vdso.so.1 (0x00007ffca05a0000)
	libgdk-3.so.0 => /lib/x86_64-linux-gnu/libgdk-3.so.0 (0x00007f7a7df44000)
	libgmodule-2.0.so.0 => /lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007f7a7df3e000)
	libpangocairo-1.0.so.0 => /lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x00007f7a7df2c000)
	libX11.so.6 => /lib/x86_64-linux-gnu/libX11.so.6 (0x00007f7a7ddee000)
	libXi.so.6 => /lib/x86_64-linux-gnu/libXi.so.6 (0x00007f7a7dddc000)
	libXfixes.so.3 => /lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f7a7ddd4000)
	libcairo-gobject.so.2 => /lib/x86_64-linux-gnu/libcairo-gobject.so.2 (0x00007f7a7ddc6000)
	libcairo.so.2 => /lib/x86_64-linux-gnu/libcairo.so.2 (0x00007f7a7dca3000)
	libgdk_pixbuf-2.0.so.0 => /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x00007f7a7dc7c000)
	libatk-1.0.so.0 => /lib/x86_64-linux-gnu/libatk-1.0.so.0 (0x00007f7a7dc52000)
	libatk-bridge-2.0.so.0 => /lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0 (0x00007f7a7dc1a000)
	libepoxy.so.0 => /lib/x86_64-linux-gnu/libepoxy.so.0 (0x00007f7a7dae7000)
	libfribidi.so.0 => /lib/x86_64-linux-gnu/libfribidi.so.0 (0x00007f7a7dac8000)
	libgio-2.0.so.0 => /lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007f7a7d8e1000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7a7d792000)
	libpangoft2-1.0.so.0 => /lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x00007f7a7d778000)
	libpango-1.0.so.0 => /lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x00007f7a7d725000)
	libgobject-2.0.so.0 => /lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f7a7d6ca000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f7a7d596000)
	libharfbuzz.so.0 => /lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f7a7d4b5000)
	libfontconfig.so.1 => /lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f7a7d46e000)
	libfreetype.so.6 => /lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f7a7d3ab000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7a7d389000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7a7d19f000)
	libXinerama.so.1 => /lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007f7a7d198000)
	libXrandr.so.2 => /lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007f7a7d18b000)
	libXcursor.so.1 => /lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007f7a7d17e000)
	libXcomposite.so.1 => /lib/x86_64-linux-gnu/libXcomposite.so.1 (0x00007f7a7d179000)
	libXdamage.so.1 => /lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007f7a7d174000)
	libxkbcommon.so.0 => /lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007f7a7d132000)
	libwayland-cursor.so.0 => /lib/x86_64-linux-gnu/libwayland-cursor.so.0 (0x00007f7a7d125000)
	libwayland-egl.so.1 => /lib/x86_64-linux-gnu/libwayland-egl.so.1 (0x00007f7a7d120000)
	libwayland-client.so.0 => /lib/x86_64-linux-gnu/libwayland-client.so.0 (0x00007f7a7d10f000)
	libXext.so.6 => /lib/x86_64-linux-gnu/libXext.so.6 (0x00007f7a7d0fa000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f7a7d0ef000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7a7d0e7000)
	libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f7a7d0bd000)
	libpixman-1.so.0 => /lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007f7a7d016000)
	libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f7a7cfdd000)
	libxcb-shm.so.0 => /lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007f7a7cfd8000)
	libxcb-render.so.0 => /lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007f7a7cfc9000)
	libXrender.so.1 => /lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f7a7cdbd000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f7a7cda0000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f7a7cd4e000)
	libatspi.so.0 => /lib/x86_64-linux-gnu/libatspi.so.0 (0x00007f7a7cd16000)
	libmount.so.1 => /lib/x86_64-linux-gnu/libmount.so.1 (0x00007f7a7ccb8000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f7a7cc8b000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f7a7cc70000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7a7e837000)
	libthai.so.0 => /lib/x86_64-linux-gnu/libthai.so.0 (0x00007f7a7cc65000)
	libffi.so.8 => /lib/x86_64-linux-gnu/libffi.so.8 (0x00007f7a7cc59000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f7a7cbe6000)
	libgraphite2.so.3 => /lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f7a7cbb7000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f7a7cb89000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f7a7cb80000)
	libbrotlidec.so.1 => /lib/x86_64-linux-gnu/libbrotlidec.so.1 (0x00007f7a7cb72000)
	libXau.so.6 => /lib/x86_64-linux-gnu/libXau.so.6 (0x00007f7a7cb6c000)
	libXdmcp.so.6 => /lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f7a7cb62000)
	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007f7a7caae000)
	libblkid.so.1 => /lib/x86_64-linux-gnu/libblkid.so.1 (0x00007f7a7ca5b000)
	libpcre2-8.so.0 => /lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007f7a7c9cb000)
	libdatrie.so.1 => /lib/x86_64-linux-gnu/libdatrie.so.1 (0x00007f7a7c9c1000)
	libbrotlicommon.so.1 => /lib/x86_64-linux-gnu/libbrotlicommon.so.1 (0x00007f7a7c99c000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f7a7c982000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f7a7c959000)
	libzstd.so.1 => /lib/x86_64-linux-gnu/libzstd.so.1 (0x00007f7a7c889000)
	liblz4.so.1 => /lib/x86_64-linux-gnu/liblz4.so.1 (0x00007f7a7c868000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f7a7c74a000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f7a7c721000)
```

**Comment by microhobby** [comment]
@atrauzzi thanks for sharing the information. I was suspecting the case that some dependency on `libgtk-3.so.0` is not being resolved, but from the `ldd` return is all there. 

The next alternative would be some dependence on the gtk dependencies not being resolved, but I really think this is unlikely to be true.

Could you do another test please? Publish the project with:

```
dotnet publish -r linux-x64
```

After that run the following command with `strace`:

```
strace bin/Debug/net5.0/linux-x64/publish/gerty.Skia.Gtk 2>&1 | grep libgtk
```

And sorry for asking for so many tests, I'm trying to understand the scenario since I couldn't reproduce on my side. Thanks!

**Comment by atrauzzi** [comment]
Oh I don't mind at all, this is very encouraging and I'm sure I'll learn plenty here, haha.

```
~/Development/atrauzzi/gerty/gerty.Skia.Gtk ▓▒░        ░▒▓ 04:59:09
❯ dotnet publish -r linux-x64
Microsoft (R) Build Engine version 16.8.0+126527ff1 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
/home/atrauzzi/Development/atrauzzi/gerty/gerty.Skia.Gtk/gerty.Skia.Gtk.csproj : warning NU1701: Package 'SkiaSharp.Views 2.80.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.
  Restored /home/atrauzzi/Development/atrauzzi/gerty/gerty.Skia.Gtk/gerty.Skia.Gtk.csproj (in 5.14 sec).
/home/atrauzzi/Development/atrauzzi/gerty/gerty.Skia.Gtk/gerty.Skia.Gtk.csproj : warning NU1701: Package 'SkiaSharp.Views 2.80.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.
  Uno.UI is using Roslyn generators
  gerty.Skia.Gtk -> /home/atrauzzi/Development/atrauzzi/gerty/gerty.Skia.Gtk/bin/Debug/net5.0/linux-x64/gerty.Skia.Gtk.dll
  gerty.Skia.Gtk -> /home/atrauzzi/Development/atrauzzi/gerty/gerty.Skia.Gtk/bin/Debug/net5.0/linux-x64/publish/

~/Development/atrauzzi/gerty/gerty.Skia.Gtk ▓▒░                       ░▒▓ 9s 04:59:23
❯ strace bin/Debug/net5.0/linux-x64/publish/gerty.Skia.Gtk 2>&1 | grep libgtk
openat(AT_FDCWD, "/snap/core18/current/lib/x86_64-linux-gnu/libgtk-3.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libgtk-3.so.0", O_RDONLY|O_CLOEXEC) = 38
openat(AT_FDCWD, "/snap/core18/current/lib/x86_64-linux-gnu/libgtk-3-0.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libgtk-3-0.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/libgtk-3-0.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/libgtk-3-0.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/libgtk-3-0.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/snap/core18/current/lib/x86_64-linux-gnu/libgtk-3.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libgtk-3.so.0", O_RDONLY|O_CLOEXEC) = 38
openat(AT_FDCWD, "/snap/core18/current/lib/x86_64-linux-gnu/libgtk-3.0.dylib", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libgtk-3.0.dylib", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/libgtk-3.0.dylib", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/libgtk-3.0.dylib", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/libgtk-3.0.dylib", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
zsh: abort (core dumped)  strace bin/Debug/net5.0/linux-x64/publish/gerty.Skia.Gtk 2>&1 | 
zsh: done                 grep libgtk

```

**Comment by microhobby** [comment]
@atrauzzi thanks, as expected the issue is not in the `libgtk-3.so.0` he is being found:

```
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libgtk-3.so.0", O_RDONLY|O_CLOEXEC) = 38
```

Ok, so the next step will be to run the `strace` without the grep (many many lines). But we will have a better clue of the root cause of the issue:

```
strace bin/Debug/net5.0/linux-x64/publish/gerty.Skia.Gtk 1> strace.log 2>&1
```

After that share with me the contents of the `strace.log`.

**Comment by atrauzzi** [comment]
It looks like it segfaults at the end of the file.

[strace.log](https://github.com/unoplatform/uno/files/5822862/strace.log)

**Comment by microhobby** [comment]
@atrauzzi yeah now it's complaining that the system doesn't have the ICU packages, please check if you have installed the:

```
sudo apt get install libicu67
```

**Comment by atrauzzi** [comment]
![image](https://user-images.githubusercontent.com/115199/104862224-6dab2b00-58f8-11eb-84f2-519f0662a4e8.png)

**Comment by microhobby** [comment]
@atrauzzi ok, 🤷‍♂️ it is also there, it's strange let me analyze the strace more calmly.

**Comment by microhobby** [comment]
@atrauzzi interesting, it finds the library, but is also looking inside `/snap/core18/current/lib/`:

```
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libicuuc.so.67", O_RDONLY|O_CLOEXEC) = 40
read(40, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\340X\6\0\0\0\0\0"..., 832) = 832
fstat(40, {st_mode=S_IFREG|0644, st_size=2001224, ...}) = 0
mmap(NULL, 2011584, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 40, 0) = 0x7ffb2368f000
mprotect(0x7ffb236f4000, 1515520, PROT_NONE) = 0
mmap(0x7ffb236f4000, 958464, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 40, 0x65000) = 0x7ffb236f4000
mmap(0x7ffb237de000, 552960, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 40, 0x14f000) = 0x7ffb237de000
mmap(0x7ffb23866000, 77824, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 40, 0x1d6000) = 0x7ffb23866000
mmap(0x7ffb23879000, 4544, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7ffb23879000
close(40)                               = 0
openat(AT_FDCWD, "/snap/core18/current/lib/x86_64-linux-gnu/libicudata.so.67", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libicudata.so.67", O_RDONLY|O_CLOEXEC) = 40
read(40, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0@\20\0\0\0\0\0\0"..., 832) = 832
fstat(40, {st_mode=S_IFREG|0644, st_size=28407424, ...}) = 0
mmap(NULL, 28409872, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 40, 0) = 0x7ffaac76c000
mmap(0x7ffaac76d000, 4096, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 40, 0x1000) = 0x7ffaac76d000
mmap(0x7ffaac76e000, 28397568, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 40, 0x2000) = 0x7ffaac76e000
mmap(0x7ffaae283000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 40, 0x1b16000) = 0x7ffaae283000
close(40)                               = 0
munmap(0x7ffb2387b000, 107003)          = 0
munmap(0x7ffb2368f000, 2011584)         = 0
munmap(0x7ffaac76c000, 28409872)        = 0
```

And apparently your system is looking for libraries first on `/snap` instead of `/usr/lib` or `/lib`. And I'm not sure why.

```
openat(AT_FDCWD, "/snap/core18/current/lib/x86_64-linux-gnu/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\16\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=14560, ...}) = 0
mmap(NULL, 2109712, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7ffb293d9000
mprotect(0x7ffb293dc000, 2093056, PROT_NONE) = 0
mmap(0x7ffb295db000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7ffb295db000
close(3)                                = 0
openat(AT_FDCWD, "/snap/core18/current/lib/x86_64-linux-gnu/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=107003, ...}) = 0
mmap(NULL, 107003, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7ffb29a08000
close(3)                               
```

The process is turning into a mixed mess of  `/snap/` and `/lib/` libraries, and I think this is coming into conflict.

**Comment by jeromelaban** [comment]
Since it seems Snap related, here's an Uno app built using Gtk: https://github.com/unoplatform/calculator/blob/uno/build/snap/snapcraft.yaml

**Comment by atrauzzi** [comment]
I used to use the dotnet snap, but I switched to the regular deb installation.  Any chance there's maybe some lingering state somewhere?

**Comment by microhobby** [comment]
I think if you ran `snap remove` it should clean up the things 🤷‍♂️, I think that in your case the `dotnet` is still running inside the snap sandbox.
