### ISSUE TITLE
Add wpf and not_wpf to the xaml prefix.

### ISSUE THREAD

**Issue by kaki104** [unoplatform/uno#4824]
## What would you like to be added:
Please add wpf and not_wpf to the xaml prefix.

## Why is this needed:
I was working on adding the Wpf.Host project to the UnoContoso appsample, because the following error occurred.

The problematic part is using:Microsoft.Toolkit.Uwp.UI.Converters. It is using.Microsoft.Toolkit.Wpf.UI.Converters in wpf, but currently uwp and wpf cannot be distinguished.

```
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" 
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:converters="using:Microsoft.Toolkit.Uwp.UI.Converters">

    <converters:BoolToVisibilityConverter x:Key="BoolToVisibilityConverter" TrueValue="Visible" FalseValue="Collapsed"/>
    <converters:BoolToVisibilityConverter x:Key="ReverseBoolToVisibilityConverter" TrueValue="Collapsed" FalseValue="Visible"/>
    <converters:BoolNegationConverter x:Key="BoolNegationConverter"/>
    <converters:StringFormatConverter  x:Key="StringFormatConverter" />

</ResourceDictionary>
```

```
Error		Generation failed: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Generation failed for Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator. System.AggregateException: One or more errors occurred. ---> System.Exception: Processing failed for file C:\Users\kaki1\source\repos\Uno.Samples\UI\UnoContoso\UnoContoso.Shared\Styles\_Converters.xaml (System.InvalidOperationException: The type {using:Microsoft.Toolkit.Uwp.UI.Converters}BoolToVisibilityConverter could not be found
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GetType(XamlType type) in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.Reflection.cs:line 835
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildExtendedProperties(IIndentedStringBuilder outerwriter, XamlObjectDefinition objectDefinition, Boolean useChildTypeForNamedElement, Boolean useGenericApply) in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 2650
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildChild(IIndentedStringBuilder writer, XamlMemberDefinition owner, XamlObjectDefinition xamlObjectDefinition, String outerClosure) in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 4828
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildResourceDictionary(IIndentedStringBuilder writer, XamlMemberDefinition resourcesRoot, Boolean isInInitializer, String dictIdentifier) in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 2355
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.InitializeAndBuildResourceDictionary(IIndentedStringBuilder writer, XamlObjectDefinition topLevelControl, Boolean setIsParsing) in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 1209
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildTopLevelResourceDictionary(IIndentedStringBuilder writer, XamlObjectDefinition topLevelControl) in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 989
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.InnerGenerateFile() in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 340
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GenerateFile() in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 283) ---> System.InvalidOperationException: The type {using:Microsoft.Toolkit.Uwp.UI.Converters}BoolToVisibilityConverter could not be found
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GetType(XamlType type) in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.Reflection.cs:line 835
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildExtendedProperties(IIndentedStringBuilder outerwriter, XamlObjectDefinition objectDefinition, Boolean useChildTypeForNamedElement, Boolean useGenericApply) in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 2650
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildChild(IIndentedStringBuilder writer, XamlMemberDefinition owner, XamlObjectDefinition xamlObjectDefinition, String outerClosure) in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 4828
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildResourceDictionary(IIndentedStringBuilder writer, XamlMemberDefinition resourcesRoot, Boolean isInInitializer, String dictIdentifier) in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 2355
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.InitializeAndBuildResourceDictionary(IIndentedStringBuilder writer, XamlObjectDefinition topLevelControl, Boolean setIsParsing) in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 1209
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildTopLevelResourceDictionary(IIndentedStringBuilder writer, XamlObjectDefinition topLevelControl) in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 989
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.InnerGenerateFile() in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 340
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GenerateFile() in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 283

```

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [x] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
Thanks for the report.

The error you are seeing is not related to the the wpf or other namespaces. You are seeing this because you have not included the community toolkit package in the YouApp.WPF project.

**Comment by davidjohnoliver** [comment]
Although it's counterintuitive, you actually do want to use `using:Microsoft.Toolkit.Uwp.UI.Converters` on Uno's WPF head, because it's really using 'UWP Xaml' and not 'WPF Xaml'.

**Comment by kaki104** [comment]
It seems that the problem occurred because I didn't know which of WPF, UWP, Uno the NuGet package needed when the Skia.Wpf project was executed.

To solve the above problem, I deleted the Wpf NuGet package from two projects, UnoContoso.Skia.Wpf and UnoContoso.Skia.Wpf.
And, by adding Uno.Microsoft.Toolkit.Uwp.UI.Controls and Uno.Microsoft.Toolkit.Uwp.UI.Controls.DataGrid NuGet package, the error that occurs in _Converters.xaml has been resolved.

**Comment by kaki104** [comment]
I'm getting an error in Prism, but I'm not sure how to fix it.

The Wpf.Host project will need to be added later if there is a solution.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0433	The type 'PrismApplication' exists in both 'Prism.DryIoc.Uno, Version=8.0.0.1909, Culture=neutral, PublicKeyToken=null' and 'Prism.DryIoc.Wpf, Version=8.0.0.1909, Culture=neutral, PublicKeyToken=40ee6c3a2184dc59'	UnoContoso.Skia.Wpf.Host	C:\Users\kaki1\source\repos\Uno.Samples\UI\UnoContoso\UnoContoso.Skia.Wpf.Host\obj\Debug\netcoreapp3.1\App.g.cs	58	Active
```
