### ISSUE TITLE
[Uno Playground] Getting error for Adaptive trigger options of snippets.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#4917]
**How to reproduce it**
1.	Open the staging Wasm by clicking the link https://playground-wasm-staging.azurewebsites.net/
2.	Choose Adaptive trigger options in snippets.
3.	 Received error and the page is blank.

**Current behavior**
 Received error and the page is blank.

**Expected behavior**
The text should display.

**Attachment:**
**Actual Result:**
![error adaptive trigger](https://user-images.githubusercontent.com/74563602/104657275-acd64380-568e-11eb-828d-13b111d465e2.png)

Expected Result:
![correct adaptive trigger](https://user-images.githubusercontent.com/74563602/104657290-b364bb00-568e-11eb-888a-ca459e0c949a.png)

Environment
Nuget Package:

Package Version(s):

Affected platform(s):
Windows

**Comment by jeromelaban** [comment]
Full stack trace:

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ManagedWeakReference'.
   at Uno.UI.DataBinding.ManagedWeakReference.get_Target()
   at Windows.UI.Xaml.TargetPropertyPath.get_Target()
   at Windows.UI.Xaml.Setter.TryGetOrCreateBindingPath(DependencyPropertyValuePrecedences precedence, IFrameworkElement owner)
   at Windows.UI.Xaml.Setter.HasSameTarget(Setter other, DependencyPropertyValuePrecedences precedence, IFrameworkElement owner)
   at Windows.UI.Xaml.VisualStateGroup.<>c__DisplayClass34_1.<GoToState>b__2(Setter o)
   at System.Linq.Enumerable.Any[Setter](IEnumerable`1 source, Func`2 predicate)
   at Windows.UI.Xaml.VisualStateGroup.GoToState(IFrameworkElement element, VisualState state, VisualState originalState, Boolean useTransitions, Action onStateChanged)
   at Windows.UI.Xaml.VisualStateGroup.RefreshStateTriggers(Boolean force)
   at Windows.UI.Xaml.VisualStateGroup.OnParentChanged(Object instance, Object key, DependencyObjectParentChangedEventArgs args)
   at Windows.UI.Xaml.DependencyObjectStore.<>c__DisplayClass118_0.<RegisterParentChangedCallback>b__0(Object s, Object _, DependencyObjectParentChangedEventArgs e)
   at Windows.UI.Xaml.DependencyObjectStore.OnParentChanged(Object previousParent, Object value)
   at Windows.UI.Xaml.DependencyObjectStore.set_Parent(Object value)
   at Windows.UI.Xaml.DependencyObjectExtensions.SetParent(Object dependencyObject, Object parent)
   at Windows.UI.Xaml.VisualStateManager.OnVisualStateGroupsChanged(Object sender, DependencyPropertyChangedEventArgs args)
   at Windows.UI.Xaml.PropertyMetadata.RaisePropertyChanged(DependencyObject source, DependencyPropertyChangedEventArgs e)
   at Windows.UI.Xaml.DependencyObjectStore.InvokeCallbacks(DependencyObject actualInstanceAlias, DependencyProperty property, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence, Boolean bypassesPropagation)
   at Windows.UI.Xaml.DependencyObjectStore.RaiseCallbacks(DependencyObject actualInstanceAlias, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence)
   at Windows.UI.Xaml.DependencyObjectStore.InnerSetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails)
   at Windows.UI.Xaml.DependencyObjectStore.SetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails)
   at Windows.UI.Xaml.DependencyObjectStore.SetValue(DependencyProperty property, Object value)
   at Windows.UI.Xaml.UIElement.SetValue(DependencyProperty dp, Object value)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.ProcessMemberElements(DependencyObject instance, XamlMemberDefinition member, DependencyProperty property)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.ProcessNamedMember(XamlObjectDefinition control, Object instance, XamlMemberDefinition member)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.LoadObject(XamlObjectDefinition control)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.ProcessMemberElements(Object instance, XamlMemberDefinition member, PropertyInfo propertyInfo)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.ProcessNamedMember(XamlObjectDefinition control, Object instance, XamlMemberDefinition member)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.LoadObject(XamlObjectDefinition control)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.AddCollectionItems(Object collectionInstance, IEnumerable`1 nonBindingObjects)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.ProcessMemberElements(Object instance, XamlMemberDefinition member, PropertyInfo propertyInfo)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.ProcessNamedMember(XamlObjectDefinition control, Object instance, XamlMemberDefinition member)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.LoadObject(XamlObjectDefinition control)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.Build()
   at Windows.UI.Xaml.Markup.XamlReader.Load(String xaml)
   at Uno.UI.Demo.Samples.Playground.Update()
   ```

**Comment by sakshi173** [comment]
Verified, Issue is Fixed -- Closing

Below is the screenshot.
![PG1](https://user-images.githubusercontent.com/74563602/106814095-e2dc6700-663f-11eb-8bc3-b4de768a1c83.png)
