### ISSUE TITLE
[Uno Gallery][Android] Binding to a non-DependencyProperty is not supported (Uno.UI.Controls.BindableSwitchCompat.Text)

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#5022]
## Current behavior

```
FATAL EXCEPTION: main
Process: com.nventive.uno.ui.demo, PID: 933
android.runtime.JavaProxyThrowable: System.InvalidOperationException: Binding to a non-DependencyProperty is not supported (Uno.UI.Controls.BindableSwitchCompat.Text)
  at Windows.UI.Xaml.DependencyObjectStore.SetBindingValue (System.Object value, System.String propertyName) <0x7f7d642684 + 0x000a4> in <d8b971f259784fcd844ccfe6f4bc1b26>:0 
  at Uno.UI.Controls.BindableSwitchCompat.SetBindingValue (System.Object value, System.String propertyName) <0x7f7d732604 + 0x0003f> in <d8b971f259784fcd844ccfe6f4bc1b26>:0 
  at Uno.UI.Controls.BindableSwitchCompat.OnTextChange (System.Object sender, Android.Text.TextChangedEventArgs e) [0x00007] in <d8b971f259784fcd844ccfe6f4bc1b26>:0 
  at Android.Text.TextWatcherImplementor.Android.Text.ITextWatcher.OnTextChanged (Java.Lang.ICharSequence s, System.Int32 start, System.Int32 before, System.Int32 count) [0x0001b] in <748ce49873424f92bece4e5711268bf9>:0 
  at Android.Text.ITextWatcherInvoker.n_OnTextChanged_Ljava_lang_CharSequence_III (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_s, System.Int32 start, System.Int32 before, System.Int32 count) [0x0000f] in <748ce49873424f92bece4e5711268bf9>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.172(intptr,intptr,intptr,int,int,int)
	at mono.android.text.TextWatcherImplementor.n_onTextChanged(Native Method)
	at mono.android.text.TextWatcherImplementor.onTextChanged(TextWatcherImplementor.java:49)
	at android.widget.TextView.sendOnTextChanged(TextView.java:7755)
	at android.widget.TextView.setText(TextView.java:4100)
	at android.widget.TextView.setText(TextView.java:3955)
	at android.widget.TextView.getIterableTextForAccessibility(TextView.java:9148)
	at android.view.View.onInitializeAccessibilityNodeInfoInternal(View.java:5682)
	at android.view.View.onInitializeAccessibilityNodeInfo(View.java:5537)
	at android.widget.TextView.onInitializeAccessibilityNodeInfo(TextView.java:8502)
	at android.widget.Button.onInitializeAccessibilityNodeInfo(Button.java:122)
	at android.widget.CompoundButton.onInitializeAccessibilityNodeInfo(CompoundButton.java:328)
	at androidx.appcompat.widget.SwitchCompat.onInitializeAccessibilityNodeInfo(SwitchCompat.java:1401)
	at android.view.View.createAccessibilityNodeInfoInternal(View.java:5498)
	at android.view.View.createAccessibilityNodeInfo(View.java:5485)
```

## Expected behavior

No failure.

## How to reproduce it (as minimally and precisely as possible)

https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=23894&view=results

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
This issue is caused by the accessibility features being enabled on the device, causing some pieces of code to run and fail:

https://github.com/unoplatform/uno/blob/ef5961fd9bf1fb6c617de6842ff4cc3643fdf47b/src/Uno.UI/Controls/BindableSwitchCompat.Android.cs#L121-L129

Those were present in case the system were to modify the text, but this not a supported scenario anymore.
