### ISSUE TITLE
[Calculator][Android] The numbers keypad is missing for Programmer calculator.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5068]
**Steps To Reproduce:**

1. Launch an UNO Calculator app on Android device.
2. Open Programmer calculator.
3. Observe the number keypad is missing for landing page of programmer calculator.

**Current behavior**
The  number keypad is missing for the first landing page of programmer.

**Expected behavior**
The full number and calculation keypad should be present.

**Attachment:
Actual Result:**
![programmer issue](https://user-images.githubusercontent.com/74563602/106207859-6efa1480-6190-11eb-93ae-24017ceaa53d.png)

**Expected Result:**
![programmer correct](https://user-images.githubusercontent.com/74563602/106207873-74575f00-6190-11eb-8749-1af514329390.png)

**Version(s):**
Version 1.2.4 (401296)

**Device:**
Samsung S8 - 8.0
Motorola g(7) – 9

**Affected platform(s):**
Android

**Comment by jeromelaban** [comment]
Reported exception stack trace:

```
      Failed to apply binding to property [DependencyPropertyDetails(Visibility)] on [Windows.UI.Xaml.UIElement] (Attempt to invoke virtual method 'void android.view.View.unFocus(android.view.View)' on a null object reference)
Java.Lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.unFocus(android.view.View)' on a null object reference
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in <752fdd13968240edbcfe9cac17987009>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0005d] in <752fdd13968240edbcfe9cac17987009>:0 
  at Android.Views.ViewGroup.RemoveViewAt (System.Int32 index) [0x00018] in /Users/builder/azdo/_work/453/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-30/mcw/Android.Views.ViewGroup.cs:4121 
  at Windows.UI.Xaml.ElementStub.MaterializeContent () [0x0004b] in C:\a\1\s\src\Uno.UI\UI\Xaml\ElementStub.Android.cs:30 
  at Windows.UI.Xaml.ElementStub.Materialize (System.Boolean isVisibilityChanged) [0x00000] in C:\a\1\s\src\Uno.UI\UI\Xaml\ElementStub.cs:59 
  at Windows.UI.Xaml.ElementStub.OnVisibilityChanged (Windows.UI.Xaml.Visibility oldValue, Windows.UI.Xaml.Visibility newValue) [0x00017] in C:\a\1\s\src\Uno.UI\UI\Xaml\ElementStub.cs:38 
  at Windows.UI.Xaml.UIElement+<>c.<CreateVisibilityProperty>b__798_0 (Windows.UI.Xaml.DependencyObject instance, Windows.UI.Xaml.DependencyPropertyChangedEventArgs args) [0x00000] in C:\a\1\s\src\Uno.UI\obj\Release\MonoAndroid11.0\g\DependencyPropertyGenerator\Windows_UI_Xaml_UIElement_85915f7d6b7124464cf9d270ce415b49.g.cs:123 
  at (wrapper delegate-invoke) <Module>.invoke_void_DependencyObject_DependencyPropertyChangedEventArgs(Windows.UI.Xaml.DependencyObject,Windows.UI.Xaml.DependencyPropertyChangedEventArgs)
  at Windows.UI.Xaml.PropertyMetadata.RaisePropertyChanged (Windows.UI.Xaml.DependencyObject source, Windows.UI.Xaml.DependencyPropertyChangedEventArgs e) [0x00000] in C:\a\1\s\src\Uno.UI\UI\Xaml\PropertyMetadata.cs:187 
  at Windows.UI.Xaml.DependencyObjectStore.InvokeCallbacks (Windows.UI.Xaml.DependencyObject actualInstanceAlias, Windows.UI.Xaml.DependencyProperty property, Windows.UI.Xaml.DependencyPropertyDetails propertyDetails, System.Object previousValue, Windows.UI.Xaml.DependencyPropertyValuePrecedences previousPrecedence, System.Object newValue, Windows.UI.Xaml.DependencyPropertyValuePrecedences newPrecedence, System.Boolean bypassesPropagation) [0x000e3] in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:1574 
  at Windows.UI.Xaml.DependencyObjectStore.RaiseCallbacks (Windows.UI.Xaml.DependencyObject actualInstanceAlias, Windows.UI.Xaml.DependencyPropertyDetails propertyDetails, System.Object previousValue, Windows.UI.Xaml.DependencyPropertyValuePrecedences previousPrecedence, System.Object newValue, Windows.UI.Xaml.DependencyPropertyValuePrecedences newPrecedence) [0x0005b] in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:1483 
  at Windows.UI.Xaml.DependencyObjectStore.InnerSetValue (Windows.UI.Xaml.DependencyProperty property, System.Object value, Windows.UI.Xaml.DependencyPropertyValuePrecedences precedence, Windows.UI.Xaml.DependencyPropertyDetails propertyDetails) [0x00195] in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:482 
  at Windows.UI.Xaml.DependencyObjectStore.SetValue (Windows.UI.Xaml.DependencyProperty property, System.Object value, Windows.UI.Xaml.DependencyPropertyValuePrecedences precedence, Windows.UI.Xaml.DependencyPropertyDetails propertyDetails) [0x0002e] in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:421 
  at Windows.UI.Xaml.DependencyObjectExtensions.SetValue (System.Object instance, Windows.UI.Xaml.DependencyProperty property, System.Object value, System.Nullable`1[T] precedence) [0x00000] in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectExtensions.cs:256 
  at Uno.UI.DataBinding.BindingPropertyHelper+<>c__DisplayClass39_9.<InternalGetValueSetter>b__13 (System.Object instance, System.Object value) [0x00000] in C:\a\1\s\src\Uno.UI\DataBinding\BindingPropertyHelper.cs:846 
  at Windows.UI.Xaml.Data.BindingExpression.SetTargetValue (System.Object value) [0x0000f] in C:\a\1\s\src\Uno.UI\DataBinding\BindingExpression.cs:419 
  at Windows.UI.Xaml.Data.BindingExpression.SetTargetValueSafe (System.Object v, System.Boolean useTargetNullValue) [0x00112] in C:\a\1\s\src\Uno.UI\DataBinding\BindingExpression.cs:589 
  --- End of managed Java.Lang.NullPointerException stack trace ---
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.unFocus(android.view.View)' on a null object reference
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5415)
	at android.view.ViewGroup.removeViewAt(ViewGroup.java:5378)
	at crc64122dcf5ad656876d.UIElement.n_onNativeMotionEvent(Native Method)
	at crc64122dcf5ad656876d.UIElement.onNativeMotionEvent(UIElement.java:48)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:268)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at Uno.UI.UnoRecyclerView.access$001(UnoRecyclerView.java:10)
	at Uno.UI.UnoRecyclerView$TouchMotionTarget.dispatchToSuper(UnoRecyclerView.java:37)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoRecyclerView.dispatchTouchEvent(UnoRecyclerView.java:50)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
	at crc64a5a37c43dff01024.ListViewBase.n_dispatchTouchEvent(Native Method)
	at crc64a5a37c43dff01024.ListViewBase.dispatchTouchEvent(ListViewBase.java:29)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
	at Uno.UI.TouchMotionTarget.dispatchToChild(UnoMotionHelper.java:53)
	at Uno.UI.UnoMotionHelper.dispatchStaticTransformedMotionEventCore(UnoMotionHelper.java:419)
	at Uno.UI.UnoMotionHelper.dispatchStaticTransformedMotionEvent(UnoMotionHelper.java:389)
	at Uno.UI.UnoMotionHelper.dispatchStaticTransformedMotionEvent(UnoMotionHelper.java:331)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:187)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:465)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1849)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3993)
	at crc6467d88aaa7548788d.BaseActivity.n_dispatchTouchEvent(Native Method)
	at crc6467d88aaa7548788d.BaseActivity.dispatchTouchEvent(BaseActivity.java:137)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:423)
	at android.view.View.dispatchPointerEvent(View.java:13674)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5482)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5285)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4841)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4807)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4947)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4815)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5004)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4841)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4807)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4815)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7505)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7474)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7435)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7630)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:188)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:174)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
m_CalculatorViewMode = CalculatorApp.ViewModel.StandardCalculatorViewModel
```

and

```
[41m[30mfail[39m[22m[49m: Windows.UI.Xaml.Data.BindingExpression[0]
      Failed to apply binding to property [DependencyPropertyDetails(IsScientific)] on [CalculatorApp.Calculator] (Attempt to invoke virtual method 'void android.view.View.unFocus(android.view.View)' on a null object reference)
Java.Lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.unFocus(android.view.View)' on a null object reference
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in <752fdd13968240edbcfe9cac17987009>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0005d] in <752fdd13968240edbcfe9cac17987009>:0 
  at Windows.UI.Xaml.ElementStub.MaterializeContent () [0x0004b] in C:\a\1\s\src\Uno.UI\UI\Xaml\ElementStub.Android.cs:30 
  at Windows.UI.Xaml.ElementStub.Materialize (System.Boolean isVisibilityChanged) [0x00000] in C:\a\1\s\src\Uno.UI\UI\Xaml\ElementStub.cs:59 
  at Windows.UI.Xaml.ElementStub.Materialize () [0x00000] in C:\a\1\s\src\Uno.UI\UI\Xaml\ElementStub.cs:55 
  at Windows.UI.Xaml.IFrameworkElementHelper.ConvertFromStubToElement (Windows.UI.Xaml.IFrameworkElement element, Windows.UI.Xaml.IFrameworkElement originalRootElement, System.String name) [0x0000a] in C:\a\1\s\src\Uno.UI\UI\Xaml\IFrameworkElement.cs:383 
  at Windows.UI.Xaml.IFrameworkElementHelper.FindName (Windows.UI.Xaml.IFrameworkElement e, System.Collections.Generic.IEnumerable`1[T] subviews, System.String name) [0x0008e] in C:\a\1\s\src\Uno.UI\UI\Xaml\IFrameworkElement.cs:242 
  at Windows.UI.Xaml.FrameworkElement.FindName (System.String name) [0x0000a] in C:\a\1\s\src\Uno.UI\Mixins\Android\FrameworkElementMixins.g.cs:64 
  at Windows.UI.Xaml.IFrameworkElementHelper.ConvertFromStubToElement (Windows.UI.Xaml.IFrameworkElement element, Windows.UI.Xaml.IFrameworkElement originalRootElement, System.String name) [0x00010] in C:\a\1\s\src\Uno.UI\UI\Xaml\IFrameworkElement.cs:384 
  at Windows.UI.Xaml.IFrameworkElementHelper.FindName (Windows.UI.Xaml.IFrameworkElement e, System.Collections.Generic.IEnumerable`1[T] subviews, System.String name) [0x0008e] in C:\a\1\s\src\Uno.UI\UI\Xaml\IFrameworkElement.cs:242 
  at Windows.UI.Xaml.FrameworkElement.FindName (System.String name) [0x0000a] in C:\a\1\s\src\Uno.UI\Mixins\Android\FrameworkElementMixins.g.cs:64 
[m02-01 12:23:1ono-stdout]   at Windows.UI.Xaml.IFrameworkElementHelper.ConvertFromStubToElement (Windows.UI.Xaml.IFrameworkElement element, Windows.UI.Xaml.IFrameworkElement originalRootElement, System.String name) [0x00010] in C:\a\1\s\src\Uno.UI\UI\Xaml\IFrameworkElement.cs:384 
  at Windows.UI.Xaml.IFrameworkElementHelper.FindName (Windows.UI.Xaml.IFrameworkElement e, System.Collections.Generic.IEnumerable`1[T] subviews, System.String name) [0x0008e] in C:\a\1\s\src\Uno.UI\UI\Xaml\IFrameworkElement.cs:242 
  at Windows.UI.Xaml.FrameworkElement.FindName (System.String name) [0x0000a] in C:\a\1\s\src\Uno.UI\Mixins\Android\FrameworkElementMixins.g.cs:64 
  at Windows.UI.Xaml.IFrameworkElementHelper.ConvertFromStubToElement (Windows.UI.Xaml.IFrameworkElement element, Windows.UI.Xaml.IFrameworkElement originalRootElement, System.String name) [0x00010] in C:\a\1\s\src\Uno.UI\UI\Xaml\IFrameworkElement.cs:384 
  at Windows.UI.Xaml.IFrameworkElementHelper.FindName (Windows.UI.Xaml.IFrameworkElement e, System.Collections.Generic.IEnumerable`1[T] subviews, System.String name) [0x0008e] in C:\a\1\s\src\Uno.UI\UI\Xaml\IFrameworkElement.cs:242 [0:] CalculatorManager.SetPrimaryDisplayCallback(0, False)

  at Windows.UI.Xaml.FrameworkElement.FindName (System.String name) [0x0000a] in C:\a\1\s\src\Uno.UI\Mixins\Android\FrameworkElementMixins.g.cs:64 
  at Windows.UI.Xaml.IFrameworkElementHelper.ConvertFromStubToElement (Windows.UI.Xaml.IFrameworkElement element, Windows.UI.Xaml.IFrameworkElement originalRootElement, System.String name) [0x00010] in C:\a\1\s\src\Uno.UI\UI\Xaml\IFrameworkElement.cs:384 [0:] CalculatorManager.SetIsInErrorCallback(False)

  at Windows.UI.Xaml.IFrameworkElementHelper.FindName (Windows.UI.Xaml.IFrameworkElement e, System.Collections.Generic.IEnumerable`1[T] subviews, System.String name) [0x0008e] in C:\a\1\s\src\Uno.UI\UI\Xaml\IFrameworkElement.cs:242 
```

**Comment by jeromelaban** [comment]
Will be fixed https://github.com/unoplatform/uno/pull/5077

**Comment by sakshi173** [comment]
Verified Issue is Fixed -- Closing
Verified Version:
Version 1.2.4 (401304)
Feb 09, 2021 at 23:27

![programmer correct1](https://user-images.githubusercontent.com/74563602/107549919-6517de80-6b9e-11eb-95f5-c86f3256b71f.png)

**Comment by sakshi173** [comment]
Again same issue is happening for the below canary build , due to that reopening the issue.
Version 1.2.4 (401304)
Device:
Samsung S8 - 8.0
Motorola g(7) – 9

Affected platform(s):
Android

**Comment by jeromelaban** [comment]
@sakshi173 can you revalidate this one with the latest canaries ? Thanks!

**Comment by sakshi173** [comment]
I Revalidated and the issue is fixed for the below version.

Version 1.2.4 (401308)
Mar 22, 2021 at 12:05
41.42 MB
![calc correct](https://user-images.githubusercontent.com/74563602/112054917-92a46000-8b2c-11eb-8fff-fe18bb1792cd.png)

**Comment by sakshi173** [comment]
Verified, issue is fixed, closing
