### ISSUE TITLE
Uno.UI.Toolkit.VisibleBoundsPadding.PaddingMask=“All” crash a UWP app occasionally

### ISSUE THREAD

**Issue by zipswich** [unoplatform/uno#5274]
## Current behavior

Uno.UI.Toolkit.VisibleBoundsPadding.PaddingMask="All" is used on almost every page of an app like the following:

```
<Grid
    x:Name="gridRoot"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}"
    toolkit:VisibleBoundsPadding.PaddingMask="All"
    >
```
Occasionally, the UWP version crashes with the following exception:
```
Exception: Object reference not set to an instance of an object.
Type: System.NullReferenceException
Stack trace:    at Uno.UI.Toolkit.VisibleBoundsPadding.VisibleBoundsDetails.UpdatePadding() + 0x8d
   at Uno.UI.Toolkit.VisibleBoundsPadding.VisibleBoundsDetails.<.ctor>b__5_0(ApplicationView, Object) + 0x8
   at System.EventHandler`1.Invoke(Object, TEventArgs) + 0x2e
   at __Interop.Intrinsics.HasThisCall__51(Object, IntPtr, Object, Object) + 0x26
   at SharedLibrary!<BaseAddress>+0x94ca05
```

## Expected behavior

No crash

## How to reproduce it (as minimally and precisely as possible)

Put VisibleBoundsPadding.PaddingMask="All" on every page, and run a UWP app day and night in different ways, and observe the occasional crachses.

## Workaround

Yet to be found.

## Environment

Nuget Package:

- [x ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.6.0-dev.59

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.8.5)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report.

## Note for contributors

It may be that under some conditions, `Window.Current` may be null:
https://github.com/unoplatform/uno/blob/ef5961fd9bf1fb6c617de6842ff4cc3643fdf47b/src/Uno.UI/Behaviors/VisibleBoundsPadding.cs#L200

**Comment by xperiandri** [comment]
WinUI
```
   at Uno.UI.Toolkit.VisibleBoundsPadding.VisibleBoundsDetails.UpdatePadding()
   at Uno.UI.Toolkit.VisibleBoundsPadding.VisibleBoundsDetails.OnIsPaddingMaskChanged(PaddingMask oldValue, PaddingMask newValue)
   at Uno.UI.Toolkit.VisibleBoundsPadding.OnIsPaddingMaskChanged(DependencyObject dependencyObject, DependencyPropertyChangedEventArgs args)
   at ABI.Microsoft.UI.Xaml.PropertyChangedCallback.<>c__DisplayClass10_0.<Do_Abi_Invoke>b__0(PropertyChangedCallback invoke)
   at WinRT.ComWrappersSupport.MarshalDelegateInvoke[T](IntPtr thisPtr, Action`1 invoke)
   at ABI.Microsoft.UI.Xaml.PropertyChangedCallback.Do_Abi_Invoke(IntPtr thisPtr, IntPtr d, IntPtr e)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IDependencyObject.global::Microsoft.UI.Xaml.IDependencyObject.SetValue(DependencyProperty dp, Object value)
   at Microsoft.UI.Xaml.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at Uno.UI.Toolkit.VisibleBoundsPadding.SetPaddingMask(DependencyObject obj, PaddingMask value)
   at Elmish.Uno.Samples.Samples_Windows_Desktop_XamlTypeInfo.XamlTypeInfoProvider.set_18_VisibleBoundsPadding_PaddingMask(Object instance, Object Value) in C:\Users\Andrii\Dev\GitHub\Elmish.Uno\src\Samples\Samples.Windows.Desktop\obj\x64\Debug\net5.0-windows10.0.19041.0\XamlTypeInfo.g.cs:line 1234
```

**Comment by xperiandri** [comment]
Branch https://github.com/xperiandri/Elmish.Uno/tree/uno_winui
Files `Shell.xaml`, `MainPage.xaml`

**Comment by zipswich** [comment]
Could anyone change the following code:
```
			private void UpdatePadding()
			{
				if (Window.Current.Content == null)
				{
					return;
				}
```
to the following?
```
			private void UpdatePadding()
			{
				if (Window.Current?.Content == null)
				{
					return;
				}
```
In other words, just add a "?" to solve this problem once for all.  Though the crash happens only occasionally, it is a nuisance affecting many app users.

**Comment by jeromelaban** [comment]
This is a bit more complex than adding the null coalescing, as there are other locations `Window.Current` is used.

**Comment by zipswich** [comment]
The crash is caused by the UpdatePadding() currently.  Do you mean other methods would crash the app after UpdatePadding() returned safely?

**Comment by jeromelaban** [comment]
Indeed, `Window.Current` is used in other locations, so fixing this particular location may just reveal the other ones as well.
