### ISSUE TITLE
WASM head targeting .NET 5 crashes on start when using localization

### ISSUE THREAD

**Issue by s-beltz** [unoplatform/uno#5389]
## Current behavior

We use localization features according to this documentation:
https://platform.uno/docs/articles/using-uno-ui.html#localization

When targeting .NET 5 in WASM head the app crashes on startup. We see 2 errors in the browser's console output:

```
Unhandled exception in processFetchResponseBuffer RuntimeError: abort(Assertion failed: Cannot call unknown function mono_wasm_load_icu_data, make sure it is exported) at Error
    at jsStackTrace (http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:1635:19)
    at stackTrace (http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:1652:16)
    at abort (http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:1372:44)
    at assert (http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:588:5)
    at getCFunc (http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:595:3)
    at ccall (http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:630:14)
    at http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:657:12
    at Object.mono_wasm_load_icu_data (http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:7743:16)
    at Object._handle_loaded_asset (http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:7693:16)
    at processFetchResponseBuffer (http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:7834:13)
    at abort (http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:1378:11)
    at assert (http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:588:5)
    at getCFunc (http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:595:3)
    at ccall (http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:630:14)
    at http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:657:12
    at Object.mono_wasm_load_icu_data (http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:7743:16)
    at Object._handle_loaded_asset (http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:7693:16)
    at processFetchResponseBuffer (http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:7834:13)
processFetchResponseBuffer @ dotnet.js:7836
```
and 

```
dotnet.js:1378 Uncaught (in promise) RuntimeError: abort(Assertion failed: Cannot call unknown function mono_wasm_load_icu_data, make sure it is exported) at Error
    at jsStackTrace (http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:1635:19)
    at stackTrace (http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:1652:16)
    at abort (http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:1372:44)
    at assert (http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:588:5)
    at getCFunc (http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:595:3)
    at ccall (http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:630:14)
    at http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:657:12
    at Object.mono_wasm_load_icu_data (http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:7743:16)
    at Object._handle_loaded_asset (http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:7693:16)
    at processFetchResponseBuffer (http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:7834:13)
    at abort (http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:1378:11)
    at assert (http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:588:5)
    at getCFunc (http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:595:3)
    at ccall (http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:630:14)
    at http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:657:12
    at Object.mono_wasm_load_icu_data (http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:7743:16)
    at Object._handle_loaded_asset (http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:7693:16)
    at processFetchResponseBuffer (http://localhost:58082/package_29c8bbb98b64a9377946c4bfe493f20534f57323/dotnet.js:7834:13)
```

Targeting .NET Standard 2.0 in the WASM head works as expected.
## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="2.0.0-dev.167" />
    <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="2.0.0-dev.167" />

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.8.6)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report. This issue has been fixed in the Uno.Wasm.Bootstrap 2.0.0-dev.180. Can you try upgrading to this version and let us know?

**Comment by s-beltz** [comment]
Hello @jeromelaban, Thanks for the quick response! 
Would love to do that but I can not find that package version on nuget.org. Do I need to use another package source?

**Comment by jeromelaban** [comment]
It was just published, so it may take some time to appear on your side :) Give it a try in 10 or 20 minutes.

**Comment by s-beltz** [comment]
Hello @jeromelaban, things have changed with 2.0.0-dev.180. ICU error is gone, but now we see an issue when initializing SQLite in our app startup routine:
```
fail: Windows.UI.Core.CoreDispatcher[0]
dotnet.js:2240       Dispatcher unhandled exception
dotnet.js:2240 System.NullReferenceException: Arg_NullReferenceException
dotnet.js:2240    at SQLitePCL.SQLite3Provider_dynamic_cdecl.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number()
dotnet.js:2240    at SQLitePCL.raw.SetProvider(ISQLite3Provider imp)
dotnet.js:2240    at SQLitePCL.Batteries_V2.DoDynamic_cdecl(String name, Int32 flags)
dotnet.js:2240    at SQLitePCL.Batteries_V2.Init()
dotnet.js:2240    at SQLitePCL.Batteries.Init()
dotnet.js:2240    at Apliconus.WorkbookApp.App.<OnLaunched>d__3.MoveNext() in C:\VSO_2.1\5-Apps\APLICONUS Foundation 5.1\Apps\Apliconus.WorkbookApp\Apliconus.WorkbookApp.Shared\App.xaml.cs:line 126

```
We are using:
<PackageReference Include="Uno.SQLitePCLRaw.provider.wasm" Version="3.0.14" />
