### ISSUE TITLE
[WASM] Bootstrapper 2.0.0 debugging does not start properly

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#5647]
I'm getting gazillions of exceptions as per below.
This is latest UNO (and related packages):
- Uno.UI 3.6.6
- Uno.Ui.WebASsembly 3.6.6
- Uno.Wasm.Bootstrap 2.0.0
- Uno.Wasm.Bootstrap.DevServer 2.0.0

Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

System.IO.FileNotFoundException: Could not load file or assembly 'Mono.WebAssembly.DebuggerProxy, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Mono.WebAssembly.DebuggerProxy, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Uno.Wasm.Bootstrap.Cli.DebuggingProxy.DebuggerHostExtensions.DebugWebSocketProxyRequest(ILoggerFactory loggerFactory, HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Uno.Wasm.Bootstrap.Cli.DebuggingProxy.DebuggerHostExtensions.DebugWebSocketProxyRequest(ILoggerFactory loggerFactory, HttpContext context)
   at Uno.Wasm.Bootstrap.Cli.DebuggingProxy.DebuggerHostExtensions.<>c__DisplayClass0_0.<UseDebugHost>b__0(HttpContext context, Func`1 next) in D:\a\1\s\src\Uno.Wasm.Bootstrap.Cli\DebuggingProxy\DebugHostExtensions.cs:line 56
   at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass0_1.<Use>b__1(HttpContext context)
   at Microsoft.AspNetCore.WebSockets.WebSocketMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by DierkDroth** [comment]
More info: removing the 2 offending lines in launchsettings.json as per [here ](https://github.com/unoplatform/uno/issues/2372#issuecomment-805829641) resolves the issue. Expected?

**Comment by jeromelaban** [comment]
@DierkDroth yes, this is expected at this point. The upstream changes in the dotnet/runtime are moving to .NET 6, and there's no adjustment available for the bootstrapper at this time. This should start to resolve once more .NET 6 previews are getting released.

**Comment by DierkDroth** [comment]
Understand. 

I tried to revert to Uno.Wasm.Bootstrap + Uno.Wasm.Bootstrap.DevServer 1.3.6 and now 
- am getting tons of exception as per below
- on next try VS throws an error "Failed to launch debug adapter..."

"DebugStore.cs not found"
+
Mono.ArgumentNullOrEmptyException
  HResult=0x80070057
  Message=Argument null or empty (Parameter 'fileName')
  Source=Mono.Cecil
  StackTrace:
   at Mono.Cecil.Mixin.CheckFileName(String fileName)
   at Mono.Cecil.Pdb.PdbReaderProvider.GetSymbolReader(ModuleDefinition module, String fileName)
   at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
   at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(Disposable`1 stream, String fileName, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(Stream stream, ReaderParameters parameters)
   at WebAssembly.Net.Debugging.AssemblyInfo..ctor(IAssemblyResolver resolver, String url, Byte[] assembly, Byte[] pdb) in /__w/1/s/mono/sdks/wasm/Mono.WebAssembly.DebuggerProxy/DebugStore.cs:line 395

**Comment by jeromelaban** [comment]
Thanks for the update.

At this point, the `netstandard2.0` debugging experience will not change as Microsoft has moved from [mono/mono](https://github.com/mono/mono) to [dotnet/runtime](https://github.com/dotnet/runtime), which means the 1.3.6 debugger won't evolve as well.

On the `net5.0` front, we've made changes to the bootstrapper so it works properly without having to install .NET 6 previews. This will be available as part of a `Uno.Wasm.Bootstrap` 2.0.2 stable package, and in the 2.1 branch. The update should be available soon. Let us know if the debugging starts working properly.

**Comment by DierkDroth** [comment]
Thanks @jeromelaban. We'll try that...
