### ISSUE TITLE
XamlReader in WPF doesn't load TypeConverter for Brush string

### ISSUE THREAD

**Issue by Poppyto** [unoplatform/uno#5692]
## Current behavior

With WPF Uno :

`XamlReader.Load("<ContentControl xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation' xmlns:c='using:Windows.UI.Xaml.Media'><c:Brush>Blue</c:Brush></ContentControl>")`

returns

 ```
Cannot create an abstract class.
  at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.LoadObject(XamlObjectDefinition control)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.ProcessMemberElements(Object instance, XamlMemberDefinition member, PropertyInfo propertyInfo)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.ProcessNamedMember(XamlObjectDefinition control, Object instance, XamlMemberDefinition member)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.LoadObject(XamlObjectDefinition control)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.Build()
   at Windows.UI.Xaml.Markup.XamlReader.Load(String xaml)
   at Microsoft.Xaml.Interactions.Core.TypeConverterHelper.Convert(String value, String destinationTypeFullName) in D:\Projets\Uno\MyApp1\MyApp1\MyApp1.Shared\Interactions\Core\TypeConverterHelper.cs:line 168
```

## Expected behavior

It should create a ContentControl with SolidColorBrush (based on TypeConverter Attribute of Brush class), or use this function :
`XamlBindingHelper.ConvertValue(vBrushType, value);`

## Workaround

`XamlReader.Load("<ContentControl xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation' xmlns:c='using:Windows.UI.Xaml.Media'><c:SolidColorBrush>Blue</c:SolidColorBrush></ContentControl>")`

## Environment

Nuget Package:

- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl

Nuget Package Version(s): Last version 3.6.6

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [X] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: 16.9.3)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

I initially tried to use XamlBehavior library with Uno-WPF project and get stucked with a simple feature :

```
<TextBlock Text="IsLoading">
                <Interactivity:Interaction.Behaviors>
                    <Core:DataTriggerBehavior Binding="{Binding IsBusy}" Value="False">
                        <Core:ChangePropertyAction PropertyName="Foreground" Value="Blue" />
                    </Core:DataTriggerBehavior>
                </Interactivity:Interaction.Behaviors>
</TextBlock>
```

Then I extracted the code from github and found the MissingMethod exception

**Comment by francoistanguay** [comment]
@Poppyto  if we can't repro, I'll close for now but please, if you are able to reproduce somehow with latest Uno, attach a sample repro so we can look into this more closely. Thank you!
