### ISSUE TITLE
Error building project with Uno.Xamarin.Forms.Platform

### ISSUE THREAD

**Issue by MaxwellDAssistek** [unoplatform/uno#5854]
## Current behavior

Followed the exact instructions of the README in the Uno.Xamarin.Forms.Platform repo.
After updating to latest stable version 4.3.4 on the Wasm project, I end up with a fatal error in Mono linker when running.

```
[...]\.nuget\packages\uno.wasm.bootstrap\1.3.0\build\Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:08.0249276] Fatal error in Mono IL Linker
[...]\.nuget\packages\uno.wasm.bootstrap\1.3.0\build\Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:08.0262022] 
[...]\.nuget\packages\uno.wasm.bootstrap\1.3.0\build\Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:08.0296265] Unhandled Exception: Mono.Cecil.ResolutionException: Failed to resolve Uno.Diagnostics.Eventing.IEventProvider
[...]\.nuget\packages\uno.wasm.bootstrap\1.3.0\build\Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:08.0296470]    at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
[...]\.nuget\packages\uno.wasm.bootstrap\1.3.0\build\Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:08.0296505]    at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
[...]\.nuget\packages\uno.wasm.bootstrap\1.3.0\build\Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:08.0296522]    at Mono.Linker.Steps.MarkStep.MarkField(FieldDefinition field)
[...]\.nuget\packages\uno.wasm.bootstrap\1.3.0\build\Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:08.0296537]    at Mono.Linker.Steps.MarkStep.MarkFields(TypeDefinition type, Boolean includeStatic, Boolean markBackingFieldsOnlyIfPropertyMarked)
[...]\.nuget\packages\uno.wasm.bootstrap\1.3.0\build\Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:08.0296552]    at Mono.Linker.Steps.MarkStep.ApplyPreserveInfo(TypeDefinition type)
[...]\.nuget\packages\uno.wasm.bootstrap\1.3.0\build\Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:08.0296566]    at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
[...]\.nuget\packages\uno.wasm.bootstrap\1.3.0\build\Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:08.0296581]    at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
[...]\.nuget\packages\uno.wasm.bootstrap\1.3.0\build\Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:08.0296595]    at Mono.Linker.Steps.MarkStep.InitializeType(TypeDefinition type)
[...]\.nuget\packages\uno.wasm.bootstrap\1.3.0\build\Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:08.0296609]    at Mono.Linker.Steps.MarkStep.InitializeType(TypeDefinition type)
[...]\.nuget\packages\uno.wasm.bootstrap\1.3.0\build\Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:08.0296622]    at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
[...]\.nuget\packages\uno.wasm.bootstrap\1.3.0\build\Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:08.0296637]    at Mono.Linker.Steps.MarkStep.Initialize()
[...]\.nuget\packages\uno.wasm.bootstrap\1.3.0\build\Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:08.0296650]    at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
[...]\.nuget\packages\uno.wasm.bootstrap\1.3.0\build\Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:08.0296855]    at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
[...]\.nuget\packages\uno.wasm.bootstrap\1.3.0\build\Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:08.0296894]    at Mono.Linker.Pipeline.Process(LinkContext context)
[...]\.nuget\packages\uno.wasm.bootstrap\1.3.0\build\Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:08.0296921]    at Mono.Linker.Driver.Run(ILogger customLogger)
[...]\.nuget\packages\uno.wasm.bootstrap\1.3.0\build\Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:08.0296947]    at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
[...]\.nuget\packages\uno.wasm.bootstrap\1.3.0\build\Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:08.0296971]    at Mono.Linker.Driver.Main(String[] args)
[...]\.nuget\packages\uno.wasm.bootstrap\1.3.0\build\Uno.Wasm.Bootstrap.targets(126,2): error : System.Exception: Failed to execute the linker
[...]\.nuget\packages\uno.wasm.bootstrap\1.3.0\build\Uno.Wasm.Bootstrap.targets(126,2): error :    at Uno.Wasm.Bootstrap.ShellTask_v9b71577ff853e31443bbf7eeaf28b6e534ed35b0.RunPackager() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 709
[...]\.nuget\packages\uno.wasm.bootstrap\1.3.0\build\Uno.Wasm.Bootstrap.targets(126,2): error :    at Uno.Wasm.Bootstrap.ShellTask_v9b71577ff853e31443bbf7eeaf28b6e534ed35b0.Execute() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 182
```

## Expected behavior

Project runs successfully.

## How to reproduce it (as minimally and precisely as possible)

Follow instruction from README: 

> Create a Xamarin.Forms project
> 
>     Check Place project and solution in the same directory
>     Check Windows (UWP)
> 
> Using a VS Developer Command Prompt, navigate to the folder containing the solution
> Type the following to install the latest template:
> 
> dotnet new -i Uno.ProjectTemplates.Dotnet::3.1.6
> 
> Then type the following to create the new WebAssembly project:
> 
> dotnet new wasmxfhead
> 
> Open or Reload the solution in Visual Studio
> Set the Wasm project as the startup project
> Open the Nuget Package manager for the Wasm project and update the Uno.Xamarin.Forms.Platform project to the latest stable package

## Workaround

> The workaround seems to be to downgrade all the other projects to Xamarin.Forms 5.0.0.1931 and then update to the Latest prerelease of Uno.Xamarin.Forms.Platform on the Wasm project.

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [x] Other: *Uno.Xamarin.Forms.Platform*

Nuget Package Version(s): 4.3.4

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: *16.9.4*)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

None

**Comment by jeromelaban** [comment]
Thanks for the report. Can you try again after installing the latest templates, as follows:
```
dotnet new -i Uno.ProjectTemplates.Dotnet
```

**Comment by MaxwellDAssistek** [comment]
After making a new fresh project, installing the latest template, then running `dotnet new wasmxfhead`, I tried to just run as is and got:
```
[...]\XamarinTest4\XamarinTest4.Wasm\XamarinTest4.Wasm.csproj : error NU1107: Version conflict detected for Xamarin.Forms. Install/reference Xamarin.Forms 5.0.0.2012 directly to project XamarinTest4.Wasm to resolve this issue. 
[...]\XamarinTest4\XamarinTest4.Wasm\XamarinTest4.Wasm.csproj : error NU1107:  XamarinTest4.Wasm -> XamarinTest4 -> Xamarin.Forms (>= 5.0.0.2012) 
[...]\XamarinTest4\XamarinTest4.Wasm\XamarinTest4.Wasm.csproj : error NU1107:  XamarinTest4.Wasm -> Uno.Xamarin.Forms.Platform 4.8.0-uno.1322 -> Xamarin.Forms (= 4.8.0.1451).
```

If I update to latest stable, I get the same error as the initial post.
If I try to update the Wasm project to Latest prerelease, I get:
```
NU1107: Version conflict detected for Xamarin.Forms. Install/reference Xamarin.Forms 5.0.0.2012 directly to project XamarinTest4.Wasm to resolve this issue. 
 XamarinTest4.Wasm -> XamarinTest4 -> Xamarin.Forms (>= 5.0.0.2012) 
 XamarinTest4.Wasm -> Uno.Xamarin.Forms.Platform 5.0.0-uno.1796 -> Xamarin.Forms (= 5.0.0.1931).
```

**Comment by MaxwellDAssistek** [comment]
The workaround seems to be to downgrade all the other projects to Xamarin.Forms 5.0.0.1931 and then updating to the Latest prerelease. Perhaps there is a better way, or this can be better documented.

**Comment by jeromelaban** [comment]
Xamarin.Forms versions must be explicitly aligned.
