### ISSUE TITLE
Android FATAL crash from inside Framework

### ISSUE THREAD

**Issue by BrianDT** [unoplatform/uno#5855]
## Current behavior

Occasional crash probably related to a ListView update

## Expected behavior

Expect situations to be handled more gracefully 

## How to reproduce it (as minimally and precisely as possible)

Happens infrequently in a production app, have not been able to reproduce in a sample.

## Workaround

None known.

## Environment

Nuget Package:

- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.6.6

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.9.4)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

Stack trace

```
2021-04-29 15:54:29.5804 [1] FATAL @ApplicationExtensions.RaiseRecoverableUnhandledExceptionOrLog 0 @RaiseRecoverableUnhandledException 0 @.ctor 0 @LogAndExit 0 @LogException 0 @LogFatal 0 @LogWithLibraryLayout 0 @UnhandledException Java.Lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 18(offset:18).state:50 crc64a5a37c43dff01024.NativeListViewBase{86e8a2a VFED.V.. ......ID 0,0-800,1097}, adapter:crc64a5a37c43dff01024.NativeListViewBaseAdapter@124af91, layout:Windows.UI.Xaml.Controls.ItemsStackPanelLayout, context:OnBoardRemote.Droid.MainActivity
  at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <365a6962c3c943c9bef39bcfc052d252>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeAbstractObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00014] in <365a6962c3c943c9bef39bcfc052d252>:0 
  at AndroidX.RecyclerView.Widget.RecyclerView+Recycler.GetViewForPosition (System.Int32 position) [0x00022] in <934637245da64b148fe94c410d26de8e>:0 
  at Uno.UI.Extensions.RecyclerExtensions.GetViewForPosition (AndroidX.RecyclerView.Widget.RecyclerView+Recycler recycler, System.Int32 position, AndroidX.RecyclerView.Widget.RecyclerView+State state) [0x0002e] in <db14ec18228a486b83dcfd375d53c9ce>:0 
  at Windows.UI.Xaml.Controls.BufferViewCache.PrefetchView (AndroidX.RecyclerView.Widget.RecyclerView+Recycler recycler, AndroidX.RecyclerView.Widget.RecyclerView+State state, System.Int32 displayPosition) [0x0001b] in <db14ec18228a486b83dcfd375d53c9ce>:0 
  at Windows.UI.Xaml.Controls.BufferViewCache.<PrefetchViews>g__PrefetchExtra|49_2 (Windows.UI.Xaml.Controls.BufferViewCache+<>c__DisplayClass49_0& ) [0x0003e] in <db14ec18228a486b83dcfd375d53c9ce>:0 
  at Windows.UI.Xaml.Controls.BufferViewCache.PrefetchViews (AndroidX.RecyclerView.Widget.RecyclerView+Recycler recycler, AndroidX.RecyclerView.Widget.RecyclerView+State state) [0x00046] in <db14ec18228a486b83dcfd375d53c9ce>:0 
  at Windows.UI.Xaml.Controls.BufferViewCache.UpdateBuffers (AndroidX.RecyclerView.Widget.RecyclerView+Recycler recycler, AndroidX.RecyclerView.Widget.RecyclerView+State state) [0x00029] in <db14ec18228a486b83dcfd375d53c9ce>:0 
  at Windows.UI.Xaml.Controls.VirtualizingPanelLayout.UpdateBuffers (AndroidX.RecyclerView.Widget.RecyclerView+Recycler recycler, AndroidX.RecyclerView.Widget.RecyclerView+State state) [0x0000c] in <db14ec18228a486b83dcfd375d53c9ce>:0 
  at Windows.UI.Xaml.Controls.VirtualizingPanelLayout.UpdateLayout (Windows.UI.Xaml.Controls.Primitives.GeneratorDirection direction, System.Int32 availableExtent, System.Int32 availableBreadth, AndroidX.RecyclerView.Widget.RecyclerView+Recycler recycler, AndroidX.RecyclerView.Widget.RecyclerView+State state, System.Boolean isMeasure) [0x000da] in <db14ec18228a486b83dcfd375d53c9ce>:0 
  at Windows.UI.Xaml.Controls.VirtualizingPanelLayout.OnMeasure (AndroidX.RecyclerView.Widget.RecyclerView+Recycler recycler, AndroidX.RecyclerView.Widget.RecyclerView+State state, System.Int32 widthSpec, System.Int32 heightSpec) [0x0003e] in <db14ec18228a486b83dcfd375d53c9ce>:0 
  --- End of managed Java.Lang.IndexOutOfBoundsException stack trace ---
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 18(offset:18).state:50 crc64a5a37c43dff01024.NativeListViewBase{86e8a2a VFED.V.. ......ID 0,0-800,1097}, adapter:crc64a5a37c43dff01024.NativeListViewBaseAdapter@124af91, layout:Windows.UI.Xaml.Controls.ItemsStackPanelLayout, context:OnBoardRemote.Droid.MainActivity
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6183)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
	at crc64a5a37c43dff01024.VirtualizingPanelLayout.n_onMeasure(Native Method)
	at crc64a5a37c43dff01024.VirtualizingPanelLayout.onMeasure(VirtualizingPanelLayout.java:113)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3593)
	at android.view.View.measure(View.java:18926)
	at crc64122dcf5ad656876d.FrameworkElement.n_onMeasure(Native Method)
	at crc64122dcf5ad656876d.FrameworkElement.onMeasure(FrameworkElement.java:60)
	at android.view.View.measure(View.java:18926)
	at crc64122dcf5ad656876d.FrameworkElement.n_onMeasure(Native Method)
	at crc64122dcf5ad656876d.FrameworkElement.onMeasure(FrameworkElement.java:60)
	at android.view.View.measure(View.java:18926)
	at crc64122dcf5ad656876d.FrameworkElement.n_onMeasure(Native Method)
	at crc64122dcf5ad656876d.FrameworkElement.onMeasure(FrameworkElement.java:60)
	at android.view.View.measure(View.java:18926)
	at crc64122dcf5ad656876d.FrameworkElement.n_onMeasure(Native Method)
	at crc64122dcf5ad656876d.FrameworkElement.onMeasure(FrameworkElement.java:60)
	at android.view.View.measure(View.java:18926)
	at crc64a5a37c43dff01024.ItemsControl.n_onMeasure(Native Method)
	at crc64a5a37c43dff01024.ItemsControl.onMeasure(ItemsControl.java:29)
	at android.view.View.measure(View.java:18926)
	at crc64122dcf5ad656876d.FrameworkElement.n_onMeasure(Native Method)
	at crc64122dcf5ad656876d.FrameworkElement.onMeasure(FrameworkElement.java:60)
	at android.view.View.measure(View.java:18926)
	at crc64122dcf5ad656876d.FrameworkElement.n_onMeasure(Native Method)
	at crc64122dcf5ad656876d.FrameworkElement.onMeasure(FrameworkElement.java:60)
	at android.view.View.measure(View.java:18926)
	at crc64122dcf5ad656876d.FrameworkElement.n_onMeasure(Native Method)
	at crc64122dcf5ad656876d.FrameworkElement.onMeasure(FrameworkElement.java:60)
	at android.view.View.measure(View.java:18926)
	at crc64122dcf5ad656876d.FrameworkElement.n_onMeasure(Native Method)
	at crc64122dcf5ad656876d.FrameworkElement.onMeasure(FrameworkElement.java:60)
	at android.view.View.measure(View.java:18926)
	at crc64122dcf5ad656876d.FrameworkElement.n_onMeasure(Native Method)
	at crc64122dcf5ad656876d.FrameworkElement.onMeasure(FrameworkElement.java:60)
	at android.view.View.measure(View.java:18926)
	at crc64122dcf5ad656876d.FrameworkElement.n_onMeasure(Native Method)
	at crc64122dcf5ad656876d.FrameworkElement.onMeasure(FrameworkElement.java:60)
	at android.view.View.measure(View.java:18926)
	at crc64122dcf5ad656876d.FrameworkElement.n_onMeasure(Native Method)
	at crc64122dcf5ad656876d.FrameworkElement.onMeasure(FrameworkElement.java:60)
	at android.view.View.measure(View.java:18926)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5908)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
	at android.view.View.measure(View.java:18926)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5908)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:721)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
	at android.view.View.measure(View.java:18926)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5908)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
	at android.view.View.measure(View.java:18926)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5908)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:721)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
	at android.view.View.measure(View.java:18926)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5908)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:3076)
	at android.view.View.measure(View.java:18926)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2403)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1421)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1669)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1306)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7031)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:821)
	at android.view.Choreographer.doCallbacks(Choreographer.java:606)
	at android.view.Choreographer.doFrame(Choreographer.java:576)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:807)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6914)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
   at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <365a6962c3c943c9bef39bcfc052d252>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeAbstractObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00014] in <365a6962c3c943c9bef39bcfc052d252>:0 
  at AndroidX.RecyclerView.Widget.RecyclerView+Recycler.GetViewForPosition (System.Int32 position) [0x00022] in <934637245da64b148fe94c410d26de8e>:0 
  at Uno.UI.Extensions.RecyclerExtensions.GetViewForPosition (AndroidX.RecyclerView.Widget.RecyclerView+Recycler recycler, System.Int32 position, AndroidX.RecyclerView.Widget.RecyclerView+State state) [0x0002e] in <db14ec18228a486b83dcfd375d53c9ce>:0 
  at Windows.UI.Xaml.Controls.BufferViewCache.PrefetchView (AndroidX.RecyclerView.Widget.RecyclerView+Recycler recycler, AndroidX.RecyclerView.Widget.RecyclerView+State state, System.Int32 displayPosition) [0x0001b] in <db14ec18228a486b83dcfd375d53c9ce>:0 
  at Windows.UI.Xaml.Controls.BufferViewCache.<PrefetchViews>g__PrefetchExtra|49_2 (Windows.UI.Xaml.Controls.BufferViewCache+<>c__DisplayClass49_0& ) [0x0003e] in <db14ec18228a486b83dcfd375d53c9ce>:0 
  at Windows.UI.Xaml.Controls.BufferViewCache.PrefetchViews (AndroidX.RecyclerView.Widget.RecyclerView+Recycler recycler, AndroidX.RecyclerView.Widget.RecyclerView+State state) [0x00046] in <db14ec18228a486b83dcfd375d53c9ce>:0 
  at Windows.UI.Xaml.Controls.BufferViewCache.UpdateBuffers (AndroidX.RecyclerView.Widget.RecyclerView+Recycler recycler, AndroidX.RecyclerView.Widget.RecyclerView+State state) [0x00029] in <db14ec18228a486b83dcfd375d53c9ce>:0 
  at Windows.UI.Xaml.Controls.VirtualizingPanelLayout.UpdateBuffers (AndroidX.RecyclerView.Widget.RecyclerView+Recycler recycler, AndroidX.RecyclerView.Widget.RecyclerView+State state) [0x0000c] in <db14ec18228a486b83dcfd375d53c9ce>:0 
  at Windows.UI.Xaml.Controls.VirtualizingPanelLayout.UpdateLayout (Windows.UI.Xaml.Controls.Primitives.GeneratorDirection direction, System.Int32 availableExtent, System.Int32 availableBreadth, AndroidX.RecyclerView.Widget.RecyclerView+Recycler recycler, AndroidX.RecyclerView.Widget.RecyclerView+State state, System.Boolean isMeasure) [0x000da] in <db14ec18228a486b83dcfd375d53c9ce>:0 
  at Windows.UI.Xaml.Controls.VirtualizingPanelLayout.OnMeasure (AndroidX.RecyclerView.Widget.RecyclerView+Recycler recycler, AndroidX.RecyclerView.Widget.RecyclerView+State state, System.Int32 widthSpec, System.Int32 heightSpec) [0x0003e] in <db14ec18228a486b83dcfd375d53c9ce>:0 
  --- End of managed Java.Lang.IndexOutOfBoundsException stack trace ---
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 18(offset:18).state:50 crc64a5a37c43dff01024.NativeListViewBase{86e8a2a VFED.V.. ......ID 0,0-800,1097}, adapter:crc64a5a37c43dff01024.NativeListViewBaseAdapter@124af91, layout:Windows.UI.Xaml.Controls.ItemsStackPanelLayout, context:OnBoardRemote.Droid.MainActivity
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6183)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
	at crc64a5a37c43dff01024.VirtualizingPanelLayout.n_onMeasure(Native Method)
	at crc64a5a37c43dff01024.VirtualizingPanelLayout.onMeasure(VirtualizingPanelLayout.java:113)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3593)
	at android.view.View.measure(View.java:18926)
	at crc64122dcf5ad656876d.FrameworkElement.n_onMeasure(Native Method)
	at crc64122dcf5ad656876d.FrameworkElement.onMeasure(FrameworkElement.java:60)
	at android.view.View.measure(View.java:18926)
	at crc64122dcf5ad656876d.FrameworkElement.n_onMeasure(Native Method)
	at crc64122dcf5ad656876d.FrameworkElement.onMeasure(FrameworkElement.java:60)
	at android.view.View.measure(View.java:18926)
	at crc64122dcf5ad656876d.FrameworkElement.n_onMeasure(Native Method)
	at crc64122dcf5ad656876d.FrameworkElement.onMeasure(FrameworkElement.java:60)
	at android.view.View.measure(View.java:18926)
	at crc64122dcf5ad656876d.FrameworkElement.n_onMeasure(Native Method)
	at crc64122dcf5ad656876d.FrameworkElement.onMeasure(FrameworkElement.java:60)
	at android.view.View.measure(View.java:18926)
	at crc64a5a37c43dff01024.ItemsControl.n_onMeasure(Native Method)
	at crc64a5a37c43dff01024.ItemsControl.onMeasure(ItemsControl.java:29)
	at android.view.View.measure(View.java:18926)
	at crc64122dcf5ad656876d.FrameworkElement.n_onMeasure(Native Method)
	at crc64122dcf5ad656876d.FrameworkElement.onMeasure(FrameworkElement.java:60)
	at android.view.View.measure(View.java:18926)
	at crc64122dcf5ad656876d.FrameworkElement.n_onMeasure(Native Method)
	at crc64122dcf5ad656876d.FrameworkElement.onMeasure(FrameworkElement.java:60)
	at android.view.View.measure(View.java:18926)
	at crc64122dcf5ad656876d.FrameworkElement.n_onMeasure(Native Method)
	at crc64122dcf5ad656876d.FrameworkElement.onMeasure(FrameworkElement.java:60)
	at android.view.View.measure(View.java:18926)
	at crc64122dcf5ad656876d.FrameworkElement.n_onMeasure(Native Method)
	at crc64122dcf5ad656876d.FrameworkElement.onMeasure(FrameworkElement.java:60)
	at android.view.View.measure(View.java:18926)
	at crc64122dcf5ad656876d.FrameworkElement.n_onMeasure(Native Method)
	at crc64122dcf5ad656876d.FrameworkElement.onMeasure(FrameworkElement.java:60)
	at android.view.View.measure(View.java:18926)
	at crc64122dcf5ad656876d.FrameworkElement.n_onMeasure(Native Method)
	at crc64122dcf5ad656876d.FrameworkElement.onMeasure(FrameworkElement.java:60)
	at android.view.View.measure(View.java:18926)
	at crc64122dcf5ad656876d.FrameworkElement.n_onMeasure(Native Method)
	at crc64122dcf5ad656876d.FrameworkElement.onMeasure(FrameworkElement.java:60)
	at android.view.View.measure(View.java:18926)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5908)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
	at android.view.View.measure(View.java:18926)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5908)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:721)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
	at android.view.View.measure(View.java:18926)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5908)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
	at android.view.View.measure(View.java:18926)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5908)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:721)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
	at android.view.View.measure(View.java:18926)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5908)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:3076)
	at android.view.View.measure(View.java:18926)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2403)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1421)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1669)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1306)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7031)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:821)
	at android.view.Choreographer.doCallbacks(Choreographer.java:606)
	at android.view.Choreographer.doFrame(Choreographer.java:576)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:807)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6914)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by jeromelaban** [comment]
We've made many changes in listview since this issue was opened, and this have been fixed. I'm going to close this issue for now. You can reopen as needed.
