### ISSUE TITLE
Exception keeps occuring in Web Browser Console :: Failed to raise 'PointerEnteredEvent'

### ISSUE THREAD

**Issue by sigmarsson** [unoplatform/uno#6051]
## Failed to raise 'PointerEnteredEvent'

![image](https://user-images.githubusercontent.com/43340959/119051535-971db580-b9c3-11eb-8081-63dc44e567e5.png)

Stack trace in browser Console:

```
Failed to raise 'PointerEnteredEvent': System.NullReferenceException: Object reference not set to an instance of an object.
         at Uno.UI.DataBinding.BindingPropertyHelper.InternalGetValueGetter(Type type, String property, Nullable`1 precedence, Boolean allowPrivateMembers) in C:\a\1\s\src\Uno.UI\DataBinding\BindingPropertyHelper.cs:line 592
         at Uno.UI.DataBinding.BindingPropertyHelper.GetValueGetter(Type type, String property, Nullable`1 precedence, Boolean allowPrivateMembers) in C:\a\1\s\src\Uno.UI\DataBinding\BindingPropertyHelper.cs:line 136
         at Uno.UI.DataBinding.BindingPath.BindingItem.BuildValueGetter() in C:\a\1\s\src\Uno.UI\DataBinding\BindingPath.cs:line 704
         at Uno.UI.DataBinding.BindingPath.BindingItem.GetSourceValue() in C:\a\1\s\src\Uno.UI\DataBinding\BindingPath.cs:line 727
         at Uno.UI.DataBinding.BindingPath.BindingItem.get_Value() in C:\a\1\s\src\Uno.UI\DataBinding\BindingPath.cs:line 508
         at Uno.UI.DataBinding.BindingPath.BindingItem.OnDataContextChanged() in C:\a\1\s\src\Uno.UI\DataBinding\BindingPath.cs:line 612
         at Uno.UI.DataBinding.BindingPath.BindingItem.SetWeakDataContext(ManagedWeakReference weakDataContext, Boolean transferReferenceOwnership) in C:\a\1\s\src\Uno.UI\DataBinding\BindingPath.cs:line 491
         at Uno.UI.DataBinding.BindingPath.OnDataContextChanged() in C:\a\1\s\src\Uno.UI\DataBinding\BindingPath.cs:line 246
         at Uno.UI.DataBinding.BindingPath.SetWeakDataContext(ManagedWeakReference weakDataContext) in C:\a\1\s\src\Uno.UI\DataBinding\BindingPath.cs:line 233
         at Uno.UI.DataBinding.BindingPath.set_DataContext(Object value) in C:\a\1\s\src\Uno.UI\DataBinding\BindingPath.cs:line 223
         at Microsoft.UI.Xaml.Setter.TryGetOrCreateBindingPath(DependencyPropertyValuePrecedences precedence, IFrameworkElement owner) in C:\a\1\s\src\Uno.UI\UI\Xaml\Setter.cs:line 176
         at Microsoft.UI.Xaml.Setter.ApplyValue(DependencyPropertyValuePrecedences precedence, IFrameworkElement owner) in C:\a\1\s\src\Uno.UI\UI\Xaml\Setter.cs:line 115
         at Microsoft.UI.Xaml.VisualStateGroup.GoToState(IFrameworkElement element, VisualState state, VisualState originalState, Boolean useTransitions, Action onStateChanged) in C:\a\1\s\src\Uno.UI\UI\Xaml\VisualStateGroup.cs:line 276
         at Microsoft.UI.Xaml.VisualStateManager.GoToStateCore(Control control, IFrameworkElement templateRoot, String stateName, VisualStateGroup group, VisualState state, Boolean useTransitions) in C:\a\1\s\src\Uno.UI\UI\Xaml\VisualStateManager.cs:line 220
         at Microsoft.UI.Xaml.VisualStateManager.GoToState(Control control, String stateName, Boolean useTransitions) in C:\a\1\s\src\Uno.UI\UI\Xaml\VisualStateManager.cs:line 164
         at Microsoft.UI.Xaml.Controls.NavigationViewItem.UpdateVisualStateForPointer() in C:\a\1\s\src\Uno.UI\Microsoft\UI\Xaml\Controls\NavigationView\NavigationViewItem.cs:line 505
         at Microsoft.UI.Xaml.Controls.NavigationViewItem.UpdateVisualState(Boolean useTransitions) in C:\a\1\s\src\Uno.UI\Microsoft\UI\Xaml\Controls\NavigationView\NavigationViewItem.cs:line 521
         at Microsoft.UI.Xaml.Controls.NavigationViewItem.ProcessPointerOver(PointerRoutedEventArgs args) in C:\a\1\s\src\Uno.UI\Microsoft\UI\Xaml\Controls\NavigationView\NavigationViewItem.cs:line 971
         at Microsoft.UI.Xaml.Controls.NavigationViewItem.OnPresenterPointerEntered(Object sender, PointerRoutedEventArgs args) in C:\a\1\s\src\Uno.UI\Microsoft\UI\Xaml\Controls\NavigationView\NavigationViewItem.cs:line 877
         at Microsoft.UI.Xaml.UIElement.InvokeHandler(Object handler, RoutedEventArgs args) in C:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.RoutedEvents.cs:line 826
         at Microsoft.UI.Xaml.UIElement.RaiseEvent(RoutedEvent routedEvent, RoutedEventArgs args, BubblingContext ctx) in C:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.RoutedEvents.cs:line 613
         at Microsoft.UI.Xaml.UIElement.RaisePointerEvent(RoutedEvent evt, PointerRoutedEventArgs args) in C:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.Pointers.cs:line 933

```

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [x] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
<PackageReference Include="Microsoft.Extensions.Logging" Version="5.0.0" />
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="5.0.2" />
    <PackageReference Include="Ninject" Version="3.3.4" />
    <PackageReference Include="Uno.Extensions.Logging.WebAssembly.Console" Version="1.0.1" />
    <PackageReference Include="Uno.WinUI.WebAssembly" Version="3.7.4" />
    <PackageReference Include="Uno.WinUI.RemoteControl" Version="3.7.4" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="2.1.0" />
    <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="2.1.0" />

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 2019 16.10 Preview 4)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report. Are you able to reproduce this in a sample application ?

**Comment by sigmarsson** [comment]
@jeromelaban [6051](https://github.com/sigmarsson/6051)


![image](https://user-images.githubusercontent.com/43340959/119231950-86845100-bb23-11eb-96c8-1c8f7ec004a5.png)
