### ISSUE TITLE
TargetInvocationException while debugging Windows Desktop Application

### ISSUE THREAD

**Issue by sharpninja** [unoplatform/uno#6064]
## Current behavior

When trying to debug the Windows Desktop version of my app, I get a `TargetInvocationException` during startup:

```
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache) in /_/src/coreclr/src/System.Private.CoreLib/src/System/RuntimeType.CoreCLR.cs:line 4005
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions) in /_/src/coreclr/src/System.Private.CoreLib/src/System/RuntimeType.CoreCLR.cs:line 4062
   at System.Activator.CreateInstance[T]() in /_/src/libraries/System.Private.CoreLib/src/System/Activator.RuntimeType.cs:line 151
   at WinRT.WeakLazy`1.get_Value()
   at Microsoft.UI.Xaml.Application._IApplicationStatics.get_Instance()
   at Microsoft.UI.Xaml.Application.Start(ApplicationInitializationCallback callback)
   at ArchMastery.Program.Main(String[] args) in C:\GitHub\SharpNinja\ArchMastery\src\ArchMastery.Windows.Desktop\obj\x64\Debug\net5.0-windows10.0.19041\win-x64\App.g.i.cs:line 31
```

## Expected behavior

App would startup without error.

## How to reproduce it (as minimally and precisely as possible)

1. Clone or Fork `https://github.com/ArchMastery/ArchMastery.Desktop`
2. Checkout commit `8b4a1f358363cd517905bfa802c8d9198495e335`
3. Open `ArchMastery.sln` in Visual Studio 2019 v16.10.

## Workaround

None.

## Environment

Nuget Package:
- [X] Uno.WinUI 

Nuget Package Version(s): 3.7.4

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [X] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: 16.10.0 Preview 3.0)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

Cannot get Uno Platform to build locally.

**Comment by sharpninja** [comment]
smaller example of the error: https://github.com/sharpninja/uno_error.git

**Comment by jeromelaban** [comment]
Thanks for the report. The Windows side of the solution is not something Uno can address. The only thing we can suggest is to remove code from the app until it starts working to isolate the issue.

**Comment by sharpninja** [comment]
What repo should I ask in?
