### ISSUE TITLE
Navigate to a page with InfoBar in WPF, and then throw an error.

### ISSUE THREAD

**Issue by Aloento** [unoplatform/uno#6165]
## Current behavior

**Navigate to a page with InfoBar in WPF, and then throw an error.**
The page will not load correctly.

`"The Dependency Property [TextTrimming] is owned by [Windows.UI.Xaml.Controls.TextBlock] and cannot be used on [Microsoft.UI.Xaml.Controls.InfoBar]"`

![image](https://user-images.githubusercontent.com/11802769/120878188-05b16480-c5bb-11eb-84a8-9bbb5e3b7a5b.png)

## Expected behavior

This error does not occur in UWP, and the page loads normally.

## How to reproduce it (as minimally and precisely as possible)
`git clone git@github.com:Aloento/YourWaifu2x.git`
Open `YourWaifu2x.sln`
Debug `YourWaifu2x.Skia.Wpf.Host`
Navigate to `SelectingImages`

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [x] Uno.SourceGenerationTasks
- [x] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [x] Skia
  - [x] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

```
   at Windows.UI.Xaml.DependencyObjectStore.InnerSetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isThemeBinding) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 459
   at Windows.UI.Xaml.DependencyObjectStore.SetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isThemeBinding) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 432
   at Windows.UI.Xaml.DependencyObjectStore.SetValue(DependencyProperty property, Object value) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 394
   at Windows.UI.Xaml.UIElement.SetValue(DependencyProperty dp, Object value) in C:\a\1\s\src\Uno.UI\obj\Uno.UI.Skia\Release\netstandard2.0\g\DependencyObjectGenerator\Windows_UI_Xaml_UIElement_85915f7d6b7124464cf9d270ce415b49.g.cs:line 47
   at Windows.UI.Xaml.Setter.ApplyTo(DependencyObject o) in C:\a\1\s\src\Uno.UI\UI\Xaml\Setter.cs:line 104
   at Windows.UI.Xaml.Style.ApplyTo(DependencyObject o, DependencyPropertyValuePrecedences precedence) in C:\a\1\s\src\Uno.UI\UI\Xaml\Style\Style.cs:line 70
   at Windows.UI.Xaml.FrameworkElement.OnStyleChanged(Style oldStyle, Style newStyle, DependencyPropertyValuePrecedences precedence) in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.cs:line 545
   at Windows.UI.Xaml.FrameworkElement.ApplyStyle() in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.cs:line 390
   at Windows.UI.Xaml.FrameworkElement.ApplyStyles() in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.cs:line 323
   at Windows.UI.Xaml.FrameworkElement.CreationComplete() in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.cs:line 342
   at YourWaifu2x.Skia.WPF.__Resources._ContentPageLayout_9125e536a8d260bf21c57f647560e1b1_ContentPageLayoutRDSC0.<>c.<Build>b__0_10(InfoBar c9) in C:\Codes\C#\YourWaifu2x\YourWaifu2x.Skia.WPF\obj\Debug\netstandard2.0\g\XamlCodeGenerator\ContentPageLayout_9125e536a8d260bf21c57f647560e1b1.g.cs:line 344
   at YourWaifu2x.Skia.WPF.__Resources._ContentPageLayout_9125e536a8d260bf21c57f647560e1b1_ContentPageLayoutRDSC0.Build(Object __ResourceOwner_13) in C:\Codes\C#\YourWaifu2x\YourWaifu2x.Skia.WPF\obj\Debug\netstandard2.0\g\XamlCodeGenerator\ContentPageLayout_9125e536a8d260bf21c57f647560e1b1.g.cs:line 146
   at YourWaifu2x.Skia.WPF.GlobalStaticResources.ResourceDictionarySingleton__2.<>c.<Get_2_1>b__7_1(Object __owner) in C:\Codes\C#\YourWaifu2x\YourWaifu2x.Skia.WPF\obj\Debug\netstandard2.0\g\XamlCodeGenerator\ContentPageLayout_9125e536a8d260bf21c57f647560e1b1.g.cs:line 80
   at Windows.UI.Xaml.FrameworkTemplate.LoadContent() in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkTemplate.cs:line 97
   at Windows.UI.Xaml.FrameworkTemplatePool.DequeueTemplate(FrameworkTemplate template) in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkTemplatePool.cs:line 186
   at Windows.UI.Xaml.FrameworkTemplate.LoadContentCached() in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkTemplate.cs:line 73
   at Windows.UI.Xaml.Controls.Control.UpdateTemplate() in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Control\Control.cs:line 463
   at Windows.UI.Xaml.Controls.Control.SetUpdateControlTemplate(Boolean forceUpdate) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Control\Control.cs:line 131
   at Windows.UI.Xaml.Controls.Control.OnTemplateChanged(DependencyPropertyChangedEventArgs e) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Control\Control.cs:line 113
   at Windows.UI.Xaml.Controls.Control.<>c.<.cctor>b__344_0(DependencyObject s, DependencyPropertyChangedEventArgs e) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Control\Control.cs:line 107
   at Windows.UI.Xaml.PropertyMetadata.RaisePropertyChanged(DependencyObject source, DependencyPropertyChangedEventArgs e) in C:\a\1\s\src\Uno.UI\UI\Xaml\PropertyMetadata.cs:line 188
   at Windows.UI.Xaml.DependencyObjectStore.InvokeCallbacks(DependencyObject actualInstanceAlias, DependencyProperty property, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence, Boolean bypassesPropagation) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 1627
   at Windows.UI.Xaml.DependencyObjectStore.RaiseCallbacks(DependencyObject actualInstanceAlias, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 1534
   at Windows.UI.Xaml.DependencyObjectStore.InnerSetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isThemeBinding) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 497
   at Windows.UI.Xaml.DependencyObjectStore.SetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isThemeBinding) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 432
   at Windows.UI.Xaml.DependencyObjectStore.SetValue(DependencyProperty property, Object value) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 394
   at Windows.UI.Xaml.UIElement.SetValue(DependencyProperty dp, Object value) in C:\a\1\s\src\Uno.UI\obj\Uno.UI.Skia\Release\netstandard2.0\g\DependencyObjectGenerator\Windows_UI_Xaml_UIElement_85915f7d6b7124464cf9d270ce415b49.g.cs:line 47
   at Windows.UI.Xaml.Setter.ApplyTo(DependencyObject o) in C:\a\1\s\src\Uno.UI\UI\Xaml\Setter.cs:line 104
   at Windows.UI.Xaml.Style.ApplyTo(DependencyObject o, DependencyPropertyValuePrecedences precedence) in C:\a\1\s\src\Uno.UI\UI\Xaml\Style\Style.cs:line 70
   at Windows.UI.Xaml.FrameworkElement.OnStyleChanged(Style oldStyle, Style newStyle, DependencyPropertyValuePrecedences precedence) in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.cs:line 545
   at Windows.UI.Xaml.FrameworkElement.ApplyStyle() in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.cs:line 390
   at Windows.UI.Xaml.FrameworkElement.ApplyStyles() in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.cs:line 323
   at Windows.UI.Xaml.FrameworkElement.CreationComplete() in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.cs:line 342
   at YourWaifu2x.Views.MyPages.SettingWaifu2x.<>c__DisplayClass9_0.<InitializeComponent>b__4(ContentPageLayout c48) in C:\Codes\C#\YourWaifu2x\YourWaifu2x.Skia.WPF\obj\Debug\netstandard2.0\g\XamlCodeGenerator\SettingWaifu2x_4117da5cb42f05a6473bf9e125c26087.g.cs:line 953
   at YourWaifu2x.Views.MyPages.SettingWaifu2x.InitializeComponent() in C:\Codes\C#\YourWaifu2x\YourWaifu2x.Skia.WPF\obj\Debug\netstandard2.0\g\XamlCodeGenerator\SettingWaifu2x_4117da5cb42f05a6473bf9e125c26087.g.cs:line 56
   at YourWaifu2x.Views.MyPages.SettingWaifu2x..ctor() in C:\Codes\C#\YourWaifu2x\YourWaifu2x.Shared\Views\MyPages\SettingWaifu2x.xaml.cs:line 11   at Windows.UI.Xaml.DependencyObjectStore.InnerSetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isThemeBinding) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 459
   at Windows.UI.Xaml.DependencyObjectStore.SetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isThemeBinding) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 432
   at Windows.UI.Xaml.DependencyObjectStore.SetValue(DependencyProperty property, Object value) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 394
   at Windows.UI.Xaml.UIElement.SetValue(DependencyProperty dp, Object value) in C:\a\1\s\src\Uno.UI\obj\Uno.UI.Skia\Release\netstandard2.0\g\DependencyObjectGenerator\Windows_UI_Xaml_UIElement_85915f7d6b7124464cf9d270ce415b49.g.cs:line 47
   at Windows.UI.Xaml.Setter.ApplyTo(DependencyObject o) in C:\a\1\s\src\Uno.UI\UI\Xaml\Setter.cs:line 104
   at Windows.UI.Xaml.Style.ApplyTo(DependencyObject o, DependencyPropertyValuePrecedences precedence) in C:\a\1\s\src\Uno.UI\UI\Xaml\Style\Style.cs:line 70
   at Windows.UI.Xaml.FrameworkElement.OnStyleChanged(Style oldStyle, Style newStyle, DependencyPropertyValuePrecedences precedence) in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.cs:line 545
   at Windows.UI.Xaml.FrameworkElement.ApplyStyle() in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.cs:line 390
   at Windows.UI.Xaml.FrameworkElement.ApplyStyles() in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.cs:line 323
   at Windows.UI.Xaml.FrameworkElement.CreationComplete() in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.cs:line 342
   at YourWaifu2x.Skia.WPF.__Resources._ContentPageLayout_9125e536a8d260bf21c57f647560e1b1_ContentPageLayoutRDSC0.<>c.<Build>b__0_10(InfoBar c9) in C:\Codes\C#\YourWaifu2x\YourWaifu2x.Skia.WPF\obj\Debug\netstandard2.0\g\XamlCodeGenerator\ContentPageLayout_9125e536a8d260bf21c57f647560e1b1.g.cs:line 344
   at YourWaifu2x.Skia.WPF.__Resources._ContentPageLayout_9125e536a8d260bf21c57f647560e1b1_ContentPageLayoutRDSC0.Build(Object __ResourceOwner_13) in C:\Codes\C#\YourWaifu2x\YourWaifu2x.Skia.WPF\obj\Debug\netstandard2.0\g\XamlCodeGenerator\ContentPageLayout_9125e536a8d260bf21c57f647560e1b1.g.cs:line 146
   at YourWaifu2x.Skia.WPF.GlobalStaticResources.ResourceDictionarySingleton__2.<>c.<Get_2_1>b__7_1(Object __owner) in C:\Codes\C#\YourWaifu2x\YourWaifu2x.Skia.WPF\obj\Debug\netstandard2.0\g\XamlCodeGenerator\ContentPageLayout_9125e536a8d260bf21c57f647560e1b1.g.cs:line 80
   at Windows.UI.Xaml.FrameworkTemplate.LoadContent() in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkTemplate.cs:line 97
   at Windows.UI.Xaml.FrameworkTemplatePool.DequeueTemplate(FrameworkTemplate template) in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkTemplatePool.cs:line 186
   at Windows.UI.Xaml.FrameworkTemplate.LoadContentCached() in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkTemplate.cs:line 73
   at Windows.UI.Xaml.Controls.Control.UpdateTemplate() in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Control\Control.cs:line 463
   at Windows.UI.Xaml.Controls.Control.SetUpdateControlTemplate(Boolean forceUpdate) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Control\Control.cs:line 131
   at Windows.UI.Xaml.Controls.Control.OnTemplateChanged(DependencyPropertyChangedEventArgs e) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Control\Control.cs:line 113
   at Windows.UI.Xaml.Controls.Control.<>c.<.cctor>b__344_0(DependencyObject s, DependencyPropertyChangedEventArgs e) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Control\Control.cs:line 107
   at Windows.UI.Xaml.PropertyMetadata.RaisePropertyChanged(DependencyObject source, DependencyPropertyChangedEventArgs e) in C:\a\1\s\src\Uno.UI\UI\Xaml\PropertyMetadata.cs:line 188
   at Windows.UI.Xaml.DependencyObjectStore.InvokeCallbacks(DependencyObject actualInstanceAlias, DependencyProperty property, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence, Boolean bypassesPropagation) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 1627
   at Windows.UI.Xaml.DependencyObjectStore.RaiseCallbacks(DependencyObject actualInstanceAlias, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 1534
   at Windows.UI.Xaml.DependencyObjectStore.InnerSetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isThemeBinding) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 497
   at Windows.UI.Xaml.DependencyObjectStore.SetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isThemeBinding) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 432
   at Windows.UI.Xaml.DependencyObjectStore.SetValue(DependencyProperty property, Object value) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 394
   at Windows.UI.Xaml.UIElement.SetValue(DependencyProperty dp, Object value) in C:\a\1\s\src\Uno.UI\obj\Uno.UI.Skia\Release\netstandard2.0\g\DependencyObjectGenerator\Windows_UI_Xaml_UIElement_85915f7d6b7124464cf9d270ce415b49.g.cs:line 47
   at Windows.UI.Xaml.Setter.ApplyTo(DependencyObject o) in C:\a\1\s\src\Uno.UI\UI\Xaml\Setter.cs:line 104
   at Windows.UI.Xaml.Style.ApplyTo(DependencyObject o, DependencyPropertyValuePrecedences precedence) in C:\a\1\s\src\Uno.UI\UI\Xaml\Style\Style.cs:line 70
   at Windows.UI.Xaml.FrameworkElement.OnStyleChanged(Style oldStyle, Style newStyle, DependencyPropertyValuePrecedences precedence) in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.cs:line 545
   at Windows.UI.Xaml.FrameworkElement.ApplyStyle() in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.cs:line 390
   at Windows.UI.Xaml.FrameworkElement.ApplyStyles() in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.cs:line 323
   at Windows.UI.Xaml.FrameworkElement.CreationComplete() in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.cs:line 342
   at YourWaifu2x.Views.MyPages.SettingWaifu2x.<>c__DisplayClass9_0.<InitializeComponent>b__4(ContentPageLayout c48) in C:\Codes\C#\YourWaifu2x\YourWaifu2x.Skia.WPF\obj\Debug\netstandard2.0\g\XamlCodeGenerator\SettingWaifu2x_4117da5cb42f05a6473bf9e125c26087.g.cs:line 953
   at YourWaifu2x.Views.MyPages.SettingWaifu2x.InitializeComponent() in C:\Codes\C#\YourWaifu2x\YourWaifu2x.Skia.WPF\obj\Debug\netstandard2.0\g\XamlCodeGenerator\SettingWaifu2x_4117da5cb42f05a6473bf9e125c26087.g.cs:line 56
   at YourWaifu2x.Views.MyPages.SettingWaifu2x..ctor() in C:\Codes\C#\YourWaifu2x\YourWaifu2x.Shared\Views\MyPages\SettingWaifu2x.xaml.cs:line 11
```

**Comment by MartinZikmund** [comment]
I checked the code and think the problem was here:

```
<InfoBar Style="{StaticResource MaterialSubtitle1}" />
```

Where `MaterialSubtitle1` is actually a `Style` which has `TargetType` of `TextBlock`. This is not allowed and hence the exception. Verifying on UWP I get the same behavior too, so this should be ok.
