### ISSUE TITLE
CalendarDatePicker in Flyout on Android 8.1 doesn't work

### ISSUE THREAD

**Issue by pkar70** [unoplatform/uno#6312]
## Current behavior
I cannot select/change date in CalendarDatePicker.
Flyout with CDP is opened, it shows current date (as it is set in code), but when I try to tap it to change date, nothing happens.

## Expected behavior
I should be able to use CalendarDatePicker

## How to reproduce it (as minimally and precisely as possible)
As "depth" inside XAML maybe influence this behaviour:

    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}" Name="uiGrid" SizeChanged="uiGrid_Resized">
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto"/>
            <RowDefinition Height="*"/>
            <RowDefinition Height="Auto" />
        </Grid.RowDefinitions>

        <TextBlock x:Uid="mpHeader" HorizontalAlignment="Center" Margin="0,10,0,15" Text="Anniversaries - today in history" VerticalAlignment="Center" FontSize="24"/>
        <Grid Name="naView" Grid.Row="1" >
            <WebView Name="wbViewer" Margin="5,10,5,10" HorizontalAlignment="Stretch" VerticalAlignment="Stretch" />
            <ProgressBar HorizontalAlignment="Stretch" Visibility="Collapsed" VerticalAlignment="Bottom" Name="uiProgBar"/>
        </Grid>

        <not_win:Grid Grid.Row="2" Name="uiAndroBottom" Margin="0,10,0,0">
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="120" />
                <ColumnDefinition Width="*" />
            </Grid.ColumnDefinitions>
            <TextBlock Text=" " Name="tbDzien" Margin="20,0,0,0" VerticalAlignment="Center" />
            <StackPanel Orientation="Horizontal" Grid.Column="1">

                <AppBarSeparator Name="uiBarSeparat1"/>
                <AppBarButton x:Uid="bRefresh" Name="bRefresh"  Icon="Refresh" Label="Wczytaj" Click="bRead_Click">
                </AppBarButton>
                <AppBarButton x:Uid="resDay" Label="Kalendarz" Icon="Calendar" Name="uiKalend">
                    <AppBarButton.Flyout>
                        <Flyout >
                            <CalendarDatePicker Name="uiDay" DateChanged="uiDay_Changed"/>
                        </Flyout>
                    </AppBarButton.Flyout>
                </AppBarButton>

## Workaround
None.

## Environment
Nuget Package:
- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
 3.8.6 and 3.9.0-dev83.

Affected platform(s):
- [ ] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: Version 16.9.4)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?
In "Output" window inside Visual Studio I get this:

[WindowClient] Add to mViews: android.widget.PopupWindow$PopupDecorView{8e6c6a5 V.E...... ......I. 0,0-0,0}, this = android.view.WindowManagerGlobal@87553a
[ViewRootImpl[PopupWindow:7fb7922]] hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
[41m[30mfail[39m[22m[49m: Windows.UI.Xaml.UIElement[0]
      Failed to raise 'PointerReleasedEvent': Android.Views.WindowManagerBadTokenException: Unable to add window -- token android.view.ViewRootImpl$W@3670a7a is not valid; is your activity running?
        at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <94b04e1756104d1fa1d144932ae2720c>:0 
        at Windows.UI.Xaml.Controls.Popup06-20 14:19:57.405 I/mono-stdout( 9478):         at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <94b04e1756104d1fa1d144932ae2720c>:0 
        at Android.Widget.PopupWindow.ShowAtLocation (Android.Views.View parent, Android.Views.GravityFlags gravity, System.Int32 x, System.Int32 y) [0x00067] in /Users/builder/azdo/_work/278/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-30/mcw/Android.Widget.PopupWindow.cs:2037 
        at Windows.UI.Xaml.Controls.Popup.OnIsOpenChangedNative (System.Boolean oldIsOpen, System.Boolean newIsOpen) [0x0000f] in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Popup\Popup.Android.cs:68 
        at Windows.UI.Xaml.Controls.Popup.OnIsOpenChanged (System.Boolean oldIsOpen, System.Boolean newIsOpen) [0x00040] in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Popup\Popup.WithPopupRoot.cs:79 
        at Windows.UI.Xaml.Controls.PopupBase+<>c.<.cctor>b__68_0 (Windows.UI.Xaml.DependencyObject s, Windows.UI.Xaml.DependencyPropertyChangedEventArgs e) [0x00000] in C:\a\1\s\src\Uno.UI\Mixins\DependencyPropertyMixins.g.cs:138 
        at Windows.UI.Xaml.PropertyMetadata.RaisePropertyChanged (Windows.UI.Xaml.DependencyObject source, Windows.UI.Xaml.DependencyPropertyChangedEventArgs e) [0x00000] in C:\a\1\s\src\Uno.UI\UI\Xaml\PropertyMetadata.cs:187 
        at Windows.UI.Xaml.DependencyObjectStore.InvokeCallbacks (Windows.UI.Xaml.DependencyObject actualInstanceAlias, Windows.UI.Xaml.DependencyProperty property, Windows.UI.Xaml.DependencyPropertyDetails propertyDetails, System.Object previousValue, Windows.UI.Xaml.DependencyPropertyValuePrecedences previousPrecedence, System.Object newValue, Windows.UI.Xaml.DependencyPropertyValuePrecedences newPrecedence, System.Boolean bypassesPropagation) [0x000e0] in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:1624 
        at Windows.UI.Xaml.DependencyObjectStore.RaiseCallbacks (Windows.UI.Xaml.DependencyObject actualInstanceAlias, Windows.UI.Xaml.DependencyPropertyDetails propertyDetails, System.Object previousValue, Windows.UI.Xaml.DependencyPropertyValuePrecedences previousPrecedence, System.Object newValue, Windows.UI.Xaml.DependencyPropertyValuePrecedences newPrecedence) [0x0005b] in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:1534 
        at Windows.UI.Xaml.DependencyObjectStore.InnerSetValue (Windows.UI.Xaml.DependencyProperty property, System.Object value, Windows.UI.Xaml.DependencyPropertyValuePrecedences precedence, Windows.UI.Xaml.DependencyPropertyDetails propertyDetails, System.Boolean isThemeBinding) [0x001b4] in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:496 
        at Windows.UI.Xaml.DependencyObjectStore.SetValue (Windows.UI.Xaml.DependencyProperty property, System.Object value, Windows.UI.Xaml.DependencyPropertyValuePrecedences precedence, Windows.UI.Xaml.DependencyPropertyDetails propertyDetails, System.Boolean isThemeBinding) [0x00030] in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:429 
        at Windows.UI.Xaml.DependencyObjectStore.SetValue (Windows.UI.Xaml.DependencyProperty property, System.Object value) [0x00000] in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:393 
        at Uno.UI.Controls.BindableView.SetValue (Windows.UI.Xaml.DependencyProperty dp, System.Object value) [0x00000] in C:\a\1\s\src\Uno.UI\obj\Release\MonoAndroid11.0\g\DependencyObjectGenerator\Uno_UI_Controls_BindableView_eefac468be1af0c618115e95339af76c.g.cs:47 
        at Windows.UI.Xaml.Controls.PopupBase.set_IsOpen (System.Boolean value) [0x00000] in C:\a\1\s\src\Uno.UI\Mixins\DependencyPropertyMixins.g.cs:127 
        at Windows.UI.Xaml.Controls.Primitives.FlyoutBase.Open () [0x00018] in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Flyout\FlyoutBase.cs:291 
        at Windows.UI.Xaml.Controls.Flyout.Open () [0x00000] in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Flyout\Flyout.cs:103 
        at Windows.UI.Xaml.Controls.Primitives.FlyoutBase.ShowAt (Windows.UI.Xaml.FrameworkElement placementTarget) [0x00000] in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Flyout\FlyoutBase.cs:206 
        at Windows.UI.Xaml.Controls.CalendarDatePicker.UpdateCalendarVisibility () [0x0001c] in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\CalendarView\calendardatepicker_partial.cs:440 
        at Windows.UI.Xaml.Controls.CalendarDatePicker.OnPropertyChanged2 (Windows.UI.Xaml.DependencyPropertyChangedEventArgs args) [0x0000d] in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\CalendarView\calendardatepicker_partial.cs:101 
        at Windows.UI.Xaml.DependencyObjectStore.InvokeCallbacks (Windows.UI.Xaml.DependencyObject actualInstanceAlias, Windows.UI.Xaml.DependencyProperty property, Windows.UI.Xaml.DependencyPropertyDetails propertyDetails, System.Object previousValue, Windows.UI.Xaml.DependencyPropertyValuePrecedences previousPrecedence, System.Object newValue, Windows.UI.Xaml.DependencyPropertyValuePrecedences newPrecedence, System.Boolean bypassesPropagation) [0x000f4] in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:1629 
        at Windows.UI.Xaml.DependencyObjectStore.RaiseCallbacks (Windows.UI.Xaml.DependencyObject actualInstanceAlias, Windows.UI.Xaml.DependencyPropertyDetails propertyDetails, System.Object previousValue, Windows.UI.Xaml.DependencyPropertyValuePrecedences previousPrecedence, System.Object newValue, Windows.UI.Xaml.DependencyPropertyValuePrecedences newPrecedence) [0x0005b] in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:1534 
        at Windows.UI.Xaml.DependencyObjectStore.InnerSetValue (Windows.UI.Xaml.DependencyProperty property, System.Object value, Windows.UI.Xaml.DependencyPropertyValuePrecedences precedence, Windows.UI.Xaml.DependencyPropertyDetails propertyDetails, System.Boolean isThemeBinding) [0x001b4] in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:496 
        at Windows.UI.Xaml.DependencyObjectStore.SetValue (Windows.UI.Xaml.DependencyProperty property, System.Object value, Windows.UI.Xaml.DependencyPropertyValuePrecedences precedence, Windows.UI.Xaml.DependencyPropertyDetails propertyDetails, System.Boolean isThemeBinding) [0x00030] in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:429 
        at Windows.UI.Xaml.DependencyObjectStore.SetValue (Windows.UI.Xaml.DependencyProperty property, System.Object value) [0x00000] in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:393 
        at Uno.UI.Controls.BindableView.SetValue (Windows.UI.Xaml.DependencyProperty dp, System.Object value) [0x00000] in C:\a\1\s\src\Uno.UI\obj\Release\MonoAndroid11.0\g\DependencyObjectGenerator\Uno_UI_Controls_BindableView_eefac468be1af0c618115e95339af76c.g.cs:47 
        at Windows.UI.Xaml.Controls.CalendarDatePicker.set_IsCalendarOpen (System.Boolean value) [0x00000] in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\CalendarView\CalendarDatePicker.Properties.cs:112 
        at Windows.UI.Xaml.Controls.CalendarDatePicker.PerformPointerUpAction () [0x0000f] in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\CalendarView\calendardatepicker_partial.cs:942 
        at Windows.UI.Xaml.Controls.CalendarDatePicker.OnPointerReleased (Windows.UI.Xaml.Input.PointerRoutedEventArgs pArgs) [0x0008f] in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\CalendarView\calendardatepicker_partial.cs:803 
        at Windows.UI.Xaml.Controls.Control+<>c.<.cctor>b__349_11 (System.Object sender, Windows.UI.Xaml.Input.PointerRoutedEventArgs args) [0x00000] in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Control\Control.cs:875 
        at Windows.UI.Xaml.UIElement.InvokeHandler (System.Object handler, Windows.UI.Xaml.RoutedEventArgs args) [0x000e7] in C:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.RoutedEvents.cs:863 
        at Windows.UI.Xaml.UIElement.RaiseEvent (Windows.UI.Xaml.RoutedEvent routedEvent, Windows.UI.Xaml.RoutedEventArgs args, Windows.UI.Xaml.UIElement+BubblingContext ctx) [0x0008b] in C:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.RoutedEvents.cs:615 
        at Windows.UI.Xaml.UIElement.RaisePointerEvent (Windows.UI.Xaml.RoutedEvent evt, Windows.UI.Xaml.Input.PointerRoutedEventArgs args, Windows.UI.Xaml.UIElement+BubblingContext ctx) [0x0000d] in C:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.Pointers.cs:938 
        --- End of managed Android.Views.WindowManagerBadTokenException stack trace ---
      android.view.WindowManager$BadTokenException: Unable to add window -- token android.view.ViewRootImpl$W@3670a7a is not valid; is your activity running?
      	at android.view.ViewRootImpl.setView(ViewRootImpl.java:775)
      	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:359)
      	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
      	at android.widget.PopupWindow.invokePopup(PopupWindow.java:1433)
      	at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1203)
      	at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1170)
      	at crc64122dcf5ad656876d.UIElement.n_onNativeMotionEvent(Native Method)
      	at crc64122dcf5ad656876d.UIElement.onNativeMotionEvent(UIElement.java:48)
      	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:268)
      	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
      	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3022)
      	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
      	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
      	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
      	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
      	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
      	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3022)
      	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
      	at crc64a5a37c43dff01024.NativeScrollContentPresenter.n_dispatchTouchEvent(Native Method)
      	at crc64a5a37c43dff01024.NativeScrollContentPresenter.dispatchTouchEvent(NativeScrollContentPresenter.java:83)
      	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3022)
      	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
      	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
      	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
      	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
      	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
      	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3022)
      	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
      	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
      	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
      	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
      	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
      	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3022)
      	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
      	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
      	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
      	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
      	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
      	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3022)
      	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
      	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
      	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
      	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
      	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
      	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3022)
      	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
      	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
      	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
      	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
      	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
      	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3022)
      	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
      	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
      	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
      	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
      	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
      	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3022)
      	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
      	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3022)
      	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
      	at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2406)
      	at android.view.View.dispatchPointerEvent(View.java:12052)
      	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4967)
      	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4777)
      	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4309)
      	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4362)
      	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4328)
      	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4455)
      	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4336)
      	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4512)
      	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4309)
      	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4362)
      	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4328)
      	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4336)
      	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4309)
      	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6887)
      	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6861)
      	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6818)
      	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6998)
      	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
      	at android.os.MessageQueue.nativePollOnce(Native Method)
      	at android.os.MessageQueue.next(MessageQueue.java:325)
      	at android.os.Looper.loop(Looper.java:142)
      	at android.app.ActivityThread.main(ActivityThread.java:6523)
      	at java.lang.reflect.Method.invoke(Native Method)
      	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
      
[Choreographer] Skipped 55 frames!  The application may be doing too much work on its main thread.
[GraphicBuffer] register, handle(0x84809d80) (w:952 h:600 s:960 f:0x1 u:f02)
The thread 0x6 has exited with code 0 (0x0).
Thread finished: <Thread Pool> #6

**Comment by pkar70** [comment]
Can this bug get attention? :)

**Comment by jeromelaban** [comment]
This issue cannot be fixed by any android mean, because it's not supported the only way to work around it is to disable native popups, see https://github.com/unoplatform/uno/issues/1583#issuecomment-823242453.

**Comment by pkar70** [comment]
So, in some ways my implementation of CalendarDatePicker (#2079) was better :)
I will try `Uno.UI.FeatureConfiguration.Popup.UseNativePopup = false` when my Android tablet returns from service; now I have no Android device to try it.

**Comment by pkar70** [comment]
Yes, this workaround works in my app. Thank you.
I added `Uno.UI.FeatureConfiguration.Popup.UseNativePopup = false` in `X.Droid\Main.cs:Application`.
