### ISSUE TITLE
Telemetry reported unexpected exception in XamlFileGenerator

### ISSUE THREAD

**Issue by sharwell** [unoplatform/uno#6373]
Telemetry is reporting a relatively large number of cases where an unexpected exception is thrown by XamlFileGenerator and not handled. Source generators are expected to handle errors internally and report them (when necessary) as diagnostics. The diagnostic report looks like this (some sections have been `[redacted]`):

```
 System.Exception
 Processing failed for file [path\to]\App.xaml (System.InvalidOperationException: The reference [AssemblyName] could not be found in [AssemblyName]
    at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GenerateResourceLoader(IndentedStringBuilder writer)
    at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildApplicationInitializerBody(IndentedStringBuilder writer, XamlObjectDefinition topLevelControl)
    at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.InnerGenerateFile()
    at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GenerateFile())
 Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GenerateFile()
 Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGeneration.<>c__DisplayClass39_0.<Generate>b__1(XamlFileDefinition file)
 System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorResults.GetElement(Int32 index)
 System.Linq.Parallel.QueryResults`1.get_Item(Int32 index)
 System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
 System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
 System.Linq.Parallel.SpoolingTaskBase.Work()
 System.Linq.Parallel.QueryTask.BaseWork(Object unused)
 System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
 System.Threading.Tasks.Task.InnerInvoke()
 System.Threading.Tasks.Task.Execute()

     Inner Exception:
     System.Exception
     Processing failed for file [path\to]\App.xaml (System.InvalidOperationException: The reference [AssemblyName] could not be found in [AssemblyName]
        at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GenerateResourceLoader(IndentedStringBuilder writer)
        at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildApplicationInitializerBody(IndentedStringBuilder writer, XamlObjectDefinition topLevelControl)
        at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.InnerGenerateFile()
        at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GenerateFile())
     Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GenerateFile()
     Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGeneration.<>c__DisplayClass39_0.<Generate>b__1(XamlFileDefinition file)
     System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorResults.GetElement(Int32 index)
     System.Linq.Parallel.QueryResults`1.get_Item(Int32 index)
     System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
     System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
     System.Linq.Parallel.SpoolingTaskBase.Work()
     System.Linq.Parallel.QueryTask.BaseWork(Object unused)
     System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
     System.Threading.Tasks.Task.InnerInvoke()
     System.Threading.Tasks.Task.Execute()

         Inner Exception:
         System.InvalidOperationException
         The reference [AssemblyName] could not be found in [AssemblyName]
         Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GenerateResourceLoader(IndentedStringBuilder writer)
         Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildApplicationInitializerBody(IndentedStringBuilder writer, XamlObjectDefinition topLevelControl)
         Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.InnerGenerateFile()
         Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GenerateFile()
```

Based on a quick search, it appears the exception is thrown here:

https://github.com/unoplatform/uno/blob/edf996446a8e8d38273708ee9f1c1dd0d0bcc286/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs#L560

**Comment by jeromelaban** [comment]
Thanks for the report! And apologies for spamming your traces...

We're indeed not reporting errors correctly for now; we'll need to adjust that.
