### ISSUE TITLE
Uno WASM Crashes with Microsoft Graph SDK

### ISSUE THREAD

**Issue by ahoefling** [unoplatform/uno#6379]
## Current behavior
When using the Microsoft Graph SDK deserialization/serialization crashes using either Newtonsoft.Json (Graph SDK 3.x) or System.Text.Json (Graph SDK v4.x). I am not 100% certain if the issue is in mono compatibility with WASM or the graph sdk not fully supporting mono. A couple things in the exception log made me think it might be an issue with the WASM implementation. More than happy to bring this issue over to the graph sdk project if it isn't an uno problem.

After using MSAL.NET or Microsoft Graph Auth to retrieve an access token you can use the following code to trigger the error.
```c#
var graphClient = new GraphServiceClient(httpClient);
graphClient.AuthenticationProvider = this;

var me = await graphClient.Me
    .Request()
    .Select(u => new
    {
        Id = u.Id,
        DisplayName = u.DisplayName,
        UserPrincipalName = u.UserPrincipalName
    })
    .GetAsync();
```

This syntax is correct for Microsoft Graph SDK usage and the only reason why I think it is an issue with Uno WASM is the exception stack trace says it is not supported.

Exception Log with Microsoft.Graph 3.35.0
```
Error creating 'Microsoft.Graph.DerivedTypeConverter'.
Newtonsoft.Json.JsonException: Error creating 'Microsoft.Graph.DerivedTypeConverter'.
 ---> Newtonsoft.Json.JsonException: No parameterless constructor defined for 'Microsoft.Graph.DerivedTypeConverter'.
   at Newtonsoft.Json.Serialization.JsonTypeReflector.<>c__DisplayClass22_0.<GetCreator>b__0(Object[] parameters)
   Exception_EndOfInnerExceptionStack
   at Newtonsoft.Json.Serialization.JsonTypeReflector.<>c__DisplayClass22_0.<GetCreator>b__0(Object[] parameters)
   at Newtonsoft.Json.Serialization.JsonTypeReflector.GetJsonConverter(Object attributeProvider)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContractConverter(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.InitializeContract(JsonContract contract)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.Type, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Newtonsoft.Json.Serialization.JsonContract, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed]].GetOrAdd(Type key, Func`2 valueFactory) in /__w/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs:line 1160
   at Newtonsoft.Json.Utilities.ThreadSafeStore`2[[System.Type, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Newtonsoft.Json.Serialization.JsonContract, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed]].Get(Type key)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.GetContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.GetContractSafe(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[User](String value, JsonSerializerSettings settings)
   at Microsoft.Graph.Serializer.DeserializeObject[User](String inputString)
   at Microsoft.Graph.ResponseHandler.<HandleResponse>d__2`1[[Microsoft.Graph.User, Microsoft.Graph, Version=3.35.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
   at Microsoft.Graph.BaseRequest.<SendAsync>d__34`1[[Microsoft.Graph.User, Microsoft.Graph, Version=3.35.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
   at Microsoft.Graph.UserRequest.<GetAsync>d__6.MoveNext()
```

Exception Log with Microsoft.Graph 4.0.0-preview.7
```
DeserializeNoConstructor, JsonConstructorAttribute, Microsoft.Graph.User Path: $ | LineNumber: 0 | BytePositionInLine: 1.
System.NotSupportedException: DeserializeNoConstructor, JsonConstructorAttribute, Microsoft.Graph.User Path: $ | LineNumber: 0 | BytePositionInLine: 1.
 ---> System.NotSupportedException: DeserializeNoConstructor, JsonConstructorAttribute, Microsoft.Graph.User
   Exception_EndOfInnerExceptionStack
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(ReadStack& state, Utf8JsonReader& reader, NotSupportedException ex) in /__w/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Text.Json/src/System/Text/Json/ThrowHelper.Serialization.cs:line 463
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_DeserializeNoConstructor(Type type, Utf8JsonReader& reader, ReadStack& state) in /__w/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Text.Json/src/System/Text/Json/ThrowHelper.Serialization.cs:line 511
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Microsoft.Graph.User, Microsoft.Graph, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, User& value) in /__w/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Object/ObjectDefaultConverter.cs:line 102
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.Graph.User, Microsoft.Graph, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, User& value) in /__w/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.cs:line 242
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.Graph.User, Microsoft.Graph, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state) in /__w/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.ReadCore.cs:line 103
   at System.Text.Json.JsonSerializer.ReadCore[User](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state) in /__w/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Helpers.cs:line 25
   at System.Text.Json.JsonSerializer.ReadCore[User](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase) in /__w/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Stream.cs:line 408
   at System.Text.Json.JsonSerializer.ContinueDeserialize[User](ReadAsyncBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options) in /__w/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Stream.cs:line 346
   at System.Text.Json.JsonSerializer.<ReadAllAsync>d__24`1[[Microsoft.Graph.User, Microsoft.Graph, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext() in /__w/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Stream.cs:line 268
   at Microsoft.Graph.Serializer.DeserializeObject[User](Stream stream)
   at Microsoft.Graph.ResponseHandler.<HandleResponse>d__2`1[[Microsoft.Graph.User, Microsoft.Graph, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
   at Microsoft.Graph.BaseRequest.<SendAsync>d__34`1[[Microsoft.Graph.User, Microsoft.Graph, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
   at Microsoft.Graph.UserRequest.<GetAsync>d__5.MoveNext()
```

## Expected behavior
The message should serialize and deserialize correctly

## How to reproduce it (as minimally and precisely as possible)
Reproducing this will be a bit tricky as several things need to be in place in Azure as well as the project to authenticate and then query the Microsoft Graph. I suspect we might be able to create a sample project without the graph part but I haven't researched that too much.

steps
1. Use @carldebilly [Uno.MSAL.GraphDemo](https://github.com/unoplatform/Uno.MSAL.Graph.Demo) as a starting point
2. Create an Azure App Registration following the guide on the sample code
3. Add the code snippet above to after the authentication
4. Run the app

The WASM code will crash on the `GetAsync()`

## Workaround
Doesn't solve the problem, but we should be able to send requests manually to Microsoft Graph instead of using the SDK. Doesn't solve the Uno problem, but it solves the integration problem with the Microsoft Graph

## Works on UWP/WinUI
Yes, the code works as expected in UWP, Android, and WPF. I have not tested it in iOS or other platforms.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [x] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.9.3)
- [ ] Visual Studio for Mac (version: )
- [x] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
My guess is that linker removed that constructor, based on the error message. Can you try adding `Microsoft.Graph` into `LinkerConfig.xml` in the WASM project?

**Comment by ahoefling** [comment]
@MartinZikmund This is a great idea and I forgot about the `LinkerConfig.xml`. After a little trial and error I was able to get it working by adding the following to my `LinkerConfig.xml`. The trick was including `Microsoft.Graph.Core`

```xml
  <assembly fullname="Microsoft.Graph" />
  <assembly fullname="Microsoft.Graph.Core" />
```

Thanks for the help ♥

Closing issue, but glad I opened it as it will hopefully help others
