### ISSUE TITLE
Cannot Extract Interface in VS 2019 16.10.3

### ISSUE THREAD

**Issue by GRS-Leedo** [unoplatform/uno#6421]
## Current behavior

Create a class.
![image](https://user-images.githubusercontent.com/47821931/124837187-f9b61b00-df49-11eb-82d0-8746388a3028.png)

Attempt to Extract Interface
![image](https://user-images.githubusercontent.com/47821931/124837239-13eff900-df4a-11eb-8905-81dcdf809d9e.png)

The result is that the ExtractInterfaceCodeRefactoringProvider encounters a bug and quits.
![image](https://user-images.githubusercontent.com/47821931/124837342-44379780-df4a-11eb-8e6e-84b0dae3bd01.png)

The Stack trace provides a clue
System.Runtime.InteropServices.COMException : Files and folders cannot:
-be empty strings
- contain any of the following characters: / ? : & \ * " < > | # %
- contain Unicode control characters
- contain surrogate characters
- be system reserved names, including 'CON', 'AUX', 'PRN', 'COM1' or 'LPT2'
- be '.' or '..'

Please enter a valid name.
   at EnvDTE.ProjectItems.AddFolder(String Name,String Kind)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.Extensions.ProjectExtensions.CreateFolder(ProjectItems currentItems,String container)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.Extensions.ProjectExtensions.FindOrCreateFolder(Project project,IEnumerable`1 containers)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.AddDocumentToFolder(Project project,DocumentId documentId,IEnumerable`1 folders,String documentName,TextDocumentKind documentKind,SourceText initialText,String filePath)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.AddDocumentCore(DocumentInfo info,SourceText initialText,TextDocumentKind documentKind)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyDocumentAdded(DocumentInfo info,SourceText text)
   at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ProcessOperations(Workspace workspace,ImmutableArray`1 operations,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.Apply(Workspace workspace,Document fromDocument,ImmutableArray`1 operations,String title,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass22_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

All of the folders and hence the directory names contain '.' which causes an error.

## Expected behavior

Extract interface to work properly and extract an interface from a class.

## How to reproduce it (as minimally and precisely as possible)

Please provide a **MINIMAL REPRO PROJECT** and the **STEPS TO REPRODUCE**

The steps to re-create are above.  This happens 100% of the time and for the obvious reason.

## Workaround

Manually create the interface

## Works on UWP/WinUI
Yes as well as every other template that I have used.

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [x ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
Uno.Core 2.0.3
Uno.Extensions.Logging.WebAssembly.Console 1.1.0
Uno.UI 3.8.11
Uno.UI.RemoteControl 3.8.11
Uno.UI.Skia.Gtk 3.8.11
Uno.UI.Skia.Wpf 3.8.11
Uno.UI.WebAssembly 3.8.11
Uno.UniversalImageLoader 1.9.33
Uno.Wasm.Bootstrap 2.1.0
Uno.Wasm.Bootstra.DevServer 2.1.0

Affected platform(s):

- [x ] iOS
- [ x] Android
- [ x] WebAssembly
- [ x] WebAssembly renderers for Xamarin.Forms
- [ x] macOS
- [ x] Skia
  - [x ] WPF
  - [ x] GTK (Linux)
  - [ x] Tizen
- [ x] Windows
- [ x] Build tasks
- [x ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ x] Visual Studio 2019 (version: 16.10.3 )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report. Is this working in another project type? Is this in a shared project?

Can you create a repro sample and update the steps so that we're looking at the same issue ?

**Comment by GRS-Leedo** [comment]
This works in all other project types, non-mono UWP, ASPNET, Console App, etc...

Created Solution in VS2019.  As a side note, as when the Uno Platform Template is chosen, it would be great to be able to choose target platforms rather than having to go back an delete them after the solution is created.

Add new folder named 'Services' under <Solution Name>.Shared

Attempt to Extract Interface
![image](https://user-images.githubusercontent.com/47821931/124950809-5eb85200-dfd8-11eb-9a78-99ca9451de6c.png)

![image](https://user-images.githubusercontent.com/47821931/124950880-6e379b00-dfd8-11eb-9810-3512956b123f.png)

Results in 
![image](https://user-images.githubusercontent.com/47821931/124950973-85768880-dfd8-11eb-93f8-87837e35ebb4.png)

Stack Trace
System.Runtime.InteropServices.COMException : Files and folders cannot:
-be empty strings
- contain any of the following characters: / ? : & \ * " < > | # %
- contain Unicode control characters
- contain surrogate characters
- be system reserved names, including 'CON', 'AUX', 'PRN', 'COM1' or 'LPT2'
- be '.' or '..'

Please enter a valid name.
   at EnvDTE.ProjectItems.AddFolder(String Name,String Kind)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.Extensions.ProjectExtensions.CreateFolder(ProjectItems currentItems,String container)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.Extensions.ProjectExtensions.FindOrCreateFolder(Project project,IEnumerable`1 containers)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.AddDocumentToFolder(Project project,DocumentId documentId,IEnumerable`1 folders,String documentName,TextDocumentKind documentKind,SourceText initialText,String filePath)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.AddDocumentCore(DocumentInfo info,SourceText initialText,TextDocumentKind documentKind)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyDocumentAdded(DocumentInfo info,SourceText text)
   at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ProcessOperations(Workspace workspace,ImmutableArray`1 operations,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.Apply(Workspace workspace,Document fromDocument,ImmutableArray`1 operations,String title,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass22_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

I repeated the same process under the UWP project
![image](https://user-images.githubusercontent.com/47821931/124951442-fb7aef80-dfd8-11eb-80a5-cd62a81c75b1.png)

Which was successful.  This is good, however most services are shared and not specific to a project type.

[ExtractInterface.zip](https://github.com/unoplatform/uno/files/6785777/ExtractInterface.zip)

**Comment by jeromelaban** [comment]
Thanks. This looks like a Shared project issue, unfortunately, and this is not something we can fix. It's likely that if you create a Shared project in a "Vanilla" UWP (or anything else) project, you'll face the same error.

**Comment by francoistanguay** [comment]
Cannot fix.
