### ISSUE TITLE
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap

### ISSUE THREAD

**Issue by furoTmark** [unoplatform/uno#7031]
### Current behavior

I have a Listview and in the Listview there are images displayed that have as a UriSource a link to a .jpg (like https://upload.wikimedia.org/wikipedia/commons/1/18/Color-white.JPG). The images are displayed correctly, but after some scrolling a fatal error shows up and the application closes. 

Code example:

```html
    <ListView  ItemsSource="{x:Bind ViewModel.Posts,Mode=OneWay}" ScrollViewer.VerticalScrollBarVisibility="Auto" IsItemClickEnabled="True" ItemClick="ListView_ItemClick">
                <ListView.ItemTemplate>
                <DataTemplate>
                    <Grid>
    ...
                        <Border Grid.Column="0" Grid.Row="0" HorizontalAlignment="Left" Grid.RowSpan="3">
                            <Image HorizontalAlignment="Center" Stretch="UniformToFill" Margin="0" VerticalAlignment="Center">
                                <Image.Source>
                                    <BitmapImage UriSource="{Binding ImageLink}" />
                                </Image.Source>
                            </Image>
    ...
```

Stacktrace:

```[View] requestLayout() improperly called by Windows.UI.Xaml.Controls.StackPanel during layout: running second layout pass
[chatty] uid=10189(EgyKettoUno.EgyKettoUno) identical 6 lines
[View] requestLayout() improperly called by Windows.UI.Xaml.Controls.StackPanel during layout: running second layout pass
[AndroidRuntime] Shutting down VM
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: EgyKettoUno.EgyKettoUno, PID: 6762
[AndroidRuntime] java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@a6522f1
[AndroidRuntime] 	at android.graphics.BaseCanvas.throwIfCannotDraw(Unknown Source:73)
[AndroidRuntime] 	at android.graphics.MiuiCanvas.throwIfCannotDraw(Unknown Source:0)
[AndroidRuntime] 	at android.graphics.RecordingCanvas.throwIfCannotDraw(Unknown Source:0)
[AndroidRuntime] 	at android.graphics.BaseRecordingCanvas.drawBitmap(Unknown Source:8)
[AndroidRuntime] 	at android.graphics.drawable.BitmapDrawable.draw(Unknown Source:137)
[AndroidRuntime] 	at android.widget.ImageView.onDraw(Unknown Source:95)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:77)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(Unknown Source:205)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:264)
[AndroidRuntime] 	at android.view.ViewGroup.drawChild(Unknown Source:0)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchDraw(Unknown Source:295)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(Unknown Source:168)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:264)
[AndroidRuntime] 	at android.view.ViewGroup.drawChild(Unknown Source:0)
[AndroidRuntime] 	at android.dispatchDraw(Unknown Source:295)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:83)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(Unknown Source:205)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:264)
[AndroidRuntime] 	at android.view.ViewGroup.drawChild(Unknown Source:0)
[AndroidRuntime] 	at android.view.ViewGroup.09-12 12:53:13.522 E/AndroidRuntime( 6762): 	at android.view.ViewGroup.dispatchDraw(Unknown Source:295)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:83)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(Unknown Source:205)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:264)
[AndroidRuntime] 	at android.view.ViewGroup.drawChild(Unknown Source:0)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchDraw(Unknown Source:295)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:264)
[AndroidRuntime] 	at android.view.ViewGroup.drawChild(Unknown Source:0)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchDraw(Unknown Source:295)
[AndroidRuntime09-12 12:53:13.522 E] 	at android.view.View.draw(Unknown Source:83)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(Unknown Source:205)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:264)
[AndroidRuntime] 	at android.view.ViewGroup.drawChild(Unknown Source:0)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchDraw(Unknown Source:295)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(Unknown Source:205)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:264)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchDraw(Unknown Source:295)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:209-12 12:53:13.522 E/AndroidRuntime( 6762): 	at android.view.View.updateDisplayListIfDirty(Unknown Source:168)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:264)
[AndroidRuntime] 	at android.view.ViewGroup.drawChild(Unknown Source:0)
[AndroidRuntime] 	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5030)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchDraw(Unknown Source:295)
[AndroidRuntime] 	at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4429)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(Unknown Source:205)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:264)
[AndroidRuntime] 	at android.view.ViewGroup.drawChild(Unknown Source:0)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchDraw(Unknown Source:295)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(Unknown Source:168)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:264)
[AndroidRuntime] 	at android.view.ViewGroup.drawChild(Unknown Source:0)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchDraw(Unknown Source:295)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:83)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(Unknown Source:205)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:264)
[AndroidRuntime] 	at android.view.ViewGroup.drawChild(Unknown Source:0)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchDraw(Unknown Source:295)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(Unknown Source:168)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:264)
[AndroidRuntime] 	at android.view.ViewGroup.drawChild(Unknown Source:0)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchDraw(Unknown Source:295)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:83)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(Unknown Source:205)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:264)
[AndroidRuntime] 	at android.view.ViewGroup.drawChild(Unknown Source:0)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchDraw(Unknown Source:295)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(Unknown Source:168)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:264)
[AndroidRuntime] 	at android.view.ViewGroup.drawChild(Unknown Source:0)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchDraw(Unknown Source:295)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:83)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(Unknown Source:205)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:264)
[AndroidRuntime] 	at android.view.ViewGroup.drawChild(Unknown Source:0)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchDraw(Unknown Source:295)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:83)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(Unknown Source:205)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:264)
[AndroidRuntime] 	at android.view.ViewGroup.drawChild(Unknown Source:0)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchDraw(Unknown Source:295)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:83)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(Unknown Source:205)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:264)
[AndroidRuntime] 	at android.view.ViewGroup.drawChild(Unknown Source:0)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchDraw(Unknown Source:295)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(Unknown Source:168)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:264)
[AndroidRuntime] 	at android.view.ViewGroup.drawChild(Unknown Source:0)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchDraw(Unknown Source:295)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:83)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(Unknown Source:205)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:264)
[AndroidRuntime] 	at android.view.ViewGroup.drawChild(Unknown Source:0)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchDraw(Unknown Source:295)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:83)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(Unknown Source:205)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:264)
[AndroidRuntime] 	at android.view.ViewGroup.drawChild(Unknown Source:0)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchDraw(Unknown Source:295)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(Unknown Source:168)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:264)
[AndroidRuntime] 	at android.view.ViewGroup.drawChild(Unknown Source:0)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchDraw(Unknown Source:295)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(Unknown Source:168)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:264)
[AndroidRuntime] 	at android.view.ViewGroup.drawChild(Unknown Source:0)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchDraw(Unknown Source:295)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(Unknown Source:168)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:264)
[AndroidRuntime] 	at android.view.ViewGroup.drawChild(Unknown Source:0)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchDraw(Unknown Source:295)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(Unknown Source:168)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:264)
[AndroidRuntime] 	at android.view.ViewGroup.drawChild(Unknown Source:0)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchDraw(Unknown Source:295)
[AndroidRuntime] 	at android.view.View.draw(Unknown Source:83)
[AndroidRuntime] 	at com.android.internal.policy.DecorView.draw(Unknown Source:0)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(Unknown Source:205)
[AndroidRuntime] 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(Unknown Source:27)
[AndroidRuntime] 	at android.view.ThreadedRenderer.updateRootDisplayList(Unknown Source:10)
[AndroidRuntime] 	at android.view.ThreadedRenderer.draw(Unknown Source:9)
[AndroidRuntime] 	at android.view.ViewRootImpl.draw(Unknown Source:483)
[AndroidRuntime] 	at android.view.ViewRootImpl.performDraw(Unknown Source:145)
[AndroidRuntime] 	at android.view.ViewRootImpl.performTraversals(Unknown Source:2773)
[AndroidRuntime] 	at android.view.ViewRootImpl.doTraversal(Unknown Source:36)
[AndroidRuntime] 	at android.view.ViewRootImpl$TraversalRunnable.run(Unknown Source:2)
[AndroidRuntime] 	at android.view.Choreographer$CallbackRecord.run(Unknown Source:20)
[AndroidRuntime] 	at android.view.Choreographer.doCallbacks(Unknown Source:88)
[AndroidRuntime] 	at android.view.Choreographer.doFrame(Unknown Source:227)
[AndroidRuntime] 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Unknown Source:9)
[AndroidRuntime] 	at android.os.Handler.handleCallback(Unknown Source:2)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Unknown Source:4)
[AndroidRuntime] 	at android.os.Looper.loop(Unknown Source:249)
[AndroidRuntime] 	at android.app.ActivityThread.main(Unknown Source:134)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(Unknown Source:313)
**Java.Lang.RuntimeException:** 'Loading...'
```

### Expected behavior

No fatal error after scrolling through the list of images.

### How to reproduce it (as minimally and precisely as possible)

Add to a ListView a list of images with links to jpg and start to scroll through them.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

Android

### IDE

Visual Studio 2019

### Anything else we need to know?

The error can be reproduced in the emulator and on a real device also.

**Comment by MartinZikmund** [comment]
No longer relevant, works correctly for Skia Android Uno Platform target
