### ISSUE TITLE
[WASM] FocusManager.ReceiveFocusNative error after upgrade to WinUI

### ISSUE THREAD

**Issue by HavenDV** [unoplatform/uno#7406]
### Current behavior

I am trying to update my WebAssembly project to use Uno.WinUI instead of Uno.UI and I get the following error while loading:
![image](https://user-images.githubusercontent.com/3002068/139606648-5cb03f9f-21f5-4fa3-8531-06b03e2243e8.png)

### How to reproduce it (as minimally and precisely as possible)

[ratbuddyssey-winuibug.zip](https://github.com/unoplatform/uno/files/7459140/ratbuddyssey-datacontextbug.1.1.zip)

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

3.12.0-dev.2

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

preview 7.0

**Comment by MartinZikmund** [comment]
The confusing this is that it happens only for WinUI, which suggests something is not initialized properly. I will look into this

**Comment by HavenDV** [comment]
Still exists in Uno.WinUI.WebAssembly 4.1.0-dev.18:
```
VM103:1 fail: Microsoft.UI.Xaml.Window[0]
      Resize ignore, no current window defined
eval @ VM103:1
VM104:1 fail: Uno.UI.Dispatching.CoreDispatcher[0]
      Dispatcher unhandled exception
System.ArgumentException: Don't know how to detect when ReactiveUI.Uno.RoutedViewHost is activated/deactivated, you may need to implement IActivationForViewFetcher
   at ReactiveUI.ViewForMixins.WhenActivated(IActivatableView item, Func`1 block, IViewFor view) in /_/src/ReactiveUI/Activation/ViewForMixins.cs:line 153
   at ReactiveUI.ViewForMixins.WhenActivated(IActivatableView item, Action`1 block, IViewFor view) in /_/src/ReactiveUI/Activation/ViewForMixins.cs:line 200
   at ReactiveUI.ViewForMixins.WhenActivated(IActivatableView item, Action`1 block) in /_/src/ReactiveUI/Activation/ViewForMixins.cs:line 180
   at ReactiveUI.Uno.RoutedViewHost..ctor() in /_/src/ReactiveUI.Uwp/common/RoutedViewHost.cs:line 109
   at Ratbuddyssey.Views.MainView.InitializeComponent() in C:\Users\haven\source\repos\HavenDV\ratbuddyssey\src\apps\Ratbuddyssey.Apps.Uno.WebAssembly\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\MainView_78ae60a25305526d42d961b4e4668528.cs:line 59
   at Ratbuddyssey.Views.MainView..ctor() in C:\Users\haven\source\repos\HavenDV\ratbuddyssey\src\apps\Ratbuddyssey.Apps.Uno.WebAssembly\ViewBaseGenerator\H.Generators.ConstructorGenerator\Constructors.cs:line 278
   at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, Object[] parameters, Boolean wrapExceptions) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\mono\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs:line 875
   at System.Reflection.RuntimeConstructorInfo.DoInvoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\mono\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs:line 846
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\mono\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs:line 888
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.Type, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Func`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetOrAdd(Type key, Func`2 valueFactory) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\libraries\System.Collections.Concurrent\src\System\Collections\Concurrent\ConcurrentDictionary.cs:line 1161
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices(IServiceProvider provider, Type serviceType)
   at Splat.Microsoft.Extensions.DependencyInjection.MicrosoftDependencyResolver.GetServices(Type serviceType, String contract) in /_/src/Splat.Microsoft.Extensions.DependencyInjection/MicrosoftDependencyResolver.cs:line 107
   at Splat.Microsoft.Extensions.DependencyInjection.MicrosoftDependencyResolver.GetService(Type serviceType, String contract) in /_/src/Splat.Microsoft.Extensions.DependencyInjection/MicrosoftDependencyResolver.cs:line 86
   at ReactiveUI.DefaultViewLocator.AttemptViewResolution(String viewTypeName, String contract) in /_/src/ReactiveUI/View/DefaultViewLocator.cs:line 224
   at ReactiveUI.DefaultViewLocator.AttemptViewResolutionFor(Type viewModelType, String contract) in /_/src/ReactiveUI/View/DefaultViewLocator.cs:line 195
   at ReactiveUI.DefaultViewLocator.ResolveView[MainViewModel](MainViewModel viewModel, String contract) in /_/src/ReactiveUI/View/DefaultViewLocator.cs:line 100
   at Ratbuddyssey.App.GetView[MainViewModel](MainViewModel& viewModel) in C:\Users\haven\source\repos\HavenDV\ratbuddyssey\src\shared\Ratbuddyssey.Apps.Shared\App.xaml.cs:line 54
   at Ratbuddyssey.App.OnLaunched(LaunchActivatedEventArgs args) in C:\Users\haven\source\repos\HavenDV\ratbuddyssey\src\shared\Ratbuddyssey.Apps.Shared\App.xaml.cs:line 110
   at Microsoft.UI.Xaml.Application.Initialize()
   at Uno.UI.Dispatching.CoreDispatcher.InvokeOperationSafe(UIAsyncOperation operation) in C:\a\1\s\src\Uno.UI.Dispatching\Core\CoreDispatcher.cs:line 337
eval @ VM104:1
dotnet.js:1 
put_char @ dotnet.js:1
dotnet.js:1 Unhandled Exception:
put_char @ dotnet.js:1
dotnet.js:1 System.NullReferenceException: Object reference not set to an instance of an object.
put_char @ dotnet.js:1
dotnet.js:1    at Microsoft.UI.Xaml.Input.FocusManager.ReceiveFocusNative(Int32 handle)
put_char @ dotnet.js:1
dotnet.js:1 Uncaught Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.UI.Xaml.Input.FocusManager.ReceiveFocusNative(:56600/Int32 handle)
    at Object._convert_exception_for_method_call (dotnet.js:1)
    at Object._handle_exception_for_call (dotnet.js:1)
    at Function.managed__Uno_UI__Microsoft_UI_Xaml_Input_FocusManager_ReceiveFocusNative [as focusInMethod] (managed__Uno_UI__Microsoft_UI_Xaml_Input_FocusManager_ReceiveFocusNative:17)
    at onWindowBlur (Uno.UI.js:1870)
VM106:1 fail: Microsoft.UI.Xaml.Window[0]
      Resize ignore, no current window defined
```

But it seems that the original problem is with ReactiveUI.

**Comment by jeromelaban** [comment]
@HavenDV the original error is likely to be linker issue (unrelated to this one):
```
System.ArgumentException: Don't know how to detect when ReactiveUI.Uno.RoutedViewHost is activated/deactivated, you may need to implement IActivationForViewFetcher
```
See https://platform.uno/docs/articles/features/using-il-linker-webassembly.html?q=linker

**Comment by HavenDV** [comment]
Linker is disabled in both

**Comment by jeromelaban** [comment]
In this case, this is likely to be a configuration error, but this is not a pointers issue (even if appears later in the logs).

**Comment by HavenDV** [comment]
I will wait for the expected fix from ReactiveUI and close the issue if the problem is resolved.
<img width="830" alt="image" src="https://user-images.githubusercontent.com/3002068/144692014-230b1402-b6c0-450f-bb0b-37d52916c3b3.png">

**Comment by jeromelaban** [comment]
The pointer exception needs to be fixed, but it's not the cause of your other error message. We can reopen this issue.

**Comment by HavenDV** [comment]
I also have a repro for 4.1.0-dev where I am not using `ReactiveUI.Uno.RoutedViewHost`
[H.ReactiveUI.CommonInteractions-master (1).zip](https://github.com/unoplatform/uno/files/7655634/H.ReactiveUI.CommonInteractions-master.1.zip)

```
Setting UNO_BOOTSTRAP_MONO_RUNTIME_MODE=Interpreter
uno-bootstrap.js:11 Setting UNO_BOOTSTRAP_MONO_PROFILED_AOT=False
uno-bootstrap.js:11 Setting UNO_BOOTSTRAP_LINKER_ENABLED=False
uno-bootstrap.js:11 Setting UNO_BOOTSTRAP_DEBUGGER_ENABLED=True
uno-bootstrap.js:11 Setting UNO_BOOTSTRAP_MONO_RUNTIME_CONFIGURATION=release
uno-bootstrap.js:11 Setting UNO_BOOTSTRAP_APP_BASE=package_0cc6836be17e7604ad0adf3fa7692e633752d7fc
uno-bootstrap.js:11 Setting UNO_BOOTSTRAP_WEBAPP_BASE_PATH=./
uno-bootstrap.js:442 Done loading the BCL
uno-bootstrap.js:456 Loading dependency (./package_0cc6836be17e7604ad0adf3fa7692e633752d7fc/WasmWebSockets)
uno-bootstrap.js:456 Loading dependency (./package_0cc6836be17e7604ad0adf3fa7692e633752d7fc/jquery-pep)
uno-bootstrap.js:456 Loading dependency (./package_0cc6836be17e7604ad0adf3fa7692e633752d7fc/setImmediate)
uno-bootstrap.js:456 Loading dependency (./package_0cc6836be17e7604ad0adf3fa7692e633752d7fc/Uno.UI)
uno-bootstrap.js:456 Loading dependency (./package_0cc6836be17e7604ad0adf3fa7692e633752d7fc/AppManifest)
uno-bootstrap.js:449 Loaded dependency (./package_0cc6836be17e7604ad0adf3fa7692e633752d7fc/AppManifest) - remains 4 other(s).
uno-bootstrap.js:449 Loaded dependency (./package_0cc6836be17e7604ad0adf3fa7692e633752d7fc/WasmWebSockets) - remains 3 other(s).
uno-bootstrap.js:449 Loaded dependency (./package_0cc6836be17e7604ad0adf3fa7692e633752d7fc/setImmediate) - remains 2 other(s).
uno-bootstrap.js:449 Loaded dependency (./package_0cc6836be17e7604ad0adf3fa7692e633752d7fc/jquery-pep) - remains 1 other(s).
uno-bootstrap.js:449 Loaded dependency (./package_0cc6836be17e7604ad0adf3fa7692e633752d7fc/Uno.UI) - remains 0 other(s).
uno-bootstrap.js:530 Debugging hotkey: Shift+Alt+D (when application has focus)
​ fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint [fe80::bc7c:8be4:7c9a:e639].
eval @ unknown
​ fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint 169.254.230.57.
eval @ unknown
​ fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint [fe80::cd8:3b3b:756b:3179].
eval @ unknown
​ fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint 192.168.1.137.
eval @ unknown
​ fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get any remote control server endpoint from the IDE.
eval @ unknown
​ warn: Uno.UI.ResourceResolver[0]
      Couldn't statically resolve resource DefaultRepeatButtonStyle
eval @ unknown
VM96:1 fail: Microsoft.UI.Xaml.Window[0]
      Resize ignore, no current window defined
eval @ VM96:1
VM97:1 fail: Microsoft.UI.Xaml.Input.KeyboardAccelerator[0]
      The member event TypedEventHandler<KeyboardAccelerator, KeyboardAcceleratorInvokedEventArgs> KeyboardAccelerator.Invoked is not implemented in Uno.
eval @ VM97:1
VM98:1 fail: Microsoft.UI.Xaml.BrushTransition[0]
      The member BrushTransition.BrushTransition() is not implemented in Uno.
eval @ VM98:1
VM99:1 fail: Microsoft.UI.Xaml.BrushTransition[0]
      The member TimeSpan BrushTransition.Duration is not implemented in Uno.
eval @ VM99:1
VM100:1 fail: Microsoft.UI.Xaml.Controls.ContentPresenter[0]
      The member BrushTransition ContentPresenter.BackgroundTransition is not implemented in Uno.
eval @ VM100:1
VM101:1 fail: Microsoft.UI.Xaml.Controls.CommandBarFlyout[0]
      The member CommandBarFlyout.CommandBarFlyout() is not implemented in Uno.
eval @ VM101:1
VM102:1 fail: Microsoft.UI.Xaml.Controls.TextCommandBarFlyout[0]
      The member TextCommandBarFlyout.TextCommandBarFlyout() is not implemented in Uno.
eval @ VM102:1
VM103:1 fail: Uno.UI.DataBinding.BindingPropertyHelper[0]
      The [ScrollViewer] property getter does not exist on type [Microsoft.UI.Xaml.Controls.TextBox]
eval @ VM103:1
VM104:1 fail: Microsoft.UI.Xaml.Data.BindingExpression[0]
      Failed to apply binding to property [DependencyPropertyDetails(Visibility)] on [Microsoft.UI.Xaml.UIElement] (Field not found: object Microsoft.UI.Xaml.DependencyProperty.UnsetValue Due to: Could not find field in class)
System.MissingFieldException: Field not found: object Microsoft.UI.Xaml.DependencyProperty.UnsetValue Due to: Could not find field in class
   at Microsoft.UI.Xaml.Data.BindingExpression.ConvertValue(Object value)
   at Microsoft.UI.Xaml.Data.BindingExpression.<SetTargetValueSafe>g__SetTargetValueSafeWithTry|54_1(Object v, Boolean useTargetNullValue)
eval @ VM104:1
VM105:1 fail: Microsoft.UI.Xaml.VisualTransition[0]
      The member Duration VisualTransition.GeneratedDuration is not implemented in Uno.
eval @ VM105:1
VM106:1 fail: Microsoft.UI.Xaml.Media.Animation.AddDeleteThemeTransition[0]
      The member AddDeleteThemeTransition.AddDeleteThemeTransition() is not implemented in Uno.
eval @ VM106:1
VM107:1 fail: Microsoft.UI.Xaml.Media.Animation.ContentThemeTransition[0]
      The member ContentThemeTransition.ContentThemeTransition() is not implemented in Uno.
eval @ VM107:1
VM108:1 fail: Microsoft.UI.Xaml.Media.Animation.ReorderThemeTransition[0]
      The member ReorderThemeTransition.ReorderThemeTransition() is not implemented in Uno.
eval @ VM108:1
VM109:1 fail: Microsoft.UI.Xaml.Automation.Peers.AutomationPeer[0]
      The member void AutomationPeer.RaiseAutomationEvent(AutomationEvents eventId) is not implemented in Uno.
eval @ VM109:1
dotnet.js:1 
put_char @ dotnet.js:1
dotnet.js:1 Unhandled Exception:
put_char @ dotnet.js:1
dotnet.js:1 System.NullReferenceException: Object reference not set to an instance of an object.
put_char @ dotnet.js:1
dotnet.js:1    at Microsoft.UI.Xaml.Input.FocusManager.ReceiveFocusNative(Int32 handle)
put_char @ dotnet.js:1
dotnet.js:1 Uncaught Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.UI.Xaml.Input.FocusManager.ReceiveFocusNative(:56600/Int32 handle)
    at Object._convert_exception_for_method_call (dotnet.js:1)
    at Object._handle_exception_for_call (dotnet.js:1)
    at Function.managed__Uno_UI__Microsoft_UI_Xaml_Input_FocusManager_ReceiveFocusNative [as focusInMethod] (managed__Uno_UI__Microsoft_UI_Xaml_Input_FocusManager_ReceiveFocusNative:17)
    at onWindowBlur (Uno.UI.js:1870)
VM112:1 fail: Microsoft.UI.Xaml.Window[0]
      Resize ignore, no current window defined
eval @ VM112:1
browserLink:2843 POST https://dc.services.visualstudio.com/v2/track net::ERR_BLOCKED_BY_CLIENT
```

**Comment by jeromelaban** [comment]
@MartinZikmund If I were to guess, I'd say that it's caused by:

https://github.com/unoplatform/uno/blob/574a441497e0e6faee8d389a3dbac1c40d4d7891/src/Uno.UI/UI/Xaml/Input/FocusManager.wasm.cs#L132

Where `Window.Current` could be null.
