### ISSUE TITLE
[WASM/UWP] MaterialNavigationViewStyle doesn't work

### ISSUE THREAD

**Issue by mikernet** [unoplatform/uno#7460]
### Current behavior

Setting `NavigationView.Style` to the material theme style causes the page not to load and the following exception happens (browser console for WASM):

```
fail: Windows.UI.Xaml.UIElement[0]
      Failed to raise 'PointerReleasedEvent': System.InvalidOperationException: Failed to load iRatio.Dashboard.Roots.MainRoot: System.InvalidOperationException: The Dependency Property [PaneToggleButtonStyle] is owned by [Microsoft.UI.Xaml.Controls.NavigationView] and cannot be used on [Windows.UI.Xaml.Controls.NavigationView]
         at Windows.UI.Xaml.DependencyObjectStore.InnerSetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isThemeBinding)
         at Windows.UI.Xaml.DependencyObjectStore.SetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isThemeBinding)
         at Windows.UI.Xaml.DependencyObjectStore.SetValue(DependencyProperty property, Object value)
         at Windows.UI.Xaml.UIElement.SetValue(DependencyProperty dp, Object value)
         at Windows.UI.Xaml.Setter.ApplyTo(DependencyObject o)
         at Windows.UI.Xaml.Style.ApplyTo(DependencyObject o, DependencyPropertyValuePrecedences precedence)
         at Windows.UI.Xaml.FrameworkElement.OnStyleChanged(Style oldStyle, Style newStyle, DependencyPropertyValuePrecedences precedence)
         at Windows.UI.Xaml.FrameworkElement.ApplyStyle()
         at Windows.UI.Xaml.FrameworkElement.ApplyStyles()
         at Windows.UI.Xaml.FrameworkElement.CreationComplete()
         at iRatio.Dashboard.Roots.MainRoot.<InitializeComponent>b__1_4(NavigationView c10) in C:\Users\mikem\Documents\Projects\iRatio\Source\iRatio.Dashboard\iRatio.Dashboard.Wasm\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\MainRoot_9bfa3ce12034b83fe2729803038fa9e2.cs:line 215
         at iRatio.Dashboard.Roots.MainRoot.InitializeComponent() in C:\Users\mikem\Documents\Projects\iRatio\Source\iRatio.Dashboard\iRatio.Dashboard.Wasm\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\MainRoot_9bfa3ce12034b83fe2729803038fa9e2.cs:line 53
         at iRatio.Dashboard.Roots.MainRoot..ctor() in C:\Users\mikem\Documents\Projects\iRatio\Source\iRatio.Dashboard\iRatio.Dashboard.Shared\Roots\MainRoot.xaml.cs:line 25
         at iRatio.Dashboard.Wasm.MetadataBuilder_654.CreateInstance() in C:\Users\mikem\Documents\Projects\iRatio\Source\iRatio.Dashboard\iRatio.Dashboard.Wasm\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.BindableTypeProviders.BindableTypeProvidersSourceGenerator\BindableMetadata.cs:line 23731
         at Windows.UI.Xaml.Controls.Frame.CreatePageInstance(Type sourcePageType)
         at Windows.UI.Xaml.PagePool.DequeuePage(Type pageType)
         at Windows.UI.Xaml.Controls.Frame.CreatePageInstanceCached(Type sourcePageType)
         at Windows.UI.Xaml.Controls.Frame.InnerNavigate(PageStackEntry entry, NavigationMode mode)
         at iRatio.Dashboard.App.OnNavigationFailed(Object sender, NavigationFailedEventArgs e) in C:\Users\mikem\Documents\Projects\iRatio\Source\iRatio.Dashboard\iRatio.Dashboard.Shared\App.xaml.cs:line 103
         at Windows.UI.Xaml.Controls.Frame.InnerNavigate(PageStackEntry entry, NavigationMode mode)
         at Windows.UI.Xaml.Controls.Frame.Navigate(Type sourcePageType, Object parameter, NavigationTransitionInfo infoOverride)
         at Windows.UI.Xaml.Controls.Frame.Navigate(Type sourcePageType)
         at iRatio.Dashboard.Roots.LoginRoot.OnLoginClick(Object sender, RoutedEventArgs e) in C:\Users\mikem\Documents\Projects\iRatio\Source\iRatio.Dashboard\iRatio.Dashboard.Shared\Roots\LoginRoot.xaml.cs:line 59
         at iRatio.Dashboard.Roots.LoginRoot.<>c__DisplayClass2_1.<InitializeComponent>b__11(Object OnLoginClick_sender, RoutedEventArgs OnLoginClick_e) in C:\Users\mikem\Documents\Projects\iRatio\Source\iRatio.Dashboard\iRatio.Dashboard.Wasm\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\LoginRoot_8da8911665cd5b8b8a2a9b194b08b629.cs:line 183
         at Windows.UI.Xaml.Controls.Primitives.ButtonBase.OnClick()
         at Windows.UI.Xaml.Controls.Button.OnClick()
         at Windows.UI.Xaml.Controls.Primitives.ButtonBase.PerformPointerUpAction()
         at Windows.UI.Xaml.Controls.Primitives.ButtonBase.OnPointerReleased(PointerRoutedEventArgs args)
         at Windows.UI.Xaml.Controls.Control.<>c.<.cctor>b__382_10(Object sender, PointerRoutedEventArgs args)
         at Windows.UI.Xaml.UIElement.InvokeHandler(Object handler, RoutedEventArgs args)
         at Windows.UI.Xaml.UIElement.RaiseEvent(RoutedEvent routedEvent, RoutedEventArgs args, BubblingContext ctx)
         at Windows.UI.Xaml.UIElement.RaisePointerEvent(RoutedEvent evt, PointerRoutedEventArgs args, BubblingContext ctx)
```

UWP works when running in the debugger but crashes if running outside the debugger (i.e. `CTRL+F5` in VS) when the material style is applied to the navigation view.

### How to reproduce it (as minimally and precisely as possible)

Put this on a page:
```xml
<NavigationView Style="{StaticResource MaterialNavigationViewStyle}" />
```

### Workaround

None

### Works on UWP/WinUI

Only when the debugger is attached.

### NuGet package version(s)

Uno.,UI: v3.10.11, v3.11.-dev.487, v4.0.0-dev.5489
Uno.Material: v1.0.2, v1.0.3, v1.1.0-dev.7
Tried both NET5 and NET6 for WASM, no difference.

### Affected platforms

WebAssembly and UWP. Untested on other platforms.

**Comment by mikernet** [comment]
Sorry, wrong property. I think the issue is in the material theme style being applied to the navigation view. Give me a sec to work this out.

**Comment by mikernet** [comment]
Updated.

**Comment by mikernet** [comment]
So as discussed, the fix is to explicitly specify an `muxc:` prefix on the `<NavigationView>` which points to `Microsoft.UI.Xaml.Controls`. 

This should work without having to do that though, right?

**Comment by jeromelaban** [comment]
When using UWP, this is the way to handle this, as WinUI 2.7 requires a namespace to use the MUX controls. In WinUI 3, this is not necessary as MUX is the default namespace.
