### ISSUE TITLE
[WASM] Linker fails if project references dll built against older Uno.UI version

### ISSUE THREAD

**Issue by mikernet** [unoplatform/uno#7465]
### Current behavior

If you directly reference a dll built against `Uno.UI v3.10.11` from a WASM head that references `Uno.UI 4.x-dev.latest`, the linker fails. It works fine if you do the same from UWP.

Build output:

```
1>Target "BuildDist" in file "C:\Users\mikem\.nuget\packages\uno.wasm.bootstrap\3.0.0\build\Uno.Wasm.Bootstrap.targets":
1>  Task "UnoInstallSDKTask_v6068e93c4525d2d4df3d9218f789d6f8a43d0b20"
1>  Done executing task "UnoInstallSDKTask_v6068e93c4525d2d4df3d9218f789d6f8a43d0b20".
1>  Task "ShellTask_v6068e93c4525d2d4df3d9218f789d6f8a43d0b20"
1>    C:\Users\mikem\.nuget\packages\uno.wasm.bootstrap\3.0.0\build\Uno.Wasm.Bootstrap.targets(172,5): error : System.Exception: Failed to execute the linker
1>    C:\Users\mikem\.nuget\packages\uno.wasm.bootstrap\3.0.0\build\Uno.Wasm.Bootstrap.targets(172,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v6068e93c4525d2d4df3d9218f789d6f8a43d0b20.RunPackager() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 907
1>    C:\Users\mikem\.nuget\packages\uno.wasm.bootstrap\3.0.0\build\Uno.Wasm.Bootstrap.targets(172,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v6068e93c4525d2d4df3d9218f789d6f8a43d0b20.Execute() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 230
1>  Done executing task "ShellTask_v6068e93c4525d2d4df3d9218f789d6f8a43d0b20" -- FAILED.
1>Done building target "BuildDist" in project "iRatio.Dashboard.Wasm.csproj" -- FAILED.
1>
1>Done building project "iRatio.Dashboard.Wasm.csproj" -- FAILED.
```

### Expected behavior

Build should work.

### How to reproduce it (as minimally and precisely as possible)

1) Build `Syncfusion.SfCharts.Uno` using `Uno.UI v3.10.11` in `Release` mode.
2) Reference the `netstandard2.0` dll output directly from a WASM project that uses `Uno.UI v4.x-dev.latest`.
3) Build.

### Workaround

Rebuild the dll against the current version of `Uno.UI` that you are using.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

WebAssembly, possibly other platforms as well but untested.

**Comment by mikernet** [comment]
It does the same thing if I refererence it from a `v3.11.0-dev.487` build.

**Comment by mikernet** [comment]
Nevermind, that's because another package had a dependency on `4.x` so it was using a later version. All good :)

**Comment by mikernet** [comment]
Is there a log somewhere that has a better error message than just "linker failed"? I ran into this before and had to try a bunch of random things until something made it work, would be nice to be able to trace an issue better.
