### ISSUE TITLE
[Linux] FrameBuffer default template throws exception System.InvalidOperationException: CoreDispatcher.HasThreadAccessOverride must be set

### ISSUE THREAD

**Issue by ADIX7** [unoplatform/uno#7897]
### Current behavior

I created a new project with `dotnet new unoapp-net6 -o MyUnoApp`

Upon starting the `MyUnoApp.Skia.Linux.FrameBuffer` I get this exception:
```
Unhandled exception. System.InvalidOperationException: CoreDispatcher.HasThreadAccessOverride must be set
   at Uno.UI.Dispatching.CoreDispatcher.GetHasThreadAccess() in C:\a\1\s\src\Uno.UI.Dispatching\Core\CoreDispatcher.skia.cs:line 27
   at Uno.UI.Dispatching.CoreDispatcher.get_HasThreadAccess() in C:\a\1\s\src\Uno.UI.Dispatching\Core\CoreDispatcher.cs:line 121
   at Windows.System.DispatcherQueue.GetForCurrentThread() in C:\a\1\s\src\Uno.UWP\System\DispatcherQueue.cs:line 28
   at Windows.UI.Core.CoreWindow..ctor() in C:\a\1\s\src\Uno.UWP\UI\Core\CoreWindow.cs:line 57
   at Windows.UI.Xaml.Window.Init() in C:\a\1\s\src\Uno.UI\UI\Xaml\Window.skia.cs:line 47
   at Windows.UI.Xaml.Window..ctor() in C:\a\1\s\src\Uno.UI\UI\Xaml\Window.skia.cs:line 39
   at Windows.UI.Xaml.Window.InternalGetCurrentWindow() in C:\a\1\s\src\Uno.UI\UI\Xaml\Window.skia.cs:line 175
   at Windows.UI.Xaml.Window.get_Current() in C:\a\1\s\src\Uno.UI\UI\Xaml\Window.cs:line 143
   at Uno.UI.Runtime.Skia.Renderer..ctor()
   at Uno.UI.Runtime.Skia.FrameBufferHost.Initialize()
   at Uno.WinUI.Runtime.Skia.LinuxFB.EventLoop.Run()
   at System.Threading.Thread.StartCallback()
```

I'm using Debian testing and .NET 6 SDK.

Other projects do works as expected, I got exception only with the Linux.FrameBuffer project.

### Expected behavior

The default template should not throw an exception.

**Comment by jeromelaban** [comment]
Thanks for the report. This has been fixed in latest 4.1-dev builds.
