### ISSUE TITLE
[net6-android] `PopupPanel#onMeasure()` did not set the measured dimension

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#7996]
### Current behavior

Runtime tests fails to run with the following fatal exception, running on net6.0-android only:

```
java.lang.IllegalStateException: View with id -1: crc642a1e7e20b34a3939.PopupPanel#onMeasure() did not set the measured dimension by calling setMeasuredDimension()
	at android.view.View.measure(View.java:23182)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:23169)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:23169)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2718)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1572)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1855)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

[android-device-log-RuntimeTests-RuntimeTests (1).txt](https://github.com/unoplatform/uno/files/7999398/android-device-log-RuntimeTests-RuntimeTests.1.txt)

### How to reproduce it (as minimally and precisely as possible)

.NET: 6.0.200-preview.22055.15
Uno check manifest: https://raw.githubusercontent.com/unoplatform/uno.check/4b89f56d8fa3f2cdd980425dcc8cbc4db1249d99/manifests/uno.ui-preview.manifest.json

### NuGet package version(s)

4.1-dev.600

### Affected platforms

Android

**Comment by MartinZikmund** [comment]
@jeromelaban have you still encountered this recently?

**Comment by jeromelaban** [comment]
It's likely worked around of fixed since then.
