### ISSUE TITLE
[WASM] Touch hangs during panning gesture

### ISSUE THREAD

**Issue by SeRgI1982** [unoplatform/uno#8073]
### Current behavior

During panning gesture by 1 finger PointerMoved event stop responding. PointerReleased is not raised. 
When user use 2 fingers, everything start working as expected.
After 2 fingers operation, 1 finger panning gesture starts working correctly but after a couple of other tries, still hangs and not raise PointerMoved and PointerReleased events.

Additionally in browse console, an exception is printed:

```
VM130:1 fail: Windows.UI.Xaml.UIElement+PointerCapture[0]
      Failed to release native capture of Touch/11
System.InvalidOperationException: Error #1 "NotFoundError: Failed to execute 'releasePointerCapture' on 'Element': No active pointer with the given id is found.
Error: Failed to execute 'releasePointerCapture' on 'Element': No active pointer with the given id is found.
    at WindowManager.releasePointerCapture (https://localhost:1317/package_8751b48334b13a463b33b7bdc456bcf65fe23fdd/Uno.UI.js:1519:38)
    at eval (eval at 590351 (https://localhost:1317/package_8751b48334b13a463b33b7bdc456bcf65fe23fdd/dotnet.js:1:16858), <anonymous>:1:30)
    at 590351 (https://localhost:1317/package_8751b48334b13a463b33b7bdc456bcf65fe23fdd/dotnet.js:1:16858)
    at _emscripten_asm_const_int (https://localhost:1317/package_8751b48334b13a463b33b7bdc456bcf65fe23fdd/dotnet.js:1:109603)
    at wasm://wasm/00978b42:wasm-function[105]:0x654b
    at wasm://wasm/00978b42:wasm-function[219]:0x1a04a
    at wasm://wasm/00978b42:wasm-function[167]:0xcad3
    at wasm://wasm/00978b42:wasm-function[166]:0xb9e6
    at wasm://wasm/00978b42:wasm-function[2810]:0xab7c2
    at wasm://wasm/00978b42:wasm-function[1615]:0x6f707" executing javascript: "Uno.UI.WindowManager.current.releasePointerCapture(107298, 11);"
   at WebAssembly.Runtime.InvokeJS(String str) in C:\a\1\s\src\Uno.Foundation.Runtime.WebAssembly\Interop\WebAssembly.Runtime.cs:line 44
   at Uno.Foundation.WebAssemblyRuntime.InnerInvokeJS(String str) in C:\a\1\s\src\Uno.Foundation.Runtime.WebAssembly\Interop\Runtime.wasm.cs:line 260
   at Uno.Foundation.WebAssemblyRuntime.InvokeJS(String str) in C:\a\1\s\src\Uno.Foundation.Runtime.WebAssembly\Interop\Runtime.wasm.cs:line 231
   at Windows.UI.Xaml.UIElement.ReleasePointerNative(Pointer pointer)
   at Windows.UI.Xaml.UIElement.PointerCapture.ReleasePointerNative()
eval @ VM130:1
VM132:1 fail: Windows.UI.Xaml.UIElement+PointerCapture[0]
      Failed to release native capture of Touch/12
System.InvalidOperationException: Error #1 "NotFoundError: Failed to execute 'releasePointerCapture' on 'Element': No active pointer with the given id is found.
Error: Failed to execute 'releasePointerCapture' on 'Element': No active pointer with the given id is found.
    at WindowManager.releasePointerCapture (https://localhost:1317/package_8751b48334b13a463b33b7bdc456bcf65fe23fdd/Uno.UI.js:1519:38)
    at eval (eval at 590351 (https://localhost:1317/package_8751b48334b13a463b33b7bdc456bcf65fe23fdd/dotnet.js:1:16858), <anonymous>:1:30)
    at 590351 (https://localhost:1317/package_8751b48334b13a463b33b7bdc456bcf65fe23fdd/dotnet.js:1:16858)
    at _emscripten_asm_const_int (https://localhost:1317/package_8751b48334b13a463b33b7bdc456bcf65fe23fdd/dotnet.js:1:109603)
    at wasm://wasm/00978b42:wasm-function[105]:0x654b
    at wasm://wasm/00978b42:wasm-function[219]:0x1a04a
    at wasm://wasm/00978b42:wasm-function[167]:0xcad3
    at wasm://wasm/00978b42:wasm-function[166]:0xb9e6
    at wasm://wasm/00978b42:wasm-function[2810]:0xab7c2
    at wasm://wasm/00978b42:wasm-function[1615]:0x6f707" executing javascript: "Uno.UI.WindowManager.current.releasePointerCapture(107298, 12);"
   at WebAssembly.Runtime.InvokeJS(String str) in C:\a\1\s\src\Uno.Foundation.Runtime.WebAssembly\Interop\WebAssembly.Runtime.cs:line 44
   at Uno.Foundation.WebAssemblyRuntime.InnerInvokeJS(String str) in C:\a\1\s\src\Uno.Foundation.Runtime.WebAssembly\Interop\Runtime.wasm.cs:line 260
   at Uno.Foundation.WebAssemblyRuntime.InvokeJS(String str) in C:\a\1\s\src\Uno.Foundation.Runtime.WebAssembly\Interop\Runtime.wasm.cs:line 231
   at Windows.UI.Xaml.UIElement.ReleasePointerNative(Pointer pointer)
   at Windows.UI.Xaml.UIElement.PointerCapture.ReleasePointerNative()
```

### Expected behavior

No mater how many fingers user use, touch operation should raise at least those events:
- PointerPressed,
- PointerMoved,
- PointerReleased

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

**Microsoft.Windows.Compatibility**          Version="6.0.2-mauipre.1.22054.8"
**Microsoft.Extensions.Logging**          Version="6.0.2-mauipre.1.22054.8"
**Uno.Extensions.Logging.WebAssembly.Console**          Version="1.3.0-dev.1"
**Uno.UI.WebAssembly**          Version="4.2.0-dev.35"
**Uno.UI.RemoteControl**          Version="4.2.0-dev.35"
**Uno.UI.Adapter.Microsoft.Extensions.Logging**          Version="4.0.11"
**Uno.UI.Adapter.Microsoft.Extensions.Logging**          Version="4.2.0-dev.35"
**Uno.Wasm.Bootstrap**          Version="3.3.0-dev.2"
**Uno.Wasm.Bootstrap.DevServer**          Version="3.3.0-dev.2"

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### Anything else we need to know?

Sample app - WASM should behave like UWP:
[TouchSample.zip](https://github.com/unoplatform/uno/files/8051074/TouchSample.zip)

**Comment by SeRgI1982** [comment]
I have tested the issue on different browsers:

Google Chrome (98.0.4758.82) - issue reported above appeared on this browser and version.
Firefox (97.0) - works as expected
Microsoft Edge (98.0.1108.50) - hangs during pan gesture. Browser steals gesture and shows Prev/Forward arrows. When such an arrow appears and the user releases touch, the page is navigated forward/backward. When the user uses 2 fingers and after that starts using touch gestures by 1 finger - touch starts working correctly.

**Comment by SeRgI1982** [comment]
Google Chrome (98.0.4758.82)

Once again I played with navigation to the other page in the tab where the WASM app was executed and navigated back to the WASM app.
Now I see that Google also steals gestures and shows Prev/Forward arrows.

Reproduction steps:
- Run Wasm app in Google Chrome,
- Navigate to another page,
- Navigate back to Wasm app,
- Do Pan gesture from right to left <- arrow should appear (right-center border of the browser) 

In delivered TouchSample app you should see that 'Pointer moved' register a few changing position then hangs and browser arrow mentioned above starts to slide-in from the right side of the browser

**Comment by SeRgI1982** [comment]
Disabling this option: 
```
chrome://flags/#overscroll-history-navigation
```
only stopped showing arrows

**Comment by jeromelaban** [comment]
This looks like the interaction with the rest of the browser's navigation modes. Would you know of any other javascript-based app that shows does what you want but does not have this issue?

@dr1rrb does this look familiar?

**Comment by SeRgI1982** [comment]
I think I have got it:

https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action

Of course, it needs to be tested how it influence on ScrollView when it is disabled but in my case I should be able to narrow down it to specific div element

**Comment by SeRgI1982** [comment]
> This looks like the interaction with the rest of the browser's navigation modes. Would you know of any other javascript-based app that shows does what you want but does not have this issue?
> 
> @dr1rrb does this look familiar?

If you need sample, just open Google Maps in the browser. Those touch actions are disabled there.

**Comment by francoistanguay** [comment]
@dr1rrb  ?

**Comment by dr1rrb** [comment]
This is a change introduced in recent versions of chromium as it's indeed completely broken. Setting the `touch-action: none;` **only on the root of the app** do prevent this issue without impacting the ability to scroll using finger or pen.

It's going to be fixed by my PR (which also makes sure that we don't alter that property when we capture the pointer like it is currently).
