### ISSUE TITLE
[WASM] DataTemplates on ComboBox not working

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#8355]
### Current behavior

Please see attached where I´m using a DataTemplate for a ComboBox. Works as expected on WindowsAppSdk but not on WASM. There are tons of errors in the browser console (Chrome on Windows 11)

[DataTemplate.zip](https://github.com/unoplatform/uno/files/8261637/DataTemplate.zip)

[localhost-1647432052993.zip](https://github.com/unoplatform/uno/files/8261874/localhost-1647432052993.zip)

```
System.ArgumentOutOfRangeException: No strategy registration for conversion 'DataTemplate' to 'ControlTemplate' (Parameter 'extensionPoint')
   at Uno.Conversion.DefaultConversionExtensions.To(Object value, Type toType, CultureInfo culture) in C:\a\1\s\src\Uno.Foundation\Uno.Core.Extensions\Uno.Core.Extensions.Compatibility\Conversion\DefaultConversionExtensions.cs:line 85
   at Uno.UI.DataBinding.BindingPropertyHelper.Convert(Func`1 propertyType, Object value)
   at Microsoft.UI.Xaml.Setter.ApplyTo(DependencyObject o)
   at Microsoft.UI.Xaml.Style.ApplyTo(DependencyObject o, DependencyPropertyValuePrecedences precedence)
   at Microsoft.UI.Xaml.FrameworkElement.OnStyleChanged(Style oldStyle, Style newStyle, DependencyPropertyValuePrecedences precedence)
   at Microsoft.UI.Xaml.FrameworkElement.ApplyStyle()
   at Microsoft.UI.Xaml.FrameworkElement.OnStyleChanged(Style oldStyle, Style newStyle)
   at Microsoft.UI.Xaml.FrameworkElement.<>c.<.cctor>b__512_0(DependencyObject s, DependencyPropertyChangedEventArgs e)
   at Microsoft.UI.Xaml.PropertyMetadata.RaisePropertyChanged(DependencyObject source, DependencyPropertyChangedEventArgs e)
   at Microsoft.UI.Xaml.DependencyObjectStore.InvokeCallbacks(DependencyObject actualInstanceAlias, DependencyProperty property, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence, 
```

### Expected behavior

WASM should work like WindowsAppSdk

### Works on UWP/WinUI

Yes

### Affected platforms

WebAssembly

**Comment by jeromelaban** [comment]
Thanks for the report. If you see errors, please post them in the issue as well.

**Comment by DierkDroth** [comment]
@jeromelaban sure. Please see above

**Comment by jeromelaban** [comment]
The issue is in the code of the sample, where the following style:
```csharp
Setters = { new Setter(ComboBoxItem.TemplateProperty, dataTemplate) },
```
is setting a `DataTemplate` to the the `Template` property of `ComboBoxItem`. Make sure to define a `ControlTemplate` instead.

**Comment by DierkDroth** [comment]
@jeromelaban thanks for follow up.

However, there are 2 problems:
- the ellipse still is not rendered in WASM -> the template approach would be completely useless
- please see the the revised repo (attached): do I really need a DataTemplate **and** a ControlTemplate?!?

[DataTemplate2.zip](https://github.com/unoplatform/uno/files/8448539/DataTemplate2.zip)
