### ISSUE TITLE
Playground: Double.Parse Exception on #cards sample

### ISSUE THREAD

**Issue by carldebilly** [unoplatform/uno#8466]
## Steps
1. Set your browser to french (reproduced with french canadian)
2. Navigate to https://playground.platform.uno/#cards
3. Observe the right part of the app is empty
4. Press F12 and check in the console.

<details><summary>--Logs--</summary>

```
fail: Uno.UI.Demo.App[0]
      UnhandledException
System.FormatException: Format_InvalidString
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseDouble(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Double.Parse(String s, NumberStyles style)
   at Uno.UI.DataBinding.BindingPropertyHelper.GetDoubleValues(String input)
   at Uno.UI.DataBinding.BindingPropertyHelper.FastStringToPoint(Type outputType, String input, Object& output)
   at Uno.UI.DataBinding.BindingPropertyHelper.FastStringConvert(Type outputType, String input, Object& output)
   at Uno.UI.DataBinding.BindingPropertyHelper.FastConvert(Type outputType, Object input, Object& output)
   at Uno.UI.DataBinding.BindingPropertyHelper.Convert(Func`1 propertyType, Object value)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.BuildLiteralValue(Type propertyType, String memberValue)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.BuildLiteralValue(XamlMemberDefinition member, Type propertyType)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.ProcessNamedMember(XamlObjectDefinition control, Object instance, XamlMemberDefinition member, Object rootInstance)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.LoadObject(XamlObjectDefinition control, Object rootInstance, Object component, Boolean createInstanceFromXClass)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.ProcessMemberElements(Object instance, XamlMemberDefinition member, PropertyInfo propertyInfo, Object rootInstance)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.ProcessNamedMember(XamlObjectDefinition control, Object instance, XamlMemberDefinition member, Object rootInstance)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.LoadObject(XamlObjectDefinition control, Object rootInstance, Object component, Boolean createInstanceFromXClass)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.AddCollectionItems(Object collectionInstance, IEnumerable`1 nonBindingObjects, Object rootInstance)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.ProcessMemberElements(Object instance, XamlMemberDefinition member, PropertyInfo propertyInfo, Object rootInstance)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.ProcessNamedMember(XamlObjectDefinition control, Object instance, XamlMemberDefinition member, Object rootInstance)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.LoadObject(XamlObjectDefinition control, Object rootInstance, Object component, Boolean createInstanceFromXClass)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.AddCollectionItems(Object collectionInstance, IEnumerable`1 nonBindingObjects, Object rootInstance)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.ProcessMemberElements(Object instance, XamlMemberDefinition member, PropertyInfo propertyInfo, Object rootInstance)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.ProcessNamedMember(XamlObjectDefinition control, Object instance, XamlMemberDefinition member, Object rootInstance)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.LoadObject(XamlObjectDefinition control, Object rootInstance, Object component, Boolean createInstanceFromXClass)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.<>c__DisplayClass11_0.<LoadObject>b__3()
   at Windows.UI.Xaml.FrameworkTemplate.<>c__DisplayClass5_0.<.ctor>b__0(Object _)
   at Windows.UI.Xaml.FrameworkTemplate.LoadContent()
   at Windows.UI.Xaml.FrameworkTemplatePool.DequeueTemplate(FrameworkTemplate template)
   at Windows.UI.Xaml.FrameworkTemplate.LoadContentCached()
   at Windows.UI.Xaml.Controls.Primitives.Selector.GetRootOfItemTemplateAsContainer(DataTemplate template)
   at Windows.UI.Xaml.Controls.ItemsControl.GetContainerForTemplate(DataTemplate template)
   at Windows.UI.Xaml.Controls.ItemsControl.GetContainerForIndex(Int32 index)
   at Windows.UI.Xaml.Controls.VirtualizingPanelGenerator.DequeueViewForItem(Int32 index)
   at Windows.UI.Xaml.Controls.ItemsStackPanelLayout.CreateLine(GeneratorDirection fillDirection, Double extentOffset, Double availableBreadth, IndexPath nextVisibleItem)
   at Windows.UI.Xaml.Controls.VirtualizingPanelLayout.AddLine(GeneratorDirection fillDirection, IndexPath nextVisibleItem)
   at Windows.UI.Xaml.Controls.VirtualizingPanelLayout.<>c__DisplayClass114_0.<FillLayout>g__FillForward|2()
   at Windows.UI.Xaml.Controls.VirtualizingPanelLayout.FillLayout(Double extentAdjustment)
   at Windows.UI.Xaml.Controls.VirtualizingPanelLayout.UpdateLayout(Nullable`1 extentAdjustment, Boolean isScroll)
   at Windows.UI.Xaml.Controls.VirtualizingPanelLayout.MeasureOverride(Size availableSize)
   at Windows.UI.Xaml.Controls.ItemsStackPanel.MeasureOverride(Size availableSize)
   at Windows.UI.Xaml.FrameworkElement.InnerMeasureCore(Size availableSize)
   at Windows.UI.Xaml.FrameworkElement.MeasureCore(Size availableSize)
   at Windows.UI.Xaml.UIElement.DoMeasure(Size availableSize)
   at Windows.UI.Xaml.UIEl
eval @ VM387:1
dotnet.js:1 Uncaught Error: System.FormatException: Format_InvalidString
   at System.Number.ThrowOverflowOrFormatException(/ParsingStatus status, TypeCode type)
   at System.Number.ParseDouble(/ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Double.Parse(/String s, NumberStyles style)
   at Uno.UI.DataBinding.BindingPropertyHelper.GetDoubleValues(/String input)
   at Uno.UI.DataBinding.BindingPropertyHelper.FastStringToPoint(/Type outputType, String input, Object& output)
   at Uno.UI.DataBinding.BindingPropertyHelper.FastStringConvert(/Type outputType, String input, Object& output)
   at Uno.UI.DataBinding.BindingPropertyHelper.FastConvert(/Type outputType, Object input, Object& output)
   at Uno.UI.DataBinding.BindingPropertyHelper.Convert(/Func`1 propertyType, Object value)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.BuildLiteralValue(/Type propertyType, String memberValue)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.BuildLiteralValue(/XamlMemberDefinition member, Type propertyType)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.ProcessNamedMember(/XamlObjectDefinition control, Object instance, XamlMemberDefinition member, Object rootInstance)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.LoadObject(/XamlObjectDefinition control, Object rootInstance, Object component, Boolean createInstanceFromXClass)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.ProcessMemberElements(/Object instance, XamlMemberDefinition member, PropertyInfo propertyInfo, Object rootInstance)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.ProcessNamedMember(/XamlObjectDefinition control, Object instance, XamlMemberDefinition member, Object rootInstance)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.LoadObject(/XamlObjectDefinition control, Object rootInstance, Object component, Boolean createInstanceFromXClass)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.AddCollectionItems(/Object collectionInstance, IEnumerable`1 nonBindingObjects, Object rootInstance)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.ProcessMemberElements(/Object instance, XamlMemberDefinition member, PropertyInfo propertyInfo, Object rootInstance)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.ProcessNamedMember(/XamlObjectDefinition control, Object instance, XamlMemberDefinition member, Object rootInstance)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.LoadObject(/XamlObjectDefinition control, Object rootInstance, Object component, Boolean createInstanceFromXClass)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.AddCollectionItems(/Object collectionInstance, IEnumerable`1 nonBindingObjects, Object rootInstance)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.ProcessMemberElements(/Object instance, XamlMemberDefinition member, PropertyInfo propertyInfo, Object rootInstance)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.ProcessNamedMember(/XamlObjectDefinition control, Object instance, XamlMemberDefinition member, Object rootInstance)
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.LoadObject(/XamlObjectDefinition control, Object rootInstance, Object component, Boolean createInstanceFromXClass)
   at /Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.<>c__DisplayClass11_0.<LoadObject>b__3()
   at Windows.UI.Xaml.FrameworkTemplate.<>c__DisplayClass5_0.<.ctor>b__0(/Object _)
   at /Windows.UI.Xaml.FrameworkTemplate.LoadContent()
   at Windows.UI.Xaml.FrameworkTemplatePool.DequeueTemplate(/FrameworkTemplate template)
   at /Windows.UI.Xaml.FrameworkTemplate.LoadContentCached()
   at Windows.UI.Xaml.Controls.Primitives.Selector.GetRootOfItemTemplateAsContainer(/DataTemplate template)
   at Windows.UI.Xaml.Controls.ItemsControl.GetContainerForTemplate(/DataTemplate template)
   at Windows.UI.Xaml.Controls.ItemsControl.GetContainerForIndex(/Int32 index)
   at Windows.UI.Xaml.Controls.VirtualizingPanelGenerator.DequeueViewForItem(/Int32 index)
   at Windows.UI.Xaml.Controls.ItemsStackPanelLayout.CreateLine(/GeneratorDirection fillDirection, Double extentOffset, Double availableBreadth, IndexPath nextVisibleItem)
   at Windows.UI.Xaml.Controls.VirtualizingPanelLayout.AddLine(/GeneratorDirection fillDirection, IndexPath nextVisibleItem)
   at /Windows.UI.Xaml.Controls.VirtualizingPanelLayout.<>c__DisplayClass114_0.<FillLayout>g__FillForward|2()
   at Windows.UI.Xaml.Controls.VirtualizingPanelLayout.FillLayout(/Double extentAdjustment)
   at Windows.UI.Xaml.Controls.VirtualizingPanelLayout.UpdateLayout(/Nullable`1 extentAdjustment, Boolean isScroll)
   at Windows.UI.Xaml.Controls.VirtualizingPanelLayout.MeasureOverride(/Size availableSize)
   at Windows.UI.Xaml.Controls.ItemsStackPanel.MeasureOverride(/Size availableSize)
   at Windows.UI.Xaml.FrameworkElement.InnerMeasureCore(/Size availableSize)
   at Windows.UI.Xaml.FrameworkElement.MeasureCore(/Size availableSize)
   at Windows.UI.Xaml.UIElement.DoMeasure(/Size availableSize)
   at Windows.UI.Xaml.UIElement.Measure(/Size availableSize)
   at Windows.UI.Xaml.FrameworkElement.MeasureElement(/UIElement view, Size availableSize)
   at Windows.UI.Xaml.FrameworkElement.MeasureOverride(/Size availableSize)
   at Windows.UI.Xaml.Controls.ItemsPresenter.MeasureOverride(/Size size)
   at /Windows.UI.Xaml.Window.DispatchInvalidateMeasure()
   [ ... a lot of recursive .Measure() here]
   at Windows.UI.Xaml.Window.OnNativeSizeChanged(/Size size)
   at Windows.UI.Xaml.Window.Resize(/Double width, Double height)
    at Object._convert_exception_for_method_call (/package_2fbce3bfd0db46b0853bec503c9c3477dc4307b2/dotnet.js:1:184193)
    at Object._handle_exception_for_call (/package_2fbce3bfd0db46b0853bec503c9c3477dc4307b2/dotnet.js:1:186162)
    at Function.managed__Uno_UI__Windows_UI_Xaml_Window_Resize [as resizeMethod] (mono-wasm.invalid/managed__Uno_UI__Windows_UI_Xaml_Window_Resize:18:21)
    at WindowManager.resize (/package_2fbce3bfd0db46b0853bec503c9c3477dc4307b2/Uno.UI.js:1674:35)
    at /package_2fbce3bfd0db46b0853bec503c9c3477dc4307b2/Uno.UI.js:1649:61
```

</details>

**Comment by jeromelaban** [comment]
Parsing is incorrect:
https://github.com/unoplatform/uno/blob/5075bd5b680bb26c17e13e26885ff5a2f6022d09/src/Uno.UI/DataBinding/BindingPropertyHelper.FastConvert.cs#L1018

and here as well:
https://github.com/unoplatform/uno/blob/5075bd5b680bb26c17e13e26885ff5a2f6022d09/src/Uno.UI/DataBinding/BindingPropertyHelper.FastConvert.cs#L1033

We must add additional unit tests with various locales, short of adding roslyn analyzers validation for all number parsing (https://github.com/dotnet/roslyn-analyzers/pull/3851 may have helped, but is not available yet).

**Comment by Youssef1313** [comment]
@jeromelaban This appears to be fixed in https://github.com/unoplatform/uno/pull/10337
Should we close? There are no unit tests for this though, but the CA1305 does a good job it seems.

**Comment by jeromelaban** [comment]
Let's close indeed.
