### ISSUE TITLE
NavigationViewItem with empty MenuItems rendering with exception

### ISSUE THREAD

**Issue by Dimigergo** [unoplatform/uno#8470]
### Current behavior

When I have a NavigationViewItem with empty menuitems like this:
```
<muxc:NavigationViewItem x:Name="Views"
                         Content="{x:Bind Vm.Culture.NavItemViews}" 
                         Icon="Repair" 
                         SelectsOnInvoked="False"
                         Visibility="{x:Bind Vm.HasViews, Mode=OneWay}"
                         ToolTipService.ToolTip="{x:Bind Vm.Culture.NavItemViews}" >
    <muxc:NavigationViewItem.MenuItems>
    </muxc:NavigationViewItem.MenuItems>
</muxc:NavigationViewItem>
```

the following exception occures:
```
Uno.UI.Dispatching.CoreDispatcher[0]
      Dispatcher unhandled exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.UI.Xaml.Controls.NavigationViewItem.PropagateDepthToChildren(Int32 depth)
   at Microsoft.UI.Xaml.Controls.NavigationView.OnRepeaterElementPrepared(ItemsRepeater ir, ItemsRepeaterElementPreparedEventArgs args)
   at Microsoft.UI.Xaml.Controls.NavigationView.OnRepeaterUnoBeforeElementPrepared(ItemsRepeater itemsRepeater, ItemsRepeaterElementPreparedEventArgs args)
   at Microsoft.UI.Xaml.Controls.ItemsRepeater.OnUnoBeforeElementPrepared(UIElement element, Int32 index)
   at Microsoft.UI.Xaml.Controls.ViewManager.GetElementFromElementFactory(Int32 index)
   at Microsoft.UI.Xaml.Controls.ViewManager.GetElement(Int32 index, Boolean forceCreate, Boolean suppressAutoRecycle)
   at Microsoft.UI.Xaml.Controls.ItemsRepeater.GetElementImpl(Int32 index, Boolean forceCreate, Boolean suppressAutoRecycle)
   at Microsoft.UI.Xaml.Controls.RepeaterLayoutContext.GetOrCreateElementAtCore(Int32 index, ElementRealizationOptions options)
   at Microsoft.UI.Xaml.Controls.VirtualizingLayoutContext.GetOrCreateElementAt(Int32 index, ElementRealizationOptions options)
   at Microsoft.UI.Xaml.Controls.ElementManager.EnsureElementRealized(Boolean forward, Int32 dataIndex, String layoutId)
   at Microsoft.UI.Xaml.Controls.FlowLayoutAlgorithm.Generate(GenerateDirection direction, Int32 anchorIndex, Size availableSize, Double minItemSpacing, Double lineSpacing, UInt32 maxItemsPerLine, Boolean disableVirtualization, String layoutId)
   at Microsoft.UI.Xaml.Controls.FlowLayoutAlgorithm.Measure(Size availableSize, VirtualizingLayoutContext context, Boolean isWrapping, Double minItemSpacing, Double lineSpacing, UInt32 maxItemsPerLine, ScrollOrientation orientation, Boolean disableVirtualization, String layoutId)
   at Microsoft.UI.Xaml.Controls.StackLayout.MeasureOverride(VirtualizingLayoutContext context, Size availableSize)
   at Microsoft.UI.Xaml.Controls.Layout.Measure(LayoutContext context, Size availableSize)
   at Microsoft.UI.Xaml.Controls.ItemsRepeater.MeasureOverride(Size availableSize)
   at Microsoft.UI.Xaml.FrameworkElement.InnerMeasureCore(Size availableSize)
   at Microsoft.UI.Xaml.FrameworkElement.MeasureCore(Size availableSize)
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize)
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize)
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize)
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize)
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize)
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize)
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize)
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize)
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize)
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize)
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize)
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize)
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize)
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize)
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize)
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize)
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize)
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize)
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize)
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize)
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize)
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize)
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize)
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize)
   at Microsoft.UI.Xaml.Window.DispatchInvalidateMeasure()
   at Microsoft.UI.Xaml.Window.<InnerInvalidateMeasure>b__79_0()
   at Uno.UI.Dispatching.CoreDispatcher.InvokeOperationSafe(UIAsyncOperation operation) in C:\a\1\s\src\Uno.UI.Dispatching\Core\CoreDispatcher.cs:line 337
```

### Expected behavior

No exception occures and navigation view is shown.

### How to reproduce it (as minimally and precisely as possible)

```
<muxc:NavigationViewItem x:Name="Views"
                         Content="{x:Bind Vm.Culture.NavItemViews}" 
                         Icon="Repair" 
                         SelectsOnInvoked="False"
                         Visibility="{x:Bind Vm.HasViews, Mode=OneWay}"
                         ToolTipService.ToolTip="{x:Bind Vm.Culture.NavItemViews}" >
    <muxc:NavigationViewItem.MenuItems>
    </muxc:NavigationViewItem.MenuItems>
</muxc:NavigationViewItem>
```

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

WASM project:
Uno.WinUI.WebAssembly 4.2.0-dev.521
Uno.WinUI.RemoteControl 4.2.0-dev.521
Uno.Wasm.Bootstrap.DevServer 4.0.0-dev.103
Uno.Wasm.Bootstrap 4.0.0-dev.103
Uno.CommunityToolkit.WinUI.UI.Controls 7.1.100-dev.15.g12261e2626

WinUI project:
Microsoft.WindowsAppSDK 1.1.0-preview1
Uno.WinUI 4.2.0-dev.521
CommunityToolkit.WinUI.UI 7.1.2

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

17.1.2

**Comment by Dimigergo** [comment]
In this repo, you can see the exception in wasm.
If I uncomment `<!--<muxc:NavigationViewItem Content="Dummy" />-->` in CMain.cs everything works fine.

[NavigationView2.zip](https://github.com/unoplatform/uno/files/8395559/NavigationView2.zip)

**Comment by ramezgerges** [comment]
I tested this with the given repro and couldn't recreate the exception.

**Comment by MartinZikmund** [comment]
As @ramezgerges wasn't able to repro this, it is likely fixed - closing!
