### ISSUE TITLE
New project from latest template doesn't build Android on VS2017

### ISSUE THREAD

**Issue by FrancoisM** [unoplatform/uno#852]
## I'm submitting a...
Bug report (I searched for similar issues and did not find one) 

## Current behavior
Error below

## Expected behavior
It should build on VS2107 (it does on VS2019)?

## Minimal reproduction of the problem with instructions
Brand new project from Uno template created in VS2019

## Environment

Nuget Package: Uno.UI

Package Version(s): 1.43.1

Affected platform(s):
- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [x] 2017 (version:  15.9.11)
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

Error:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Generation failed: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Generation failed for Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator. System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: The type Windows.UI.Xaml.ElementStub could not be found
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GetType(String name) in D:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.Reflection.cs:line 687
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator..ctor(XamlFileDefinition file, String targetPath, String defaultNamespace, RoslynMetadataHelper medataHelper, String fileUniqueId, DateTime lastReferenceUpdateTime, String[] analyzerSuppressions, String[] resourceKeys, Boolean outputSourceComments, XamlGlobalStaticResourcesMap globalStaticResourcesMap, Boolean isUiAutomationMappingEnabled, Dictionary`2 uiAutomationMappings, String defaultLanguage, Boolean isWasm, Boolean isDebug) in D:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 124
   at Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGeneration.<>c__DisplayClass22_0.<Generate>b__0(XamlFileDefinition file) in D:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlCodeGeneration.cs:line 155
   at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.QueryOpeningEnumerator`1.OpenQuery()
   at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
   at System.Linq.ParallelEnumerable.ToList[TSource](ParallelQuery`1 source)
   at Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGeneration.Generate() in D:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlCodeGeneration.cs:line 144
   at Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator.Execute(SourceGeneratorContext context) in D:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlCodeGenerator.cs:line 20
   at Uno.SourceGeneration.Host.SourceGeneratorEngine.<>c__DisplayClass3_1.<Generate>b__13(ValueTuple`2 generatorDef)
---> (Inner Exception #0) System.InvalidOperationException: The type Windows.UI.Xaml.ElementStub could not be found
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GetType(String name) in D:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.Reflection.cs:line 687
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator..ctor(XamlFileDefinition file, String targetPath, String defaultNamespace, RoslynMetadataHelper medataHelper, String fileUniqueId, DateTime lastReferenceUpdateTime, String[] analyzerSuppressions, String[] resourceKeys, Boolean outputSourceComments, XamlGlobalStaticResourcesMap globalStaticResourcesMap, Boolean isUiAutomationMappingEnabled, Dictionary`2 uiAutomationMappings, String defaultLanguage, Boolean isWasm, Boolean isDebug) in D:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 124
   at Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGeneration.<>c__DisplayClass22_0.<Generate>b__0(XamlFileDefinition file) in D:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlCodeGeneration.cs:line 155
   at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.Tasks.Task.Execute()<---

---> (Inner Exception #1) System.InvalidOperationException: The type Windows.UI.Xaml.ElementStub could not be found
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GetType(String name) in D:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.Reflection.cs:line 687
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator..ctor(XamlFileDefinition file, String targetPath, String defaultNamespace, RoslynMetadataHelper medataHelper, String fileUniqueId, DateTime lastReferenceUpdateTime, String[] analyzerSuppressions, String[] resourceKeys, Boolean outputSourceComments, XamlGlobalStaticResourcesMap globalStaticResourcesMap, Boolean isUiAutomationMappingEnabled, Dictionary`2 uiAutomationMappings, String defaultLanguage, Boolean isWasm, Boolean isDebug) in D:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 124
   at Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGeneration.<>c__DisplayClass22_0.<Generate>b__0(XamlFileDefinition file) in D:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlCodeGeneration.cs:line 155
   at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.Tasks.Task.Execute()<---

   at Uno.SourceGeneration.Host.SourceGeneratorEngine.<>c__DisplayClass3_1.<Generate>b__13(ValueTuple`2 generatorDef)
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---

Server stack trace: 
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.ScanQueryOperator`1.ScanEnumerableQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.ExecuteAndGetResultsAsArray()
   at Uno.SourceGeneration.Host.SourceGeneratorEngine.Generate()
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Uno.SourceGeneratorTasks.RemoteSourceGeneratorEngine.Generate(RemotableLogger2 logger, BuildEnvironment environment)
   at Uno.SourceGeneration.Host.Server.GenerationServerHost.RunGeneration(RunRequest request, CancellationToken cancellationToken)
---> (Inner Exception #0) System.InvalidOperationException: Generation failed for Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator. System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: The type Windows.UI.Xaml.ElementStub could not be found
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GetType(String name) in D:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.Reflection.cs:line 687
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator..ctor(XamlFileDefinition file, String targetPath, String defaultNamespace, RoslynMetadataHelper medataHelper, String fileUniqueId, DateTime lastReferenceUpdateTime, String[] analyzerSuppressions, String[] resourceKeys, Boolean outputSourceComments, XamlGlobalStaticResourcesMap globalStaticResourcesMap, Boolean isUiAutomationMappingEnabled, Dictionary`2 uiAutomationMappings, String defaultLanguage, Boolean isWasm, Boolean isDebug) in D:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 124
   at Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGeneration.<>c__DisplayClass22_0.<Generate>b__0(XamlFileDefinition file) in D:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlCodeGeneration.cs:line 155
   at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.QueryOpeningEnumerator`1.OpenQuery()
   at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
   at System.Linq.ParallelEnumerable.ToList[TSource](ParallelQuery`1 source)
   at Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGeneration.Generate() in D:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlCodeGeneration.cs:line 144
   at Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator.Execute(SourceGeneratorContext context) in D:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlCodeGenerator.cs:line 20
   at Uno.SourceGeneration.Host.SourceGeneratorEngine.<>c__DisplayClass3_1.<Generate>b__13(ValueTuple`2 generatorDef)
---> (Inner Exception #0) System.InvalidOperationException: The type Windows.UI.Xaml.ElementStub could not be found
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GetType(String name) in D:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.Reflection.cs:line 687
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator..ctor(XamlFileDefinition file, String targetPath, String defaultNamespace, RoslynMetadataHelper medataHelper, String fileUniqueId, DateTime lastReferenceUpdateTime, String[] analyzerSuppressions, String[] resourceKeys, Boolean outputSourceComments, XamlGlobalStaticResourcesMap globalStaticResourcesMap, Boolean isUiAutomationMappingEnabled, Dictionary`2 uiAutomationMappings, String defaultLanguage, Boolean isWasm, Boolean isDebug) in D:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 124
   at Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGeneration.<>c__DisplayClass22_0.<Generate>b__0(XamlFileDefinition file) in D:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlCodeGeneration.cs:line 155
   at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.Tasks.Task.Execute()<---

---> (Inner Exception #1) System.InvalidOperationException: The type Windows.UI.Xaml.ElementStub could not be found
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GetType(String name) in D:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.Reflection.cs:line 687
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator..ctor(XamlFileDefinition file, String targetPath, String defaultNamespace, RoslynMetadataHelper medataHelper, String fileUniqueId, DateTime lastReferenceUpdateTime, String[] analyzerSuppressions, String[] resourceKeys, Boolean outputSourceComments, XamlGlobalStaticResourcesMap globalStaticResourcesMap, Boolean isUiAutomationMappingEnabled, Dictionary`2 uiAutomationMappings, String defaultLanguage, Boolean isWasm, Boolean isDebug) in D:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 124
   at Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGeneration.<>c__DisplayClass22_0.<Generate>b__0(XamlFileDefinition file) in D:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlCodeGeneration.cs:line 155
   at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.Tasks.Task.Execute()<---

   at Uno.SourceGeneration.Host.SourceGeneratorEngine.<>c__DisplayClass3_1.<Generate>b__13(ValueTuple`2 generatorDef)
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.Tasks.Task.Execute()<---	App1.Droid			
Error		Error reading response	App1.Droid			
Error		Generation failed, error code Rejected	App1.Droid

**Comment by jeromelaban** [comment]
Support for VS2017 has been deprecated, and Microsoft is not pushing in that direction anymore.
