### ISSUE TITLE
[Skia.Gtk][WSL] `DatePicker` and `CalendarDatePicker` throw exceptions

### ISSUE THREAD

**Issue by Thorachu** [unoplatform/uno#8573]
### Current behavior

Adding a DatePicker/CalendarDatePicker to a page causes an exception to be thrown when the page is initialized:

DatePicker:
```
The type initializer for 'Windows.Globalization.ApplicationLanguages' threw an exception.
   at Windows.Globalization.ApplicationLanguages.get_Languages() in C:\a\1\s\src\Uno.UWP\Globalization\ApplicationLanguages.cs:line 31
   at Windows.Globalization.Calendar..ctor() in C:\a\1\s\src\Uno.UWP\Globalization\Calendar.cs:line 92
   at Windows.UI.Xaml.Controls.DatePicker.CreateNewCalendar(String strCalendarIdentifier, Calendar& ppCalendar) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\DatePicker\DatePicker.cs:line 1522
   at Windows.UI.Xaml.Controls.DatePicker.UpdateState() in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\DatePicker\DatePicker.cs:line 2100
   at Windows.UI.Xaml.Controls.DatePicker.PrepareState() in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\DatePicker\DatePicker.cs:line 223
   at Windows.UI.Xaml.Controls.DatePicker..ctor() in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\DatePicker\DatePicker.cs:line 196
   at BugTesting.MainPage.InitializeComponent() in <redacted>\BugTesting\BugTesting\BugTesting.Skia.Gtk\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\MainPage_e8491afeb7a659d367fea60bf5dcd3a7.cs:line 59
   at BugTesting.MainPage..ctor() in <redacted>\BugTesting\BugTesting\BugTesting.Shared\MainPage.xaml.cs:line 30
Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Windows.Globalization.ApplicationLanguages.ApplyLanguages() in C:\a\1\s\src\Uno.UWP\Globalization\ApplicationLanguages.cs:line 82
   at Windows.Globalization.ApplicationLanguages..cctor() in C:\a\1\s\src\Uno.UWP\Globalization\ApplicationLanguages.cs:line 16
```

CalendarDatePicker:
```
The type initializer for 'Windows.UI.Xaml.Controls.CalendarView' threw an exception.
   at System.Runtime.CompilerServices.RuntimeHelpers._RunClassConstructor(RuntimeType type)
   at Windows.UI.Xaml.DependencyProperty.ForceInitializeTypeConstructor(Type type) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyProperty.cs:line 449
   at Windows.UI.Xaml.DependencyProperty.InternalGetPropertiesForType(Type type) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyProperty.cs:line 412
   at Windows.UI.Xaml.DependencyProperty.GetPropertiesForType(Type type) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyProperty.cs:line 367
   at Windows.UI.Xaml.DependencyPropertyDetailsCollection.EnsureEntriesInitialized() in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyPropertyDetailsCollection.cs:line 71
   at Windows.UI.Xaml.DependencyPropertyDetailsCollection.TryGetPropertyDetails(DependencyProperty property, Boolean forceCreate) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyPropertyDetailsCollection.cs:line 125
   at Windows.UI.Xaml.DependencyPropertyDetailsCollection.GetPropertyDetails(DependencyProperty property) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyPropertyDetailsCollection.cs:line 113
   at Windows.UI.Xaml.DependencyObjectStore.GetValueUnderPrecedence(DependencyProperty property, DependencyPropertyValuePrecedences precedence) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 977
   at Windows.UI.Xaml.DependencyObjectStore.CoerceValue(DependencyProperty property) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 581
   at Windows.UI.Xaml.DependencyObjectExtensions.CoerceValue(IDependencyObjectStoreProvider storeProvider, DependencyProperty property) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectExtensions.cs:line 314
   at Windows.UI.Xaml.UIElement.UpdateHitTest() in C:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.Pointers.Managed.cs:line 403
   at Windows.UI.Xaml.UIElement..ctor() in C:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.skia.cs:line 40
   at Windows.UI.Xaml.FrameworkElement..ctor() in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.skia.cs:line 24
   at Windows.UI.Xaml.Controls.Control..ctor() in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Control\Control.skia.cs:line 18
   at Windows.UI.Xaml.Controls.CalendarView..ctor() in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\CalendarView\CalendarView_Partial.cs:line 150
   at Uno.UI.FluentTheme.v2.__Resources._themeresources_v2_45f76a11e2ea901415bf5c04615d7196_themeresources_v2RDSC35.<>c__DisplayClass0_0.<Build>b__0(Grid c2741) in C:\a\1\s\src\Uno.UI.FluentTheme.v2\obj\Uno.UI.FluentTheme.v2.Skia\Release\netstandard2.0\g\XamlCodeGenerator\themeresources_v2_45f76a11e2ea901415bf5c04615d7196.g.cs:line 90767
   at Uno.UI.FluentTheme.v2.__Resources._themeresources_v2_45f76a11e2ea901415bf5c04615d7196_themeresources_v2RDSC35.Build(Object __ResourceOwner_1464) in C:\a\1\s\src\Uno.UI.FluentTheme.v2\obj\Uno.UI.FluentTheme.v2.Skia\Release\netstandard2.0\g\XamlCodeGenerator\themeresources_v2_45f76a11e2ea901415bf5c04615d7196.g.cs:line 89893
   at Uno.UI.FluentTheme.v2.GlobalStaticResources.ResourceDictionarySingleton__0.<>c.<Get_0_152>b__74_1(Object __owner) in C:\a\1\s\src\Uno.UI.FluentTheme.v2\obj\Uno.UI.FluentTheme.v2.Skia\Release\netstandard2.0\g\XamlCodeGenerator\themeresources_v2_45f76a11e2ea901415bf5c04615d7196.g.cs:line 1859
   at Windows.UI.Xaml.FrameworkTemplate.LoadContent() in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkTemplate.cs:line 97
   at Windows.UI.Xaml.FrameworkTemplatePool.DequeueTemplate(FrameworkTemplate template) in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkTemplatePool.cs:line 207
   at Windows.UI.Xaml.FrameworkTemplate.LoadContentCached() in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkTemplate.cs:line 73
   at Windows.UI.Xaml.Controls.Control.UpdateTemplate() in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Control\Control.cs:line 470
   at Windows.UI.Xaml.Controls.Control.SetUpdateControlTemplate(Boolean forceUpdate) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Control\Control.cs:line 136
   at Windows.UI.Xaml.Controls.Control.OnTemplateChanged(DependencyPropertyChangedEventArgs e) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Control\Control.cs:line 118
   at Windows.UI.Xaml.Controls.Control.<>c.<.cctor>b__378_0(DependencyObject s, DependencyPropertyChangedEventArgs e) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Control\Control.cs:line 113
   at Windows.UI.Xaml.DependencyObjectStore.InvokeCallbacks(DependencyObject actualInstanceAlias, DependencyProperty property, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence, Boolean bypassesPropagation) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 1824
   at Windows.UI.Xaml.DependencyObjectStore.RaiseCallbacks(DependencyObject actualInstanceAlias, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 1734
   at Windows.UI.Xaml.DependencyObjectStore.InnerSetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isPersistentResourceBinding) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 501
   at Windows.UI.Xaml.DependencyObjectStore.SetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isPersistentResourceBinding) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 435
   at Windows.UI.Xaml.DependencyObjectStore.SetValue(DependencyProperty property, Object value) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 389
   at Windows.UI.Xaml.UIElement.SetValue(DependencyProperty dp, Object value) in C:\a\1\s\src\Uno.UI\obj\Uno.UI.Skia\Release\netstandard2.0\g\DependencyObjectGenerator\Windows_UI_Xaml_UIElement_85915f7d6b7124464cf9d270ce415b49.g.cs:line 45
   at Windows.UI.Xaml.Setter.ApplyTo(DependencyObject o) in C:\a\1\s\src\Uno.UI\UI\Xaml\Setter.cs:line 133
   at Windows.UI.Xaml.Style.ApplyTo(DependencyObject o, DependencyPropertyValuePrecedences precedence) in C:\a\1\s\src\Uno.UI\UI\Xaml\Style\Style.cs:line 90
   at Windows.UI.Xaml.FrameworkElement.OnStyleChanged(Style oldStyle, Style newStyle, DependencyPropertyValuePrecedences precedence) in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.cs:line 634
   at Windows.UI.Xaml.FrameworkElement.ApplyStyle() in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.cs:line 415
   at Windows.UI.Xaml.FrameworkElement.ApplyStyles() in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.cs:line 348
   at Windows.UI.Xaml.FrameworkElement.CreationComplete() in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.cs:line 367
   at BugTesting.MainPage.<>c.<InitializeComponent>b__1_4(CalendarDatePicker c0) in <redacted>\BugTesting\BugTesting\BugTesting.Skia.Gtk\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\MainPage_e8491afeb7a659d367fea60bf5dcd3a7.cs:line 74
   at BugTesting.MainPage.InitializeComponent() in <redacted>\BugTesting\BugTesting\BugTesting.Skia.Gtk\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\MainPage_e8491afeb7a659d367fea60bf5dcd3a7.cs:line 59
   at BugTesting.MainPage..ctor() in <redacted>\BugTesting\BugTesting\BugTesting.Shared\MainPage.xaml.cs:line 30
The type initializer for 'Windows.Globalization.ApplicationLanguages' threw an exception.
   at Windows.Globalization.ApplicationLanguages.get_Languages() in C:\a\1\s\src\Uno.UWP\Globalization\ApplicationLanguages.cs:line 31
   at Windows.Globalization.Calendar..ctor() in C:\a\1\s\src\Uno.UWP\Globalization\Calendar.cs:line 92
   at Windows.UI.Xaml.Controls.CalendarView.GetOrCreateGregorianCalendar() in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\CalendarView\CalendarView.Properties.cs:line 888
   at Windows.UI.Xaml.Controls.CalendarView.GetDefaultMaxDate() in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\CalendarView\CalendarView.Properties.cs:line 911
   at Windows.UI.Xaml.Controls.CalendarView..cctor() in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\CalendarView\CalendarView.Properties.cs:line 875
Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Windows.Globalization.ApplicationLanguages.ApplyLanguages() in C:\a\1\s\src\Uno.UWP\Globalization\ApplicationLanguages.cs:line 82
   at Windows.Globalization.ApplicationLanguages..cctor() in C:\a\1\s\src\Uno.UWP\Globalization\ApplicationLanguages.cs:line 16
```

### Expected behavior

Creating DatePicker and CalendarDatePicker objects should not throw exceptions

### How to reproduce it (as minimally and precisely as possible)

- Create a new Uno app in Visual Studio
- Setup the Skia.Gtk project to use WSL
- Add a DatePicker or CalendarDatePicker to the XAML
```
<Page
    x:Class="BugTesting.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:BugTesting"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Grid>
        <CalendarDatePicker></CalendarDatePicker>
    </Grid>
</Page>
```
- Debug the Skia.Gtk project and see the exception get thrown

### Workaround

Add `System.Globalization.CultureInfo.CurrentCulture = new System.Globalization.CultureInfo("en-US");` before `InitializeComponent();` in the Page constructor.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.1.9

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2019

### IDE version

16.11.12

### Anything else we need to know?

This seems like it might be an issue with Uno getting the CultureInfo from the WSL environment. I tried running this on a Linux system without the workaround, and the application started up fine, and the DatePicker was visible. Maybe there's something that needs to be added to the WSL setup section in the documentation?

**Comment by jeromelaban** [comment]
Thanks for the report! 

This is indeed caused by this piece:
https://github.com/unoplatform/uno/blob/b1fdfd5a5d764b9c4ad7bd1fd127f680bbb46e59/src/Uno.UWP/Globalization/ApplicationLanguages.cs#L42-L58

Which is using the currently set UICulture. In the context that you're running in, it may very well be that the current culture is invariant, causing this issue. 


## Note for contributors
We'll likely need to pick the default user-defined culture instead, as we're doing here:

https://github.com/unoplatform/uno/blob/b1fdfd5a5d764b9c4ad7bd1fd127f680bbb46e59/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs#L674
