### ISSUE TITLE
[Skia] OpenGL render surface fails with a null reference on WSL

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#8643]
### Current behavior

```
Marshaling render signal
GLIB UNHANDLED EXCEPTIONSystem.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Uno.UI.Runtime.Skia.GLRenderSurface.UnoGLDrawingArea_Render(Object o, RenderArgs args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
```

### Expected behavior

OpenGL rendering works properly

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.2.6

### IDE

Visual Studio 2022

**Comment by microhobby** [comment]
Maybe related to https://github.com/microsoft/wslg/issues/715

**Comment by jeromelaban** [comment]
The null reference happens because there's no OpenGL context when running under Wayland (it's OpenGL ES). 

This line returns null, and causes the rest to fail:
https://github.com/unoplatform/uno/blob/6d97c470f88327496e309cf2823e65dff25b7eb8/src/Uno.UI.Runtime.Skia.Gtk/GLRenderSurface.cs#L82

The suggestion from https://github.com/unoplatform/uno/issues/8660 to set `GDK_BACKEND=x11` as an environment variable does help on WSL and bare Linux but detecting the required conditions may be tricky.

Another option is to use OpenGL ES, but this does not solve the support for WSL, because the hardware abstraction for WSL does not support a high enough version so that Skia can use it. Here's an error that arises when using GLES:

```
Shader compilation error
------------------------
   1	#version 320 es
   2	
   3	precision mediump float;
   4	precision mediump sampler2D;
   5	out mediump vec4 sk_FragColor;
   6	flat in mediump vec4 vcolor_Stage0;
   7	void main() {
   8	    mediump vec4 outputColor_Stage0;
   9	    {
  10	        outputColor_Stage0 = vcolor_Stage0;
  11	    }
  12	    {
  13	        sk_FragColor = outputColor_Stage0;
  14	    }
  15	}
  16	
Errors:
0:1(10): error: GLSL ES 3.20 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.50, 3.30, 1.00 ES, and 3.00 ES
```
This seems to be caused by the following reported configuration:
```
glxinfo -v | grep "OpenGL"
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: llvmpipe (LLVM 9.0.1, 256 bits)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 20.0.4
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.1 Mesa 20.0.4
OpenGL shading language version string: 1.40
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 20.0.4
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
OpenGL ES profile extensions:
```

Overall, this means changes to detect if OpenGL can be used and if not, try using OpenGL ES. We'll need to find a way to detect the OpenGL ES version (`_gl.GetStringS(GLEnum.Version)` returns `3.3 (Core Profile) Mesa 20.0.4` on my system) and report the appropriate error.

In the meantime, as it's not possible to set the `GDK_BACKEND` variable in the `GtkHost` (it does not seem to be taken into account), we'll need to provide a meaningful error to the user with the available options.
