### ISSUE TITLE
OpenGL Render does not work with wayland backend

### ISSUE THREAD

**Issue by microhobby** [unoplatform/uno#8660]
### Current behavior

Trying to use the OpenGL render with Wayland backend:

```
Marshaling realize signal
GLIB UNHANDLED EXCEPTIONSystem.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Uno.UI.Runtime.Skia.GLRenderSurface.GLRenderSurface_Realized(Object sender, EventArgs e)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)      
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
```

### Expected behavior

run with no issues, like when using X11 backend

### How to reproduce it (as minimally and precisely as possible)

- create a Uno Skia.Gtk app
- run in a desktop environment using Wayland
- check the stack trace

### Workaround

run the app with the environment variable `GDK_BACKEND=x11`, this will force the XWayland to handle the app

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.2.6

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio Code

### IDE version

1.66.2

### Anything else we need to know?

The issue https://github.com/unoplatform/uno/issues/8643 also can be "worarounded" by using the `GDK_BACKEND=x11`

**Comment by jeromelaban** [comment]
Thanks for the report. Is the difference with https://github.com/unoplatform/uno/issues/8643 only for the fact that it's Wayland? You're not mentioning an OS, but is it with Linux specifically?

**Comment by microhobby** [comment]
@jeromelaban the error stack is different from https://github.com/unoplatform/uno/issues/8643 (this issue appears to be something related to the Nvidia library and WSL)

Yeah, Linux, and I was trying in other environment with (no WSL).

**Comment by jeromelaban** [comment]
This is actually the same issue, let's follow-up on https://github.com/unoplatform/uno/issues/8643.
