### ISSUE TITLE
[Gallery][Android] Overview(Material) - All Controls section (Button, Textbox, Checkbox....) is missing.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#8790]
### Current behavior

![Overview](https://user-images.githubusercontent.com/74563602/168642102-03b20e8e-28da-4ab6-b023-6381f00baacd.png)

https://user-images.githubusercontent.com/74563602/168642118-f520fe7b-e182-4de9-b40c-7254a7da6571.mp4

### Expected behavior

![Overview correct](https://user-images.githubusercontent.com/74563602/168642573-1ad212bf-9553-482b-8108-81b53e18cc13.png)

### How to reproduce it (as minimally and precisely as possible)

Launch the Uno.Gallry app on Skia.GTK.
Click on the “Material" section on the "overview" page.
Observe that for material All Controls(Button, Textbox, Checkbox....) details section is missing.

### Affected platforms

Android

**Comment by agneszitte-nventive** [comment]
> Hi @agneszitte-nventive, I retested the bug fix with the latest canary build, But still getting the same issue. The latest canary build version is: **Version 1.5.0 (6142127) Jun 14, 2022 at 09:38 52.35 MB Canary 0e817f4c744933c392b0f34c6f54b3bc36a4b1a6**

What device are you using for Android to test @sakshi173 please ?

**Comment by Xiaoy312** [comment]
it is empty because an error was thrown when MaterialTemplate is materializing:
<details>
<summary>System.TypeLoadException: Could not load type '{0}' from assembly '{1}'., Android.Text.ITextWatcherInvoker, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null</summary>

```
    at System.RuntimeTypeHandle.GetTypeByName(String , Boolean , Boolean , StackCrawlMark& , Boolean )
    at System.RuntimeType.GetType(String , Boolean , Boolean , StackCrawlMark& )
    at System.Type.GetType(String , Boolean )
    at Android.Runtime.AndroidTypeManager.RegisterNativeMembers(JniType , Type , String )
    --- End of stack trace from previous location ---
    at Java.Interop.JniEnvironment.StaticMethods.CallStaticObjectMethod(JniObjectReference , JniMethodInfo , JniArgumentValue* )
    at Android.Runtime.JNIEnv.CallStaticObjectMethod(IntPtr , IntPtr , JValue* )
    at Android.Runtime.JNIEnv.CallStaticObjectMethod(IntPtr , IntPtr , JValue[] )
    at Android.Runtime.JNIEnv.FindClass(String )
    at Android.Runtime.JNIEnv.AllocObject(String )
    at Android.Runtime.JNIEnv.StartCreateInstance(String , String , JValue* )
    at Android.Runtime.JNIEnv.StartCreateInstance(String , String , JValue[] )
    at Android.Text.TextWatcherImplementor..ctor(Object , EventHandler`1 , EventHandler`1 , EventHandler`1 )
    at Android.Widget.TextView.add_TextChanged(EventHandler`1 )
    at Uno.UI.Controls.BindableSwitchCompat..ctor()
    at Uno.Material.__Resources._mergedpages_v2_44627d8de4433209f2b1934267892e44_mergedpages_v2RDSC54.Build(Object __ResourceOwner_8083)
    at Uno.Material.GlobalStaticResources.ResourceDictionarySingleton__4.<>c.<Get_4_322>b__118_1(Object __owner)
    at Windows.UI.Xaml.FrameworkTemplate.LoadContent()
    at Windows.UI.Xaml.FrameworkTemplatePool.DequeueTemplate(FrameworkTemplate )
    at Windows.UI.Xaml.FrameworkTemplate.LoadContentCached()
    at Windows.UI.Xaml.Controls.Control.UpdateTemplate()
    at Windows.UI.Xaml.Controls.Control.SetUpdateControlTemplate(Boolean )
    at Windows.UI.Xaml.Controls.Control.OnTemplateChanged(DependencyPropertyChangedEventArgs )
    at Windows.UI.Xaml.Controls.Control.<>c.<.cctor>b__379_0(DependencyObject , DependencyPropertyChangedEventArgs )
    at Windows.UI.Xaml.PropertyMetadata.RaisePropertyChanged(DependencyObject , DependencyPropertyChangedEventArgs )
    at Windows.UI.Xaml.DependencyObjectStore.InvokeCallbacks(DependencyObject , DependencyProperty , DependencyPropertyDetails , Object , DependencyPropertyValuePrecedences , Object , DependencyPropertyValuePrecedences , Boolean )
    at Windows.UI.Xaml.DependencyObjectStore.RaiseCallbacks(DependencyObject , DependencyPropertyDetails , Object , DependencyPropertyValuePrecedences , Object , DependencyPropertyValuePrecedences )
    at Windows.UI.Xaml.DependencyObjectStore.InnerSetValue(DependencyProperty , Object , DependencyPropertyValuePrecedences , DependencyPropertyDetails , Boolean )
    at Windows.UI.Xaml.DependencyObjectStore.SetValue(DependencyProperty , Object , DependencyPropertyValuePrecedences , DependencyPropertyDetails , Boolean )
    at Windows.UI.Xaml.DependencyObjectStore.SetValue(DependencyProperty , Object )
    at Uno.UI.Controls.BindableView.SetValue(DependencyProperty , Object )
    at Windows.UI.Xaml.Setter.ApplyTo(DependencyObject )
    at Windows.UI.Xaml.Style.ApplyTo(DependencyObject , DependencyPropertyValuePrecedences )
    at Windows.UI.Xaml.FrameworkElement.OnStyleChanged(Style , Style , DependencyPropertyValuePrecedences )
    at Windows.UI.Xaml.FrameworkElement.ApplyStyle()
    at Windows.UI.Xaml.FrameworkElement.ApplyStyles()
    at Windows.UI.Xaml.FrameworkElement.CreationComplete()
    at Uno.Gallery.Views.GeneralPages.OverviewPage._OverviewPage_3a6fef22f85abd239159cb6f3853d12f_UnoGalleryViewsGeneralPagesOverviewPageSC1.<Build>b__0_30(ToggleSwitch c30)
    at Uno.Gallery.Views.GeneralPages.OverviewPage._OverviewPage_3a6fef22f85abd239159cb6f3853d12f_UnoGalleryViewsGeneralPagesOverviewPageSC1.Build(Object __ResourceOwner_67)
    at Uno.Gallery.Views.GeneralPages.OverviewPage.<>c.<InitializeComponent>b__2_5(Object __owner)
    at Windows.UI.Xaml.FrameworkTemplate.LoadContent()
    at Windows.UI.Xaml.FrameworkTemplatePool.DequeueTemplate(FrameworkTemplate )
    at Windows.UI.Xaml.FrameworkTemplate.LoadContentCached()
    at Windows.UI.Xaml.Controls.ContentPresenter.UpdateContentTemplateRoot()
    at Windows.UI.Xaml.Controls.ContentPresenter.SetUpdateTemplate()
    at Windows.UI.Xaml.Controls.ContentPresenter.OnVisibilityChanged(Visibility , Visibility )
    at Windows.UI.Xaml.UIElement.<>c.<CreateVisibilityProperty>b__1089_0(DependencyObject , DependencyPropertyChangedEventArgs )
    at Windows.UI.Xaml.PropertyMetadata.RaisePropertyChanged(DependencyObject , DependencyPropertyChangedEventArgs )
    at Windows.UI.Xaml.DependencyObjectStore.InvokeCallbacks(DependencyObject , DependencyProperty , DependencyPropertyDetails , Object , DependencyPropertyValuePrecedences , Object , DependencyPropertyValuePrecedences , Boolean )
    at Windows.UI.Xaml.DependencyObjectStore.RaiseCallbacks(DependencyObject , DependencyPropertyDetails , Object , DependencyPropertyValuePrecedences , Object , DependencyPropertyValuePrecedences )
    at Windows.UI.Xaml.DependencyObjectStore.InnerSetValue(DependencyProperty , Object , DependencyPropertyValuePrecedences , DependencyPropertyDetails , Boolean )
    at Windows.UI.Xaml.DependencyObjectStore.SetValue(DependencyProperty , Object , DependencyPropertyValuePrecedences , DependencyPropertyDetails , Boolean )
    at Windows.UI.Xaml.DependencyObjectExtensions.SetValue(Object , DependencyProperty , Object , Nullable`1 )
    at Uno.UI.DataBinding.BindingPropertyHelper.<>c__DisplayClass40_9.<InternalGetValueSetter>b__13(Object , Object )
    at Uno.UI.DataBinding.BindingPath.BindingItem.SetSourceValue(ValueSetterHandler , Object )
```
</details>

emphasis on this 2 lines:
```
    at Android.Widget.TextView.add_TextChanged(EventHandler`1 )
    at Uno.UI.Controls.BindableSwitchCompat..ctor()
```

this seems only be a problem in released build of Uno.Gallery.Mobile.csproj (net6-android)
    ^ likely something to do with the linker

by removing the ToggleSwitch samples from OverviewPage, the content will render correctly

**Comment by Xiaoy312** [comment]
related?: https://github.com/xamarin/xamarin-android/issues/3263

**Comment by kazo0** [comment]
Seems related to: https://github.com/xamarin/xamarin-android/issues/7097

**Comment by sakshi173** [comment]
Verified this issue is fixed with latest build.
