### ISSUE TITLE
x:Bind does not look for the class/properties for the source if they are in other libraries

### ISSUE THREAD

**Issue by HavenDV** [unoplatform/uno#9212]
### Current behavior

Code from example gives:
```
1>CSC : error UXAML0001: The type {using:xbindtwoway}MainPageBase could not be found
1>CSC : error UXAML0001: Processing failed for file C:\Users\haven\source\repos\HavenDV\Uno.Issues\xbindtwoway\xbindtwoway.Shared\MainPage.xaml (System.InvalidOperationException: The type {using:xbindtwoway}MainPageBase could not be found
1>C:\Users\haven\source\repos\HavenDV\Uno.Issues\xbindtwoway\xbindtwoway.Shared\MainPage.xaml.cs(23,40,23,52): error CS0246: The type or namespace name 'MainPageBase' could not be found (are you missing a using directive or an assembly reference?)
1>Done building project "xbindtwoway.Skia.WPF_4anndqri_wpftmp.csproj" -- FAILED.
```

if MyUserControl<T> in second library, this gives:
```
1>CSC : error UXAML0001: Unable to find member [ViewModel] on type [Dedoose.Views.CodeCountXMediaView]
1>CodeCharts\CodeCountXMediaView.xaml(37,18,37,18): error UXAML0001: An error was found in StackPanel
1>CodeCharts\CodeCountXMediaView.xaml(31,6,31,6): error UXAML0001: An error was found in Grid
1>CodeCharts\CodeCountXMediaView.xaml(1,2,1,2): error UXAML0001: An error was found in CodeCountXMediaViewBase
1>CSC : error UXAML0001: Processing failed for file CodeCountXMediaView.xaml (Uno.UI.SourceGenerators.XamlGenerator.XamlParsingException: An error was found in CodeCountXMediaViewBase ---> Uno.UI.SourceGenerators.XamlGenerator.XamlParsingException: An error was found in Grid ---> Uno.UI.SourceGenerators.XamlGenerator.XamlParsingException: An error was found in StackPanel ---> System.InvalidOperationException: Unable to find member [ViewModel] on type [Dedoose.Views.CodeCountXMediaView]
```

### How to reproduce it (as minimally and precisely as possible)

```xml
<local:MainPageBase
    x:Class="xbindtwoway.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:xbindtwoway"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}"
    >
    <Grid>
        <TextBox
            Text="{x:Bind ViewModel.Text, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"
            Margin="20"
            FontSize="30"
            />
    </Grid>
</local:MainPageBase>
```
```cs
public sealed partial class MainPage : MainPageBase
{
    public MainPage()
    {
        this.InitializeComponent();

        ViewModel = new MainViewModel();
    }
}
```

In library(In a complex situation, each of these classes is in three different libraries):
```cs
// MyUserControl is equivalent to ReactiveUserControl from the ReactiveUI package
public class MyUserControl<TViewModel> : UserControl where TViewModel : class
{
    public static readonly DependencyProperty ViewModelProperty =
        DependencyProperty.Register(
            "ViewModel",
            typeof(TViewModel),
            typeof(MyUserControl<TViewModel>),
            new PropertyMetadata(null));

    public TViewModel? BindingRoot => ViewModel;

    public TViewModel? ViewModel
    {
        get
        {
            return (TViewModel)GetValue(ViewModelProperty);
        }
        set
        {
            SetValue(ViewModelProperty, value);
        }
    }
}

public class MainViewModel
{
    public string Text { get; set; } = "hello";
}

public abstract partial class MainPageBase : MyUserControl<MainViewModel>
{
}
```
[Uno.Issues_setbinding_without_generator_2.zip](https://github.com/unoplatform/uno/files/9105369/Uno.Issues_setbinding_without_generator_2.zip)

1. Open H.ReactiveUI.Apps.Uno.Shared/Views/FileInteractionsView.xaml
2. Add `Mode=TwoWay` to `TextBox`.

```
Build started...
1>------ Build started: Project: H.ReactiveUI.Apps.Uno.Skia.Wpf, Configuration: Debug Any CPU ------
1>CSC : error UXAML0001: Unable to find member [ViewModel] on type [HReactiveUI.Apps.Views.FileInteractionsView]
1>C:\Users\haven\source\repos\HavenDV\Uno.Issues\setbinding\H.ReactiveUI.Apps.Uno.Shared\Views\FileInteractionsView.xaml(28,14,28,14): error UXAML0001: An error was found in StackPanel
1>C:\Users\haven\source\repos\HavenDV\Uno.Issues\setbinding\H.ReactiveUI.Apps.Uno.Shared\Views\FileInteractionsView.xaml(19,10,19,10): error UXAML0001: An error was found in StackPanel
1>C:\Users\haven\source\repos\HavenDV\Uno.Issues\setbinding\H.ReactiveUI.Apps.Uno.Shared\Views\FileInteractionsView.xaml(18,6,18,6): error UXAML0001: An error was found in Grid
1>C:\Users\haven\source\repos\HavenDV\Uno.Issues\setbinding\H.ReactiveUI.Apps.Uno.Shared\Views\FileInteractionsView.xaml(1,2,1,2): error UXAML0001: An error was found in FileInteractionsViewBase
1>CSC : error UXAML0001: Processing failed for file C:\Users\haven\source\repos\HavenDV\Uno.Issues\setbinding\H.ReactiveUI.Apps.Uno.Shared\Views\FileInteractionsView.xaml (Uno.UI.SourceGenerators.XamlGenerator.XamlParsingException: An error was found in FileInteractionsViewBase ---> Uno.UI.SourceGenerators.XamlGenerator.XamlParsingException: An error was found in Grid ---> Uno.UI.SourceGenerators.XamlGenerator.XamlParsingException: An error was found in StackPanel ---> Uno.UI.SourceGenerators.XamlGenerator.XamlParsingException: An error was found in StackPanel ---> System.InvalidOperationException: Unable to find member [ViewModel] on type [HReactiveUI.Apps.Views.FileInteractionsView]
1>C:\Users\haven\source\repos\HavenDV\Uno.Issues\setbinding\H.ReactiveUI.Apps.Shared\App.xaml.cs(49,29,49,39): error CS0115: 'App.OnLaunched(LaunchActivatedEventArgs)': no suitable method found to override
1>Done building project "H.ReactiveUI.Apps.Uno.Skia.Wpf.csproj" -- FAILED.
1>CSC : error UXAML0001: Unable to find member [ViewModel] on type [HReactiveUI.Apps.Views.FileInteractionsView]
1>C:\Users\haven\source\repos\HavenDV\Uno.Issues\setbinding\H.ReactiveUI.Apps.Uno.Shared\Views\FileInteractionsView.xaml(28,14,28,14): error UXAML0001: An error was found in StackPanel
1>C:\Users\haven\source\repos\HavenDV\Uno.Issues\setbinding\H.ReactiveUI.Apps.Uno.Shared\Views\FileInteractionsView.xaml(19,10,19,10): error UXAML0001: An error was found in StackPanel
1>C:\Users\haven\source\repos\HavenDV\Uno.Issues\setbinding\H.ReactiveUI.Apps.Uno.Shared\Views\FileInteractionsView.xaml(18,6,18,6): error UXAML0001: An error was found in Grid
1>C:\Users\haven\source\repos\HavenDV\Uno.Issues\setbinding\H.ReactiveUI.Apps.Uno.Shared\Views\FileInteractionsView.xaml(1,2,1,2): error UXAML0001: An error was found in FileInteractionsViewBase
1>CSC : error UXAML0001: Processing failed for file C:\Users\haven\source\repos\HavenDV\Uno.Issues\setbinding\H.ReactiveUI.Apps.Uno.Shared\Views\FileInteractionsView.xaml (Uno.UI.SourceGenerators.XamlGenerator.XamlParsingException: An error was found in FileInteractionsViewBase ---> Uno.UI.SourceGenerators.XamlGenerator.XamlParsingException: An error was found in Grid ---> Uno.UI.SourceGenerators.XamlGenerator.XamlParsingException: An error was found in StackPanel ---> Uno.UI.SourceGenerators.XamlGenerator.XamlParsingException: An error was found in StackPanel ---> System.InvalidOperationException: Unable to find member [ViewModel] on type [HReactiveUI.Apps.Views.FileInteractionsView]
1>C:\Users\haven\source\repos\HavenDV\Uno.Issues\setbinding\H.ReactiveUI.Apps.Shared\App.xaml.cs(49,29,49,39): error CS0115: 'App.OnLaunched(LaunchActivatedEventArgs)': no suitable method found to override
1>Done building project "H.ReactiveUI.Apps.Uno.Skia.Wpf.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 2 up-to-date, 0 skipped ==========

```

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

4.4.13

### Affected platforms

WebAssembly, Skia (WPF)

### IDE

Visual Studio 2022

### IDE version

17.3 preview 2

**Comment by HavenDV** [comment]
[Uno.Issues-main.zip](https://github.com/unoplatform/uno/files/9045020/Uno.Issues-main.zip)

**Comment by spouliot** [comment]
@HavenDV I do not see any reference between the (executable) projects (both Wpf and Wasm) and the `xbindtwoway.Library`.

IOW that assembly is never loaded so the source generator does not know about the type.

You can see the 3rd error from the build, `CS0246` coming from the C# compiler (not Uno's source generator), that complains about the missing `MainPageBase`.


```
/Users/poupou/Downloads/Uno-2.Issues-main/xbindtwoway/xbindtwoway.Wasm/xbindtwoway.Wasm.csproj : warning NU1504: Duplicate 'PackageReference' items found. Remove the duplicate items or use the Update functionality to ensure a consistent restore behavior. The duplicate 'PackageReference' items are: Microsoft.Windows.Compatibility 5.0.0, Microsoft.Windows.Compatibility 5.0.0.
CSC : error UXAML0001: The type {using:xbindtwoway}MainPageBase could not be found
CSC : error UXAML0001: Processing failed for file /Users/poupou/Downloads/Uno-2.Issues-main/xbindtwoway/xbindtwoway.Shared/MainPage.xaml (System.InvalidOperationException: The type {using:xbindtwoway}MainPageBase could not be found
/Users/poupou/Downloads/Uno-2.Issues-main/xbindtwoway/xbindtwoway.Shared/MainPage.xaml.cs(23,44,23,56): error CS0246: The type or namespace name 'MainPageBase' could not be found (are you missing a using directive or an assembly reference?)
    1 Warning(s)
    3 Error(s)
```

Now if I add a reference to `xbindtwoway.Library` from the shared project, like adding this snippet inside `xbindtwoway.Shared.projitems`:

```xml
  <ItemGroup>
    <ProjectReference Include="..\xbindtwoway.Library\xbindtwoway.Library.csproj">
      <GlobalPropertiesToRemove></GlobalPropertiesToRemove>
    </ProjectReference>
  </ItemGroup>
```

then it gets loaded, while compiling, and the build succeed (both Uno errors and the `CS0246` are gone)

```
/Users/poupou/Downloads/Uno-2.Issues-main/xbindtwoway/xbindtwoway.Wasm/xbindtwoway.Wasm.csproj : warning NU1504: Duplicate 'PackageReference' items found. Remove the duplicate items or use the Update functionality to ensure a consistent restore behavior. The duplicate 'PackageReference' items are: Microsoft.Windows.Compatibility 5.0.0, Microsoft.Windows.Compatibility 5.0.0.
    1 Warning(s)
    0 Error(s)
```

I'm not sure how UWP/WinUI are _implying_ this reference... I'll need to set up Windows to diagnose that. It would be useful if you can attach the `binlog` from the Windows/WinUI build. Thanks!

**Comment by spouliot** [comment]
Easier than I thought. Your Windows-based project has the reference to `xbindtwoway.Library` ;-)

<img width="227" alt="Screen Shot 2022-07-13 at 1 25 37 PM" src="https://user-images.githubusercontent.com/260465/178794081-447855bc-071a-4546-9037-47617ab87633.png">

while the WPF project did not

<img width="237" alt="Screen Shot 2022-07-13 at 1 27 03 PM" src="https://user-images.githubusercontent.com/260465/178794376-2bbc276f-37c5-46b5-947f-f15e949758a5.png">

I still think it's best for you to change the shared project - but doing this for each executable project is also a valid option (as long as it's done for all of them).

**Comment by HavenDV** [comment]
Sorry, omission when creating repro. The problem is still there, I will upload a new repro soon.

**Comment by HavenDV** [comment]
[Uno.Issues_setbinding_without_generator_2.zip](https://github.com/unoplatform/uno/files/9105369/Uno.Issues_setbinding_without_generator_2.zip)

1. Open H.ReactiveUI.Apps.Uno.Shared/Views/FileInteractionsView.xaml
2. Add `Mode=TwoWay` to `TextBox`.

**Comment by spouliot** [comment]
These don't look like the same errors as before, but it could be related. I'll have another look :)

Sadly everything (or too much things) seems to be reported as `UXAML0001` which makes it harder to identify the root problem.

**Comment by spouliot** [comment]
I can confirm that
```xml
                   Text="{x:Bind ViewModel.Content, Mode=OneWay}"
```
works (builds and app starts), while
```xml
                   Text="{x:Bind ViewModel.Content, Mode=TwoWay}"
```
fails at build time with several `UXAML0001` errors (with different messages)

```
    CSC : error UXAML0001: Unable to find member [ViewModel] on type [HReactiveUI.Apps.Views.FileInteractionsView]
    /Users/poupou/Downloads/Uno-3.Issues-main/setbinding/H.ReactiveUI.Apps.Uno.Shared/Views/FileInteractionsView.xaml(47,14,47,14): error UXAML0001: An error was found in StackPanel
    /Users/poupou/Downloads/Uno-3.Issues-main/setbinding/H.ReactiveUI.Apps.Uno.Shared/Views/FileInteractionsView.xaml(20,10,20,10): error UXAML0001: An error was found in StackPanel
    /Users/poupou/Downloads/Uno-3.Issues-main/setbinding/H.ReactiveUI.Apps.Uno.Shared/Views/FileInteractionsView.xaml(19,6,19,6): error UXAML0001: An error was found in Grid
    /Users/poupou/Downloads/Uno-3.Issues-main/setbinding/H.ReactiveUI.Apps.Uno.Shared/Views/FileInteractionsView.xaml(1,2,1,2): error UXAML0001: An error was found in FileInteractionsViewBase
    CSC : error UXAML0001: Processing failed for file /Users/poupou/Downloads/Uno-3.Issues-main/setbinding/H.ReactiveUI.Apps.Uno.Shared/Views/FileInteractionsView.xaml (Uno.UI.SourceGenerators.XamlGenerator.XamlParsingException: An error was found in FileInteractionsViewBase
    /Users/poupou/Downloads/Uno-3.Issues-main/setbinding/H.ReactiveUI.Apps.Shared/App.xaml.cs(49,29,49,39): error CS0115: 'App.OnLaunched(LaunchActivatedEventArgs)': no suitable method found to override
    CompilerServer: server - server processed compilation - 721ed218-26f1-4a1d-81d2-2cc53ad9c940
```

**Comment by spouliot** [comment]
A bit more details (stack trace)
```
Microsoft (R) Visual C# Compiler version 4.2.0-4.22220.5 (432d17a8)
Copyright (C) Microsoft Corporation. All rights reserved.

error UXAML0001: Unable to find member [ViewModel] on type [HReactiveUI.Apps.Views.FileInteractionsView]
/Users/poupou/Downloads/Uno-3.Issues-main/setbinding/H.ReactiveUI.Apps.Uno.Shared/Views/FileInteractionsView.xaml(47,14,47,14): error UXAML0001: An error was found in StackPanel
/Users/poupou/Downloads/Uno-3.Issues-main/setbinding/H.ReactiveUI.Apps.Uno.Shared/Views/FileInteractionsView.xaml(20,10,20,10): error UXAML0001: An error was found in StackPanel
/Users/poupou/Downloads/Uno-3.Issues-main/setbinding/H.ReactiveUI.Apps.Uno.Shared/Views/FileInteractionsView.xaml(19,6,19,6): error UXAML0001: An error was found in Grid
/Users/poupou/Downloads/Uno-3.Issues-main/setbinding/H.ReactiveUI.Apps.Uno.Shared/Views/FileInteractionsView.xaml(1,2,1,2): error UXAML0001: An error was found in FileInteractionsViewBase
error UXAML0001: Processing failed for file /Users/poupou/Downloads/Uno-3.Issues-main/setbinding/H.ReactiveUI.Apps.Uno.Shared/Views/FileInteractionsView.xaml (Uno.UI.SourceGenerators.XamlGenerator.XamlParsingException: An error was found in FileInteractionsViewBase
 ---> Uno.UI.SourceGenerators.XamlGenerator.XamlParsingException: An error was found in Grid
 ---> Uno.UI.SourceGenerators.XamlGenerator.XamlParsingException: An error was found in StackPanel
 ---> Uno.UI.SourceGenerators.XamlGenerator.XamlParsingException: An error was found in StackPanel
 ---> System.InvalidOperationException: Unable to find member [ViewModel] on type [HReactiveUI.Apps.Views.FileInteractionsView]
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GetXBindPropertyPathType(String propertyPath, INamedTypeSymbol rootType) in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 4298
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.<BuildXBindEvalFunction>g__buildBindBack|191_6(<>c__DisplayClass191_0& ) in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 4240
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildXBindEvalFunction(XamlMemberDefinition member, XamlObjectDefinition bindNode) in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 4259
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.<>c__DisplayClass188_0.<BuildComplexPropertyValue>g__WriteBinding|8(String prefix, <>c__DisplayClass188_1& , <>c__DisplayClass188_2& ) in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 4051
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildComplexPropertyValue(IIndentedStringBuilder writer, XamlMemberDefinition member, String prefix, String closureName, Boolean generateAssignation) in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 3983
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildExtendedProperties(IIndentedStringBuilder outerwriter, XamlObjectDefinition objectDefinition, Boolean useChildTypeForNamedElement, Boolean useGenericApply) in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 3154
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildChild(IIndentedStringBuilder writer, XamlMemberDefinition owner, XamlObjectDefinition xamlObjectDefinition, String outerClosure) in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 5741
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildProperties(IIndentedStringBuilder writer, XamlObjectDefinition topLevelControl, Boolean isInline, Boolean returnsContent, String closureName, Boolean useBase) in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 2407
   --- End of inner exception stack trace ---
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildProperties(IIndentedStringBuilder writer, XamlObjectDefinition topLevelControl, Boolean isInline, Boolean returnsContent, String closureName, Boolean useBase) in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 2558
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildChild(IIndentedStringBuilder writer, XamlMemberDefinition owner, XamlObjectDefinition xamlObjectDefinition, String outerClosure) in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 5737
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildProperties(IIndentedStringBuilder writer, XamlObjectDefinition topLevelControl, Boolean isInline, Boolean returnsContent, String closureName, Boolean useBase) in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 2407
   --- End of inner exception stack trace ---
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildProperties(IIndentedStringBuilder writer, XamlObjectDefinition topLevelControl, Boolean isInline, Boolean returnsContent, String closureName, Boolean useBase) in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 2558
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildChild(IIndentedStringBuilder writer, XamlMemberDefinition owner, XamlObjectDefinition xamlObjectDefinition, String outerClosure) in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 5737
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildProperties(IIndentedStringBuilder writer, XamlObjectDefinition topLevelControl, Boolean isInline, Boolean returnsContent, String closureName, Boolean useBase) in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 2407
   --- End of inner exception stack trace ---
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildProperties(IIndentedStringBuilder writer, XamlObjectDefinition topLevelControl, Boolean isInline, Boolean returnsContent, String closureName, Boolean useBase) in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 2558
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildChild(IIndentedStringBuilder writer, XamlMemberDefinition owner, XamlObjectDefinition xamlObjectDefinition, String outerClosure) in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 5737
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildProperties(IIndentedStringBuilder writer, XamlObjectDefinition topLevelControl, Boolean isInline, Boolean returnsContent, String closureName, Boolean useBase) in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 2504
   --- End of inner exception stack trace ---
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildProperties(IIndentedStringBuilder writer, XamlObjectDefinition topLevelControl, Boolean isInline, Boolean returnsContent, String closureName, Boolean useBase) in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 2558
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildGenericControlInitializerBody(IndentedStringBuilder writer, XamlObjectDefinition topLevelControl, Boolean isDirectUserControlChild) in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 809
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildInitializeComponent(IndentedStringBuilder writer, XamlObjectDefinition topLevelControl, INamedTypeSymbol controlBaseType, Boolean isDirectUserControlChild) in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 547
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.InnerGenerateFile() in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 475
   at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.GenerateFile() in C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 340)
/Users/poupou/Downloads/Uno-3.Issues-main/setbinding/H.ReactiveUI.Apps.Shared/App.xaml.cs(49,29,49,39): error CS0115: 'App.OnLaunched(LaunchActivatedEventArgs)': no suitable method found to override
```

Leading to

https://github.com/unoplatform/uno/blob/730aaadd240a8df9eb3f21ce775120322a529be3/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs#L4298

**Comment by spouliot** [comment]
> 	Microsoft.CodeAnalysis.ITypeSymbol.OriginalDefinition	{HReactiveUI.Apps.Views.FileInteractionsView}	Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.NonErrorNamedTypeSymbol

> 	_xClassName.Symbol.BaseType.OriginalDefinition	{object}	Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.NonErrorNamedTypeSymbol

So according to the source generator the base type of `FileInteractionsView` is `System.Object`, not `ReactiveObject`.

This is why an error is reported when looking for the `ViewModel` member...

This happens only for `TwoWay` since that lookup code is only executed for them.

**Comment by spouliot** [comment]
Inside `setbinding/H.ReactiveUI.Apps.Shared/Views/FileInteractionsView.xaml.cs` if I change

```csharp
public partial class FileInteractionsView
```

into 

```csharp
public partial class FileInteractionsView : FileInteractionsViewBase
```

then things seems to build just fine.

I am no expert in this code base but it seems like, at the time the source generator executes, there's nothing to hint the base type of `FileInteractionsView` so that makes it subclass `System.Object`.

Later there is something (no sure what/where) that generates the (missing) _hint_ that makes `FileInteractionsView` subclass `FileInteractionsViewBase` while also adding a bunch of generated code inside it. That's why the final binaries looks correct (for subclassing).

**Comment by HavenDV** [comment]
It turns out, again a duplicate, and the reason is the same everywhere?
https://github.com/unoplatform/uno/issues/9241
https://github.com/unoplatform/uno/issues/7404

**Comment by spouliot** [comment]
> the reason is the same everywhere?

I believe so - but @jeromelaban will be able to confirm that (once back from vacation)

**Comment by HavenDV** [comment]
Sad. Sorry guys for creating extra work for you out of nothing.
