### ISSUE TITLE
Error MSB4018

### ISSUE THREAD

**Issue by workgroupengineering** [unoplatform/uno#9261]
### Current behavior

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "LinkerDefinitionMergerTask_v0" task failed unexpectedly.
Mono.Cecil.Cil.SymbolsNotMatchingException: Symbols were found but are not matching the assembly
   at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader, Boolean throwIfSymbolsAreNotMaching)
   at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
   at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Mono.Cecil.AssemblyDefinition.ReadAssembly(String fileName, ReaderParameters parameters)
   at Uno.UI.Tasks.LinkerHintsGenerator.LinkerDefinitionMergerTask_v0.Execute() in C:\GitHub\uno\src\SourceGenerators\Uno.UI.Tasks\LinkerHintsGenerator\LinkerDefinitionMergerTask.cs:line 84
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Uno.UI.Skia	C:\GitHub\uno\src\SourceGenerators\Uno.UI.Tasks\Content\Uno.UI.Tasks.targets	104	

### How to reproduce it (as minimally and precisely as possible)

- Rebuild Uno.UI-Skya-Only

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

Skia (WPF), Build tasks

### IDE version

17.3.0 Preview 2

**Comment by jeromelaban** [comment]
@ebariche was this fixed by https://github.com/unoplatform/uno/pull/9226 ?
