### ISSUE TITLE
[Android][iOS] Image Asset Named with ISO Code doesn't Work

### ISSUE THREAD

**Issue by Soap-141** [unoplatform/uno#9264]
### Current behavior

When an image asset is named with an ISO code representing a language the image doesn't work on Android and iOS.

For example: `image_bg.png`.

The image on the left is named `Doge.png` and the Image on the right is named `Doge_bg.png`.

UWP:
![Capture_76](https://user-images.githubusercontent.com/57812285/178817440-58609477-ef15-4674-948d-7a291ca9a401.PNG)

Android:
![Capture_75](https://user-images.githubusercontent.com/57812285/178817472-86ec128b-09f8-4c19-a6d4-28a8089cc9e7.PNG)

### Expected behavior

The image should work properly.

### How to reproduce it (as minimally and precisely as possible)

1. Download [SampleImg.zip](https://github.com/unoplatform/uno/files/9105294/SampleImg.zip)
2. Open the solution in Visual Studio
3. Start the application in UWP
4. Notice two images
5. Start the application on Android or iOS
6. Notice only one image

### Workaround

Rename the image asset.

Example: `Doge_bg.png` would not work but `Doge.png` would work.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno 4.4.13 & 4.5.0-dev.222

### Affected platforms

iOS, Android

### IDE

Visual Studio 2022

### IDE version

17.2.6

### Anything else we need to know?

I did not test on other platforms.

**Comment by jeromelaban** [comment]
This is likely related to https://github.com/unoplatform/uno/issues/7431

**Comment by MartinZikmund** [comment]
Related issue:

Related to https://github.com/unoplatform/nventive-private/issues/404

## Current behavior

Images that use CA without letters beside it, do not appear

## Expected behavior

Images should appear

## How to reproduce it (as precisely as possible)
Open the app

Sample:
[ImageDisplayPath.zip](https://github.com/unoplatform/uno/files/8903871/ImageDisplayPath.zip)

Output Debug:
Uno.Helpers.DrawableHelper[0]
      Couldn't find drawable with key: CA
Uno.Helpers.DrawableHelper[0]
      Couldn't find drawable with key: CA
Uno.Helpers.DrawableHelper[0]
      Couldn't find drawable with key: ca_Flag
Uno.Helpers.DrawableHelper[0]
      Couldn't find drawable with key: ca_Flag

[ImageView] Unable to find resource: 2131165184
[ImageView] android.content.res.Resources$NotFoundException: Resource ID #0x7f070000
[ImageView] 	at crc64122dcf5ad656876d.FrameworkElement.06-14 14:51:01.340 W/ImageView( 4267): 	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:234)
[ImageView] 	at android.content.res.Resources.getDrawableForDensity(Resources.java:982)

**Comment by yeahg-dev** [comment]
image file name containing "mic" also does not rendering.

**Comment by MartinZikmund** [comment]
Should be validated on Skia targets

**Comment by MartinZikmund** [comment]
# Repro generator

This issue was classified as not reproducible with a code sample or test.

**Reason:** Android/iOS-specific image asset ISO code issue.
