### ISSUE TITLE
Windows Wasm preview build fails when WasmShellILLinkerEnabled is false

### ISSUE THREAD

**Issue by Rytisgit** [unoplatform/uno#9302]
### Current behavior

setting ```<WasmShellILLinkerEnabled>false</WasmShellILLinkerEnabled>``` causes build on preview to fail due to the builder checking for a missing folder.

```
Error		System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\source\VS2022SkiaError\VS2022SkiaError\VS2022SkiaError.Wasm\obj\Debug\net6.0\workAot\linker-out'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at Uno.Wasm.Bootstrap.ShellTask_v2ca1f3f426d59c56cf8c4c553470858c53361dd9.CleanupLinkerRemovedFiles(String workAotPath) in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 981
   at Uno.Wasm.Bootstrap.ShellTask_v2ca1f3f426d59c56cf8c4c553470858c53361dd9.RunPackager() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 973
   at Uno.Wasm.Bootstrap.ShellTask_v2ca1f3f426d59c56cf8c4c553470858c53361dd9.Execute() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 243	VS2022SkiaError.Wasm	C:\Users\SuperPC\.nuget\packages\uno.wasm.bootstrap\4.0.0-dev.174\build\Uno.Wasm.Bootstrap.targets	185	
```

### Expected behavior

The build works correctly with WasmShellILLinkerEnabled set to false

### How to reproduce it (as minimally and precisely as possible)

create a new uno app
update wasm nugets to preview 
```
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="4.0.0-dev.174" />
    <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="4.0.0-dev.174" />
```
```<WasmShellILLinkerEnabled>false</WasmShellILLinkerEnabled>``` is enabled by default on debug version

### Workaround

don't set WasmShellILLinkerEnabled to false

### NuGet package version(s)

    <PackageReference Include="Uno.Wasm.Bootstrap" Version="4.0.0-dev.174" />
    <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="4.0.0-dev.174" />

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

17.3.0 Preview 3.0

**Comment by jeromelaban** [comment]
Thanks for the report. Are you using AOT, native dependencies or SkiaSharp in your project ?
