### ISSUE TITLE
[Skia] Burger menu does not appear properly on Calculator

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#9814]
### Current behavior

The burger menu sometimes does not appear:
![image](https://user-images.githubusercontent.com/5839577/189755581-d43121bf-25cc-4982-8ae8-2d2b63918147.png)

```
Gdk-Message: 16:46:30.909: Unable to load sb_up_arrow from the cursor theme
fail: Windows.UI.Xaml.Media.Animation.AddDeleteThemeTransition[0]
      The member AddDeleteThemeTransition.AddDeleteThemeTransition() is not implemented in Uno.
fail: Windows.UI.Xaml.Media.Animation.ContentThemeTransition[0]
      The member ContentThemeTransition.ContentThemeTransition() is not implemented in Uno.
fail: Windows.UI.Xaml.Media.Animation.ReorderThemeTransition[0]
      The member ReorderThemeTransition.ReorderThemeTransition() is not implemented in Uno.
fail: Uno.UI.DataBinding.BindingPropertyHelper[0]
      The [ScrollViewer] property getter does not exist on type [Windows.UI.Xaml.Controls.NavigationViewList]
new StandardCalculatorViewModel()
warn: Windows.Globalization.ApplicationLanguages[0]
      Unable to determine the default culture, using invariant culture
fail: Windows.Globalization.Fonts.LanguageFontGroup[0]
      The member LanguageFontGroup.LanguageFontGroup(string languageTag) is not implemented in Uno.
fail: Windows.ApplicationModel.Core.CoreApplicationViewTitleBar[0]
      The member event TypedEventHandler<CoreApplicationViewTitleBar, object> CoreApplicationViewTitleBar.LayoutMetricsChanged is not implemented in Uno.
fail: Windows.ApplicationModel.Core.CoreApplicationViewTitleBar[0]
      The member event TypedEventHandler<CoreApplicationViewTitleBar, object> CoreApplicationViewTitleBar.IsVisibleChanged is not implemented in Uno.
fail: Windows.UI.Xaml.UIElement[0]
      The member event TypedEventHandler<UIElement, AccessKeyInvokedEventArgs> UIElement.AccessKeyInvoked is not implemented in Uno.
fail: Windows.ApplicationModel.Core.CoreApplicationViewTitleBar[0]
      The member bool CoreApplicationViewTitleBar.IsVisible is not implemented in Uno.
fail: Windows.Storage.ApplicationDataContainer[0]
      The member void ApplicationDataContainer.DeleteContainer(string name) is not implemented in Uno.
m_CalculatorViewMode = CalculatorApp.ViewModel.StandardCalculatorViewModel
fail: Windows.UI.Xaml.UIElement[0]
      The member event TypedEventHandler<UIElement, RoutedEventArgs> UIElement.ContextCanceled is not implemented in Uno.
fail: Windows.UI.Xaml.UIElement[0]
      The member event TypedEventHandler<UIElement, ContextRequestedEventArgs> UIElement.ContextRequested is not implemented in Uno.
fail: Windows.UI.Xaml.VisualTransition[0]
      The member Duration VisualTransition.GeneratedDuration is not implemented in Uno.
warn: Windows.UI.Xaml.NameScope[0]
      The name [] already exists in the current XAML scope
warn: Windows.UI.Xaml.NameScope[0]
      The name [] already exists in the current XAML scope
warn: Windows.UI.Xaml.NameScope[0]
      The name [] already exists in the current XAML scope
warn: Windows.UI.Xaml.NameScope[0]
      The name [] already exists in the current XAML scope
warn: Windows.UI.Xaml.NameScope[0]
      The name [] already exists in the current XAML scope
warn: Windows.UI.Xaml.NameScope[0]
      The name [] already exists in the current XAML scope
warn: Windows.UI.Xaml.NameScope[0]
      The name [] already exists in the current XAML scope
warn: Windows.UI.Xaml.NameScope[0]
      The name [] already exists in the current XAML scope
warn: Windows.UI.Xaml.NameScope[0]
      The name [] already exists in the current XAML scope
warn: Windows.UI.Xaml.NameScope[0]
      The name [] already exists in the current XAML scope
warn: Windows.UI.Xaml.NameScope[0]
      The name [] already exists in the current XAML scope
warn: Windows.UI.Xaml.NameScope[0]
      The name [] already exists in the current XAML scope
warn: Windows.UI.Xaml.NameScope[0]
      The name [] already exists in the current XAML scope
fail: Uno.UI.DataBinding.BindingPropertyHelper[0]
      The [ScrollViewer] property getter does not exist on type [Windows.UI.Xaml.Controls.ListView]
fail: Windows.UI.Xaml.Data.BindingExpression[0]
      Failed to apply binding to property [DependencyPropertyDetails(Data)] on [Windows.UI.Xaml.Controls.PathIcon] (No strategy registration for conversion 'StandardCalculatorViewModel' to 'Geometry' (Parameter 'extensionPoint'))
      System.ArgumentOutOfRangeException: No strategy registration for conversion 'StandardCalculatorViewModel' to 'Geometry' (Parameter 'extensionPoint')
         at Uno.Conversion.DefaultConversionExtensions.To(Object value, Type toType, CultureInfo culture) in C:\a\1\s\src\Uno.Foundation\Uno.Core.Extensions\Uno.Core.Extensions.Compatibility\Conversion\DefaultConversionExtensions.cs:line 85         at Uno.UI.DataBinding.BindingPropertyHelper.Convert(Func`1 propertyType, Object value) in C:\a\1\s\src\Uno.UI\DataBinding\BindingPropertyHelper.cs:line 1081
         at Windows.UI.Xaml.Data.BindingExpression.ConvertToBoundPropertyType(Object value) in C:\a\1\s\src\Uno.UI\DataBinding\BindingExpression.cs:line 727
         at Windows.UI.Xaml.Data.BindingExpression.ConvertValue(Object value) in C:\a\1\s\src\Uno.UI\DataBinding\BindingExpression.cs:line 714
         at Windows.UI.Xaml.Data.BindingExpression.<SetTargetValueSafe>g__SetTargetValueSafeWithTry|54_1(Object v, Boolean useTargetNullValue) in C:\a\1\s\src\Uno.UI\DataBinding\BindingExpression.cs:line 644
warn: Windows.UI.Xaml.UIElement[0]
      The BorderThicknessProperty dependency property does not exist on Windows.UI.Xaml.Controls.Viewbox
warn: Windows.UI.Xaml.UIElement[0]
      The BorderThicknessProperty dependency property does not exist on Windows.UI.Xaml.Controls.ItemsPresenter
fail: Windows.UI.Xaml.Controls.ScrollContentPresenter[0]
      The member float ZoomFactor is not implemented in Uno.
warn: Windows.UI.Xaml.UIElement[0]
      The BorderThicknessProperty dependency property does not exist on Windows.UI.Xaml.Controls.PathIcon
warn: Windows.UI.Xaml.UIElement[0]
      The BorderThicknessProperty dependency property does not exist on Windows.UI.Xaml.Controls.Primitives.PivotHeaderPanel
warn: Windows.UI.Xaml.UIElement[0]
      The BorderThicknessProperty dependency property does not exist on Windows.UI.Xaml.Controls.FontIcon
warn: Windows.UI.Xaml.UIElement[0]
      The BorderThicknessProperty dependency property does not exist on Windows.UI.Xaml.Controls.Primitives.PivotPanel
```

### Expected behavior

The burger menu shows up

### NuGet package version(s)

4.5.8

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by jeromelaban** [comment]
Fixed in latest builds
