### ISSUE TITLE
[4.5.9][VisualStudio 2022] Uno Platform Solution Templates VisualStudio Extension fails to install

### ISSUE THREAD

**Issue by baskren** [unoplatform/uno#9887]
### Current behavior

When installing [latest (4.5.9) version of Uno Platform Solution Templates VisualStudio Extension](https://marketplace.visualstudio.com/items?itemName=nventivecorp.uno-platform-addin) installation fails with the following dialog and log:

<img width="327" alt="image" src="https://user-images.githubusercontent.com/2528888/191031083-b407106d-65cb-49e5-a4ff-012ededbefa3.png">

```
9/19/2022 9:38:16 AM - Microsoft VSIX Installer
9/19/2022 9:38:16 AM - -------------------------------------------
9/19/2022 9:38:16 AM - vsixinstaller.exe version:
9/19/2022 9:38:16 AM - 17.4.1084-preview2
9/19/2022 9:38:16 AM - -------------------------------------------
9/19/2022 9:38:16 AM - Command line parameters:
9/19/2022 9:38:16 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\ben\Downloads\UnoPlatform-4.5.9.x86.vsix
9/19/2022 9:38:16 AM - -------------------------------------------
9/19/2022 9:38:16 AM - Microsoft VSIX Installer
9/19/2022 9:38:16 AM - -------------------------------------------
9/19/2022 9:38:17 AM - Initializing Install...
9/19/2022 9:38:17 AM - Extension Details...
9/19/2022 9:38:17 AM - 	Identifier         : UnoSolutionTemplate.b8e0806a-a194-4442-8634-474e089e479e
9/19/2022 9:38:17 AM - 	Name               : Uno Platform Solution Templates
9/19/2022 9:38:17 AM - 	Author             : unoplatform
9/19/2022 9:38:17 AM - 	Version            : 4.5.9.27
9/19/2022 9:38:17 AM - 	Description        : Solution templates for Uno Platform enabled projects
9/19/2022 9:38:17 AM - 	Locale             : en-US
9/19/2022 9:38:17 AM - 	MoreInfoURL        : https://github.com/unoplatform/uno
9/19/2022 9:38:17 AM - 	InstalledByMSI     : False
9/19/2022 9:38:17 AM - 	SupportedFrameworkVersionRange : [4.5,)
9/19/2022 9:38:17 AM - 
9/19/2022 9:38:17 AM - 	SignatureState     : ValidSignature
9/19/2022 9:38:17 AM - 	SignedBy           : UNO Platform Inc.
9/19/2022 9:38:17 AM - 	Certificate Info   : 
9/19/2022 9:38:17 AM - 		-------------------------------------------------------
9/19/2022 9:38:17 AM - 		[Subject]       : CN=UNO Platform Inc., O=UNO Platform Inc., L=Montréal, S=Quebec, C=CA
9/19/2022 9:38:17 AM - 		[Issuer]        : CN=SSL.com Code Signing Intermediate CA RSA R1, O=SSL Corp, L=Houston, S=Texas, C=US
9/19/2022 9:38:17 AM - 		[Serial Number] : 46B87C76B4D288072A0E3CF23D6255D1
9/19/2022 9:38:17 AM - 		[Not Before]    : 4/1/2022 2:24:03 PM
9/19/2022 9:38:17 AM - 		[Not After]     : 3/30/2024 2:24:03 PM
9/19/2022 9:38:17 AM - 		[Thumbprint]    : 26E7EBFDC706F4E1AFD7589D90B1407C3ECAC93B
9/19/2022 9:38:17 AM - 
9/19/2022 9:38:17 AM - 	Supported Products : 
9/19/2022 9:38:17 AM - 		Microsoft.VisualStudio.Community
9/19/2022 9:38:17 AM - 			Version : [15.0,17.0)
9/19/2022 9:38:17 AM - 			ProductArchitecture : x86
9/19/2022 9:38:17 AM - 
9/19/2022 9:38:17 AM - 	References         : 
9/19/2022 9:38:17 AM - 	Prerequisites      : 
9/19/2022 9:38:17 AM - 		-------------------------------------------------------
9/19/2022 9:38:17 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
9/19/2022 9:38:17 AM - 		Name         : Visual Studio core editor
9/19/2022 9:38:17 AM - 		Version      : [16.1.28811.260,17.0)
9/19/2022 9:38:17 AM - 
9/19/2022 9:38:17 AM - 		-------------------------------------------------------
9/19/2022 9:38:17 AM - 		Identifier   : Microsoft.VisualStudio.Workload.NetCrossPlat
9/19/2022 9:38:17 AM - 		Name         : Mobile development with .NET
9/19/2022 9:38:17 AM - 		Version      : [16.3.29230.54,17.0)
9/19/2022 9:38:17 AM - 
9/19/2022 9:38:17 AM - 		-------------------------------------------------------
9/19/2022 9:38:17 AM - 		Identifier   : Microsoft.VisualStudio.Workload.Universal
9/19/2022 9:38:17 AM - 		Name         : Universal Windows Platform development
9/19/2022 9:38:17 AM - 		Version      : [16.3.29102.218,17.0)
9/19/2022 9:38:17 AM - 
9/19/2022 9:38:17 AM - 		-------------------------------------------------------
9/19/2022 9:38:17 AM - 		Identifier   : Microsoft.VisualStudio.Workload.NetWeb
9/19/2022 9:38:17 AM - 		Name         : ASP.NET and web development
9/19/2022 9:38:17 AM - 		Version      : [16.3.29311.71,17.0)
9/19/2022 9:38:17 AM - 
9/19/2022 9:38:17 AM - Signature Details...
9/19/2022 9:38:17 AM - 	Extension is signed with a valid signature.
9/19/2022 9:38:17 AM - 
9/19/2022 9:38:17 AM - Searching for applicable products...
9/19/2022 9:38:17 AM - Found installed product - Global Location
9/19/2022 9:38:17 AM - Found installed product - Visual Studio Enterprise 2022
9/19/2022 9:38:17 AM - Found installed product - Visual Studio Enterprise 2022 Preview
9/19/2022 9:38:17 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

```

### Expected behavior

Extension installs without incident

### How to reproduce it (as minimally and precisely as possible)

1. On Windows 10 PC with Visual Studio 2022 and/or VisualStudio 2022 preview, download version 4.5.9 of Uno Platform Solution Templates VisualStudio Extension:

  https://marketplace.visualstudio.com/items?itemName=nventivecorp.uno-platform-addin

2. Be sure VisualStudio is not running
3. Attempt to install the downloaded extension file.

### Workaround

None?

### NuGet package version(s)

n/a

### IDE

Visual Studio 2022

### IDE version

Visual Studio Enterprise 2022 - 17.3.4; Visual Studio Enterprise 2022 - Preview

### Relevant plugins

n/a

**Comment by Youssef1313** [comment]
I'm not sure, but as a guess:

https://github.com/unoplatform/uno/blob/470dc159580661a940005bbc7029a3a489405ec9/src/SolutionTemplate/UnoSolutionTemplate.VSIX.2022/source.extension.vsixmanifest#L11-L15

We have only a "Community" installation target, but the installation found is "Enterprise". So that might be the issue?
