### ISSUE TITLE
[wasm] runtime error since Uno.WinUI.WebAssembly dev.214

### ISSUE THREAD

**Issue by sarosigy** [unoplatform/uno#9986]
### Current behavior

At start - either dotnet run interactively or build AOT release - while loading the application it throws exception:

```
/usr/bin/dotnet run
...
Uncaught ReferenceError ReferenceError: Microsoft is not defined
    at <anonymous> (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/Uno.UI.js:4632:37)
    at <anonymous> (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/Uno.UI.js:4635:11)
    at <anonymous> (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/Uno.UI.js:4636:7)
    at <anonymous> (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/Uno.UI.js:4637:3)
<anonymous> @ localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/Uno.UI.js:4632:37
<anonymous> @ localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/Uno.UI.js:4635:11
<anonymous> @ localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/Uno.UI.js:4636:7
<anonymous> @ localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/Uno.UI.js:4637:3
Debugging hotkey: Shift+Alt+D (when application has focus)
Uncaught ManagedError Error: jsCallDispatcher.methodMap[(id + "")] is not a function
TypeError: jsCallDispatcher.methodMap[(id + "")] is not a function
    at marshal_exception_to_js (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/dotnet.js:5:53508)
    at invoke_method_and_handle_exception (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/dotnet.js:5:76910)
    at runtimeHelpers.javaScriptExports.call_entry_point (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/dotnet.js:5:80119)
    at mono_run_main (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/dotnet.js:5:3270)
    at mainInit (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/uno-bootstrap.js:353:30)
    at checkDone (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/uno-bootstrap.js:560:38)
    at processDependency (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/uno-bootstrap.js:578:37)
    at execCb (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:16727)
    at check (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:10499)
    at <anonymous> (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:12915)
    at <anonymous> (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:1542)
    at <anonymous> (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:13376)
    at each (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:1020)
    at emit (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:13344)
    at check (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:11058)
    at <anonymous> (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:12915)
    at <anonymous> (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:1542)
    at <anonymous> (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:13376)
    at each (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:1020)
    at emit (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:13344)
    at check (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:11058)
    at enable (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:13242)
    at init (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:9605)
    at a (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:8305)
    at completeLoad (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:16151)
    at onScriptLoad (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:16882)
    --- load ---
    at req.load (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:3483)
    at load (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:16680)
    at load (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:10087)
    at fetch (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:9888)
    at check (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:11152)
    at enable (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:13242)
    at enable (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:15790)
    at <anonymous> (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:13099)
    at <anonymous> (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:1542)
    at each (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:1020)
    at enable (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:12599)
    at init (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:9605)
    at a (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:8305)
    at completeLoad (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:15962)
    at onScriptLoad (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:16882)
    --- load ---
    at req.load (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:3483)
    at load (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:16680)
    at load (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:10087)
    at fetch (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:9888)
    at check (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:11152)
    at enable (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:13242)
    at enable (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:15790)
    at <anonymous> (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:13099)
    at <anonymous> (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:1542)
    at each (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:1020)
    at enable (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:12599)
    at init (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:9605)
    at <anonymous> (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:15109)
    --- setTimeout ---
    at req.nextTick (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:2434)
    at s (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:15048)
    at requirejs (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/require.js:5:2335)
    at require (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/uno-bootstrap.js:601:25)
    at <anonymous> (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/uno-bootstrap.js:581:34)
    at initializeRequire (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/uno-bootstrap.js:563:58)
    at RuntimeReady (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/uno-bootstrap.js:312:26)
    at Bootstrapper.onDotnetReady (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/uno-bootstrap.js:208:53)
    at mono_wasm_after_user_runtime_initialized (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/dotnet.js:5:135833)
    at onRuntimeInitializedAsync (localhost꞉5000/package_bb5667f68eba715d6db770f6a59547f252f6db64/dotnet.js:5:132742)
[15:26:04] fail: DevToolsProxy[0]
      failed: System.NullReferenceException: Object reference not set to an instance of an object.
         at Microsoft.WebAssembly.Diagnostics.DebugStore.Load(SessionId id, String[] loaded_files, ExecutionContext context, Boolean useDebuggerProtocol, CancellationToken token)+MoveNext() in /__w/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/mono/wasm/debugger/BrowserDebugProxy/DebugStore.cs:line 1468
         at Microsoft.WebAssembly.Diagnostics.DebugStore.Load(SessionId id, String[] loaded_files, ExecutionContext context, Boolean useDebuggerProtocol, CancellationToken token)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at Microsoft.WebAssembly.Diagnostics.MonoProxy.LoadStore(SessionId sessionId, Boolean tryUseDebuggerProtocol, CancellationToken token) in /__w/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:line 1510
         at Microsoft.WebAssembly.Diagnostics.MonoProxy.LoadStore(SessionId sessionId, Boolean tryUseDebuggerProtocol, CancellationToken token) in /__w/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:line 1510
mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28

```
In dev.437 the faulting line is different:
```
Uncaught ReferenceError ReferenceError: Microsoft is not defined
    at <anonymous> (localhost꞉5000/package_bd3e05a900d07715ec8127fa6f52c03981ff5a64/Uno.UI.js:4646:37)
    at <anonymous> (localhost꞉5000/package_bd3e05a900d07715ec8127fa6f52c03981ff5a64/Uno.UI.js:4649:11)
and so on.
```

### Workaround

The last working version (at least for me) is dev.168

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

    <PackageReference Include="Microsoft.Windows.Compatibility" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="5.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="Uno.Extensions.Logging.WebAssembly.Console" Version="1.4.0" />
    <PackageReference Include="Uno.WinUI.WebAssembly" Version="4.6.0-dev.214" />
    <PackageReference Include="Uno.WinUI.RemoteControl" Version="4.6.0-dev.214" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.6.0-dev.214" />
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="7.0.0-dev.169" />
    <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="7.0.0-dev.169" />

### Affected platforms

WebAssembly

### IDE version

- not relevant -

**Comment by jeromelaban** [comment]
Thanks for the report. `Uno.Wasm.Bootstrap` 7.0-dev builds are still in heavy development, and you should keep using 3.3.x builds.

**Comment by sarosigy** [comment]
Is it a bootstrap issue? It works with the same bootstrap but with the earlier dev.168 WinUI.WebAssembly

**Comment by jeromelaban** [comment]
Ah, interesting, it could be another change then. We'll look into it.
